### ISSUE TITLE
Unavailable map service blocks widgets from loading

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#140]
I have a map service that I am using that is currently (this moment in time) returning a "503 Service Temporarily Unavailable" error. This means that none of the widgets on the sidebar appear to load until the offending map requests time out (approximately 180 secs).

I cannot think of a simple solution to this. Maybe reducing the timeout would help if it is configurable?

**Comment by tmcgee** [comment]
I believe this was addressed in #339

**Comment by tr3vorm** [comment]
@tmcgee Was this merged in to CMV?

**Comment by tmcgee** [comment]
Nope not part of CMV. Larry Stout posted a possible solution in #339 that was not core to CMV. Either of the issues can be reopened if desired.

**Comment by tr3vorm** [comment]
Leave it closed - it was raised a while ago, and I (incorrectly) thought it was on the radar for being brought in to CMV.

**Comment by tmcgee** [comment]
It might be a good candidate for a Controller mix-in if/when mix-ins become a real thing.
