### ISSUE TITLE
Related recods info in a popup

### ISSUE THREAD

**Issue by gnevan** [cmv/cmv-app#156]
Is there a way to display any related recods info in a popup? There is an add-in to the ArcGIS Viewer for Silverlight, Query Related Records, which is able to request the related records from the identification popup window.
Is there any ability to do this or do you have the plans for it?

**Comment by serip12** [comment]
hi @geoggeek , i'm a Vietnamese student. Can you tell me what is the javascript framework you're using? it looks very nice. Thanks so much

**Comment by MesquiteGIS** [comment]
Anyone out there have any luck with related records? I've tried to configure the widget, but can't get the table to come up. Any suggestions or help would be appreciated. I get a "Error performing query operation."
Thanks

**Comment by DavidSpriggs** [comment]
@MesquiteGIS it's bast to ask @roemhildtg as he is the widget author. You can post an issue on his repo here: https://github.com/roemhildtg/CMV_Widgets/

**Comment by roemhildtg** [comment]
The related record widget can be embedded in the Identify popular using the content property of the Identify config. I recently made some changes to the widget and split into separate classes to allow for this.

**Comment by MesquiteGIS** [comment]
Everything is working fairly well now with the related records table. Thank you Gregg for the awesome work on the widget and your help! Just need to figure out how to exclude the "Extra" tab and still have my related table populate.
![pic3](https://cloud.githubusercontent.com/assets/7807619/7950199/360035e4-094c-11e5-89f6-0c0f5d713e74.JPG)

**Comment by jfuto** [comment]
@MesquiteGIS , how did you get rid of the extra tab?

**Comment by roemhildtg** [comment]
@jfuto the problem with that example above was related to the [related records widget](https://github.com/roemhildtg/cmv-widgets/tree/master/widgets/RelationshipTable) (no pun intended) just so we're on the same page. You can exclude a tab by specifying something like this in the related records widget config:
```Javascript
options: {
        //required option
        layerControlLayerInfos: true,

        //optional relationships property
        relationships: {
            <layerID)>: { //layerID (integer) key refers to featurelayer id on the rest services page
                <relationshipID>: { //relationshipID (integer) key referrs to the relationship id on the rest services page

                    //set exclude to true to skip this relationship
                    exclude: true
                }
            }
        }
    }
```

**Comment by carrbrpoa** [comment]
Hello guys,

Does it coexists with [Attributes Table widget](https://github.com/tmcgee/cmv-widgets#attributes-tables)?

**Comment by roemhildtg** [comment]
@carrbrpoa do you mean the related record widget? Yes, you can use the `tabContainerId` and the related record widget will add tabs to the attribute table widget's tab container.

**Comment by carrbrpoa** [comment]
Hey @roemhildtg,
Actually I want to do what you described in [Include in Identify Popup section](https://github.com/roemhildtg/cmv-widgets/tree/master/widgets/RelationshipTable#include-in-identify-popup). 

What if I would like to show the "normal popup info" + the related data? In your example, seems that the related data clear all the rest. Would I need to handle it manually?

**Comment by saurabhgis** [comment]
@roemhildtg I am working on Attribute Table Widget with Advance Search Widget, need to implement field alias like identify widget but not able to know how we can do this?

**Comment by tmcgee** [comment]
@saurabhgis Your question has been addressed in  [issue 82](https://github.com/tmcgee/cmv-widgets/issues/82) you posted in my widgets repo. Any follow up should occur there.

**Comment by ERS-Long** [comment]
@carrbrpoa Hi, Could you please let us know if you could do the "normal popup info" + the related data in the popup and how. Thanks!

**Comment by ERS-Long** [comment]
Managed to get this going, seems like in @roemhildtg relationship function, the 'data' object includes all the info, not just the related record. Great related record widget!  I also managed to use an array to handle one of my layers that has 4 relationships.

**Comment by roemhildtg** [comment]
@ERS-Long, yes that code snippet function `data` is the identify graphic with attributes. That's actually provided by the identify widget content function though, and then that data is passed to the related records widget which performs your `getRelatedRecords` logic

**Comment by ERS-Long** [comment]
@roemhildtg, only one issue left so far, the date field in the related grid, I could not figure out how to format it from epoch to correct format. Please see if you have a solution already or not. Thanks a lot!

**Comment by carrbrpoa** [comment]
Hey @ERS-Long,

Considering you have a function like the following declared in your `config/searchWidget.js`:

```javascript
function formatDateTime(value) {
	if (!value)
		return '';
	var date = new Date(value);
	return locale.format(date, {
		formatLength : 'short'
	});
}
```
...you can declare a `gridOptions`'s `column` like this:

```javascript
{
	field : 'LAST_EDITED_DATE',
	label : 'Data de Edição',
	get : function (object) { // allow export as a proper date
		if (object.LAST_EDITED_DATE) {
			return new Date(object.LAST_EDITED_DATE);
		}
	},
	formatter : formatDateTime
}
```

**Comment by tmcgee** [comment]
Considering this issue has been closed for a year and a half, maybe the conversation should continue in a new issue with a specific topic? Perhaps that belongs in @roemhildtg [cmv-widgets](https://github.com/roemhildtg/cmv-widgets/issues) repo? just a suggestion. :smile:
