### ISSUE TITLE
Help configuring mediaInfos config/identify.js

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#159]
I am trying to get this to work but not having much luck. I would like to have a picture show up in my pop-up. I am trying to provide a url and concatenate a parcel id value to the end, so no matter which parcel you click on the correct image appears. My issue seems to be the sourceURL is not recognizing the field {PIN}, thoughts on what I am doing wrong?

Here is my code:

``` javascript
        parcels: {
            15: {
                title: "Parcels",
                fieldInfos: [{
                    fieldName: "PIN",
                    label: "Parcel ID : ",
                    visible: !0
                }, {
                    fieldName: "FULLADDR",
                    visible: !0
                }, {
                    fieldName: "OWN1",
                    visible: !0
                }, {
                    fieldName: "OWN2",
                    visible: !0
                }, {
                    fieldName: "ACRES",
                    visible: !0
                }],
                mediaInfos: [{
                    value: {
                        sourceURL: "http://www.clermontauditorrealestate.org/iDocs/iPhotoDownload.aspx?pin={PIN}"
                    }
                }],
            },
```

**Comment by carrbrpoa** [comment]
Do you have any suggestions to *toggle/render* the display of mediaInfos whether or not for example *{Location URL}* is a valid one?

**Comment by tmcgee** [comment]
@carrbrpoa You would have to use a JavaScript function to test the value and return JSON. Can you please create a new issue to continue the discussion?

**Comment by carrbrpoa** [comment]
Sure, [Issue 437](https://github.com/cmv/cmv-app/issues/437) created.
