### ISSUE TITLE
Their are 2 combobox , 1st combobox is getting populated from mapservice, I want the 2nd combobox to be populated from the same mapservices based on the selection of 1st combobox 

### ISSUE THREAD

**Issue by chissarya** [cmv/cmv-app#163]
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no">
    <title>Tank I</title>

    <link rel="stylesheet" href="http://js.arcgis.com/3.10/js/dojo/dijit/themes/claro/claro.css">
    <link rel="stylesheet" href="http://js.arcgis.com/3.10/js/dojo/dojox/grid/resources/Grid.css">
    <link rel="stylesheet" href="http://js.arcgis.com/3.10/js/dojo/dojox/grid/resources/claroGrid.css">
    <link rel="stylesheet" href="http://js.arcgis.com/3.10/js/esri/css/esri.css">
    <style>
      html, 
	  body {
	  height: 100%; 
	  width: 100%;
	  margin: 0;
	  padding: 0; 
	  }

        #header {
            background-image: url(TIS_HEADER.jpg);
		 
            background-repeat: repeat-x;
            border: solid 4px #224a54;
            color: #FFF;
            font-size: 18pt;
            text-align: left;
            font-weight: 700;
            height: 70px;
            margin: 2px;
        }
        #leftPane {
			//background-image: url(tank.jpg);
            background-color: #FFF;
            color: #3f3f3f;
            border: solid 2px #224a54;
            width: 20%;
            margin: 5px;
            padding: 2px;
        }
		 #map {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
        }
		#HomeButton {
            position: absolute;
            top: 220px;
            left: 280px;
            z-index: 50;
        }

    </style>
    <script src="http://js.arcgis.com/3.10/"></script>
    <script>
      require([
        "esri/map",  "esri/layers/ArcGISTiledMapServiceLayer",
        "esri/tasks/FindTask",
        "esri/tasks/FindParameters",
        "esri/symbols/SimpleMarkerSymbol",
        "esri/symbols/SimpleLineSymbol",
        "esri/symbols/SimpleFillSymbol",
          
        "esri/Color",
        "dojo/on",
        "dojo/dom",
        "dijit/registry",
        "dojo/_base/array",
        "dojo/_base/connect",
        "dojox/grid/DataGrid",
        "dojo/data/ItemFileReadStore",
        "dijit/form/Button",
        "dojo/parser",
		"dojo/store/Memory", 
		"dijit/form/FilteringSelect",
		"esri/graphicsUtils",
		"dijit/form/ComboBox",
		"dojo/dom-construct", 
		"esri/main", 
		"esri/dijit/Attribution",
		"esri/layers/FeatureLayer",
		"esri/geometry/Extent",
		"esri/InfoTemplate",
          "esri/dijit/HomeButton", 
		
        "dijit/layout/BorderContainer",
        "dijit/layout/ContentPane",
		"dijit/layout/TabContainer",
      
        "dojo/domReady!"
      ], function(
        Map,Tiled, FindTask, FindParameters, SimpleMarkerSymbol, SimpleLineSymbol, SimpleFillSymbol,
        Color, on, dom, registry, array, connect, DataGrid, ItemFileReadStore, Button, parser,Memory,FilteringSelect, graphicsUtils, ComboBox,omConstruct, esri, Attribution,FeatureLayer,Extent,InfoTemplate,HomeButton
      ) {      
        var findTask, findParams;
        var map, center, zoom;
        var grid, store, store1;
		var prevdname;
		var prevtname;
        parser.parse();        
        registry.byId("search").on("click", doFind);
		var tiled = new Tiled("service.....StateBasemap/MapServer");
 		 var bounds = new Extent({
                "xmin": 7583508.66876001,
                "ymin": 754519.306341084,
                "xmax": 10843390.8045407,
                "ymax": 4451565.92247309,
                "spatialReference": {
                    "wkid": 3857
                }
            });
           var map = new Map("map", {extent: bounds});
		   var u = " service...........................MapServer/1";
            var template = new InfoTemplate("Tank Information System", "<tr>Taluk:Hungund</tr><br><tr>Catchment Slope : <td>${CatchmentS}</tr></td><br><tr>Catchment LULC:<td>${CatchmentL}</tr></td><br><tr>Catchment_Area:<td>${Catchment_}</tr></td><br><tr>Channel_Length:<td>${Supplychan}Meters</tr></td><br><tr>TankArea_Ha:<td>${TankArea_H}</tr><br><tr>Water Spread:<td>${WaterSprea}</tr><br><tr>Percentage of WaterSpreadToCatchment:<td>${perOfwsToC}</tr><br><tr>Percentage of WaterSpreadToTank:<td>${perOfwsToT}</tr><br><tr>Bund_Status:<td>${Bund_Statu}</tr><br><tr>Population:<td>${Population}</tr></td></td>");
            var fl = new FeatureLayer(u, {
                id: "1",outFields: ["*"],
                infoTemplate: template.
            });
           var home = new HomeButton({
                map: map
            }, "HomeButton");
           var populateList = function(results) {
            //Populate the ComboBox with unique values
            var zone;
            var values = [];
            var testVals = {};
         //Add option to display all zoning types to the ComboBox
				values.push({name: "Select District"})
					
					//Loop through the QueryTask results and populate an array
					//with the unique values
					var features = results.features;
					array.forEach(features, function(feature) {
						zone = feature.attributes.DistrictCode ;
						if (zone) {
							if (!testVals[zone]) {
								testVals[zone] = true;
								values.push({	name: zone});
							}
						}
					});
					
					//Create a ItemFileReadStore and use it for the
					//ComboBox's data source
					var dataItems = {
						identifier: 'name',
						label: 'name',
						items: values
					};
					var store = new ItemFileReadStore({
						data: dataItems
					});
					registry.byId("District").set('store', store);
					
				}
				
		  queryTask = new esri.tasks.QueryTask("service................................MapServer/74");
		  var query = new esri.tasks.Query();
		  query.returnGeometry = false;
		  query.outFields = ["DistrictCode"];
		  query.where = "DistrictCode <> ''";
		  queryTask.execute(query, populateList);
	
			var populateList1 = function(results) {
            //Populate the ComboBox with unique values
            var zone1;
            var values1 = [];
            var testVals1 = {};

		       //Add option to display all zoning types to the ComboBox
					values1.push({name: "Select Taluk"})
        			var features1 = results.features;
	                array.forEach(features1, function(feature) 
					{
					zone1 = feature.attributes.TalukName ;
						if (zone1) {
							if (!testVals1[zone1] ) {
								testVals1[zone1] = true;
								values1.push({name: zone1});
							}
						}
                   });
					
					//Create a ItemFileReadStore and use it for the
					//ComboBox's data source
					var dataItems1 = {
						identifier: 'name',
						label: 'name',
						items: values1
					};
					var store1 = new ItemFileReadStore({
						data: dataItems1
					});
					
					registry.byId("Taluk").set('store', store1);
				}

		   var query1 = new esri.tasks.Query();
		  query1.returnGeometry = false;
		  query1.outFields = ["TalukName"];
		prevdname=dom.byId("District").value;
		query1.where = "DistrictCode = '" + dom.byId("District").value + "'"; 
		queryTask.execute(query1, populateList1);

        //Create Find Task using the URL of the map service to search
        findTask = new FindTask("service.......................................MapServer");

          map.on("load", function () {
          //Create the find parameters
          findParams = new FindParameters();
          findParams.returnGeometry = true;
          findParams.layerIds = [74];
          //findParams.searchFields = ["DistrictCode ","FID","T_NAME"];
          findParams.outSpatialReference = map.spatialReference;
          console.log("find sr: ", findParams.outSpatialReference);
        });
		 function doFind() 
		{
		if(findParams.searchText = dom.byId("District").value)
			{
				if (prevdname != dom.byId("District").value)
				{
					findParams.searchFields = ["FID","DistrictCode","TalukName"];
					findTask.execute(findParams, showResults);
				}
            }			
			prevtname=dom.byId("Taluk").value;
			prevdname=dom.byId("District").value;
	 	} 
		
        function showResults(results) {
          //This function works with an array of FindResult that the task returns
          map.graphics.clear();
          var symbol = new SimpleFillSymbol(
            SimpleFillSymbol.STYLE_SOLID, 
            new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID, new Color([98, 194, 204]), 1), 
            new Color([98, 194, 204, 0.5])
          );

          //create array of attributes
            var items = array.map(results, function (result) {
            var graphic = result.feature;
            graphic.setSymbol(symbol);
            map.graphics.add(graphic);
			var extent = esri.graphicsExtent(map.graphics.graphics);  
			map.setExtent(extent, true); 
            return result.feature.attributes;
          });

        }

        //Zoom to the parcel when the user clicks a row
        function onRowClickHandler2(evt) {
          var clickedTaxLotId = evt.grid.getItem(evt.rowIndex).DistrictCode ;
          var selectedTaxLot = arrayUtils.filter(map.graphics.graphics, function (graphic) {
            return ((graphic.attributes) && graphic.attributes.DistrictCode  === clickedTaxLotId);
          });
          if ( selectedTaxLot.length ) {
            map.setExtent(selectedTaxLot[0].geometry.getExtent(), true);
          }
        }
            map.addLayer(tiled);
            map.addLayer(fl);
            home.startup();
      }); 
  </script>
  </head>
  <body class="claro">
 <div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design:'headline'"  style="width:100%;height:100%;margin:0;">
  <div id="header" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region:'top'">
       <div id="title"></div> </div>
	 <div data-dojo-type="dijit.layout.ContentPane" id="leftPane" data-dojo-props="region:'left'">
        <div data-dojo-type="dijit.layout.TabContainer">
           <div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title:'Table of Content', selected:'true'">Content for the first tab</div>
                <div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title:'Search'"> Content for the second tab
                   <select id="District" dojotype="dijit.form.ComboBox" style="width:200px;font-size:16px;"
					autoComplete="true"
					forceValidOption="true"
					value=""></select>
                    
				   <select id="Taluk"  dojotype="dijit.form.ComboBox"  style="width:200px;font-size:16px;"  
                   autoComplete="true"  
                   forceValidOption="true"  
                   value=""> </select> 
 	               <button id="search" data-dojo-type="dijit/form/Button" type="button" data-dojo-attach-point="button" >Search</button>
                </div>
            </div>
        </div>
    <div id="map" data-dojo-props="region:'center'" data-dojo-type="dijit/layout/ContentPane" style="border:1px solid #000;"></div></div>
   <div id="HomeButton"></div>
  </body>
</html>

**Comment by chissarya** [comment]
Thank  You .

**Comment by saurabhgis** [comment]
@DavidSpriggs I have checked code in that combobox bind using json, I need to bind from mapservice.

**Please help and thanks in advance if someone share the code CMV widget of the same requirement.**

**Comment by tmcgee** [comment]
@saurabhgis my [Zoom To Feature widget](https://github.com/tmcgee/cmv-widgets#zoom-to-feature) populates the dropdown from a map service layer. You can combine that with the dependencies in the swingley demo to get what you are after.
