### ISSUE TITLE
Detached widget gets closed in sidebar unless it is moved.

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#166]
If you detach a widget in the sidebar, then *without moving* the detached widget, close the sidebar. 

The detached widget disappears along with the sidebar. Minor I know, but I would have expected any detached widget to remain on the display, regardless of whether they were open or not.

**Comment by tmcgee** [comment]
I think this was addressed with the enhancements to detachable/movable sidebar widgets included in v. 1.3.3 and improved in v 1.3.4
