### ISSUE TITLE
showAttachments not honored in Identify.js against MapService

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#177]
REST Service : http://engineer05.gomvo.org/arcgis/rest/services/SP/RoadRecords/MapServer

LayerId: 13

identify.js 
```javascript
roadrecords: {
            13: {
                title: 'Road Records Index',
                showAttachments: true,
                description: [
                    '<table class="attrTable">',
                    '<tr valign="top">',
                    '<td class="attrName">Document :</td>',
                    '<td class="attrValue">{Document}</td>',
                    '</tr>',
                    '</table>'
                ].join('')
            }
```

viewer.js
```javascript
{
		    type: 'dynamic',
		    url: 'http://engineer05.gomvo.org/arcgis/rest/services/SP/RoadRecords/MapServer',
		    title: 'Road Records',
		    noLegend: true,
		    collapsed: true,
		    identifyLayerInfos: {
		        layerIds: [1, 3, 5, 7, 9, 11, 13]
		    },
		    options: {
		        id: 'roadrecords',
		        opacity: 1.0,
		        visible: true
		    }
```

Attachments are not showing in popup.

**Comment by kcarrier** [comment]
@tmcgee - I see this was looked at on Nov 25, 2014 wondering if it is still on the radar or if there is a fix I have not found yet. I essentially want to setup popups where the attachment will come across in the popup as mentioned a while back. I know you all are continuing to work hard on this and trust me it is appreciated, just curious on your thoughts about when this might make it in?

**Comment by tmcgee** [comment]
@kcarrier to my knowledge there's been no further investigation into this even as to whether an enhancement required or a different configuration. I will do some more research on the issue if you or anyone can provide a public url to a MapServer that has attachments?

**Comment by rkoelpin** [comment]
Here is an arcserver service



https://gis.dhs.in.gov/arcgis/rest/services/OpenAccess/EditParcelsD5_Small/FeatureServer



Do you need the ArcGIS online url with credentials too?

________________________________

**Comment by kcarrier** [comment]
Here is another one, it is a point service

layerIds: [1,3,5,7,9,11,13]

http://engineer.gomvo.org/arcgis/rest/services/WMAS/MCEO_SurveyRecords/MapServer

Here is some code I was using

viewer.js:
```javascript
operationalLayers: [{
            type: 'dynamic',
            url: 'http://engineer.gomvo.org/arcgis/rest/services/WMAS/MCEO_SurveyRecords/MapServer',
            title: 'Survey Records',
            options: {
                id: 'SurveyRecords',
                opacity: 1.0,
                visible: true,
                imageParameters: imageParameters
            },
            identifyLayerInfos: {
                layerIds: [1,3,5,7,9,11,13]
            }
  },
```
identify.js:
```javascript
SurveyRecords: {
	        1: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        },
	        3: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        },
	        5: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        },
	        7: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        },
	        9: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        },
	        11: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        },
	        13: {
	            title: 'SURVEY_NUMBER',
	            showAttachments: true,
	            fieldInfos: [{
	                fieldName: 'SURVEY_NUMBER',
	                visible: true
	            }]
	        }
		},
```

**Comment by tmcgee** [comment]
@rkoelpin @kcarrier thank you. I guess if I was paying full attention last night, I would have noticed/remembered that kcarrier provided another example in the initial description of this issue. Now I have 3 examples to investigate. ;)

**Comment by kcarrier** [comment]
@tmcgee - Thanks for looking into this, let me know if you need anything else.

**Comment by taran03** [comment]
Along these lines, I just noticed an issue in my CMV application with opening attachments on a secured service via the attachment link in the feature's ID pop up window.  The attachment links display as intended in the pop up window, but when the user clicks on the attachment link the URL is calling for a redirect that requires the user to authenticate with our ArcGIS Server in order to see the attached image. Of course, the attachments work fine if the service is public. I'm already using proxy to auto authenticate user access to secure services, so I'm a little stumped as to why clicking on the attachment link leads to a login redirect page (the standard ArcGIS Server REST API Login page) instead of direct authentication from the functioning proxy. Any thoughts as to whether this is an ESRI thing or a CMV issue?  Thanks.

![image](https://cloud.githubusercontent.com/assets/8386074/6419781/d1aa8394-be85-11e4-9197-481ea7e947fa.png)

![image](https://cloud.githubusercontent.com/assets/8386074/6419790/df4038fa-be85-11e4-8373-8dc1bcd680c5.png)

**Comment by tmcgee** [comment]
@taran03 All of the logic for displaying the contents within the InfoWindow including the list of attachments and opening those attachments is handled by the ESRI JS API. Sorry if that comes across like I'm passing the buck. ;)

**Comment by taran03** [comment]
Ok, that is what I suspected. Thanks for confirming this.

**Comment by kcarrier** [comment]
@tmcgee - I know you have other things in your life to do but I was just curious what the initial findings were from the examples we were able to provide.

**Comment by tmcgee** [comment]
@kcarrier Sorry, I have not had the opportunity yet.

**Comment by kcarrier** [comment]
@tmcgee - Hope you had a good time at DevSummit, just checking in.

**Comment by tmcgee** [comment]
@kcarrier this is still on my "when I get around to it" list.

**Comment by tmcgee** [comment]
@kcarrier: I finally spent some time this afternoon to look into this. This defauly map functionality behind the mapclick is not well documented in the API docs beyond what @DavidSpriggs mentioned about the `setInfoWindowOnClick` method to turn it on/off.  In essence they treat each sublayer in a dynamic layer as if it were a feature layer - that's is why the `showAttachments` behaves similar to that of a feature layer.  They then use multiple QueryTasks per layer (one per sub layer) to get the identify results instead of a single IdentifyTask per layer as we do in CMV. 

You can use the built-in functionality within the map in CMV. You will need to not include the identify widget in your app and you will need to define your infoTemplates directly within each operationalLayer like this:

```
{
        type: 'dynamic',
        url: 'http://engineer.gomvo.org/arcgis/rest/services/WMAS/MCEO_SurveyRecords/MapServer',
        title: 'Survey Records',
        options: {
            id: 'SurveyRecords',
            opacity: 1.0,
            visible: true,
            imageParameters: imageParameters,
            infoTemplates: {
                1: {
                    infoTemplate: new PopupTemplate({
                        title: 'SURVEY_NUMBER',
                        showAttachments: true,
                        fieldInfos: [{
                            fieldName: 'SURVEY_NUMBER',
                            visible: true
                        }]
                    })
                }
            }
        }
}
```

I have not tested whether this plays nice with other cmv widgets that interact with the map so there may be a can of worms there.

I'm not sure if it a good idea or not to do away with the current Identify widget completely within CMV and rely on this undocumented functionality. That would require more discussion. I'm not a fan of their approach since using QueryTask as ESRI does instead of IdentifyTask is certainly less efficient for the server and the client.

Now that I have a better understanding of what they are doing and why it behaves the way it does, I have a few thoughts to explore how we might incorporate similar `showAttachments` functionality for dynamic layers within the cmv identify widget.

**Comment by kcarrier** [comment]
@tmcgee - I just tested the code above and it does not work as expected. Still no attachments coming through in the Popup Window, just the Survey Number comes through in the title and in the field section.

**Comment by tmcgee** [comment]
Hmm. I used the exact layer config that I posted above and the attachments were there in the InfoWindow. Did you disable the cmv Identify widget? That's an integral step to getting this to work..

**Comment by kcarrier** [comment]
@tmcgee - Disabling the identify fixed it, sorry glossed over that step. So rather than build the identifies in the identify.js file, I would just build them within viewer.js correct? Thanks for the prompt reply very much appreciated!

**Comment by kcarrier** [comment]
@tmcgee - Thanks again for all the help!

**Comment by igover007** [comment]
@DavidSpriggs , @tmcgee . Hi all, love the work going on here. Just wondering, with regard to the  showInfoWindowOnClick  functionality, where abouts in CMV do I setInfoWindowOnClick(true); ?
Thanks again for working on this.

**Comment by tmcgee** [comment]
@igover007 There isn't anything to set for this functionality. The default value is true.

**Comment by kcarrier** [comment]
@tmcgee - It appears I might not be able to use the description method in the viewer.js file, it is like it does not recognize anything except the first field value, all other field values come back blank. The attachments still work as you explained earlier but now the field values are not coming through as they were in the identify.js file. When I use fieldInfos[{}] as specified in the Esri JS API documentation the values come through, any thoughts. My code example can be seen below, the map service is publicly accessible.

https://gist.github.com/kcarrier/d28cec24ebc9a2f4f708

**Comment by tmcgee** [comment]
@kcarrier the description property in your example looks correct (when used in identify.js). This `infoTemplates` functionality for dynamic layers is relatively new and not well documented so it could be that the description parameter is not (yet) supported by the API for a dynamic layer's infoTemplates array.

**Comment by kcarrier** [comment]
@tmcgee - I think I see where I screwed up I did not close the table </table>

**Comment by kcarrier** [comment]
@tmcgee - I am trying to allow for the attachments to be visible and this is working the issue I am running into now is that I have some fields which have hyperlinks and i am not sure how to set the code up to support both hyperlinks and showAttachments. The question I guess I need to try and figure out is there any way of having a hyperlink value inside of fieldInfos.

description works but only for the first field and I am not sure if it is possible to get a hyperlink inside of fieldInfos any thoughts?

```
{
            type: 'dynamic',
            url: 'http://maps6.cityoftrenton.com/arcgis/rest/services/Water/WaterLayers/MapServer',
            title: 'Water Assets',
            noLegend: true,
            collapsed: true,
            options: {
                id: 'waterassets',
                opacity: 1,
                visible: true,
                imageParameters: imageParameters,
                infoTemplates: {
                    1: {
                        infoTemplate: new PopupTemplate({
                            title: 'Water Curb Stop Valve',
                            showAttachments: true,
                            description:[
                            '<table class="attrTable">',
                            '<tr valign="top">',
                            '<td class="attrName">Control Station Data Sheet :</td>',
                            '<td class="attrValue"><a href="{HYPERLINK}" target="_blank">Click Here</a></td>',
                            '</tr>',
                            '</table>'
                            ].join('')
                            fieldInfos: [
                            { fieldName: 'MAPREF', label: 'MAPREF : ', visible: true },
                            { fieldName: 'FACILITYID', label: 'Facility ID : ', visible: true },
                            { fieldName: 'LOCDESC', label: 'Address : ', visible: true },
                            { fieldName: 'ROTATION', label: 'Rotation : ', visible: true },
                            { fieldName: 'DIAMETER', label: 'Diameter : ', visible: true },
                            { fieldName: 'VALVETYPE', label: 'Valve Type : ', visible: true },
                            { fieldName: 'NORMALLYOPEN', label: 'Normally Open : ', visible: true },
                            { fieldName: 'TURNSTOCLOSE', label: 'Turns To Close : ', visible: true },
                            { fieldName: 'OPERABLE', label: 'Operable : ', visible: true },
                            { fieldName: 'CURROPEN', label: 'Currently Open : ', visible: true },
                            { fieldName: 'ACTIVEFLAG', label: 'Active : ', visible: true },
                            { fieldName: 'OWNEDBY', label: 'Owned By : ', visible: true },
                            { fieldName: 'MAINTBY', label: 'Managed By : ', visible: true },
                            { fieldName: 'Install_Year', label: 'Install Year : ', visible: true }
                            ]
                        })
                    }
                },
                layerControlLayerInfos: {
                    sublayers: false
                }
            }
        }
```

**Comment by kcarrier** [comment]
@tmcgee - I think I figured out how to get description to work in conjunction with fieldInfos. I was trying some different methods and move fieldInfos above description and with both of them under the PopupTemplate it is now working and I can have hyperlinks and attachments, in case anyone ever runs across this, here is how I got it to work

```
{
            type: 'dynamic',
            url: 'http://maps6.cityoftrenton.com/arcgis/rest/services/Water/WaterLayers/MapServer',
            title: 'Water Assets',
            noLegend: true,
            collapsed: true,
            options: {
                id: 'waterassets',
                opacity: 1,
                visible: true,
                imageParameters: imageParameters,
                infoTemplates: {
                    1: {
                        infoTemplate: new PopupTemplate({
                            title: 'Water Curb Stop Valve',
                            showAttachments: true,
                            fieldInfos: [
                            { fieldName: 'FACILITYID', label: 'Facility ID : ', visible: true },
                            { fieldName: 'MAPREF', label: 'MAPREF : ', visible: true },
                            { fieldName: 'LOCDESC', label: 'Address : ', visible: true },
                            { fieldName: 'ROTATION', label: 'Rotation : ', visible: true },
                            { fieldName: 'DIAMETER', label: 'Diameter : ', visible: true },
                            { fieldName: 'VALVETYPE', label: 'Valve Type : ', visible: true },
                            { fieldName: 'NORMALLYOPEN', label: 'Normally Open : ', visible: true },
                            { fieldName: 'TURNSTOCLOSE', label: 'Turns To Close : ', visible: true },
                            { fieldName: 'OPERABLE', label: 'Operable : ', visible: true },
                            { fieldName: 'CURROPEN', label: 'Currently Open : ', visible: true },
                            { fieldName: 'ACTIVEFLAG', label: 'Active : ', visible: true },
                            { fieldName: 'OWNEDBY', label: 'Owned By : ', visible: true },
                            { fieldName: 'MAINTBY', label: 'Managed By : ', visible: true },
                            { fieldName: 'Install_Year', label: 'Install Year : ', visible: true }
                            ],
                            description: [
                            '<table class="attrTable">',
                            '<tr valign="top">',
                            '<td class="attrName">Diameter :</td>',
                            '<td class="attrValue"><a href="{DIAMETER}" target="_blank">{DIAMETER}</a></td>',
                            '</tr>',
                            '<tr valign="top">',
                            '<td class="attrName">MAPREF :</td>',
                            '<td class="attrValue"><a href="{MAPREF}" target="_blank">{MAPREF}</a></td>',
                            '</tr>',
                            '<tr valign="top">',
                            '<td class="attrName">VALVETYPE :</td>',
                            '<td class="attrValue"><a href="{VALVETYPE}" target="_blank">{VALVETYPE}</a></td>',
                            '</tr>',
                            '</table>'
                            ].join('')
                        })
                    }
                },
                layerControlLayerInfos: {
                    sublayers: false
                }
            }
        }
```

**Comment by rutzmosh** [comment]
I found this thread looking for answer, my popups were not showing attachments in for dynamic layers, I needed for only a few items...add similar lines starting around line 288 of the identify.js file.
Basically you can hijack the identify use the default htmlPopup template for the layers of interest...default works fine but you can get really fancy with the html popup prior to publishing your map service.

                        if (infoTemplate) {
                            //custom handle layers with attachments work around for now...
                            if (infoTemplate.info.title == 'My layer with attachments'){
                                 infoTemplate.setTitle("<b>My layer with attachmentss</b>");
                                 infoTemplate.setContent("<iframe src='https://your_url.com/arcgis/rest/services/Utilites/MapServer/0/${OBJECTID}/htmlPopup?f=html' frameborder='0' width='275px' height='800px' style='width: 275px; height: 800px; display: block; padding: 0px; margin: 0px;'></iframe>");
                            }                           
                            result.feature.setInfoTemplate(infoTemplate);
                        } else
