### ISSUE TITLE
Add the Widget IMPORT CSV file or Enter points by Coordinate Lat Long Text box in Measurement

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#200]
Add  the Widget IMPORT CSV file or Enter points by Coordinate Lat Long Text box in Measurement
 http://gis.icao.int/DRAGDROP/

**Comment by tmcgee** [comment]
Closing since there is now a [contributed widget](https://github.com/BrianBunker/cmv-widgets/tree/master/DnD) for this.
