### ISSUE TITLE
More robust search widget?

### ISSUE THREAD

**Issue by taran03** [cmv/cmv-app#207]
Is there any interest in expanding the capabilities of the current "Find" widget in CMV?  I found this rather robust Flexviewer search widget that allows users to build simple queries on the fly and even in some cases provides dropdown/picklists of valid attributes or domains for a selected field. 

http://www.arcgis.com/home/item.html?id=5d4995ccdb99429185dfd8d8fb2a513e#!

Seems like a similar tool could be a great addition to the CMV?  Specifically, I think the tool's function of providing a dropdown/picklist of attributes from the user's selected field allows the map user an intuitive and easy way to query data for map display.  See below for a picture of the Flex tool that illustrates this. The current CMV find widget has great functionality, but it assumes the map user knows enough about the layer's attributes to enter valid or somewhat valid search criteria.  Thanks!   

![image](https://cloud.githubusercontent.com/assets/8386074/4238816/050a0d10-39dc-11e4-9444-6efe54e89b5d.png)

**Comment by saurabhgis** [comment]
Hello @tmcgee Sir

I am interested on this search widget and not able to find in current release.

Sir I am learner and follows you in development and at this point need your help and guidance.

If possible share search widget with me on my email id : sbh.upd1@gmail.com

**Comment by saurabhgis** [comment]
@tmcgee Sir

I have seen your search widget which fullfill my basic requirement. Please share widget code.


![tr](https://cloud.githubusercontent.com/assets/10755932/6038965/0d6bf3dc-ac88-11e4-8ce2-ba43a4ae107b.png)

**Comment by taran03** [comment]
Hi @tmcgee

Wondering if you still have plans to release a search/query task widget for the CMV in the near future?  

Thanks!

**Comment by msamwill** [comment]
I created a search widget.  It's nothing special.  It is a copy of the find widget but the find task has been replaced with the query task.  It can display additional attribute fields other than the one you are searching (This is the reason I had to create this widget).  It also has an autocomplete feature.  The feature(s) are not auto selected.  You click on a feature in the grid and it zooms to it.   
![search](https://cloud.githubusercontent.com/assets/7591429/6402832/bc4eb8ec-bdd8-11e4-99d5-70be34eb5e7f.png) 
The config file looks like the below.  The commented out layers are examples of different things you can do with the where clause.

define({
	map: true,
	queries: [
	    {
            description: 'Find A Fire Station Location By Name',
            url: 'http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/PublicSafety/PublicSafetyOperationalLayers/MapServer/1',
            where: "FDNAME LIKE '${0}%' ",
            outFields: ["SITEID", "FDNAME", "ADDRESS"],
            dgridColumns: {
                SITEID: "ID",
                FDNAME: "NAME",
                ADDRESS: "ADDRESS"
            },
            dgridSort: [ {attribute: "NAME", descending: false}],
            minChars: 3
        },
        {
            description: 'Find A Police Station Location By Name',
            url: 'http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/PublicSafety/PublicSafetyOperationalLayers/MapServer/2',
            where: "FDNAME LIKE '${0}%' ",
            outFields: ["SITEID", "PDNAME", "ADDRESS"],
            dgridColumns: {
                SITEID: "ID",
                PDNAME: "NAME",
                ADDRESS: "ADDRESS"
            },
            dgridSort: [ {attribute: "PDNAME", descending: false}],
            minChars: 3
        }
		
        //{
        //    description: 'Find Parcel By Site Address',
        //    url: 'http://'  + GISServerName + '/arcgis/rest/services/mapapp/cama/MapServer/3',
        //    where: "UPPER(PROP_ADDRESS) + UPPER(PROP_CITY) LIKE '%${0}%'",
        //    outFields: ['JOIN_STRAP', 'PROP_ADDRESS', 'PROP_CITY'],
        //    dgridColumns: {
        //        "JOIN_STRAP": "STRAP",
        //        "PROP_ADDRESS": "PROP ADDRESS",
        //        "PROP_CITY": "PROP CITY"
        //    },
        //    dgridSort: [{ attribute: "JOIN_STRAP", descending: false }],
        //    minChars: 3
        //},
		//{
		//	description: 'Find Owner By Name',
		//	url: 'http://'  + GISServerName + '/arcgis/rest/services/mapapp/cama/MapServer/2',
		//	where: "UPPER(OWN_NAME1) LIKE '%${0}%' OR UPPER(OWN_NAME2) LIKE '%${0}%'",
		//	outFields: ['JOIN_STRAP', 'OWN_NAME1', 'OWN_NAME2'],
		//	dgridColumns: {
		//	    "JOIN_STRAP": "STRAP",
		//	    "OWN_NAME1": "OWN_NAME1",
		//	    "OWN_NAME2": "OWN_NAME2"
		//	},
		//	dgridSort: [{ attribute: "JOIN_STRAP", descending: true }],
		//	minChars: 3
		//},
		//{
		//	description: 'Find Subdivision By Name',
		//	url: 'http://'  + GISServerName +  '/arcgis/rest/services/Toggle_Subdivisions/MapServer/0',
		//	where: "UPPER(CNVYNAME) LIKE '%${0}%' ",
		//	outFields: ['CNVYNAME'],
		//	dgridColumns: {
		//	    "CNVYNAME": "NAME"
		//	},
		//	dgridSort: [{ attribute: "JOIN_STRAP", descending: false }],
		//	minChars: 4
		//}
	]
});
This is the css file:
.gis_SearchDijit {
    width: 100%;
}
.gis_SearchDijit .querySelect, .gis_SearchDijit .searchText {
	width:100%;
	margin-bottom: 10px;
}

.gis_SearchDijit .containsCheck {
	margin-bottom: 10px;
	margin-left: 10px;
}

.gis_SearchDijit .clearButton {
	float: right;
}

.gis_SearchDijit .searchIcon {
    background-image: url(../images/search.png);
    width: 16px;
    height: 16px;
}

.gis_SearchDijit .clearIcon {
    background-image: url(../images/clear.png);
    width: 16px;
    height: 16px;
}

.gis_SearchDijit label {
	font-weight:bold;
	margin-left: 5px;
}

.gis_SearchDijit .resultsContainer {
	font-weight: bold;
	margin: 10px;
	display: none;
}

.gis_SearchDijit .dgrid {
	/*height: 240px !important;
	width:100%;*/
	display: none;
}

.gis_SearchDijit .dgrid-grid {
	height: 240px !important;
	width:100%;
	/*display: none;*/
}

.gis_SearchDijit .dgrid .dgrid-scroller {
	margin-top: 35px !important;
}

.gis_SearchDijit .dgrid .dgrid-header th {
	font-weight: bold;
}

.gis_SearchDijit .dgrid .dgrid-cell {
	font-size: 11px;
	padding: 8px !important;
    width: 100px;
	cursor: pointer;
}

.gis_SearchDijit .dgrid .field-JOIN_STRAP {
	width: 120px;
}

.gis_SearchDijit .dgrid .field-foundFieldName {
	display: none;
}

This is the resource.js file:
// http://dojotoolkit.org/reference-guide/1.10/dojo/i18n.html
define({
   root: {
       selectQuery: 'Select query',
       searchText: {
           label: 'Search for',
           placeholder: 'Enter the text you want to search for.'
       },
       exactMatches: 'Find exact matches only',
       searchButton: {
           label: 'Search',
           busyLabel: 'searching'
       },
       clearButton: {
           label: 'Clear'
       },
       searching: 'Searching...',
       resultsLabel: {
           multipleResultsSuffix: 's',
           labelPrefix: 'Result',
           labelSuffix: 'found',
           noResults: 'No Results Found'
       }
   }
});

This is the html template:
<div class="gis_SearchDijit" >
    <div class="formContainer">
        <div data-dojo-type="dijit/form/Form" data-dojo-attach-point="searchFormDijit">
            <div data-dojo-attach-point="querySelectDom">
                <label>${i18n.selectQuery}:</label><br/>
    			<input type="select" data-dojo-type="dijit/form/FilteringSelect" data-dojo-props="name:'query',autoComplete:true,required:true,searchAttr:'description','class':'querySelect'" data-dojo-attach-point="querySelectDijit" data-dojo-attach-event="onChange:_onQueryChange"/>
            </div>
            <div data-dojo-attach-point="queryTextDom">
                <label>${i18n.searchText.label}:</label><br/>
    			<input id="searchTextDijit" type="text" data-dojo-type="dijit/form/ValidationTextBox" data-dojo-attach-point="searchTextDijit" data-dojo-props="name:'searchText',uppercase:true,trim:true,required:true,value:'',placeholder:'${i18n.searchText.placeholder}','class':'searchText'" /><br/>
            </div>
            <div data-dojo-type="dijit/form/Button" data-dojo-props="busyLabel:'${i18n.searchButton.busyLabel}',iconClass:'fa fa-search fa-fw','class':'searchButton'" data-dojo-attach-event="onClick:search" data-dojo-attach-point="searchButtonDijit">
                ${i18n.searchButton.label}
			</div>
			<div data-dojo-type="dijit/form/Button" data-dojo-props="iconClass:'fa fa-history fa-fw','class':'clearButton'" data-dojo-attach-event="onClick:clearResults" data-dojo-attach-point="clearButtonDijit">
                ${i18n.clearButton.label}
			</div>
        </div>
	</div>
    <div data-dojo-attach-point="searchResultsNode" class="resultsContainer"></div>
    <div data-dojo-attach-point="searchResultsGrid" class="resultsGrid"></div>
    
</div>

And Finally this is the Search.js file:

define([
	'dojo/_base/declare',
   	'dijit/_WidgetBase',
	'dijit/_TemplatedMixin',
	'dijit/_WidgetsInTemplateMixin',
    'dojo/aspect',
	'dojo/dom-construct',
	'dojo/_base/lang',
	'dojo/_base/array',
	'dojo/on',
	'dojo/keys',
	'dojo/store/Memory',
	'dgrid/OnDemandGrid',
	'dgrid/Selection',
	'dgrid/Keyboard',
   	'esri/layers/GraphicsLayer',
	'esri/graphic',
	'esri/renderers/SimpleRenderer',
	'esri/symbols/SimpleMarkerSymbol',
	'esri/symbols/SimpleLineSymbol',
	'esri/symbols/SimpleFillSymbol',
	'esri/graphicsUtils',
	'esri/tasks/QueryTask',
    'esri/tasks/query',
	'esri/geometry/Extent',
	'dojo/text!./Search/templates/Search.html',
	'dojo/i18n!./Search/nls/resource',
    'dojo/string',
    'dijit/form/Form',
	'dijit/form/FilteringSelect',
	'dijit/form/ValidationTextBox',
	'dijit/form/CheckBox',
	'xstyle/css!./Search/css/Search.css'
], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin, aspect, domConstruct, lang, array, on, keys, Memory, OnDemandGrid, Selection, Keyboard, GraphicsLayer, Graphic, SimpleRenderer, SimpleMarkerSymbol, SimpleLineSymbol, SimpleFillSymbol, graphicsUtils, QueryTask, Query, Extent, SearchTemplate, i18n, String) {
	return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
		widgetsInTemplate: true,
		templateString: SearchTemplate,
		baseClass: 'gis_SearchDijit',
		i18n: i18n,
        
	    lastselectedQuery: null,
		lastSearchString: '',
        stagedSearch: null,

		// Spatial Reference. uses the map's spatial reference if none provided
		spatialReference: null,

		// Use 0.0001 for decimal degrees (wkid 4326)
		// or 500 for meters/feet
		pointExtentSize: null,

		// default symbology for found features
		defaultSymbols: {
			point: {
				type: 'esriSMS',
				style: 'esriSMSCircle',
				size: 25,
				color: [0, 255, 255, 32],
				angle: 0,
				xoffset: 0,
				yoffset: 0,
				outline: {
					type: 'esriSLS',
					style: 'esriSLSSolid',
					color: [0, 255, 255, 255],
					width: 2
				}
			},
			polyline: {
				type: 'esriSLS',
				style: 'esriSLSSolid',
				color: [0, 255, 255, 255],
				width: 3
			},
			polygon: {
				type: 'esriSFS',
				style: 'esriSFSSolid',
				color: [0, 255, 255, 32],
				outline: {
					type: 'esriSLS',
					style: 'esriSLSSolid',
					color: [0, 255, 255, 255],
					width: 3
				}
			}
		},
		postCreate: function () {
			this.inherited(arguments);

			if (this.spatialReference === null) {
				this.spatialReference = this.map.spatialReference.wkid;
			}
			if (this.pointExtentSize === null) {
				if (this.spatialReference === 4326) { // special case for geographic lat/lng
					this.pointExtentSize = 0.0001;
				} else {
					this.pointExtentSize = 500; // could be feet or meters
				}
			}

			this.createGraphicLayers();

		    if (this.parentWidget && this.parentWidget.toggleable) {
		        this.own(aspect.after(this.parentWidget, 'toggle', lang.hitch(this, function () {
		            this.onLayoutChange(this.parentWidget.open);
		        })));
		    }

		    // auto complete search 
		    this.own(on(this.searchTextDijit, 'keyup', lang.hitch(this, function (evt) {
		            this.handleOnKeyUp(evt);
		    })));

			this.queryIdx = 0;

			// add an id so the queries becomes key/value pair store
			var k = 0, queryLen = this.queries.length;
			for (k = 0; k < queryLen; k++) {
				this.queries[k].id = k;
			}

			// add the queries to the drop-down list
			if (queryLen > 1) {
				var queryStore = new Memory({
					data: this.queries
				});
				this.querySelectDijit.set('store', queryStore);
				this.querySelectDijit.set('value', this.queryIdx);
			} else {
				this.querySelectDom.style.display = 'none';
			}

		},
		handleOnKeyUp: function (evt) {
		    var id = evt.target.id;
		    var selectedQuery = this.queries[this.queryIdx];
		    var searchText = "";

		    if (evt) {
		        if (evt.keyCode == dojo.keys.ENTER) {
		            if (dojo.byId(id).value != '') {
		                this.search();
		                return;
		            }
		        }
		        
		        if ((!((evt.keyCode >= 46 && evt.keyCode < 58) || (evt.keyCode > 64 && evt.keyCode < 91) || (evt.keyCode > 95 && evt.keyCode < 106) || evt.keyCode == 8 || evt.keyCode == 110 || evt.keyCode == 188)) || (evt.keyCode == 86 && evt.ctrlKey) || (evt.keyCode == 88 && evt.ctrlKey)) {
		            evt = (evt) ? evt : event;
		            evt.cancelBubble = true;
		            if (evt.stopPropagation) evt.stopPropagation();
		            return;
		        }

		        searchText = dojo.byId(id).value.trim();
		        if (!selectedQuery || !searchText || searchText.length === 0) {
		            return;
		        }
		       		        
		        if (searchText != '') {
		            if (this.lastSearchString != searchText) {
		                this.lastSearchString = searchText;
		                // Clear any staged search
		                clearTimeout(this.stagedSearch);
		                if (selectedQuery.minChars && (searchText.length >= selectedQuery.minChars)) {
		                    // Stage a new search, which will launch if no new searches show up before the timeout
		                    this.stagedSearch = setTimeout(lang.hitch(this, function () {
		                        this.search();
		                    }), 500);
		                }
		            }
		        } else {
		            //cleared out text should we clear the grid?
		            this.lastSearchString = searchText;
		            this.clearResults();
		        }
		    }
		},
		onLayoutChange: function (open) {
		    // if user opens widget set focus to search text
		    if (open) {
		       dojo.byId('searchTextDijit').focus();
		    }
		},
		createGraphicLayers: function () {
			var pointSymbol = null,
				polylineSymbol = null,
				polygonSymbol = null;
			var pointRenderer = null,
				polylineRenderer = null,
				polygonRenderer = null;

			var symbols = lang.mixin({}, this.symbols);
			// handle each property to preserve as much of the object heirarchy as possible
			symbols = {
				point: lang.mixin(this.defaultSymbols.point, symbols.point),
				polyline: lang.mixin(this.defaultSymbols.polyline, symbols.polyline),
				polygon: lang.mixin(this.defaultSymbols.polygon, symbols.polygon)
			};

			// points
			this.pointGraphics = new GraphicsLayer({
				id: 'searchGraphics_point',
				title: 'Search'
			});

			if (symbols.point) {
				pointSymbol = new SimpleMarkerSymbol(symbols.point);
				pointRenderer = new SimpleRenderer(pointSymbol);
				pointRenderer.label = 'Search Results (Points)';
				pointRenderer.description = 'Search results (Points)';
				this.pointGraphics.setRenderer(pointRenderer);
			}

			// poly line
			this.polylineGraphics = new GraphicsLayer({
				id: 'searchGraphics_line',
				title: 'Search Graphics'
			});

			if (symbols.polyline) {
				polylineSymbol = new SimpleLineSymbol(symbols.polyline);
				polylineRenderer = new SimpleRenderer(polylineSymbol);
				polylineRenderer.label = 'Search Results (Lines)';
				polylineRenderer.description = 'Search Results (Lines)';
				this.polylineGraphics.setRenderer(polylineRenderer);
			}

			// polygons
			this.polygonGraphics = new GraphicsLayer({
				id: 'searchGraphics_polygon',
				title: 'Search Graphics'
			});

			if (symbols.polygon) {
				polygonSymbol = new SimpleFillSymbol(symbols.polygon);
				polygonRenderer = new SimpleRenderer(polygonSymbol);
				polygonRenderer.label = 'Search Results (Polygons)';
				polygonRenderer.description = 'Search Results (Polygons)';
				this.polygonGraphics.setRenderer(polygonRenderer);
			}

			this.map.addLayer(this.polygonGraphics);
			this.map.addLayer(this.polylineGraphics);
			this.map.addLayer(this.pointGraphics);
		},
		search: function () {
			var selectedQuery = this.queries[this.queryIdx];
			var searchText = this.searchTextDijit.get('value');
			if (!selectedQuery || !searchText || searchText.length === 0) {
				return;
			}
			if (selectedQuery.minChars && (searchText.length < selectedQuery.minChars)) {
			    this.searchResultsNode.innerHTML = 'You must enter at least ' + selectedQuery.minChars + ' characters.';
				this.searchResultsNode.style.display = 'block';
				return;
			}

			//this.destroyResultsGrid();
			this.createResultsGrid(selectedQuery);
			this.clearResultsGrid();
			this.clearFeatures();
			domConstruct.empty(this.searchResultsNode);

			if (!selectedQuery || !selectedQuery.url || !selectedQuery.where || !selectedQuery.outFields || !selectedQuery.dgridColumns || !selectedQuery.dgridSort) {
				return;
			}

		    //create query parameters
			var qt = new QueryTask(selectedQuery.url);
			var query = new Query();
			query.where = String.substitute(selectedQuery.where, [searchText]);
			query.returnGeometry = true;
			query.outFields = selectedQuery.outFields;
			
			
			this.searchResultsNode.innerHTML = this.i18n.searching;
			this.searchResultsNode.style.display = 'block';

			qt.execute(query, lang.hitch(this, 'showResults'));
		},
		createResultsGrid: function (selectedQuery) {
		    if (!this.resultsStore) {
		        this.resultsStore = new Memory({
		            idProperty: 'id',
		            data: []
		        });
		    } 

            //if grid has already been created but we have changed the query update columns and sort
		    if (this.resultsGrid && this.lastselectedQuery != selectedQuery) {
		        if (this.resultsStore) {
		            this.resultsStore.setData([]);
		        }
		        this.resultsGrid._setColumns(selectedQuery.dgridColumns);
		        this.resultsGrid.updateSortArrow(selectedQuery.dgridSort, true);
		    }

		    if (!this.resultsGrid) {
		        var Grid = declare([OnDemandGrid, Keyboard, Selection]);
		        this.resultsGrid = new Grid({
		            selectionMode: 'single',
		            cellNavigation: false,
		            showHeader: true,
		            store: this.resultsStore,
		            columns: selectedQuery.dgridColumns,
		            sort: selectedQuery.dgridSort
		            //minRowsPerPage: 250,
		            //maxRowsPerPage: 500
		        }, this.searchResultsGrid);
		        this.resultsGrid.startup();
		        this.resultsGrid.on('dgrid-select', lang.hitch(this, 'selectFeature'));
		    }
		    
		},
		showResults: function (results) {
		    var resultText = '';
			this.resultIdx = 0;
			this.results = [];
			var selectedQuery = this.queries[this.queryIdx];

            //build results array that includes dynamic columns
			if (results.features.length > 0) {
			    var unique = 0;
			    array.forEach(results.features, function (feature) {
			        var x = {feature: feature, id: unique};
			        unique++;
			        for (var key in selectedQuery.dgridColumns) {
			            if (selectedQuery.dgridColumns.hasOwnProperty(key)) {
			                x[key] = feature.attributes[key];
			            }
			        }
			        this.results.push(x);
			    }, this);
			}

			if (this.results.length > 0) {
				var s = (this.results.length === 1) ? '' : this.i18n.resultsLabel.multipleResultsSuffix;
				resultText = this.results.length + ' ' + this.i18n.resultsLabel.labelPrefix + s + ' ' + this.i18n.resultsLabel.labelSuffix;
				if (this.results.length === 1) {
				    this.clearFeatures();
				    this.highlightFeature(this.results[0].feature.geometry);
				};
				this.showResultsGrid();
			} else {
			    resultText = this.i18n.resultsLabel.noResults;
			}
			this.searchResultsNode.innerHTML = resultText;
		},
		showResultsGrid: function () {
		    var selectedQuery = this.queries[this.queryIdx];
		    
            this.resultsGrid.store.setData(this.results);
			this.resultsGrid.refresh();

			if (selectedQuery && selectedQuery.hideGrid !== true) {
				this.searchResultsGrid.style.display = 'block';
			}
		},
		highlightFeature: function (geometry) {
		    switch (geometry.type) {
		        case 'point':
		            // only add points to the map that have an X/Y
		            if (feature.geometry.x && feature.geometry.y) {
		                graphic = new Graphic(geometry);
		                this.pointGraphics.add(graphic);
		            }
		            break;
		        case 'polyline':
		            // only add polylines to the map that have paths
		            if (geometry.paths && geometry.paths.length > 0) {
		                graphic = new Graphic(geometry);
		                this.polylineGraphics.add(graphic);
		            }
		            break;
		        case 'polygon':
		            // only add polygons to the map that have rings
		            if (geometry.rings && geometry.rings.length > 0) {
		                graphic = new Graphic(geometry, null, {
		                    ren: 1
		                });
		                this.polygonGraphics.add(graphic);
		            }
		            break;
		        default:
		    };

		    // zoom to layer extent
		    var zoomExtent = null;
		    //If the layer is a single point then extents are null
		    // if there are no features in the layer then extents are null
		    // the result of union() to null extents is null

		    if (this.pointGraphics.graphics.length > 0) {
		        zoomExtent = this.getPointFeaturesExtent(this.pointGraphics.graphics);
		    }
		    if (this.polylineGraphics.graphics.length > 0) {
		        if (zoomExtent === null) {
		            zoomExtent = graphicsUtils.graphicsExtent(this.polylineGraphics.graphics);
		        } else {
		            zoomExtent = zoomExtent.union(graphicsUtils.graphicsExtent(this.polylineGraphics.graphics));
		        }
		    }
		    if (this.polygonGraphics.graphics.length > 0) {
		        if (zoomExtent === null) {
		            zoomExtent = graphicsUtils.graphicsExtent(this.polygonGraphics.graphics);
		        } else {
		            zoomExtent = zoomExtent.union(graphicsUtils.graphicsExtent(this.polygonGraphics.graphics));
		        }
		    }

		    if (zoomExtent) {
		        this.zoomToExtent(zoomExtent);
		    }
		},
        selectFeature: function (event) {
			var result = event.rows;

			// zoom to feature
			if (result.length) {
				var data = result[0].data;
				if (data) {
					var feature = data.feature;
					if (feature) {
					    this.clearFeatures();
					    this.highlightFeature(feature.geometry);
						//var extent = feature.geometry.getExtent();
						//if (!extent && feature.geometry.type === 'point') {
						//	extent = this.getExtentFromPoint(feature);
						//}
						//if (extent) {
						//	this.zoomToExtent(extent);
						//}
					}
				}
			}
		},
		zoomToExtent: function (extent) {
			this.map.setExtent(extent.expand(3.0));
		},
		clearResults: function () {
		    this.results = null;
		    //this.data = null;
			this.clearResultsGrid();
			this.clearFeatures();
			this.searchFormDijit.reset();
			this.querySelectDijit.setValue(this.queryIdx);
			domConstruct.empty(this.searchResultsNode);
		},
		clearResultsGrid: function () {
			if (this.resultStore) {
				this.resultsStore.setData([]);
			}
			if (this.resultsGrid) {
				this.resultsGrid.refresh();
			}
			this.searchResultsNode.style.display = 'none';
			this.searchResultsGrid.style.display = 'none';
		},
		clearFeatures: function () {
			this.pointGraphics.clear();
			this.polylineGraphics.clear();
			this.polygonGraphics.clear();
		},
		getPointFeaturesExtent: function (pointFeatures) {
			var extent = graphicsUtils.graphicsExtent(pointFeatures);
			if (extent === null && pointFeatures.length > 0) {
				extent = this.getExtentFromPoint(pointFeatures[0]);
			}

			return extent;
		},
		getExtentFromPoint: function (point) {
			var sz = this.pointExtentSize; // hack
			var pt = point.geometry;
			var extent = new Extent({
				'xmin': pt.x - sz,
				'ymin': pt.y - sz,
				'xmax': pt.x + sz,
				'ymax': pt.y + sz,
				'spatialReference': {
					wkid: this.spatialReference
				}
			});
			return extent;
		},
		_onQueryChange: function (queryIdx) {
			if (queryIdx >= 0 && queryIdx < this.queries.length) {
			    this.queryIdx = queryIdx;
			    dojo.byId('searchTextDijit').focus();
			    //this.createResultsGrid();
			}
		}
	});
});

**Comment by tmcgee** [comment]
@taran03 Yes. Very, very soon. Definitely before the Esri Developer's Summit which is coming up in 10 days.

Watch this repo for those widgets and others: https://github.com/tmcgee/cmv-widgets

**Comment by taran03** [comment]
Thanks @msamwill and @tmcgee for your responses. @tmcgee I'll watch your repo for widget postings and look forward to testing them out - thanks again for your great contributions to CMV.  

@msamwill thanks for posting above. Any chance you could post the actual files your referenced above for your query task search widget? I'm playing around with this code above, but can't seem to make it work in CMV.  Does it require the most current CMV release (1.3.3) and/or JSAPi 3.12 to work?

Thanks again to both of you for your contributions.

**Comment by msamwill** [comment]
Hey @taran03, It works with 1.3.2 and should work with 3.11 too.  I created a repository and put the files in it.  You should be able to access the files here https://github.com/msamwill/CMV_Widgets 

I have never created a repository before so if you have any issues let me know.

**Comment by msamwill** [comment]
Hey @taran03 made a few fixes this morning.  Added comment stating that a shape field must be included in map services.

**Comment by taran03** [comment]
Great, thanks for posting the files.  I have the widget functioning now.

**Comment by tmcgee** [comment]
I have added my attributes table widget  and several others 
to my [cmv-widgets repo](https://github.com/tmcgee/cmv-widgets). A page with the examples is [here](http://tmcgee.github.io/cmv-widgets/)

### Attributes Table Widget
![attributestables1](https://cloud.githubusercontent.com/assets/200780/6512555/b7040d64-c329-11e4-8b97-4a39365a675e.jpg)

### Search Widget combined with multiple Attributes Tables
![search1](https://cloud.githubusercontent.com/assets/200780/6512558/b9811b04-c329-11e4-946a-a87d4cebeda7.jpg)

### Export Widget
![export1](https://cloud.githubusercontent.com/assets/200780/6512621/13b9de26-c32a-11e4-99ad-6000a4fb7bba.jpg)

**Comment by GilbertLasnier** [comment]
I receive your email about your great effort to do the super table I will try your stuff next week to implement in the ICAO template very good job, soon the siverlight will no need, many thanks to you to support the me and the cmv project, you make a great job, its will be very usefull, when i finish to implement all, i make a screen shot..
