### ISSUE TITLE
Adding a second field to the result of Find widget

### ISSUE THREAD

**Issue by MesquiteGIS** [cmv/cmv-app#213]
I'm wondering if it is possible to add a second field to the results of the Find widget. That is when a result is found using the find query, the results window displays two fields, say Parcel ID and Address, rather than just one.

Thanks!

**Comment by jebu75** [comment]
This may be new in the latest version of the api but the [FindResult](https://developers.arcgis.com/javascript/jsapi/findresult-amd.html#feature) returns the found feature with attributes.

**Comment by tmcgee** [comment]
Nice! I believe that was added in a recent version of the API. Certainly was not there back at 3.8 or 3.9 when the Find widget was first written.

**Comment by MesquiteGIS** [comment]
Thanks,

I'll do some updating.



On Tue, Jan 20, 2015 at 2:27 PM, Tim McGee <notifications@github.com> wrote:

> Nice! I believe that was added in a recent version of the API. Certainly
> was not there back at 3.8 or 3.9 when the Find widget was first written.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmv/cmv-app/issues/213#issuecomment-70747429>.
>



-- 
Ryan Kammerer, GISP
GIS/Programmer Analyst II
City of Mesquite, Nevada
(702) 346-8647 Ext. 4

-- 
*Confidentiality Statement:*

The information contained in this electronic mail is confidential 
information. This information may be attorney/client privileged 
and is intended only for the use of the individual or entity named above. 

If the reader of this message is not the intended recipient, you are hereby 
notified that any dissemination, distribution, copying, or re-transmission 
of this message is in violation of 18 U.S.C. 2511(1) of the ECPA and is strictly 
prohibited. If you have received the message in error, please notify the 
sender immediately. Thank you.
