### ISSUE TITLE
Identify Popups

### ISSUE THREAD

**Issue by pwild** [cmv/cmv-app#223]
Is there a way to disable all popups/infowinows for individual operational layers?

BTW, the app is great, thanks!

**Comment by JhopStl** [comment]
Is there a way to do this for a sub layer?

**Comment by tmcgee** [comment]
@JhopStl You can't explicitly exclude a sublayer but you can include only certain sublayers using the layerIds array like shown in [this example](https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L192)

**Comment by JhopStl** [comment]
@tmcgee Thanks, that's exactly what I was looking for
