### ISSUE TITLE
zoom to a feature on open

### ISSUE THREAD

**Issue by jtorresleon** [cmv/cmv-app#224]
Hi everyone,
I would like to zoom in (and selecting if possible) to a feature on opening the viewer, it is doable?
Thanks in advance

**Comment by jtorresleon** [comment]
Hi there,
The CMV Init Zoomer was never published on the CMV-contrib. and the widget does not exist anymore on the girhub site. Has anyone solved the passing parameters to CMV via URL to open the viewer zooming and selecting a given feature?

**Comment by tmcgee** [comment]
I believe that @JoelHearne who works at Okaloosa County is the same one who posted about the widget back in November. Joel has a widget with the same name here: https://github.com/JoelHearne/CMV_InitZoomer

**Comment by podli** [comment]
Hello everybody,

i have similar question. I would like to use zoom on a feature on open as well. I have a different approach in mind. I want to pass an argument (ID) in url parameter. After that i want basically the same funcionality as the find widget. You can test it here: http://biotit.geo-zs.si/ms/?ID=142 After enter the number 142 in search it finds one result and after clicking on that result the map zooms in and marks the point or poligon. That was my idea :) Any help in realizing that? 
thanks in advance

**Comment by tmcgee** [comment]
@podli Your question sounds similar to one I answered last week on [gis.stackexchange.com](https://gis.stackexchange.com/questions/142461/pass-an-attribute-to-the-find-widget-using-a-url-string). I provided an example configuration that is now in my [cmv-widgets repo](https://github.com/tmcgee/cmv-widgets/blob/master/config/queryStringSearch.js). You can also see the results in [live demo](http://tmcgee.github.io/cmv-widgets/demo.html?config=queryStringSearch&fips=12115). Let me know if that helps you out.

**Comment by podli** [comment]
Thank  you very much for this. It is very helpful. BTW: very nice viewer. It is much more beautiful that standard esri viewers.

**Comment by podli** [comment]
@tmcgee I wonder what am i doing wrong. I implemented your attributesTable widget and it works. The only problem i am having is with the identify after the selected feature (point). I cannot identify until i clear the selected feature. I tried featureOptions: infoWindow: true but the problem remains. Its the same with find widget. In your livedemo for search widget works fine. You can try it here: http://biotit.geo-zs.si/ms/?ID=142 Could it be a bug? or am i missing something?

**Comment by TPLsmitty** [comment]
@podli   It looks like you have everything configured correctly.  The issue is that the point layer is added as a feature service.  Because both your feature service and the selected feature are displayed as graphics, the identify will only work on the upper most graphic (The selected feature graphic).
I have not tried this, but my guess is if you bring the layers in as a dynamic map service, you should be able to identify on the layer without deselecting the feature. If you want to keep the ponit and polygon layers seperate, you can try using the example in issue #404.

**Comment by podli** [comment]
I will try that and let you know. Thanks

**Comment by podli** [comment]
I tried adding as dynamic but it still remains the same :( How come that this is working in demo example in search widget? http://tmcgee.github.io/cmv-widgets/demo.html?config=search here you are also using dynamic and it works. Any help will be much appreciated.
