### ISSUE TITLE
Save graphics created by draw widget

### ISSUE THREAD

**Issue by cuthberts** [cmv/cmv-app#232]
Hi,

Would it be possible to add a button in the Draw widget that allows the user to save their graphics to a txt?

Cheers,
Steve

**Comment by lee53** [comment]
I looked at the advanced draw widget but couldn't find the save option.  Is "saving graphics" available?
Saving graphics would be really useful, either local or server.

**Comment by tmcgee** [comment]
I don't think that functionality has yet been added to the advanced draw widget.

**Comment by lee53** [comment]
thanks for your quick response.
