### ISSUE TITLE
Google for Basemap gallery

### ISSUE THREAD

**Issue by kwikstrom** [cmv/cmv-app#235]
I've been very stuck attempting to get Google basemaps into the cmv gallery.  I've become lost in the code and the documentation that I've already come across.  I imagine this is possible since cmv uses Google StreetView.  This is what I've been attempting to work with: http://www.arcgis.com/home/item.html?id=a8f78cc6adea48cb8e962d7e36b9d010

Simply put, what code needs to be put where?  I'm rather new to customizing.  Thanks!

**Comment by faridcher** [comment]
By the help of WebTiledLayer module, introduced At version 3.2  of the api, one can easily utilize any online map service in the Arcgis javascript api.
To enable google base map in CMW, just add these lines to the basemap.js config file (lest you forget to use the mode:'custom'):
```javascript
    googleStreetOnline: {
                title: 'Google Street Online',
                basemap: new Basemap({
                    id: 'googleStreetOnline',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=m&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google Street Map",
                        id: "googleStreetOnline",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
```

**Comment by rogers259** [comment]
@faridcher Tested googleStreetOnline, works perfect in mode: 'custom'. One thing i did find CMV does not like it being the startup basemap...I'm assuming that LOD's may need to be defined in mapoptions on viewer.js to correct this. But didnt have time to test that this morning. 

Now we just need Google Hybrid and Satellite ... thanks Nice work!

**Comment by tmcgee** [comment]
@rogers259 

For satellite, replace `/lyrs=m` with `/lyrs=s`

For hybrid, replace `/lyrs=m` with `/lyrs=s,h` ('h' can be also used independently)

For terrain, replace `/lyrs=m` with `/lyrs=t`

You may also be able to use your own [Google Styled Maps](http://gmaps-samples-v3.googlecode.com/svn/trunk/styledmaps/wizard/index.html) once you figure out the url pattern for those. 

**Important Note** Using Google tiles as a MapTiledLayer is very likely against Google's Terms of Service. Google requires that you to use their Google Maps API. You have been warned. ;)

I believe that the original link posted by @kwikstrom uses the Google API so should be a legit. Comments on that link suggest that it no longer works with recent versions of the ArcGIS JS API and may need to be updated to work.

**Comment by lee53** [comment]
@faridcher I just followed your direction, adding those lines to the basemap.js and getting error message "basemap is not defined. What else do I need to modify?   Thank you

**Comment by tmcgee** [comment]
@lee53 please post your entire basemap.js with the offending code, if possible.

**Comment by lee53** [comment]
@tmcgee  please find the basemap.js below:   Thank you. 
-----------------------------------------------------------------
define([
    //'esri/dijit/Basemap',
    //'esri/dijit/BasemapLayer',
    //'esri/layers/osm'
], function ( /* Basemap, BasemapLayer, osm */ ) {
    return {
        map: true, // needs a refrence to the map
        mode: 'agol', //must be either 'agol' or 'custom'
        title: 'Basemaps', // tilte for widget
        mapStartBasemap: 'gray', // must match one of the basemap keys below
        //basemaps to show in menu. define in basemaps object below and reference by name here
        // TODO Is this array necessary when the same keys are explicitly included/excluded below?
        basemapsToShow: ['streets', 'satellite', 'hybrid', 'topo', 'lightGray', 'gray', 'national-geographic', 'osm', 'oceans', 'googleStreetOnline'],

        // define all valid custom basemaps here. Object of Basemap objects. For custom basemaps, the key name and basemap id must match.
        basemaps: { // agol basemaps
            streets: {
                title: 'Streets'
            },
            satellite: {
                title: 'Satellite'
            },
            hybrid: {
                title: 'Hybrid'
            },
            topo: {
                title: 'Topo'
            },
            gray: {
                title: 'Gray'
            },
           
            oceans: {
                title: 'Oceans'
            },

            'national-geographic': {
                title: 'Nat Geo'
            },
            osm: {
                title: 'Open Street Map'
            },

            googleStreetOnline: {
                title: 'Google Street Online',
                basemap: new Basemap({
                    id: 'googleStreetOnline',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=m&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google Street Map",
                        id: "googleStreetOnline",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            }

        }
    };
});

**Comment by tmcgee** [comment]
@lee53 the google basemap code uses the `Basemap` and `BasemapLayer` classes but you haven't included them. At the top of basemap.js, change this:

```
define([
//'esri/dijit/Basemap',
//'esri/dijit/BasemapLayer',
//'esri/layers/osm'
], function ( /* Basemap, BasemapLayer, osm */ ) {
```

to this: 

```
define([
'esri/dijit/Basemap',
'esri/dijit/BasemapLayer'
], function ( Basemap, BasemapLayer ) {
```

**Comment by lee53** [comment]
@tmcgee  Thank you for your quick reply.  It removed the error and add button, however google basemap deoesn't display.

**Comment by tmcgee** [comment]
@lee53 To use any layers that are not from ArcGIS Online, you'll have to switch the basemap widget mode from `agol` to `custom`.

Here's a complete working example which has 4 custom ESRI layers to mimic those from AGOL (these are documented in `basemap.js` that comes with CMV) and also adds 4 Google base maps:

``` javascript
define([
    'esri/dijit/Basemap',
    'esri/dijit/BasemapLayer'
    //'esri/layers/osm'
], function ( Basemap, BasemapLayer ) {
    return {
        map: true, // needs a refrence to the map
        mode: 'custom', //must be either 'agol' or 'custom'
        title: 'Basemaps', // title for widget
        mapStartBasemap: 'streets', // must match one of the basemap keys below
        //basemaps to show in menu. define in basemaps object below and reference by name here
        // TODO Is this array necessary when the same keys are explicitly included/excluded below?
        basemapsToShow: ['streets', 'satellite', 'hybrid', 'lightGray', 'googleStreets', 'googleSatellite', 'googleHybrid', 'googleTerrain'],

        // define all valid custom basemaps here. Object of Basemap objects. For custom basemaps, the key name and basemap id must match.
        basemaps: {
            streets: {
                title: 'Streets',
                basemap: new Basemap({
                    id: 'streets',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
                    })]
                })
            },
            satellite: {
                title: 'Satellite',
                basemap: new Basemap({
                    id: 'satellite',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer'
                    })]
                })
            },
            hybrid: {
                title: 'Hybrid',
                basemap: new Basemap({
                    id: 'hybrid',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer'
                    }), new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer',
                        isReference: true,
                        displayLevels: [0, 1, 2, 3, 4, 5, 6, 7]
                    }), new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer',
                        isReference: true,
                        displayLevels: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
                    })]
                })
            },
            lightGray: {
                title: 'Light Gray Canvas',
                basemap: new Basemap({
                    id: 'lightGray',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer'
                    }), new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer',
                        isReference: true
                    })]
                })
            },
            googleStreets: {
                title: 'Google Streets',
                basemap: new Basemap({
                    id: 'googleStreets',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=m&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleStreets",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
            googleSatellite: {
                title: 'Google Satellite',
                basemap: new Basemap({
                    id: 'googleSatellite',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=s&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleSatellite",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
            googleHybrid: {
                title: 'Google Hybrid',
                basemap: new Basemap({
                    id: 'googleHybrid',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=s,h&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleHybrid",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
            googleTerrain: {
                title: 'Google Terrain',
                basemap: new Basemap({
                    id: 'googleTerrain',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=t,r&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleTerrain",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            }
        }
    };
});
```

Please note the comment that I posted earlier in this issue about possible violations of the Google API using this method.

**Comment by lee53** [comment]
@tmcgee Thank you very much for your help.  It works like a charm.  I didn't realize I cannot mix with agol and custom.  I should read comments more carefully. 
Regards.

**Comment by tmcgee** [comment]
fyi: @DavidSpriggs pointed out to me that as of version 3.12 of the ArcGIS JavaScript API, you can mix and max your custom basemaps with those from AGOL using the new `esri/basemaps` class. This would also allow you to add the custom basemap(s) to the esri basemaps in `config/viewer.js` and set one as your starting basemap. Might be utilized in an enhancement to the CMV basemap widget in the future. Developer reference is [here](https://developers.arcgis.com/javascript/jsapi/esri.basemaps-amd.html)

**Comment by DavidSpriggs** [comment]
Also see fiddle here: http://jsfiddle.net/DavidSpriggs/wcbojd3j/

**Comment by GilbertLasnier** [comment]
Thank you very much for your help. It works like a charm. i have all the Base map possible!!!

**Comment by GilbertLasnier** [comment]
if you want more this is the place
define([
    'esri/dijit/Basemap',
    'esri/dijit/BasemapLayer',
    'esri/layers/osm'
], function (Basemap, BasemapLayer, osm) {
    return {
        map: true, // needs a refrence to the map
        mode: 'custom', //must be either 'agol' or 'custom'
        title: 'Basemaps', // tilte for widget
        mapStartBasemap: 'lightGray', // must match one of the basemap keys below
        //basemaps to show in menu. define in basemaps object below and reference by name here
        // TODO Is this array necessary when the same keys are explicitly included/excluded below?
        basemapsToShow: ['none','delorme','openstreet','IcaoFIR','streets', 'satellite', 'hybrid','topo', 'lightGray','darkGray','googleStreets','googleSatellite','googleHybrid','googleTerrain','oceans','oceansname','relief','reliefHyb','noaa','nationalgeographic','navigcharts','physical','terrain','shadedrelief','NaturalColor','VegetationAnalysis','LandsatShadedBasemap','EarthatNight','DavidRumseyMaps','BingMapsAerial'],

        // define all valid custom basemaps here. Object of Basemap objects. For custom basemaps, the key name and basemap id must match.
        basemaps: { // agol basemaps
             //streets: {
                 //title: 'Streets'
             //},
             //satellite: {
                 //title: 'Satellite'
             //},
            // hybrid: {
                 //title: 'Hybrid'
             //},
             //topo: {
                 //title: 'Topo'
             //},
             //gray: {
                 //title: 'Gray'
             //},
             //oceans: {
                 //title: 'Oceans'
             //},
             //'national-geographic': {
                 //title: 'Nat Geo'
             //},
             //osm: {
                 //title: 'Open Street Map'
			
           	
             //}

            // examples of custom basema
			none: { 
				title: 'None 20sec',
				basemap: new Basemap({
					id: 'none',
					layers: [ new BasemapLayer({
					url:'http://'
					})]
				})
			},
			
			delorme: { 
				title: 'Delorme',
				basemap: new Basemap({
					id: 'delorme',
					layers: [ new BasemapLayer({
					url:'http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/DeLorme_World_Base_Map/MapServer'
					})]
				})
			},
		    openstreet: {
				title: 'Open Street Map',
				basemap: 
					new Basemap({
					layers: [new BasemapLayer({
					type:'OpenStreetMap'
					})],
					id:'openstreet',
					title:'Open Street Map',
					thumbnailUrl:'images/OpenStreetMap.png'
				})
			},
			IcaoFIR: {
				title: 'ICAO FIR 2015 image',
				basemap: new Basemap({
                    id: 'IcaoFIR',
                    layers: [new BasemapLayer({
                         url: 'http://gis.icao.int/ArcGIS/rest/services/FIRMSD/MapServer'
					})]
					
				})
			},	
			
			
			

            streets: {
                title: 'Streets',
                basemap: new Basemap({
                    id: 'streets',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
                    })]
                })
            },
            satellite: {
                title: 'Satellite',
                basemap: new Basemap({
                    id: 'satellite',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer'
                    })]
                })
            },
            hybrid: {
                title: 'Hybrid',
                basemap: new Basemap({
                    id: 'hybrid',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer'
                    }), new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer',
                        isReference: true,
                        displayLevels: [0, 1, 2, 3, 4, 5, 6, 7]
                    }), new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer',
                        isReference: true,
                        displayLevels: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
                    })]
                })
            },
            lightGray: {
                title: 'Light Gray Canvas',
                basemap: new Basemap({
                    id: 'lightGray',
                    layers: [new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer'
                    }), new BasemapLayer({
                        url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer',
                        isReference: true
                    })]
                })
			},
			darkGray: {
                title: 'Dark Gray Canvas',
                basemap: new Basemap({
                    id: 'darkGray',
                    layers: [new BasemapLayer({
                        url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer'
                    }), new BasemapLayer({
                        url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer',
                        isReference: true
                    })]
                })
			
            
			},
            googleStreets: {
                title: 'Google Streets',
                basemap: new Basemap({
                    id: 'googleStreets',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=m&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleStreets",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
            googleSatellite: {
                title: 'Google Satellite',
                basemap: new Basemap({
                    id: 'googleSatellite',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=s&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleSatellite",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
            googleHybrid: {
                title: 'Google Hybrid',
                basemap: new Basemap({
                    id: 'googleHybrid',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=s,h&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleHybrid",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
            googleTerrain: {
                title: 'Google Terrain',
                basemap: new Basemap({
                    id: 'googleTerrain',
                    layers: [new BasemapLayer({
                        url: "http://mt${subDomain}.google.com/vt/lyrs=t,r&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleTerrain",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
			},
            oceans: {
				title: 'Oceans',
				basemap: new Basemap({
					id: 'oceans',
					layers: [new BasemapLayer({
                    url: 'http://services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer'
					})]
				})
			},
			
			oceansname: {
				title: 'Oceansname deep',
				basemap: new Basemap({
					id: 'oceansname',
					layers: [new BasemapLayer({
                    url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer'
					})]
				})
			},
			relief: {
				title: 'Relief',
				basemap: new Basemap({
					id: 'relief',
					layers: [new BasemapLayer({
						url: 'http://maps.ngdc.noaa.gov/rest/services/web_mercator/gebco08_hillshade/MapServer'
					})]
				})
			},
			
			reliefHyb: {
				title: 'Relief Hybrid',
				basemap: new Basemap({
					id: 'reliefHyb',
					layers: [new BasemapLayer({
						url: 'http://maps.ngdc.noaa.gov/rest/services/web_mercator/gebco08_hillshade/MapServer'
					}), new BasemapLayer({
						url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer',
						isReference: true,
						displayLevels: [0, 1, 2, 3, 4, 5, 6, 7]
					}), new BasemapLayer({
						url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer',
						isReference: true,
						displayLevels: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]	
					})]
				})
			},
			noaa: {
				title: 'Noaa',
				basemap: new Basemap({
					id: 'noaa',
					layers: [new BasemapLayer({
						url: 'http://maps.ngdc.noaa.gov/rest/services/web_mercator/etopo1_hillshade/MapServer'
					})]
				})
			},
			
			topo: {
				title: 'Topo elevation',
				basemap: new Basemap({
					id: 'topo',
					layers: [new BasemapLayer({
						url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer'
					})]
				})
			},
			
			nationalgeographic: {
				title: 'National geographic',
				basemap: new Basemap({
					id: 'nationalgeographic',
					layers: [new BasemapLayer({
						url: 'http://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer'
					})]
				})
			},
			navigcharts: {
				title: 'Navig charts',
				basemap: new Basemap({
					id: 'navigcharts',
					layers: [new BasemapLayer({
						url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/World_Navigation_Charts/MapServer'
					})]
				})
			},
			physical: {
				title: 'Physical',
				basemap: new Basemap({
					id: 'physical',
					layers: [new BasemapLayer({
						url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer'
					})]
				})
			},
			terrain: {
				title: 'Terrain',
				basemap: new Basemap({
					id: 'terrain',
					layers: [new BasemapLayer({
						url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer'
					})]
				})
			},
			shadedrelief : {
				title: 'Shaded Relief',
				basemap: new Basemap({
					id: 'shadedrelief',
					layers: [new BasemapLayer({
						url: 'http://services.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer'
					})]
				})
			},
			NaturalColor: {
				title: 'Natural Color 5 sec',
				basemap: new Basemap({
					id: 'NaturalColor',
					layers: [new BasemapLayer({
						url: 'http://imagery.arcgisonline.com/ArcGIS/rest/services/LandsatGLS/NaturalColor/ImageServer'
					})]
				})
			},
			VegetationAnalysis: {
				title: 'Vegetation Analysis 5 sec',
				basemap: new Basemap({
					id: 'VegetationAnalysis',
					layers: [new BasemapLayer({
						url: 'http://imagery.arcgisonline.com/ArcGIS/rest/services/LandsatGLS/VegetationAnalysis/ImageServer'
					})]
				})
        
			},
			LandsatShadedBasemap: {
				title: 'Landsat Shaded',
				basemap: new Basemap({
					id: 'LandsatShadedBasemap',
					layers: [new BasemapLayer({
						url: 'http://imagery.arcgisonline.com/arcgis/rest/services/LandsatGLS/LandsatShadedBasemap/ImageServer'
					})]
				})
			},
			EarthatNight: {
				title: 'Earth at Night',
				basemap: new Basemap({
					id: 'EarthatNight',
					layers: [new BasemapLayer({
						url: 'http://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Earth_at_Night_WM/MapServer'
					})]
				})
			},
			DavidRumseyMaps: {
				title: 'David Rumsey 1812',
				basemap: new Basemap({
					id: 'DavidRumseyMaps',
					layers: [new BasemapLayer({
						url: 'http://tiles.arcgis.com/tiles/IEuSomXfi6iB7a25/arcgis/rest/services/World_Globe_1812/MapServer'
					})]
				})
			}
			
        }
    };
});

**Comment by GilbertLasnier** [comment]
Be the way why none take 20 second to appear???
