### ISSUE TITLE
Google for geocoder and directions.

### ISSUE THREAD

**Issue by kwikstrom** [cmv/cmv-app#236]
These should probably be separate entries so I'll apologize now.

I'm developing for rural emergency services and Google provides much more accurate place finders and directions and that is what we need to have for our fire, rescue, and ambulance services.  Esri is great, but it won't work for this particular rural area, it has way too much error.  I'm seeking help on how to make this happen in the cmv.  I appreciate any help anyone can offer.  Thanks.

**Comment by lee53** [comment]
@kwikstrom Did you make any progress on google routing widget?

**Comment by lee53** [comment]
I have a very simple html page for google routing.  Please see the link below. 
(https://github.com/lee53/Google-Driving-Sample/blob/master/googleDrivingSample.html)

I am trying to convert it into a widget but having a hard time.  Can someone help me in conversion?   Your help will be much appreciated. 

![googledirection](https://cloud.githubusercontent.com/assets/6852148/5827110/e58e8492-a0c5-11e4-9923-7b4026ab09b4.JPG)

**Comment by tmcgee** [comment]
@lee53 Do you have a GitHub repo for the widget with what you have tried so far? This will be a great contributed widget when completed!

**Comment by friendde** [comment]
I am not a seasoned programmer like @tmcgee but I did convert a single page into a widget for CMV. I'll help too. Create a repo and I can help tommorow when I return to the office.

**Comment by lee53** [comment]
@tmcgee and @friendde thank you for your quick reply. 

Here is the Github repo. (https://github.com/lee53/Google-Driving-Sample)
I just added the html page (which include js script).  I never created a widget before. By looking at the streetview wideget, tried to figure out "how to" and overwhelmed. BTW the original script was from Google Geo developer blog (http://googlegeodevelopers.blogspot.com/2010/03/good-day-for-salesmen-that-travel-on.html). I think I should mention it.

**Comment by tmcgee** [comment]
OK. I'll just clone that repo and take a stab at the conversion as time and workload permit.

**Comment by lee53** [comment]
@tmcgee thank you so much for your help.

**Comment by tmcgee** [comment]
request is for a custom widget and not related to cmv core.
