### ISSUE TITLE
Custom maps in overview map

### ISSUE THREAD

**Issue by geoggeek** [cmv/cmv-app#247]
Hello, 

I'm a novice with JavaScript but I've found the viewer template really useful - thank you.
I've managed to set up my own custom basemaps and I also followed https://github.com/cmv/cmv-app/wiki/Customizing-basemaps.js to create my own LODS map service. I've found that the overview map references this map service from viewer.js and therefore does not display any map data. Is there a way to specify custom map layers for the overview map to use?

Many thanks.

**Comment by carrbrpoa** [comment]
I'm having the same problem, I guess. Whenever I fill the overviewMap's `baseLayer` property like this...

```javascript
overviewMap : {
	include : true,
	id : 'overviewMap',
	type : 'map',
	path : 'esri/dijit/OverviewMap',
	options : {
		map : true,
		attachTo : 'bottom-right',
		color : '#0000CC',
		height : 100,
		width : 125,
		opacity : 0.30,
		visible : false,
		baseLayer : new ArcGISDynamicMapServiceLayer('http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer')
	}
}
```
...it silently breaks all the widgets in left panel. But, if I debug Controller's `initWidgets` function, I see the following error:

![overview_error](https://cloud.githubusercontent.com/assets/10212618/11092063/683a4320-8867-11e5-8a42-87d0d20db733.png)

I tried to solve this with something tied to [this solution](https://geonet.esri.com/thread/31286#post114928), but no success.

PS: `ArcGISDynamicMapServiceLayer` is referenced in `config/viewer.js`.

**Comment by tmcgee** [comment]
@carrbrpoa I don't think you can use `new` here. The docs say "Note that the specified layer must be loaded, verify this using the layer's loaded property. If a base layer is not specified the dijit will use a copy of the main map's base layer."

**Comment by carrbrpoa** [comment]
Hey @tmcgee, you were right. I manage to make it work with some ugly coding. See:

End of Controller's `createWidget` function:
```javascript
(...)

// start up the widget
if (this[widgetConfig.id] && this[widgetConfig.id].startup && !this[widgetConfig.id]._started) {
	if (widgetConfig.id !== 'overviewMap') {
		this[widgetConfig.id].startup();
	} else {
		topic.publish('cmv/loadOverviewLayer');
	}
}
```

End of Controller's `startup` function:
```javascript
(...)
this.initPanes();

var app = this;

var overviewLayer = new ArcGISTiledMapServiceLayer('http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer');

topic.subscribe('cmv/loadOverviewLayer', lang.hitch(this, function (args) {
		if (overviewLayer.loaded) {
			app.overviewMap.baseLayer = overviewLayer;
			app.overviewMap.startup();
		} else {
			dojo.connect(overviewLayer, "onLoad", function () {
				app.overviewMap.baseLayer = overviewLayer;
				app.overviewMap.startup();
			});
		}
	}));

if (config.isDebug) {
	window.app = this; //dev only
}
```

Any better way? It doesn't seems right to me :p

**Comment by tmcgee** [comment]
You should be able to use an invisible widget for this.

In the invisible widget you can load the overviewLayer as you have written it with a function connected to the layer's `onLoad` event, In that function, you can load the overview map widget using:

``` javascript
topic.publish('viewer/loadWidget', {
    options: oveviewOptions
}
```

not tested but I think that will work.

**Comment by carrbrpoa** [comment]
Perfect @tmcgee, worked as you said :100:
Just to be sure it is the way: I don't declare `overviewMap` in config anymore; instead, I put it in an invisible widget, right?

```javascript
overviewMapLoader : {
	include : true,
	id : 'overviewMapLoader',
	type : 'invisible',
	path : 'dijit/_WidgetBase',
	options : {
		startup : function () {
			var overviewLayer = new ArcGISTiledMapServiceLayer('http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer');

			dojo.connect(overviewLayer, "onLoad", function () {
				topic.publish('viewer/loadWidget', {
					options : {
						include : true,
						id : 'overviewMap',
						type : 'map',
						path : 'esri/dijit/OverviewMap',
						options : {
							map : true,
							attachTo : 'bottom-right',
							color : '#0000CC',
							height : 100,
							width : 125,
							opacity : 0.30,
							visible : false,
							baseLayer : overviewLayer
						}
					}
				});
			});
		}
	}
}
```

PS: I took the *invisible* stuff [from here](https://github.com/tmcgee/cmv-widgets/issues/17#issuecomment-128541027).

**Comment by tmcgee** [comment]
@carrbrpoa That is correct. You would no longer load overview map as a widget in viewer.js. The invisible widget loads it for you.
