### ISSUE TITLE
Print Function

### ISSUE THREAD

**Issue by knabe2604** [cmv/cmv-app#28]
Can your default print service be substituted for a custom print service that we have? I tried to put the new rest end point into the code and everytime I press the print button it just has the error try again?

Thanks!

**Comment by velcroMustacho** [comment]
I'm also getting the "Error, try again" message while trying to export to a custom print layout. I've tried mosanderonimo's advice and confirmed that it's set to "synchronous" and  alwaysUseProxy is "True" and im getting the same results. is there any news on this front?
