### ISSUE TITLE
Find tool using Layer Definitions?

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#287]
This is a follow on from #202 which has been resolved by @tmcgee. I have layer definitons created dynamically which only show a subset of a layer's data. I would like to use the Find Tool to search a layer while excluding any results filtered out by the `layerDefiniton`.

**Comment by tmcgee** [comment]
closing. this was addressed in PR #289

**Comment by carrbrpoa** [comment]
What about Search widget? Is it possible to configure it to use layer definitions? (If needed, I can open a new issue)

**Comment by tmcgee** [comment]
@carrbrpoa My search widget already supports this for the FindTask. I would suggest opening a new issue over in my widgets repo to discuss how we might approach this with QueryTask in the Search widget.
