### ISSUE TITLE
Geocoder

### ISSUE THREAD

**Issue by knozaki2001** [cmv/cmv-app#307]
I noticed geocoder box seems to disappear on the small screen (especially portrait for iPhone and iPod).

**Comment by tmcgee** [comment]
There are css classes that intentionally hide some dom elements when on a small screen. You can remove or modify those classes if you desire. Alternatively, I like to use the other variation of the geocoder that is collapsed to minimize the screen real estate and is also placed on the map so it is available for all devices. Here's a screenshot from mobile:

![screen shot 2015-01-07 at 15 23 59](https://cloud.githubusercontent.com/assets/200780/5655358/f784d3fc-9681-11e4-90aa-42d6ecca7af1.png)

This is the config in viewer.js for the geocoder widget:

``` javascript
geocoder: {
	include: true,
	id: 'geocoder',
	path: 'gis/dijits/Geocoder',
	type: 'domNode',
	srcNodeRef: 'geocoderButton',
	options: {
		map: true,
		mapRightClickMenu: true,
		expanded: false,
		collapsible: true
	}
}
```

**Comment by tmcgee** [comment]
@knozaki2001 Did my response address your issue?

**Comment by knozaki2001** [comment]
Yes, thank you.

Keisuke

----- Original Message -----

**Comment by ERS-Long** [comment]
Hi, @tmcgee: 

very good and useful tip for this widget, here is a new issue, after i switched to the Search Widget, the expanded property seems does not work

            geocoder: {
                include: true,
            //    id: 'geocoder',
                type: 'domNode',
            //    path: 'gis/dijit/Geocoder',
                path: 'esri/dijit/Search',
                srcNodeRef: 'geocodeDijit',  
                options: {
                    map: true,
                    mapRightClickMenu: true,
                    expanded: false,
                    visible: false
                }  
            },

Please let me know if you have any idea about it. 

Thanks

**Comment by kcarrier** [comment]
@ERS-Long 

I think you need to change to srcNodeRef: 'geocoderButton' or something to that affect not sure what is called in the new widget.

How did you get the new search widget into CMV?

If you could share that would be awesome.

**Comment by ERS-Long** [comment]
@kcarrier 

i got that from Tim, just replace the geocoder setting in the vewier.js with this code

        geocoder: {
            include: true,
        //    id: 'geocoder',
            type: 'domNode',
        //    path: 'gis/dijit/Geocoder',
            path: 'esri/dijit/Search',
            srcNodeRef: 'geocodeDijit',  
            options: {
                map: true,
                mapRightClickMenu: true,
                expanded: false,
                visible: false
            }  
        },

for CMV 3.14, we have to use geocodeDijit for srcNodeRef

The new search widget is ESRI's new implementation.

**Comment by ERS-Long** [comment]
@kcarrier 

you can set that visible to true, i set it to false, because i hided the header initially, use a widget to turn on the header or off

**Comment by kcarrier** [comment]
@ERS-Long - I am using CMV 3.14 and the suggestion I posted is working for me.

```
geocoder: {
                include: true,
                //id: 'geocoder',
                type: 'domNode',
                path: 'gis/dijit/Geocoder',
                //srcNodeRef: 'geocodeDijit',
                srcNodeRef: 'geocoderButton',
                options: {
                    map: true,
                    mapRightClickMenu: true,
                    expanded: true,
                    collapsible: true,
                    geocoderOptions: {
                        autoComplete: true,
                        arcgisGeocoder: false, //if true a pick list showing your custom geocoder(s) below and the ESRI widget will appear for the end user to select
                        zoomScale: 1000,
                        suggest: true,
                        placeholder: 'Search for an address',
                        highlightLocation: true,
                        showResults: true,
                        symbol: new PictureMarkerSymbol({
                            angle: 15,
                            xoffset: -12,
                            yoffset: 24,
                            type: 'esriPMS',
                            url: 'http://static.arcgis.com/images/Symbols/Basic/RedFlag.png',
                            contentType: 'image/png',
                            width: 18,
                            height: 18
                        }),
                        geocoders: [{
                            url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Composite_151130/GeocodeServer',
                            name: 'My Address Points',
                            autoComplete: true,
                            zoomScale: 1000,
                            suggest: true,
                            singleLineFieldName: 'SingleLine'
                        }]
                    }
                }
            },
```

**Comment by ERS-Long** [comment]
yes, you are using path: 'gis/dijit/Geocoder', that is old way to do geocoding

ESRI has a new way,  path: 'esri/dijit/Search',

**Comment by kcarrier** [comment]
Yeah but I thought we needed a Search folder for it to work? In my dijit folder I am using @tmcgee 's Search widget so I would have to make some other changes, I thought someone was going to have to build a widget around the new esri js Search widget for us to be able to use it in CMV.

**Comment by ERS-Long** [comment]
no, this one is ESRI widget (they paln to use this to replace the geocoder), 

https://developers.arcgis.com/javascript/jsapi/search-amd.html

so the path is 

path: 'esri/dijit/Search',

we dont need to provide the implementation part of the code.

(It is not Tim's Search user CMV widget).

**Comment by tmcgee** [comment]
@ERS-Long:

`expanded` is not something supported by the ESRI search widget. That configuration item is specific to the CMV geocoder widget. Perhaps `enableButtonMode: true` will allow the ESRI search widget to behave in a similar manner. I have not tried that configuration.

You can use `geocoderButton` for the `srcNodeRef`. as @kcarrier mentioned. That has been supported for quite sometime in CMV. Using that srcNodeRef places the geocoder widget in the map next to the navigation: Here's the [domNode](https://github.com/cmv/cmv-app/blob/master/viewer/js/viewer/templates/mapOverlay.html#L20).

@kcarrier: In order to use the ESRI search widget, you have to change [this line in Controller](https://github.com/cmv/cmv-app/blob/master/viewer/js/viewer/Controller.js#L508). That ESRI widget includes its own `id` which I think is a bad practice in the dojo dijit/widget world. You should change the line in Controller from this: 

``` javascript
options.id = widgetConfig.id + '_widget';
```

to this:

``` javascript
if (options.id) {
    options.id = widgetConfig.id + '_widget';
}
```

And then omit the id in the widget configuration as @ERS-Long did:
``` javascript
//    id: 'geocoder',
```

And the ESRI Search widget works fine in the same application as my contributed Search widget. Their widget is uses the `esri/dijit`path. Other ESRI widgets like scalebar and overview map use that as well.

**Comment by ERS-Long** [comment]
Thanks @tmcgee, that enableButtonMode: true does the trick

            geocoder: {
                include: true,
            //    id: 'geocoder',
                type: 'domNode',
            //    path: 'gis/dijit/Geocoder',
                path: 'esri/dijit/Search',
                srcNodeRef: 'geocodeDijit',  
                options: {
                    map: true,
                    mapRightClickMenu: true,
                    expanded: false,
                    visible: false,
                    enableButtonMode: true
                }  
            },

**Comment by tmcgee** [comment]
good to know.

**Comment by kcarrier** [comment]
@ERS-Long - What the heck, I see how it is @tmcgee gets the credit, but I said that like 4 or 5 post ago. LOL Cool to see it can be done. Thanks for posting @ERS-Long

**Comment by ERS-Long** [comment]
my bad, i completely missed that line, was on a conference call, got side tracked i guess

Yes, that is the trick. Thanks a lot! :)

**Comment by ERS-Long** [comment]
changed to geocoderButton

            geocoder: {
                include: true,
            //    id: 'geocoder',
                type: 'domNode',
            //    path: 'gis/dijit/Geocoder',
                path: 'esri/dijit/Search',
                srcNodeRef: 'geocoderButton',  
                options: {
                    map: true,
                    mapRightClickMenu: true,
                    expanded: false,
                    visible: true,
                    enableButtonMode: true
                }  
            },


works as expected. 
![image](https://cloud.githubusercontent.com/assets/5911272/11852180/3e8969a6-a3fc-11e5-8d08-863672ad3e2d.png)

![image](https://cloud.githubusercontent.com/assets/5911272/11852239/7a90a216-a3fc-11e5-9225-19237dcd3e5c.png)

**Comment by tmcgee** [comment]
great!

@cmv/core-committers Since ESRI deprecated their Geocoder widget, perhaps it is time to retire the cmv geocoder widget that wraps it?

**Comment by tmcgee** [comment]
fyi, the revised code I posted in the [above comment](https://github.com/cmv/cmv-app/issues/307#issuecomment-165215288) was incorrect. The correct code is:

``` javascript
if (widgetConfig.id) {
     options.id = widgetConfig.id + '_widget';
}
```

This change is included in the pending Pull Request #496

**Comment by ERS-Long** [comment]
Yes, I double checked, my controller is using the above code.
Thanks!

**Comment by kcarrier** [comment]
@tmcgee, @cmv/core-committers - I would agree the new Search widget would be a good addition to the cmv app. Considering both feature searches and geocode searches can be rolled into one widget now. I still think the find widget is necessary but the Esri Search widget might help others simplify the process of searching for a feature in the app.
