### ISSUE TITLE
Maximize/resize Google StreetMap Widget Panel

### ISSUE THREAD

**Issue by jtorresleon** [cmv/cmv-app#317]
Hi,
the Google StreetMap Widget is very useful and nice, but I wonder how make a button to maximice the panel/window of the widget, or to be able to resize the tiny window. The option to see the StreetView bigger, would make this widget much more useful and helpful

**Comment by kjmueller** [comment]
Where is the adjustable sidebar option located?

Thanks for your help.

**Comment by tmcgee** [comment]
@kjmueller For the left side pane you would add this to your `config/viewer.js`:

```
panes: {
    left: {
        splitter: true
    }
},

**Comment by kjmueller** [comment]
Thanks for your help Tim!
