### ISSUE TITLE
OID/FID In Identify Window

### ISSUE THREAD

**Issue by laceys** [cmv/cmv-app#327]
Although I have set my visible fields in the layers of my service, indicated which layer/fields should be included in config/identify I still can't seem to get rid of the OID and FID fields.  Is there another way to set the fields to uninclude that data?  It works for every field but those two.

Thanks,
Lacey

**Comment by Tijsi** [comment]
Hey,

I had the same issue with the OBJECTID fields, that would show up in every pop-up. I wasn't keen on configuring every field individually and added some code on line 352 in Identify.js that fixed it:

            // from the results
            if (result && result.feature) {
                var attributes = result.feature.attributes;
                if (attributes) {
                    for (var prop in attributes) {
                        if (attributes.hasOwnProperty(prop) && prop !== 'OBJECTID') { // Added by Tijs (Interpret) to prevent OBJECTID in popup
                            fieldInfos.push({
                                fieldName: prop,
                                visible: true
                            });
                        }
                    }
                }


you could try the same for OID/FID.

**Comment by tmcgee** [comment]
@Tijsi Thanks for that. I have done similar things clients which turned into a CMV enhancement coming in the next version. These fields excluded by default:

```
excludedFields: [
    'objectid',
    'esri_oid',
    'shape',
    'shape.len',
    'shape.area',
    'shape.starea()',
    'shape.stlength()'
],
```

And of course, that array of fields is configurable so the excluded fields can be overridden for any application if needed.

**Comment by Tijsi** [comment]
nice, thanks

**Comment by Tijsi** [comment]
nice, thanks

**Comment by laceys** [comment]
Thank you!  I will add that to my code.  I also found that updating to the
latest version seems to resolve the issue as well.

I truly appreciate you taking the time to respond!
