### ISSUE TITLE
Print Widget

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#332]
Is the print widget works with Asynchronous services?
Keep getting errors.

Thank you,

**Comment by saurabhgis** [comment]
Hi All, @tmcgee @goriliukasbuxton @jebu75 @leighghunt @ajturner 

I am trying to implement custom print service published on my own server but facing some issues.

I am not able to understand when accessing print service on LAN there is no issue, but when accesing outside of LAN it throws error 

1. Error executing tool. Export Web Map Task Job ID: j551fbfab73ad4c2d970664fd1519a7bd : Layer "layer0": Unable to connect to map server at http://Public IP :6080/arcgis/rest/services/sbh/Basemap12/MapServer. Failed to execute (Export Web Map). Failed to execute (Export Web Map Task).

2. A connection with the server could not be established (WinINet Error while using HTTPS security, 12029), URL = http://Public IP:6080/arcgis/rest/services/sbh/Basemap12/MapServer?f=json

3. A connection with the server could not be established (WinINet Error while using HTTPS security, 12029), URL = http:/Public IP:6080/arcgis/rest/info?f=json

Please help how to resolve this issue.

**Comment by tmcgee** [comment]
@saurabhgis This is unrelated to the issue you commented on. This is a different issue not directly related to DMV but with the setup of your ArcGIS Server and most likely the network firewall. The message indicates that the windows user associated with the ArcGIS windows service does not have the ability to access the public server. Most often this an intentional security setting in the network firewall that prevents the server (by IP?) or the Windows user from getting to the internet. This is something that needs to addressed by the IT group. You can document/verify the issue by logging in as the same user on that internal server and attempting to browse to the public server using a browser.

**Comment by saurabhgis** [comment]
@tmcgee  agree with you that issues is not related to CMV.

I have checked firewall port is opened to access url publically even map are displayed perfectly publically only facing issue in printing. I have tried lots off option read your previous chat discussion. I have set proxy true, in proxy.config set restservices url <serverUrl url="http:PublicIP:6080/arcgis/rest/services" matchAll="true"> but not succeed. My error is Error executing tool. Export Web Map Task Job ID: j551fbfab73ad4c2d970664fd1519a7bd : Layer "layer0": Unable to connect to map server at http://IP:6080/arcgis/rest/services/sbh/Basemap12/MapServer. Failed to execute (Export Web Map). Failed to execute (Export Web Map Task).

Please suggest as per your experience what should i have to do.

**Comment by tmcgee** [comment]
@saurgis It sounds like you did not completely understand my last message. The Esri resource proxy has no role in this. 

The error message reports an issue on the AGS server where the Print Service is running. You need to check the connectivity FROM THE AGS SERVER. That requires logging on to the AGS server using the Windows login associated with the AGS Windows Services and checking that specific user can access the public server. That user often is a local user "arcgis". Typically, local users such as this are prevented access to the internet. You may need assistance from your IT group or whomever handles network security to get the configuration setup properly. You could also open a support ticket with Esri. They might be able to assist. I've provided a method to help diagnose the issue to hopefully assist you in communicating with them. For many reasons, I do not provide advice on network security without a full understanding of the operating picture within the network.
