### ISSUE TITLE
Measure Tool looses state after navigation event

### ISSUE THREAD

**Issue by ghost** [cmv/cmv-app#335]
The measure tool stops working if a zoom or pan event occurs during the course of measurement.  ESRI's sample does not exhibit this behavior.  I have not found a way to force persistence for the global 'mapClickMode' variable through navigation events.  I finally got it working after setting the default tool to null and modifying the measure widget.  However, I would like to keep the default tool setting and have the measure tool work correctly.

**Comment by DavidSpriggs** [comment]
@friendde @ghost HAs this been resolved? I will close but add link to fix please.

**Comment by friendde** [comment]
@DavidSpriggs still busy with other projects. I will fix my widget asap. If @ghost has a fix I will accept a PR.... I miss CMV it is a fun project to work with you all.

**Comment by tmcgee** [comment]
Come back friendde! come back! ;-)

**Comment by thejuskambi** [comment]
Has this issue been fixed?
