### ISSUE TITLE
Proxy page on viewer server limitation

### ISSUE THREAD

**Issue by rkoelpin** [cmv/cmv-app#342]
I am puzzled by the comments in indentify04.js and viewer.js " // url to your proxy page, must be on same machine hosting you app. See proxy folder for readme. "

Is this limitation unique to CMV or is it more general to javascript? Is there a way around this limitation? 

We are exploring the move from flex (3.x) to javascript viewers.  Our arcgis (10.2.2) services consume the security store from another application (WebEOC). In flex the httpproxy path in the config.xml is to another server - the server hosting WebEOC.

**Comment by tmcgee** [comment]
@rkoelpin Using a proxy is not unique to CMV or the ArcGIS JavaScript API. It isn't specific to JavaScript either though JavaScript is a commonly used to access resources via a proxy. It is a security mechanism called "Same-Origin Policy" and "Cross-Origin Resouce Sharing" (CORS) for web applications that is built into all browsers.

Here are more details about [Same-Origin Policy](http://en.wikipedia.org/wiki/Same-origin_policy) and [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

Here are more details about [use of a proxy](https://developers.arcgis.com/javascript/jshelp/ags_proxy.html) as it pertains to the ArcGIS JavaScript API and thus CMV.

**Comment by rkoelpin** [comment]
Thanks, I understand, to some degree, use of a proxy.

I don’t understand the limitation in the CMV that the proxy must be on the viewer’s server only. Is that requirement per the comments in the .js files of CMV unique to CMV?

**Comment by tmcgee** [comment]
Yes, a proxy on your web server (your domain) is common requirement for accessing resources from another domain (another server). Without getting into too much detail, accessing a proxy page on another server is not allowed in JavaScript.

There are other approaches such as using CORS Policies to explicitly allow access across domains or using JavaScript callback functions and [JSONP](http://en.wikipedia.org/wiki/JSONP) which may likely require changes in the response generated by the other server.

**Comment by rkoelpin** [comment]
Thanks, the confirmation is what I needed.

**Comment by DavidSpriggs** [comment]
@rkoelpin To learn more about when a proxy is used in the API and a good overview see here: https://developers.arcgis.com/javascript/jshelp/ags_proxy.html

**Comment by rkoelpin** [comment]
Thanks,

My question is more whether javascript or CMV allow us to access proxies on remote boxes.  Tim Mcgee already told me not so much for anything javascript, unless I go with CORS or callback and jsonp.

I understand use of proxies somewhat.  We are using them for the flex viewers to define roles in one application (webeoc) and then allow access to services in arcgis according to those roles. In flex we reference the proxy on the webeoc server.

Arcserver is consuming the (token-based) security store from WebEOC. Per your link, more along the lines of “You are building an application that targets end users are not known to the ArcGIS platform. In this situation the application will login to the platform using information stored in the proxy. View Authentication, OAuth 2.0, and ArcGIS<https://developers.arcgis.com/authentication/> for details.”  And the proxy is on the WebEOC box,

**Comment by rkoelpin** [comment]
Thanks turns out the short answer was here  http://enable-cors.org/server_iis7.html – just update the web.config in the viewer’s root

**Comment by rkoelpin** [comment]
Thanks turns out the short answer was here  http://enable-cors.org/server_iis7.html – just update the web.config in the viewer’s root

**Comment by tmcgee** [comment]
Glad that CORS can work for you. You are fortunate to have access/ability/cooperation to change the remote server to enable that support.
