### ISSUE TITLE
Refresh sub layers with on/off make disappear the layer? what's wrong (latest version)

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#343]
Go and try:On the site http://gis.icao.int/icaoviewernew/  every things are very great..I have just the problem of refresh layers (all dynamic layers) try ICAORADAR close Secondary and every thing disappear, and all the other clicks on the layer ICAORADAR or on the sub layer Primary give the same result nothing???Same problem on all my services with sub layers, so very strange, its just missing that redraw... and I will be able to change all my services with your cmv interface, All the other functions are very good with that version, I don't know what I make wrong, the layers of Louisville Public Safety are OK for the refresh on/off, very strange, I appreciate some help, Many thanks all of you and happy new year...

**Comment by GilbertLasnier** [comment]
I don't succeed since that time, now its very urgent!!!

**Comment by tmcgee** [comment]
One possibility is that you have run into some incompatibility with your version of ArcGIS Server. Version 10.02 is pretty old and on the verge of [retirement](http://downloads.esri.com/support/product%20life%20cycle/server_gis/ArcGISServer_PLC.pdf).

**Comment by tmcgee** [comment]
Try removing the spaces from your layer IDs in the operational layers. spaces in an ID is typically not valid.

**Comment by GilbertLasnier** [comment]
Many thanks Tim
For your answer your right I have 10.0.2 I pay my maintenance but I have no time to install because some people tell me I must remake all my 100 services , I am dead if I do that, so I try to make  the update soon and also I erase all the space in the id name thank for you great answer, I tell you if it’s working.. Merci Beaucoup
Gilbert

**Comment by GilbertLasnier** [comment]
Hello Tim you are my hero, its working perfectly now I try to incorporate your table of attribute that you send to me before chrismas, may thanks for you support
