### ISSUE TITLE
zoom level limited

### ISSUE THREAD

**Issue by lee53** [cmv/cmv-app#345]
It looks like there is a limitation on the zoom level, even the base maps have more detail zoom levels. 
Which config controls this max zoom level and how to change it?

**Comment by tmcgee** [comment]
@lee53 You can add `maxZoom` and/or `minZoom` to the [mapOptions](https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L26) in `config/viewer.js`. Those properties are usually added to restrict the zoom levels for an app not extend the zoom levels. If you do not provide those options, the ArcGIS JavaScript API uses the maximum/minimum zoom levels supported by the basemap.

Here is the documentation for the map's config object: https://developers.arcgis.com/javascript/jsapi/map-amd.html#map1

**Comment by lee53** [comment]
@tmcgee I see. depending the initial basemap in viewer.js, the zoom level is determined. I used the lightgray which has maxzoom 17 only.  So even google satellite has zoom 19, I cannot zoom to this level.  Thank you for the info.
