### ISSUE TITLE
Offline use - download all CSS and fonts

### ISSUE THREAD

**Issue by Tijsi** [cmv/cmv-app#346]
Hi,

I was wondering if there might be a way to use the cmv-app in an offline setting, on an internal server that connects to a local ArcGIS Server.

For that reason, is it possible to download all the settings and fonts connected to the reference below?
        
<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

I'm not very well known with CDN, but it might be good to have a fully offline backup for any implementation of the app.

Thanks!

**Comment by tmcgee** [comment]
1. Information on downloading the ArcGIS JavaScript API (including dojo and ESRI widgets) is here: https://developers.arcgis.com/javascript/jshelp/intro_accessapi.html

2. You can download Font-Awesome (fonts and css) here: http://fortawesome.github.io/Font-Awesome/

3. You can download the Proj4JS library here (used for coordinate transformation by some widgets): http://proj4js.org/

I'll leave up to you the tweaking of various urls in the CMV project to point to your alternative internal folders...

That will get you started. By going completely "offline", you obviously will lose access to ArcGIS On-line basemaps, Google Street View and perhaps some other things I am forgetting.

**Comment by Tijsi** [comment]
Excellent, thanks a lot!
