### ISSUE TITLE
Specify specific layer ids for dynamic layer type

### ISSUE THREAD

**Issue by gregoryaroberts1** [cmv/cmv-app#347]
Hello,
In the current version of the cmv, is it possible to specify specific layer ids for a dynamic layer? Listing those layer ids would allow that layer to be listed in the Layer Control widget and for it to be shown on the map. I've been looking through the documentation and tried several changes to the config/viewer.js file but haven't had much luck.

Also, if this currently isn't possible to do, how feasible is it? Thanks!

**Comment by tmcgee** [comment]
Are you wanting to show/hide certain sub layers/layer groups of a dynamic layer when the map is first visible? If so, look at using `ImageParameters` (https://developers.arcgis.com/javascript/jsapi/imageparameters-amd.html). There is some example code in issue #198. I believe that at present the layerControl widget doesn't fully respect layers shown/hidden in this fashion due to the way the ArcGIS JS API lists the "visiblelayers" of a dynamic layer. There has been some discussion about possible work-arounds but nothing right now.

**Comment by gregoryaroberts1** [comment]
Thanks for the quick reply. I actually did look at your sample code earlier today and tried it out. When used, it turned on the layer ids that I listed and left all the other layers turned off. But, they are still listed in the Layer Control Widget. I would ideally like to specifiy a list of layer ids and have only those layers be visible within the layer control widget.

**Comment by tmcgee** [comment]
Yep. you are running into the issue with the layerControl that I identified. @btfou might have some more insight into the issue and possible work-arounds considered. I do know that Ben is pretty busy right now so am not sure when he might be able to provide that insight.

**Comment by gregoryaroberts1** [comment]
I've been looking through the forum reading the various comments regarding the layerControl widget. I'm not totally sure what I am referring to is the same issue that you are talking about (but then again maybe I'm not totally understanding).

Just to make sure... what I am referring to is that I currently have a map service that contains six different layer ids. I am consuming that service in config/viewer.js in the operational layers as a dynamic layer type. Instead of all those six layers being listed in the layerControl widget, I would only like to include a select few (IDs 1, 2 and 3) - I do not want any of the other layers (IDs 4, 5 and 6) from that dynamic layer to be available within the map or layerControl widget. The functionality would be comparable to a feature layer type where you can specify the exact layer id to include except, I need this layer to be dynamic.

Thanks again for the help and I apologize for the confusion.

**Comment by tmcgee** [comment]
The code I linked to will handle the display of the sub layers with ids 1,2 and 3 on the map.

The part that isn't properly handled at this time is hiding the sub layers with ids 4, 5 and 6 within the layerControl. As an alternative, you can use css to hide the DOM elements for these sub layers. Something like this will work:

``` css
div#louisvillePubSafety-4-sublayer-control {
    display: none;
}
```

where `louisvillePubSafety` is the id of the dynamic layer and `4` is the id of the sub layer you want to hide.

**Comment by btfou** [comment]
@gregoryaroberts1 This has come up before. LayerControl layer options needs a parameter (array of layer ids) and the widget with handle setting the layer ids and create the UI to reflect those ids as well. I'm reluctant to make these changes to the widget right now: 1) esri layer classes will inherit from dojo/Stateful soon, 2) the next major release of CMV will include a stateful app model as well as layer/widget models. These two together will make handling dynamic sublayers much easier.

PRs are always welcome. :)

note to self: do layers inherit stateful in 3.12?

**Comment by tmcgee** [comment]
@btfou, Thanks for popping your head up. ;)

Instead of passing another array, can the layerControl grab the layerIDs from the ImageParameters that, in this case, is already part of the dynamic layer? There would also be some minor (hopefully) logic to respect the various `layerOptions` (like hide/show/visible).

**Comment by btfou** [comment]
@tmcgee Specifying layer ids via imageParameters is meant to set the sublayers and not to have change them, nor does that method work on layer groups. As I recall I hit a brick wall using imageParameters; not to say there isn't a way. The example posted on stack exchange still required an array of layer ids to be passed to build the UI. My thought moving forward was simply an options array of layer ids to include and an optional second options array of layer ids to set initially visible layers (override defaults). Then let the widget handle setting the sublayers and building the UI. But always open to suggestions.

**Comment by tmcgee** [comment]
@btfou: I see where you are going with this. Consider using ImageParameters (if there) to get the initial visibility since it would have to be included regardless - the layer is already displayed on the map before the control is loaded.

**Comment by gregoryaroberts1** [comment]
Thank you both for your input. I'm able to get the result I'm looking for by using the imageParameters example and the css. I will keep an eye on how this continues to change with the upgrade of the api and I will try to help out wherever I can.

**Comment by saurabhgis** [comment]
Can we show hide/show layerids in Layercontrol??

**Comment by tmcgee** [comment]
@saurabhgis Depending on your needs, the answers may be in the comments above. If not addressed above, can you please clarify your question.
