### ISSUE TITLE
Measurement of Segments

### ISSUE THREAD

**Issue by Zerg21** [cmv/cmv-app#348]
Some of my end users would like the ability to see the individual lengths of each line segment when using the measure tool. They are primarily running into issues when checking property boundaries against the legal descriptions where there are defined lengths. The current process requires them to either write down the lengths and subtract from the total or make multiple measurements which can lead to inaccuracies. I'm not sure which bits of code I will have to edit, but I also don't seem to be having any luck finding examples through the API Reference for this issue. I thought I better ask the community before starting from scratch to see if it has been done or if anyone had ideas for a starting point.

**Comment by tmcgee** [comment]
@Zerg21 I see that at version 3.11 of the API, there was a new `measure` [event](https://developers.arcgis.com/javascript/jsapi/measurement-amd.html#events) added for the ESRI measurement widget. You might be able to do something with that.

The cmv measurement widget wraps the ESRI version. The ESRI version is the widget that currently displays the length/area so you might need to add some additional UI to display the intermediate lengths.

If you do create something based off with the existing CMV widget, please consider adding a Pull Request in this repo with your enhancements. I know from my ArcIMS developer days that this is desirable functionality currently missing in most apps using the JavaScript API and AGS.

**Comment by Zerg21** [comment]
@tmcgee thanks and now I'll take a longer look at it. It was only recently requested for me and I was hoping to luck out and it would have been something that had come up from other users in the past. I guess you can't always get lucky, ha. If I create something that's worth adding to the repo, I'll make sure to submit a Pull Request.

**Comment by tmcgee** [comment]
@Zerg21 Did you ever get something going for this one?
