### ISSUE TITLE
Customize Login prompt

### ISSUE THREAD

**Issue by husenk** [cmv/cmv-app#351]
Hi All

Can someone show me how to customize the login prompt for secured services in CMV? I would like to change the text content and remove the cancel  button if possible.

Thanks

**Comment by faridcher** [comment]
Login prompt is part of arcgis javascript api. to change the text content you should localize the api. To remove the Cancell button you should manipulate the api itself.

**Comment by tmcgee** [comment]
One method to override the locale strings within the esri bundle with your own custom text is at the bottom of [this page](https://developers.arcgis.com/javascript/jshelp/localization.html).

To hide (not remove) the cancel button, you can use CSS:

``` css
.esriIdCancel {
    display: none !important;
}
```

**Comment by husenk** [comment]
Thanks for pointing to the solution. All good now.
