### ISSUE TITLE
Architecture Question: Access to functions in other digits?

### ISSUE THREAD

**Issue by jerrygarciame123** [cmv/cmv-app#352]
Can someone provide an example to access functions from one digit in another?

For example, I can include "gis/dijit/newCustomDijit".  I can get access to the functions via the prototype property, but with none of the current values.  

I need to get to execute a function from another digit in the current scope.

Thank you very much!

**Comment by tmcgee** [comment]
Have you tried using `dijit/registry`? You can do something like this to get access to the other widget:

``` javascript
var widget = registry.byId('myOtherWidgetID');
if (widget) {
    widget.myFunction();
}
```

**Comment by jerrygarciame123** [comment]
Great.  Thanks!
