### ISSUE TITLE
Show Attachments

### ISSUE THREAD

**Issue by knabe2604** [cmv/cmv-app#36]
Is there a way to config the infotemplate to show attachments?

**Comment by taran03** [comment]
Hi David,

Do you have any recommendations on how to display attachments for secure services in the cmv identify popup?  I'm able to do this with unsecured services, but with a secure service the user is redirected to login to the rest endpoint before they can view the attachment.  I have a proxy set in the viewer.js that is functioning, but the identify tool doesn't honor this for the attachments.  Thanks!

![image](https://cloud.githubusercontent.com/assets/8386074/6507077/3c06ae46-c315-11e4-8c2d-7e3ea53e4280.png)

![image](https://cloud.githubusercontent.com/assets/8386074/6507086/4c40934e-c315-11e4-8edf-47262bf09880.png)
