### ISSUE TITLE
Do you have a wildcard to use with the Find in cmv?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#360]
Example i must find only the code in doc7910 starting with SH contain 4 letters
So i try SH__ i put tow_ for my wildcard no result
After i try SH%% , no result, after i try SH** no result
Somebody know how to obtain the result like i want SHOB, SHOF, SHJO, SHSS, SHDU etc...
I hope its possible?
Merci

**Comment by tmcgee** [comment]
Unfortunately, the FindTask in the ArcGIS JavaScript API used by the Find widget does not support wildcards.

**Comment by GilbertLasnier** [comment]
Many thanks for you super fast anwser

Envoyé de mon iPad

Le 2015-01-24 à 16:54, Tim McGee <notifications@github.com<mailto:notifications@github.com>> a écrit :


Unfortunately, the FindTask in the ArcGIS JavaScript API used by the Find widget does not support wildcards.

**Comment by friendde** [comment]
Is typing SH acceptable then sorting result column to get all SH lined up? This will return anything with sh anywhere in the string.

**Comment by GilbertLasnier** [comment]
When you type SH its exact you obtain SH every where so if you search in name airport and code airport you have every thing...Merci quand meme
