### ISSUE TITLE
Do you think its willbe hard to make a dual query with the Find tool in cmv?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#361]
I would like to find by the name of the FIR (FLIGHT INFORMQTION REGION) and for the other attribut of the search the kind of the point for that FIR (1 legal pts 2 boundary pts)
I make that with silverlight but i like better now your javascript interface, if you go to 
Http://gis.icao.int/appsilver/icaofir2014
And you just type on the first P in the menubar, you obtain the dual query in the 3.2 silverlight api...

**Comment by tmcgee** [comment]
Unfortunately, searching for value(s) in both fields (as opposed to the same value in either field) is not possible using the FindTask in the ArcGIS JavaScript API used by the Find widget.

I don't have Silverlight installed anywhere so I cannot view your current application but by your description it sounds like the job for a custom widget using QueryTask. I suspect that's what was done in the Silverlight app.

**Comment by GilbertLasnier** [comment]
True is make with silverlight app and true ist a custom widget using Query task
![queryinsilverlight](https://cloud.githubusercontent.com/assets/6784515/5901960/7d788474-a544-11e4-9733-e7f5e5ac4c8c.jpg)

**Comment by tmcgee** [comment]
@GilbertLasnier There are now a couple of `search` widgets provided by the user community that use QueryTask that can accomplish what your are looking for.

One [search widget is written by me](https://github.com/tmcgee/cmv-widgets#search) and used in conjunction with my [Attributes Tables widget](https://github.com/tmcgee/cmv-widgets#attributes-tables) to show the results. Here is [another one](https://github.com/vojvod/CMV_AdvancedSearch_Widget) that has some different functionality.

If you need assistance in getting any user-contributed widgets configured properly, post your questions  in their repos.
