### ISSUE TITLE
With the Draw tool are we able to create the TEXT box to write the lat long of a new points?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#362]
its will be great to have a tool to write text on the top of the map...like lat long for
![point](https://cloud.githubusercontent.com/assets/6784515/5906684/8ceee6a0-a567-11e4-8863-5b7bff8b2dd6.jpg)

**Comment by billchappell** [comment]
I add the text tool to my map, my code below, a little rough but it works.

draw.js
define([
   'dojo/_base/declare',
   'dijit/_WidgetBase',
   'dijit/_TemplatedMixin',
   'dijit/_WidgetsInTemplateMixin',
   'dojo/_base/lang',
   'dojo/_base/Color',
   'esri/toolbars/draw',
   'esri/layers/GraphicsLayer',
   'esri/graphic',
   'esri/renderers/SimpleRenderer',
   'dojo/text!./Draw/templates/Draw.html',
   'esri/renderers/UniqueValueRenderer',
   'esri/symbols/SimpleMarkerSymbol',
   'esri/symbols/SimpleLineSymbol',
   'esri/symbols/SimpleFillSymbol',
   'esri/layers/FeatureLayer',
   'dojo/topic',
   'dojo/aspect',
   'dojo/i18n!./Draw/nls/resource',

   'dijit/form/Button',
   'xstyle/css!./Draw/css/Draw.css',
   'xstyle/css!./Draw/css/adw-icons.css'
], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin, lang, Color, Draw, GraphicsLayer, Graphic, SimpleRenderer, drawTemplate, UniqueValueRenderer, SimpleMarkerSymbol, SimpleLineSymbol, SimpleFillSymbol, FeatureLayer, topic, aspect, i18n) {

var textFlag = false;

    // main draw dijit
    return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        widgetsInTemplate: true,
        templateString: drawTemplate,
        i18n: i18n,
        drawToolbar: null,
        mapClickMode: null,
        postCreate: function () {
            this.inherited(arguments);
            this.drawToolbar = new Draw(this.map);
            this.drawToolbar.on('draw-end', lang.hitch(this, 'onDrawToolbarDrawEnd'));

            this.createGraphicLayers();

            this.own(topic.subscribe('mapClickMode/currentSet', lang.hitch(this, 'setMapClickMode')));
            if (this.parentWidget && this.parentWidget.toggleable) {
                this.own(aspect.after(this.parentWidget, 'toggle', lang.hitch(this, function () {
                    this.onLayoutChange(this.parentWidget.open);
                })));
            }
        },
        createGraphicLayers: function () {
            this.pointSymbol = new SimpleMarkerSymbol(SimpleMarkerSymbol.STYLE_CIRCLE, 10, new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID, new Color([255, 0, 0]), 1), new Color([255, 0, 0, 1.0]));
            this.polylineSymbol = new SimpleLineSymbol(SimpleLineSymbol.STYLE_DASH, new Color([255, 0, 0]), 1);
            this.polygonSymbol = new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID, new SimpleLineSymbol(SimpleLineSymbol.STYLE_DASHDOT, new Color([255, 0, 0]), 2), new Color([255, 255, 0, 0.0]));
            this.pointGraphics = new GraphicsLayer({
                id: 'drawGraphics_point',
                title: 'Draw Graphics'
            });
            this.pointRenderer = new SimpleRenderer(this.pointSymbol);
            this.pointRenderer.label = 'User drawn points';
            this.pointRenderer.description = 'User drawn points';
            this.pointGraphics.setRenderer(this.pointRenderer);
            this.map.addLayer(this.pointGraphics);
            this.polylineGraphics = new GraphicsLayer({
                id: 'drawGraphics_line',
                title: 'Draw Graphics'
            });
            this.polylineRenderer = new SimpleRenderer(this.polylineSymbol);
            this.polylineRenderer.label = 'User drawn lines';
            this.polylineRenderer.description = 'User drawn lines';
            this.polylineGraphics.setRenderer(this.polylineRenderer);
            this.map.addLayer(this.polylineGraphics);

            this.polygonGraphics = new FeatureLayer({
                layerDefinition: {
                    geometryType: 'esriGeometryPolygon',
                    fields: [{
                        name: 'OBJECTID',
                        type: 'esriFieldTypeOID',
                        alias: 'OBJECTID',
                        domain: null,
                        editable: false,
                        nullable: false
                    }, {
                        name: 'ren',
                        type: 'esriFieldTypeInteger',
                        alias: 'ren',
                        domain: null,
                        editable: true,
                        nullable: false
                    }]
                },
                featureSet: null
            }, {
                id: 'drawGraphics_poly',
                title: 'Draw Graphics',
                mode: FeatureLayer.MODE_SNAPSHOT
            });
            this.polygonRenderer = new UniqueValueRenderer(new SimpleFillSymbol(), 'ren', null, null, ', ');
                this.polygonRenderer.addValue({
                    value: 1,
                    symbol: new SimpleFillSymbol({
                    color: [255,170,0,255],
                    outline: {
                        color: [255,170,0,255],
                        width: 1,
                        type: 'esriSLS',
                        style: 'esriSLSSolid'
                    },
                    type: 'esriSFS',
                    style: 'esriSFSForwardDiagonal'
                }),
                label: 'User drawn polygons',
                description: 'User drawn polygons'
            });
            this.polygonGraphics.setRenderer(this.polygonRenderer);
            this.map.addLayer(this.polygonGraphics);
        },
        drawPoint: function () {
            this.disconnectMapClick();
			textFlag = false;
            this.drawToolbar.activate(Draw.POINT);
            this.drawModeTextNode.innerText = this.i18n.labels.point;
        },
        drawCircle: function () {
            this.disconnectMapClick();
            this.drawToolbar.activate(Draw.CIRCLE);
            this.drawModeTextNode.innerText = this.i18n.labels.circle;
        },
        drawLine: function () {
            this.disconnectMapClick();
            this.drawToolbar.activate(Draw.POLYLINE);
            this.drawModeTextNode.innerText = this.i18n.labels.polyline;
        },
        drawFreehandLine: function () {
            this.disconnectMapClick();
            this.drawToolbar.activate(Draw.FREEHAND_POLYLINE);
            this.drawModeTextNode.innerText = this.i18n.labels.freehandPolyline;
        },
        drawPolygon: function () {
            this.disconnectMapClick();
            this.drawToolbar.activate(Draw.POLYGON);
            this.drawModeTextNode.innerText = this.i18n.labels.polygon;
        },
        drawFreehandPolygon: function () {
            this.disconnectMapClick();
            this.drawToolbar.activate(Draw.FREEHAND_POLYGON);
            this.drawModeTextNode.innerText = this.i18n.labels.freehandPolygon;
        },
        disconnectMapClick: function () {
            topic.publish('mapClickMode/setCurrent', 'draw');
            this.enableStopButtons();
            // dojo.disconnect(this.mapClickEventHandle);
            // this.mapClickEventHandle = null;
        },
		
		drawText: function () {
            textFlag = true;
            this.drawToolbar.activate(Draw.POINT);
        },
	
		
        connectMapClick: function () {
            topic.publish('mapClickMode/setDefault');
            this.disableStopButtons();
            // if (this.mapClickEventHandle === null) {
            //     this.mapClickEventHandle = dojo.connect(this.map, 'onClick', this.mapClickEventListener);
            // }
        },
        onDrawToolbarDrawEnd: function (evt) {
            this.drawToolbar.deactivate();
            this.drawModeTextNode.innerText = this.i18n.labels.currentDrawModeNone;
            var graphic;
            switch (evt.geometry.type) {
                case 'point':
				
				    if (textFlag == true) {
						
                        var textSymbol = dojo.byId("addmaptext").value;
                        graphic = new Graphic(evt.geometry,
                            new esri.symbol.TextSymbol(textSymbol).setColor(
                            new dojo.Color([0, 191, 255])).setAlign(esri.symbol.TextSymbol.ALIGN_START).setAngle(0).setFont(
                            new esri.symbol.Font("16pt").setWeight(esri.symbol.Font.WEIGHT_BOLD))
                            )
                    }
                    else {
				     graphic = new Graphic(evt.geometry);
					}
                    this.pointGraphics.add(graphic);
                    break;
                case 'polyline':
                    graphic = new Graphic(evt.geometry);
                    this.polylineGraphics.add(graphic);
                    break;
                case 'polygon':
                    graphic = new Graphic(evt.geometry, null, {
                        ren: 1
                    });
                    this.polygonGraphics.add(graphic);
                    break;
                default:
            }
            this.connectMapClick();
        },
        clearGraphics: function () {
            this.endDrawing();
            this.connectMapClick();
            this.drawModeTextNode.innerText = 'None';
        },
        stopDrawing: function () {
            this.drawToolbar.deactivate();
            this.drawModeTextNode.innerText = 'None';
            this.connectMapClick();
        },
        endDrawing: function () {
            this.pointGraphics.clear();
            this.polylineGraphics.clear();
            this.polygonGraphics.clear();
            this.drawToolbar.deactivate();
            this.disableStopButtons();
        },
        disableStopButtons: function () {
            this.stopDrawingButton.set( 'disabled', true );
            this.eraseDrawingButton.set( 'disabled', !this.noGraphics() );
        },
        enableStopButtons: function () {
            this.stopDrawingButton.set( 'disabled', false );
            this.eraseDrawingButton.set( 'disabled', !this.noGraphics() );
        },
        noGraphics: function () {

            if ( this.pointGraphics.graphics.length > 0 ) {
                return true;
            } else if ( this.polylineGraphics.graphics.length > 0 ) {
                return true;
            } else if ( this.polygonGraphics.graphics.length > 0 ) {
                return true;
            } else {
                return false;
            }
            return false;

        },
        onLayoutChange: function (open) {
            // end drawing on close of title pane
            if (!open) {
                //this.endDrawing();
                if (this.mapClickMode === 'draw') {
                    topic.publish('mapClickMode/setDefault');
                }
            }
        },
        setMapClickMode: function (mode) {
            this.mapClickMode = mode;
        }
    });
});

Add this to draw.html.
						<li>
						  <input type="text" name="addmaptext" placeholder="Enter Text" data-dojo-type="dijit.form.TextBox"
                            data-dojo-props="trim:true, propercase:true" id="addmaptext" />
                        <button data-dojo-type="dijit/form/Button" data-dojo-props="iconClass:'fa fa-history fa-fw',showLabel:true"
                        data-dojo-attach-event="onClick:drawText">
                           Text
                        </button>
						</li>

**Comment by tmcgee** [comment]
The Advanced Drawing tool being worked on by @btfou and @jebu75 will have the ability to add text to the drawings plus a lot more.

**Comment by billchappell** [comment]
Please note it does open a pop ID template..  just enter the text , click on the text button and then the map.
![text](https://cloud.githubusercontent.com/assets/10744341/5942092/48f5f542-a6e3-11e4-8fca-8d7ceded9b96.jpg)

**Comment by billchappell** [comment]
My Draw.html change at the bottom of the file. It got clipped in my first post.	

					<li>
						  <input type="text" name="addmaptext" placeholder="Enter Text" data-dojo-type="dijit.form.TextBox"
                            data-dojo-props="trim:true, propercase:true" id="addmaptext" />
                        <button data-dojo-type="dijit/form/Button" data-dojo-props="iconClass:'fa fa-history fa-fw',showLabel:true"
                        data-dojo-attach-event="onClick:drawText">
                           Text
                        </button>
						</li>

						</ul>

**Comment by jebu75** [comment]
Unfortunately not much progress has been made on advanced draw lately.  I do plan on getting back to this as it’s definitely needed in a couple of my applications.  Look for some progress soon!

**Comment by billchappell** [comment]
Yea, I already figured it out, I was offering up my code but was told your working on a newer one. If you want my code for the draw tool with Text on http://maps.allentownpa.gov/viewerv2/ I could send it. I have an issue with the ID popup but this is 99% there. 

The new version of the CMV-app is great. I have the first version up and my co-workers were asking for more functionality and when I found the newer version it had everything they were looking for. 

I'm currently working on a tool that will take a selected parcel polygon, buffer it out a selected distance, and then use the buffer to generate a parcel mailing list, hopefully it will be done in the next month.

Thanks,

Bill

Date: Wed, 28 Jan 2015 13:40:11 -0800

**Comment by jebu75** [comment]
Thank you!  @btfou has basic text creation and editing in working and we are working on the ability to update the text styles.  We also want to add the ability for other developers to extend the widget’s functionality by creating their own plugins.  

I do think there may be cases however where the current widget being somewhat similar may still be a better fit.  With that in mind you can always create a PR with your code to add basic text functionality to the current draw widget.

Cheers!

Jade

**Comment by GilbertLasnier** [comment]
Great Bill , I try that this after noon, its  exactly what I need to complete the super cmv template, by the way that forum has the best answer communication and users I never see since 1994 the day I start working with ESRI nice things arrive...Many thanks again of all of you...I put an other new issue today about the sharing the map to social network...to do the sharing of conflict zones risk information

**Comment by GilbertLasnier** [comment]
Hello Bill thanks for your anwser...
 I follow all your directive.. I think I am ok with the file draw .js... I miss something with your draw.html
So I send you part of mine that doesnt work, if you are able to correct that file below I will be happy to put your work in the ICAO cmv viewer...thanks again to share your code...


<td>
                        <button data-dojo-type="dijit/form/Button" data-dojo-props="iconClass:'polyIcon',showLabel:true"
                        data-dojo-attach-event="onClick:drawPolygon">
                            Polygon
                        </button>
                        <button data-dojo-type="dijit/form/Button" data-dojo-props="iconClass:'freehandDrawIcon',showLabel:true"
                        data-dojo-attach-event="onClick:drawFreehandPolygon">
                            Freehand Polygon
                        </button>
						
						<button data-dojo-type="dijit/form/Button" data-dojo-props="trim:true, propercase:true" id="addmaptext" 
                        data-dojo-attach-event="onClick:drawText">
                            Text

                        </button>
						<li>
						<input type="text" name="addmaptext" placeholder="Enter Text" data-dojo-type="dijit.form.TextBox"
                        data-dojo-props="trim:true, propercase:true" id="addmaptext" />
						<button data-dojo-type="dijit/form/Button" data-dojo-props="iconClass:'fa fa-history fa-fw',showLabel:true"
						data-dojo-attach-event="onClick:drawText">
						Text
						</button>
						</li>

                   
                    </td>

**Comment by billchappell** [comment]
Sorry for the delay, please see the attached zip, it has my draw JS and HTML files, copy into the \cmv-app-1.3.2\viewer\js\gis\dijit folder and it should work. 

 Bill
bill.chappell@allentownpa.gov
bill@gistechsolutions.com
Date: Tue, 31 Mar 2015 08:36:57 -0700

**Comment by GilbertLasnier** [comment]
Sorry again where is the attached zip??? Thanks for your answer…

**Comment by billchappell** [comment]
It was in my copy. Please send your regular e-mail address to my Allentown address thx

Sent from my Windows Phone
________________________________

**Comment by GilbertLasnier** [comment]
glasnier@icao.int<mailto:glasnier@icao.int>    the same address then the open site github, you have all my emails

**Comment by DavidSpriggs** [comment]
Just a reminder that these types of questions are better to post here: 
https://gis.stackexchange.com/questions/tagged/configurable-map-viewer

**Comment by JhopStl** [comment]
Thanks Bill. How did you go about disabling the identify when adding the text to your map on top of features? As of right now, I can place the text, but after I do so, I'm forced to identify the feature underneath (i.e. parcels).

Thanks,

Jesse

**Comment by billchappell** [comment]
I'll have to find my code example, it's been a while since I worked on that. I have 2 examples on-line and I fixed it in one but not the other. 

Date: Wed, 10 Feb 2016 15:13:35 -0800

**Comment by billchappell** [comment]
Please check your file, This is the on-line file that was changed to stop identify on text..   Compare your draw.js to this one for the changes..
Bill



http://maps.allentownpa.gov/viewer/js/gis/dijit/draw.js

  drawFreehandPolygon: function () {
            this.disconnectMapClick();
            this.drawToolbar.activate(Draw.FREEHAND_POLYGON);
            this.drawModeTextNode.innerText = this.i18n.labels.freehandPolygon;
        },
        disconnectMapClick: function () {
            topic.publish('mapClickMode/setCurrent', 'draw');
            this.enableStopButtons();
            // dojo.disconnect(this.mapClickEventHandle);
            // this.mapClickEventHandle = null;
        },
		
		drawText: function () {
            textFlag = true;
			this.disconnectMapClick();
            this.drawToolbar.activate(Draw.POINT);
        },
	
		
        connectMapClick: function () {
            topic.publish('mapClickMode/setDefault');
            this.disableStopButtons();
            // if (this.mapClickEventHandle === null) {
            //     this.mapClickEventHandle = dojo.connect(this.map, 'onClick', this.mapClickEventListener);
            // }
        },



Date: Wed, 10 Feb 2016 15:13:35 -0800

**Comment by JhopStl** [comment]
Thanks Bill, got it.
