### ISSUE TITLE
Passing parameters to the viewer.js config file

### ISSUE THREAD

**Issue by msereda** [cmv/cmv-app#363]
This feels like it should be blindingly obvious, but I cannot figure it out.  I have a few parameters external to the application that I need to feed into the viewer.js file so that the viewer.js can use those parameters when assigning some of its own values.  Is there an easy way to accomplish this in the cmv?

Something like:

```javascript
require(['viewer/Controller', file], function(Controller, config){
    config.testVar = 'testing';
    Controller.startup(config);
});
```

**Comment by tmcgee** [comment]
A couple of ways to go about this. Are these "external parameters" JavaScript parameters that you have in an external class/script or are they external to the entire app as part of perhaps the app's url query string?

**Comment by msereda** [comment]
The parameters will be requested via a web service call.  I would be placing the web service call within the main html page (essentially index.html, but a cshtml in my case).  That main page is what calls the 'startup' of the Controller, so I'd need the config to be ready at that point.

**Comment by tmcgee** [comment]
Would something like this work for you?

``` javascript
var appConfig = {
    param1: 'a',
    param2: 'b'
}
require(['viewer/Controller', file], function(Controller, config){
    var newConfig = lang.mixin(config, appConfig);
    Controller.startup(newConfig);
});
```

**Comment by msereda** [comment]
I had thought about mixin, but I'm not sure how to overcome the issue I mentioned around having the parameters used to control other parameters.  Here's an example of what I mean using the mixin you provided:

```javascript
		operationalLayers: [
		{
			type: 'dynamic',
			url: 'http://myserver/' + param1 + '/MapServer',
			title: param1,
			options: {
				id: param1,
				visible: false
			}
		}
```

^ I need my parameter to be usable in the above context, but I'd get a 'param1 is not defined' error if I try to mixin.

**Comment by tr3vorm** [comment]
Is this related to the discussion in #238? I also have CMV embedded in an MVC application, and use a web API call when setting layer definitions, during the creation of `ImageParameters`. I originally just had global variables declared in index.html (changed to cshtml).

**Comment by msereda** [comment]
@tr3vorm It is somewhat related, in that I'm using MVC.  Could I get a rough idea of what/where you're doing with regards to your second sentence?  Where are you making the web api call from?

**Comment by tr3vorm** [comment]
@msereda I have index.html as a razor View (index.cshtml) in my views folder, and the rest of CMV in its own folder (say `/CMV`) in my application. In `/CMV/js/config/viewer.js` I have the following function (stripped down) to set my layer definitions, as a way of filtering layers by `projectId`.
```javascript
    function buildImageParameters() {
        var ip = new ImageParameters();
        var key = 'layerDefinitions';

        request({
            url: '/Map/GetCurrentProject',
            handleAs: 'json'
        }).then(
            function (project) {
                this.projectId = project.id || 0;

                for (var i = 0; i < 10; i++) {
                    ip[key].push('ProjectId  = ' + this.projectId);
                }
            }
        );
        return ip;
    };
```

**Comment by msereda** [comment]
Thanks for the example @tr3vorm, I'll be going in a slightly different direction, but you definitely got me thinking in the right mindset.

**Comment by tr3vorm** [comment]
I'd be interested to hear about your approach @msereda - I am sure there must be a better way than my approach, but once I got something working, I never explored further. Anyway, glad I could help out.

**Comment by tr3vorm** [comment]
@msereda did you make any progress getting the object into the `operationalLayers`? The problem with my approach was that the layer was getting defined before my `layerDefinitions` due to my asynchronous call to my web API.

**Comment by msereda** [comment]
@tr3vorm The main thing I needed as far as objects go were the server names for the URLs, as the servers change in each environment and I wanted to pull them from the web.config for several reasons, including the ability for web.config transforms.

So I ended up just using paths as my operational layer URLs, ie '/arcgis/rest/services/Folder/ServiceName/MapServer'.  Then before calling Controller.startup from my cshtml, I create variables for my servers, like the following:

```c#
		var serverUrlPrefixes = {
			baseNetUrl: '@ConfigurationManager.AppSettings[Constants.AppSettings.BaseNetUrl]',
			baseArcGISUrl: '@ConfigurationManager.AppSettings[Constants.AppSettings.BaseArcGISUrl]',
			baseOtherUrl: '@ConfigurationManager.AppSettings[Constants.AppSettings.BaseOtherUrl]'
		};
```
and then I pass that object to the controller and wherever I use a URL in my controller, I prefix it with the appropriate item from the object above.  Is there a better way to do all this?  Probably, but I had very little interest in having to call a web method to get the information, so I went w/ this.

Hope that helps.

**Comment by tr3vorm** [comment]
@msereda This works well except that the only downside (in my case) was security, as the parameters were visible in source and I needed a secure call back to my app.

**Comment by msereda** [comment]
@tr3vorm I'm not sure I understand what you're trying to do very well, but couldn't you do what I did, except instead of making the prefixes object, do your server call logic there then wait for the server call to complete before starting up the controller?

**Comment by tr3vorm** [comment]
Yes, that was my intention. I have tried that but got a scoping error - I will persevere! Thanks for the update.

**Comment by Grjalalifar** [comment]
@msereda  @tmcgee  @tr3vorm 
Hello 
i'm trying to send my URLs and service names to config/viewer.js but i couldnt understandthe solution, would you please explain more about or more sample code about it?
thanks!
