### ISSUE TITLE
Do you think its possible to incorporate the Share this map function for the cmv?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#366]
I put an other new issue today about the sharing the map to social network...to do the sharing of conflict zones risk information around the world with the super template cmv like the picture from the app on arcgis.com create app...
![share](https://cloud.githubusercontent.com/assets/6784515/5959571/57727554-a79d-11e4-84c0-4c6de542dd62.jpg)

**Comment by TPLsmitty** [comment]
Gilbert,

There is an App-Settings widget available in the User contributed widgets section  https://github.com/cmv/cmv-contrib-widgets

https://github.com/roemhildtg/CMV_Widgets/tree/master/AppSettings_Widget

This is not exactly like the widget from Web app builder, but it is close.  You could take this and customize it for you needs.

**Comment by tmcgee** [comment]
@GilbertLasnier and @TPLsmitty There are many variations of this.  

@LarryStout wrote a sharing widget using e-mail for an older version of cmv. I have his code hosted in [this repo](https://github.com/tmcgee/cmv-hamilton-county). Larry graciously provided those widgets as a starting point for anyone in the cmv community to upgrade and use. There's a link at the repo to his site using those widgets.

![screenshot from 2015-01-29 16 35 42](https://cloud.githubusercontent.com/assets/200780/5969208/a09becf0-a7d5-11e4-9a7e-93b2bf0e2991.png)

Another one that hits the major social networks and could easily be turned into a cmv widget is found in this [ESRI Public Information Map template](https://github.com/Esri/public-information-map-template-js)

![screenshot from 2015-01-29 16 39 20](https://cloud.githubusercontent.com/assets/200780/5969268/67768452-a7d6-11e4-9e8d-e26ece302789.png)

If anyone converts one of these or creates your own for CMV, please share it back to the community. Need help along the way? Just ask!

**Comment by GilbertLasnier** [comment]
Very cool Tim I try your sugestion, share back to the community tell me where?,

Envoyé de mon iPad

Le 2015-01-29 à 19:50, Tim McGee <notifications@github.com<mailto:notifications@github.com>> a écrit :


@GilbertLasnier<https://github.com/GilbertLasnier> and @TPLsmitty<https://github.com/TPLsmitty> There are many variations of this.

@LarryStout<https://github.com/LarryStout> wrote a sharing widget using e-mail for an older version of cmv. I have his code hosted in this repo<https://github.com/tmcgee/cmv-hamilton-county>. Larry graciously provided those widgets as a starting point for anyone in the cmv community to upgrade and use. There's a link at the repo to his site using those widgets.

[screenshot from 2015-01-29 16 35 42]<https://cloud.githubusercontent.com/assets/200780/5969208/a09becf0-a7d5-11e4-9a7e-93b2bf0e2991.png>

Another one that hits the major social networks and could easily be turned into a cmv widget is found in this ESRI Public Information Map template<https://github.com/Esri/public-information-map-template-js>

[screenshot from 2015-01-29 16 39 20]<https://cloud.githubusercontent.com/assets/200780/5969268/67768452-a7d6-11e4-9e8d-e26ece302789.png>

If anyone converts one of these or creates your own for CMV, please share it back to the community. Need help along the way? Just ask!

**Comment by tmcgee** [comment]
@GilbertLasnier 

There's a brief explanation on contributing widgets at the [CMV Contributed Widgets repository](https://github.com/cmv/cmv-contrib-widgets#contributing). There's also an [entry on building custom widgets](https://github.com/cmv/cmv-app/wiki/building-custom-widgets) in the Wiki that provides some additional details.

Hopefully that's enough to get you started. We are working on additional documentation as well.

**Comment by GilbertLasnier** [comment]
Many thanks to you have good night!!

Envoyé de mon iPad

Le 2015-01-30 à 22:13, Tim McGee <notifications@github.com<mailto:notifications@github.com>> a écrit :


@GilbertLasnier<https://github.com/GilbertLasnier>

There's a brief explanation on contributing widgets at the CMV Contributed Widgets repository<https://github.com/cmv/cmv-contrib-widgets#contributing>. There's also an entry on building custom widgets<https://github.com/cmv/cmv-app/wiki/building-custom-widgets> in the Wiki that provides some additional details.

Hopefully that's enough to get you started. We are working on additional documentation as well.

**Comment by tmcgee** [comment]
@GilbertLasnier Did you ever get "share this map" functionality for your cmv apps?

**Comment by tmcgee** [comment]
@GilbertLasnier 
I have adapted [this Share widget for WAB](https://github.com/USEPA/Public_Web_AppBuilder/tree/master/widgets/Share) for use with CMV. You can find it in my [widget repo](https://github.com/tmcgee/cmv-widgets#share)

![share1](https://cloud.githubusercontent.com/assets/200780/10008554/c29425da-6084-11e5-8e3a-7d4fb39842a3.jpg)

**Comment by GilbertLasnier** [comment]
Perfect its exactly What I am looking for many thanks for your great work Tim, I try to incorporate in my viewer…

**Comment by GilbertLasnier** [comment]
i try to incorporate in my viewer but the structure of my folder is not the same then you...i have js gis digit and you you have widgets...

**Comment by tmcgee** [comment]
@GilbertLasnier I replied to your issue in my widget repo. That is where further correspondence about this new widget should take place. Closing this issue.

**Comment by GilbertLasnier** [comment]
I PUT THE MINE TYPE LIKE YOU TELL ME …its work many thanks to you for your great work
[cid:image001.png@01D0F615.66C113A0]
