### ISSUE TITLE
Initial set of layers for Identify Tool are not correct

### ISSUE THREAD

**Issue by msereda** [cmv/cmv-app#367]
Has anyone run into any issues with the identify dropdown showing layers that shouldn't be available for identify (ie non-visible layers)?

Here's my initial structure from the LayerControl:

![layercontrol](https://cloud.githubusercontent.com/assets/5561775/5960356/6474798a-a79a-11e4-81bb-bb60a33f94d9.png)

^ The layer in red shows up in the identify dropdown, and is available to be identified on at startup.  It is not visible on the map itself , but if I console.log the current visible layers the layer in question is showing as visible.

That being said, if I make a change to the LayerControl by flipping _any_ layer on/off, the LayerControl appears to set _all_ layers to how they should be, and the Identify tool works fine at that point.  I can see some comments in the LayerControl code referencing "ags doesn't respect a layer group's visibility", but the code there seems fairly specific to the LayerControl so I'm not sure how I'd make that work for Identify.

Anyone else run into this issue?  Kinda feels like an API bug, but I'm hoping someone's worked around it for Identify.

**Comment by GilbertLasnier** [comment]
You are right when you are under a group the identify doesnot work for me also.... I remake all my services without the sub group

**Comment by tmcgee** [comment]
@msereda what does the JSON config in viewer.ls for this dynamic layer look like? Are you including ImageParameters?

**Comment by msereda** [comment]
@tmcgee I took a copy of the untouched CMV from here and just added in the service - is this what you're looking for ?

```javascript
		{
			type: 'dynamic',
			url: 'http://server-name/arcgis/rest/services/service-dir/service-name/MapServer',
			title: 'My Title',
			slider: true,
			noLegend: false,
			collapsed: false,
			sublayerToggle: true,
			options: {
				id: 'MyID',
				visible: true,
				imageParameters: imageParameters
			},
			layerControlLayerInfos: {
				expanded: true
			}
		}
```

**Comment by GilbertLasnier** [comment]
I think you are right again we don’t have the variable slider true it’s for that Its does not work , you are great

**Comment by tmcgee** [comment]
@msereda ok. then it is what I thought it might be. I've seen something similar when you include "layerOptions" like show/hide/exclude for the operational layer. The Layer Control then shows a similar inconsistency. I don't think it is an issue with the Identify widget since if I recall correctly, it just reads the `visibleLayers` array to determine which layers the API says are visible. I believe the Layer Control widget is doing the same thing with `visibleLayers`. I'll do some digging around. @btfou: Do you think this might be the same thing I've noted previously with the Layer Control?

**Comment by JurupaCommunity** [comment]
Is there solution to this issue? I have this issue as well. Please help.

**Comment by tmcgee** [comment]
@btfou Any thoughts on this?

**Comment by tmcgee** [comment]
@btfou ping

**Comment by roemhildtg** [comment]
Should be closed in https://github.com/cmv/cmv-app/pull/604
