### ISSUE TITLE
Layer definitions not loaded in time to render associated layer

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#369]
I have a dynamic layer defined as follows with the `buildImageParameters()` function called to dynamically filter the service data using layer definitions. My function has an asynchronous `esri.request()` call to a web API to determine which data to show based on the current user. The problem I have is that the layer is sometimes getting loaded before the layer definitions are created.

Is there a way to make the `operationalLayers` wait until after I have got the layerDefinitions loaded? 

```javascript
            type: 'dynamic',
            url: 'https://servername/adaptor/rest/services/myservice/MapServer',
            title: 'my layer',
            collapsed: false,
            options: {
                id: 'mine',
                opacity: 1.0,
                visible: true,
                imageParameters: buildImageParameters()
            }

**Comment by tmcgee** [comment]
@tr3vorm where is the esri.request()? Seems you'd want wait and startup the entire cmv app only after the request is completed.

**Comment by tr3vorm** [comment]
Hi @tmcgee In viewer.config - ok, I think I see what you are saying, but not sure where to put it now. In index.html, wrapping Controller.startup?

**Comment by tmcgee** [comment]
@tr3vorm This is related to what @msereda was asking in #363. I suggested that the code could be placed in index.html around [here](https://github.com/cmv/cmv-app/blob/master/viewer/index.html#L65). See my response to him there. In your comment, you said that you are setting global variables. Assuming I am visualizing things correctly, you can make the request there in index.html (or your dotNet equivalent), and then when it is completed, set the global vars and startup the Controller. Would that work for you?

**Comment by tr3vorm** [comment]
Ah yes, thank you @tmcgee - I missed that first time round.
