### ISSUE TITLE
Timeslider

### ISSUE THREAD

**Issue by stillwolly2013** [cmv/cmv-app#370]
is there a way we can  add a timeslider for time aware layers

**Comment by tmcgee** [comment]
I think you are referring to something like [this example](https://developers.arcgis.com/javascript/jssamples/time_sliderwithdynamiclayer.html)

The code in the `initSlider` function in that example does most of the work and could relatively easily be made into a `domNode` type custom CMV widget. The [geocoder widget](https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/Geocoder.js) is a good place to start to learn about domNode widgets. You need a [domNode to attach to](https://github.com/cmv/cmv-app/blob/master/viewer/index.html#L29) and then set the [widget type to `domNode`](https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L130)

**Comment by tmcgee** [comment]
If you do create a custom widget for this, please [contribute](https://github.com/cmv/cmv-contrib-widgets) it back to the cmv community.

**Comment by stillwolly2013** [comment]
Thanks @tmcgee  i will give it a shot and if i succeed i will contribute

**Comment by roemhildtg** [comment]
I was feeling ambitious today, so I played around with it a bit in [my contrib repo.](https://github.com/roemhildtg/CMV_Widgets#timeslider) Testers needed...

**Comment by tmcgee** [comment]
Nice!

**Comment by jtorresleon** [comment]
Let´s shout a VIVA! to roemhildtg. Nice work thanks a lot!, keep it up!
