### ISSUE TITLE
Create a buffer around a polygon with cmv (geoprocessing) tool?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#373]
I must create a buffer zone around the conflictzones , i make that manually, in the best world we enter the distance in km and we obtain the buffer wher the plane must dont go because the missile is in the border of the country or the fir, so the zone must be bigger, all that because the mh17 flight..

**Comment by tmcgee** [comment]
@GilbertLasnier Does the buffer just need to be displayed on the map (and then possbily printed/exported as graphic) or do you want to do something additional like query features within that buffer?

**Comment by GilbertLasnier** [comment]
Sorry TIM for the delay of my anwser in the best world its will be a window where the user must enter the value in Nautical Mile  to create the buffer, I make something like that with a geoprocessing but its just draw in the best world its will be a shape file around the polygon if you go to my http://gis.icao.int/appsilver/ conflictzones  you have a button to do a buffer like i want but its a draw so when you exit the browser its gone...so its bad because the buffer zone is very important its the range of the missile that the people must respect, dont go there its also very dangerous...
THanks for your help.
