### ISSUE TITLE
How to confirm before closing floating type dijit?

### ISSUE THREAD

**Issue by jerrygarciame123** [cmv/cmv-app#374]
I need to confirm with the user before they close a floating panel dijit.  I'd like to as if they really want to close before saving changes...  Thanks!

The "x" button appears to be:

titlebar--->
<span data-dojo-attach-point="closeButtonNode" class="dijitDialogCloseIcon" data-dojo-attach-event="ondijitclick: onCancel" title="Cancel" role="button" tabindex="1">
  <span data-dojo-attach-point="closeText" class="closeText" text="Cancel">x</span>
</div>

**Comment by tmcgee** [comment]
My approach to this would be to hide the `X` (css or JS, I prefer css) and then add a `Cancel` button within the dialog with the desired "Unsaved Changes! Are you sure you want to cancel?" confirmation.

**Comment by tmcgee** [comment]
Oh, you also need to handle the ESCAPE key which can close the dialog. So you probably want to listen for the 'cancel' event (possibly need to override the `onCancel` method, not sure?) and handle the confirmation there.
