### ISSUE TITLE
Find Widget Issue when Searching esriFieldTypeDouble

### ISSUE THREAD

**Issue by kjmueller** [cmv/cmv-app#375]
When searching Double fields I've noticed that I have to enter the entire number otherwise no result is returned.  Is there a modification I can make to see results returned when I don't enter an exact match?  Or do I have to change the field types to string?

Thanks for any help!

**Comment by btfou** [comment]
@kjmueller Such is the case with integers and doubles. I've created a 2nd string field before just for find task. Another approach I've seen is a having a concat string field with all values you what to find or query.

**Comment by kjmueller** [comment]
Thanks for the prompt response!
