### ISSUE TITLE
How to add widget to the bottom pane?

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#376]
Hello,
I was wondering if where is a guide how to add widget to bottom pane?

Thank you,

**Comment by tmcgee** [comment]
**Basic guide for placing widgets in panes**

* First add a bottom pane. Something like this near the top of your `viewer.js`:

``` javascript
panes: {
    left: {
        id: 'sidebarLeft',
        placeAt: 'outer',
        collapsible: true,
        region: 'left'
    },
    bottom: {
        id: 'sidebarBottom',
        placeAt: 'outer',
        splitter: true,
        collapsible: true,
        region: 'bottom'
    }
},
```

* Then place your widget there by using `placeAt` in the widget options:

```javascript
widget: {
    ...
    type: 'contentPane',
    placeAt: 'bottom'
}
```

* That will work for widgets of type `titlePane` and `contentPane`. If you want to use a type of `domNode` you need some content in your pane to attach to:

```javascript
content: '<div id="myWidgetContainer"></div>'
```

* Then include the reference to that domNode in the widget options: 

```javascript
widget: {
    ...
    type: 'domNode',
    srcNodeRef: 'myWidgetContainer'
}
```

* There are some gotchas when using things like a TabContainer dijit. Here's an earlier discussion about that which also touches on the widget placement in panes: https://github.com/cmv/cmv-app/issues/214

**Comment by goriliukasbuxton** [comment]
thank you it helped,
Actually i am gonna attempt to add:
https://github.com/Esri/elevation-profile-template/tree/master/js/ElevationsProfile
to the bottom as a widget. got struck.
