### ISSUE TITLE
ESRI Web Appbuilder widgets

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#380]
Hello,
I was just wondering if the ESRI Web Appbuilder widgets cant be incorporated into the CMV?
https://github.com/Esri/solutions-webappbuilder-widgets

**Comment by tr3vorm** [comment]
My understanding is that they can be, but there is work to do. I am sure Tim or David will reply. I am looking forward to your Elevation widget.

**Comment by goriliukasbuxton** [comment]
@tr3vorm not sure i can author that since its ESRI product.

**Comment by tmcgee** [comment]
@goriliukasbuxton I have looked at that set of widgets and am certain that they can be converted for use in CMV. Some are more easily converted than others. The main gotchas that I see are the dependencies on the `jimu.BaseWidget` and the WAB Themes.

I have not attempted to do an actual conversion. If anyone has converted some of these widgets or is planning to attempt this, please chime in.

**Comment by LarryStout** [comment]
You may want to experiment with the Print Widget since it is basically the same as the CMV Print Widget that David Spriggs wrote.

Larry

[cid:image001.jpg@01D047A3.96991300]

**Comment by tmcgee** [comment]
The original WAB Print widget was a conversion of Dave's CMV Print widget. Or so a little bird told me... ;)
