### ISSUE TITLE
Error Token at Login

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#383]
I get the "error token" for the secure services before user has a chance to enter credentials.
///////////////////////
js.arcgis.com/3.12compact/init.js:192 Error: Token Requiredcode: 499details: Array[0]httpCode: 499log: undefinedmessage: "Token Required"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: d
///////////////////

**Comment by tmcgee** [comment]
@goriliukasbuxton I believe what you are seeing is the mechanism that the ArcGIS JS API uses to determine if the service is secure. If it gets back that custom ESRI-specific HTTP Response Code of `499`, it knows the service is secure and that User Credentials are required.

**Comment by jebu75** [comment]
I've seen this in my apps as well.  I'm not clear on why the API logs this to the console though.
