### ISSUE TITLE
Exclude layer from legend?

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#384]
Is it currently possible to exclude a layer from the esri/dijit/legend widget in CMV?

**Comment by tmcgee** [comment]
@roemhildtg I'm pretty sure you can do that at present.

You can add `exclude:true` for a layer to exclude it from the identify widget in the `identifyLayerInfos` or from the layerControl widget in the 'layerControlLayerInfos'. Each of those widgets handles it differently but the configuration option is the same.

This same configuration option is not currently implemented for the `editorLayerInfos` or the `legendLayerInfos` but those are definitely good additions.

How all those LayerInfos are being used is under re-consideration for a more flexible approach and less hard-coding in `Controller.js`.

**Comment by roemhildtg** [comment]
Thanks for the response @tmcgee , I wasn't sure if I was just missing something. For consistency it would be nice to have that option with the legend and the editor. I would support a more flexible layerInfos approach too, although it would probably require a few changes for existing apps..
