### ISSUE TITLE
Selecting and labels.

### ISSUE THREAD

**Issue by Inkus** [cmv/cmv-app#386]
Hello,

I need to implement a selection tool to my CMV based application. I've found how to do it at https://developers.arcgis.com/javascript/jssamples/fl_selectfeatures.html.

The problem is that I've got really many layers, feature layers and labels which are Annotation Layers set together in a GroupLayer, so the service structure is something like that:
.../MapServer/
.../MapServer/1     - FeatureLayer
.../MapServer/2     - FeatureLayer

.../MapServer/3     - GroupLayer
.../MapServer/4     - Annotation Layer 
.../MapServer/5     - Annotation SubLayer 
.../MapServer/6     - Annotation Layer 
.../MapServer/7     - Annotation SubLayer 
...
.../MapServer/N     - FeatureLayer
...
If I connect to the service 'root' (/MapServer), all layers are loaded as sublayers and annotation are being loaded as well with all the layerControl widget functionality. I can manage their visibility and other functionalities. But to add my selection tool I need my layers as separated FeatureLayer objects. I can load my FeatureLayers as seperated layers, but I can't do that with my annotation layers. I tried to connect to the group as well as to a single AnnotationLayer, tried with dynamic and label types, but they're not seen on the map. In the layerControl widget at best I can see the grouplayer, but I cannot expand it and the annotation it not on the map. I would like to see those annotation layers in a group in my layerControl widget just like when I load my service as one main layer. Is there a way to avoid it or implement the selection on given layer tool differently?

**Comment by DavidSpriggs** [comment]
@Inkus I suggest posting a question here for this: https://gis.stackexchange.com/questions/tagged/configurable-map-viewer github issues are for reporting bugs not development support. Thanks!
