### ISSUE TITLE
Pass parameter from operationalLayers

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#387]
CMV group,
I was wondering how to pass a optional parameter to the widget from operationalLayers:[] in viewer.js
I would like to include some of the layers in to the widget but not all.

Thank you,

**Comment by tmcgee** [comment]
@goriliukasbuxton Did you work out a solution for this issue? If so, could you possibly share your solution with the group?

**Comment by goriliukasbuxton** [comment]
No i dint . I will if figure this out.
