### ISSUE TITLE
Drag-and-drop CSV files, shapefiles, KML files will be also super Brian????

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#391]
We develop a super VHF software for Frequencies finder and that software create always the kml files, In my dream i want to open directly in the cmv browser like Brian make for the CSV AN shp or something like that, I make that via the flex viewer in the past  http://gis.icao.int/kmlflexviewer31/
I try to pass by a drop box because I want to write on the server to rewrite the KML file on my server but I dont know how to rewrite a file on a server via a Desktop PC, so I try drop box but doesn't work
kkkdropbox layer failed to load: Fault code: 400
Fault info: Internal kml parser error.
Fault details: The entity name must immediately follow the '&' in the entity reference.
All my tentative: I erase all the < and the >
operationallayers
			layer label="fffdropbox" type="kml" visible="true" url="https://www.dropbox.com/sh/mrvrcwvp9hhg7j5/AACQa1_IG5QxKOIAu3MPh2Uia/mergedfff.kml?dl=1" /
			layer label="kkkdropbox" type="kml" visible="true" url="https://www.dropbox.com/sh/mrvrcwvp9hhg7j5/AACQa1_IG5QxKOIAu3MPh2Uia/mergedkkk.kml?dl=1" /
			layer label="baddropbox" type="kml" visible="true" url="https://dl.dropboxusercontent.com/u/27123852/mergekkk.kml" /
			layer label="gildropbox" type="kml" visible="true" url="https://dl.dropboxusercontent.com/u/95608235/mergeddd.kml" /
			layer label="Robert Frequency" type="kml" visible="true" url="http://gis.icao.int/GEOPDF/FIR2013.kml" / that one work
			<layer label="Robert Frequency gil" type="kml" visible="true" url="http://gis.icao.int/GEOPDF/merge.kml" / that one work, i just want rewrite on the server or use dirrectly the Drag and Drop of Brian or...any solution
Many thank to all your team...
I incorporate in the ICAO site all function http://gis.icao.int/icaoviewernew/#/

**Comment by DavidSpriggs** [comment]
@GilbertLasnier Pinging @BrianBunker as he controls that widget/repo. Post a request/issue there: https://github.com/BrianBunker/dojo-esri-dnd-widget

**Comment by tmcgee** [comment]
@GilberLasnier to the other part of your question:  Dropbox can work as the "server' for your kml file.  The layer labeled 'gildropbox' is the only one that is shared publically and so should be accessible in your app. The others are not accessible.  My answer assumes this data is supposed to be publicly available without any security.

**Comment by GilbertLasnier** [comment]
Thanks TIM , I continue to try with the gildropbox. I hope i find a way...

**Comment by GilbertLasnier** [comment]
You are wright with the Dropbox i find how to its work but it will be great in the cmv viewer!!!
