### ISSUE TITLE
Where to put the Proxy Config?

### ISSUE THREAD

**Issue by gobsmack** [cmv/cmv-app#400]
I'm wondering where others are putting their proxy rules. I added them to the Controller. I could have added them to the index.html, too. What's the best place?

We use CMV in a multi-tenant environment. That is, one CMV for lots and lots of sites. So, our proxy rules are different for each site. So, I think a great place to store the rules would be in the config. The config could have an array of objects which contain the URL prefix and the proxy URL. Then, the Controller can just spin through that array, adding the proxy rules.

I know @jebu75 expressed some worry that the config is growing too complex, and in #357 said he's doing something with the proxy in config. Using the proxy seems like a pretty standard requirement, and there should be a standard way to handle it.

OK if this idea isn't good for the core. Using the mixin ideas, I can edit my loader to do it without editing the core.

**Comment by tmcgee** [comment]
I do this within the config file for each server/url in the app that requires a proxy. Does this meet your needs?

``` javascript
define([
    'esri/urlUtils',
], function (urlUtils) {

    urlUtils.addProxyRule({
        urlPrefix: 'https://server/arcgis/rest/services/',
        proxyUrl: '../common/proxy/proxy.ashx'
    });

    return {
...
```

If you prefer an array, you could also loop though as you describe. Something like this:
``` javascript
var urls = ['server1','server2'];
array.forEach(urls, function (url) {
    urlUtils.addProxyRule({
        urlPrefix: url,
        proxyUrl: '../common/proxy/proxy.ashx'
    });
});
```

**Comment by gobsmack** [comment]
I'm treating the config file as a straight json file, so I don't include the *define*. I was thinking of something like this, which I adapted from when I tried to use the Web AppBuilder:

    config:{
        httpProxyRules: [{
            urlPrefix: 'server1',
            proxyUrl: '../common/proxy/proxy/proxy.ashx'
        }, {
            urlPrefix: 'tiles1.argis.com',
            proxyUrl: '../common/proxy/proxy/proxy.ashx'
        }, {
            urlPrefix: 'tiles2.argis.com',
            proxyUrl: '../common/proxy/proxy/proxy.ashx'
        }],
        // other config stuff
    }


And then in the _ConfigMixin, or Controller, or whatever:

    array.forEach(config.httpProxyRules., function (aProxyRule) {
        urlUtils.addProxyRule({
            urlPrefix: aProxyRule.urlPrefix,
            proxyUrl: aProxyRule.proxyUrl 
        });
    });

**Comment by tmcgee** [comment]
That seems like a pretty specialized use case. You could do it as you suggested in a Controller mix-in. 

Related to this and your recent PR with a mix-in (or were there 2 PRs?), it would be wonderful to have a way to pass in optional mixins to the controller. dgrid does something like this. I believe that CMV should take a similar approach though I haven't had enough focus time to build a proposed approach.

**Comment by gobsmack** [comment]
I'll look at the dGrid structure for mixins. Seems like a good idea. I'm hesitant to do too much without knowing that it will be relevant to the next CMV.

There were three PR's. One was mixin-related to load the config async. Another was mixin-related to load the map async. The third was for a menu, and that one needs to stew a little more. I should probably un-pull it now.
