### ISSUE TITLE
How to put an arcgis rest Imageserver in the cmv-app?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#403]
I try that... I think its not support in the background ether!!!
},{
			type: 'dynamic',
			url: 'http://apps.esri.ca/ArcGIS/rest/services/EnvironmentCanada/WeatherRADAR/ImageServer',
			title: 'CANADA Radar Image Service',
			options: {
				id: 'CANADAWeather',
				opacity: 0.6,
				visible: false,
				imageParameters: imageParameters
			},
			layerControlLayerInfos: {
				swipe: true,
				metadataUrl: true,
				expanded: true
			}

**Comment by tmcgee** [comment]
@GilbertLasnier layers from an ImageServer is supported. You need to use a layer type of `image`

**Comment by DavidSpriggs** [comment]
Please post these types of questions to:
https://gis.stackexchange.com/questions/tagged/configurable-map-viewer

**Comment by GilbertLasnier** [comment]
Tim ,thanks for you answer, I try layer type of image
