### ISSUE TITLE
Dynamic map service

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#404]
Hello,
I was wondering if it is possible to exclude layers from dynamic map service in the viewer?

Thank you,

**Comment by goriliukasbuxton** [comment]
Found some info on it:
http://gis.stackexchange.com/questions/122704/configurable-map-viewer-cmv-configure-dynamic-layer-to-not-display-all-sub-l/122872#122872

**Comment by TPLsmitty** [comment]
I have found the easiest route to go is the following.

In config\viewer.js
add near the top:
```javascript
    // Allows user to hide layers in Dynamic map service
    function buildImageParameters (config) {
       var ip = new ImageParameters();
       for (var key in config) {
           if (config.hasOwnProperty(key)) {
               ip[key] = config[key];
           }
       }
       return ip;
    }
 ```
 
 then for the operational layer add the following under the options:
```javascript
               imageParameters: buildImageParameters({
                   format: 'png32',
                   layerIds: [0, 1, 2],
                   layerOption:  ImageParameters.LAYER_OPTION_EXCLUDE
                })
```
Note that in this example the layer IDs are for the layers you do not want to show.  If you want, you can just show the layers in the layerIDs by using LAYER_OPTION_SHOW

The last thing that needs to be done is in the css file. For the layers you do not want to show (0,1,2 in the example above) add the following to your css code (I keep a separate css file for site specific changes)
```javascript 
div#DWHAreaS-0-sublayer-control {
    display:none;
}
div#DWHAreaS-1-sublayer-control {
    display:none;
}
div#DWHAreaS-2-sublayer-control {
    display:none;
} 
```

In the example above DWHAreaS is the ID of the operational layer, and the number is the layerID.

**Comment by tmcgee** [comment]
@goriliukasbuxton I answered a similar question on [GSE just yesterday](http://gis.stackexchange.com/questions/143293/cmv-layercontrol-hide-dynamic-sub-layers). I that answer I referenced several issues here in the repo. The circle of CMV life. ;) The answer above is much more complete and self-contained. Thanks @TPLsmitty
