### ISSUE TITLE
How to put in Red the Find in the toc of cmv?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#405]
I want the user use the Find... so i want to change just that color witch css I must change...Do you think its possible???

**Comment by TPLsmitty** [comment]
Gilbert,

You can do this by using your css.  Add the following:

```javascript
    div#find_parent_titleBarNode {
    color:red !important;
}
```
For the color you can add rgb, hex or any css valid color.
Smitty

**Comment by GilbertLasnier** [comment]
Thanks I try that right now…

**Comment by GilbertLasnier** [comment]
Great its work!!!

**Comment by GilbertLasnier** [comment]
David you must close that issue
