### ISSUE TITLE
How you do to have the find open in the initial view?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#406]
Find query at the opening like that picture:
![find](https://cloud.githubusercontent.com/assets/6784515/7282691/a9716312-e8ff-11e4-99fb-6e9a755840fd.jpg)

**Comment by roemhildtg** [comment]
You can set the [widget config](http://docs.cmv.io/en/1.3.3/configure/widgets/) to have the property `open: true` to set the widget open and visible by default.

**Comment by GilbertLasnier** [comment]
placeAt: 'right'    Thanks for your answer I think i must upgrade my version of the cmv because I try placeAt: 'right'  and i don't have that functionality before.... I want the find floating at the start up in the center of the page or at the top or at the right...

**Comment by DavidSpriggs** [comment]
@GilbertLasnier You can only have the widget open using the config. There is no way to undock it, the user must do this. You can have it open on start by setting open:true for the widget.
