### ISSUE TITLE
Passing parameters in URL to open specified widgets

### ISSUE THREAD

**Issue by jtorresleon** [cmv/cmv-app#411]
Hi you all,
I would like to know whether it´s possible to pass parameters via URL in order to open CMV with specified widgets. For example, I would like to show just the search widget, or I would like to open CMV with the left bar (or panel) collapsed or removed. Is it possible?

I know its is possible to do it via config.js file, but I would like to do it at runtime

Is there any guideline showing all parameters I could pass via URL to CMV?

**Comment by roemhildtg** [comment]
I don't think it is currently possible, but I know there is [some discussion](https://github.com/cmv/cmv-app/pull/398) right now about making the config a mixin so that you could override the default behavior and potentially generate configs on the fly.

**Comment by tmcgee** [comment]
@jtorresleon, @roemhildtg is correct that it isn't currently possible and probably not likely to be added to the core CMV. 

In the discussion he pointed you to there is a reference to a [new branch] (https://github.com/cmv/cmv-app/tree/feature/controller-with-mixins-tim)  which has a config mixin as well as mixin for panes and widgets.  That last one is possibly the mixin you would want to override to look at the URL parameters to choose only the widgets you request in the parameters.  Your config would be pretty ugly containing a library of all possible requested widgets/panes and your mixin would need to load only those requested in the parameters.

I don't know your use case but having all possible widgets available in a config would be hard to maintain.  And having them accessible via a url parameter is certainly not very secure as anybody can override the parameters to add the widget of their choosing.  Others like @gobsmack and @tr3vorm have generated configs on the fly via other means (ASP.net + database?)  based on the user's role and granular security. That was  one of the drivers for @gobsmack posting the PR that @roemhildtg  pointed to.  Perhaps one of them can elaborate on how they have done this.

**Comment by jebu75** [comment]
I think if you are just talking about whether or not a widget already configured in the application is open or closed initially (which is how I read @jtorresleon's question), there may be a solution.

Take a look at this answer @tmcgee posted to a question on GIS Stackexchange. 
http://gis.stackexchange.com/questions/142461/pass-an-attribute-to-the-find-widget-using-a-url-string

I think this approach could easily be adapted to allow specifying which widgets are open/closed in your viewer.js config file by reading url paramaters

I haven't tested this but here's some psuedo code that could get you started
```Javascript
//config/viewer.js
//include ioQuery 
define([
    'dojo/io-query'
], function (ioQuery) {


  //somewhere before returning the config
    var getUrlParams = function () {
        var uri = window.location.href;
        var qs = uri.substring(uri.indexOf('?') + 1, uri.length);
        var qsObj = ioQuery.queryToObject(qs);
    
        return qsObj;
    }
    var urlParams = getUrlParams();


  
  return {
    mapOptions : {},
    panes: {},

    //in your widget config section
    widgets: [
        search: {
             id: 'search'
             title: 'Search',
             type: 'titlePane',
            open: urlParams.search || true //or false depending on what you want if not specified
        },
       directions: {
            id: 'directions'
            title: 'Search',
            type: 'titlePane',
            open: urlParams.directions || false//or false depending on what you want if not specified
        }
    ]
  }
}
```

**Comment by tmcgee** [comment]
@jebu75 nice!

If the requirement is to include/exclude a specific widget (which is how I read @jtorresleon's question),  you can use your same approach with a slight modification to determine the `include` property instead of or in addition to the `open` property.

**Comment by jtorresleon** [comment]
Ok noted. Thanbks @jebu75, @tmcgee , @roemhildtg for your help, I will test you pseuco code to see if that works. And yes, the mixin strategy could be very dangerous if not done properly. I dont want to perform a mixin, my approach would be similar to what @jebu75 says

Thanks!

**Comment by jebu75** [comment]
@tmcgee right, and you could also use to open/close panes as well.

**Comment by DavidSpriggs** [comment]
Just to round this out for others that may be reading this later, as it is related to this question, you can specify which config to load by specifying a url param. for example:

http://server.com/cmv?config=app1
or
http://server.com/cmv?config=folder/app2

See the code here:
https://github.com/cmv/cmv-app/blob/master/viewer/index.html#L58-L64
