### ISSUE TITLE
Exclude layers from LayerControl

### ISSUE THREAD

**Issue by thejuskambi** [cmv/cmv-app#412]
Is is possible to exclude some sublayers from the LayerControl. In some case we would need a layer to be available in the map. but, prevent the user from changing the visibilty. This is really useful if we want to kindof hide a layer from the user, but be accessible through programs only.

**Comment by roemhildtg** [comment]
There was some discussion on that awhile back in one of the issues, check this out, I think it'll answer your question: 

Excluding entire layers from the layerControl:
https://github.com/cmv/cmv-app/issues/218

Excluding subLayers:
https://github.com/cmv/cmv-app/issues/404

**Comment by tmcgee** [comment]
this has been addressed in PR #477.
