### ISSUE TITLE
Can't use custom basemap, without it blinks first to show one of those agol basemap.

### ISSUE THREAD

**Issue by marhensa** [cmv/cmv-app#414]
why do we have to set two basemap configurations in different config file?

we can't use custom basemap without it blinks first to show one of those agol basemap.

for example, 
i have custom basemap named "xxx", and i already set in basemap.js to use custom basemap,
and set mapStartBasemap to use xxx

but in viewer.js I cant use that xxx custom basemap, 
it has to be one of those agol basemap (streets, sattellite, etc).

and because of that, 
those agol basemap will flash few seconds, then my xxx custom basemap starts loading.

i can't use agol basemap because it's uninformative and lack of data in my country.
i have to use my own basemap.

any suggestion, and solution about this?

thank you... :)

**Comment by DavidSpriggs** [comment]
This is the best way to do custom basemaps:

http://jsfiddle.net/DavidSpriggs/wcbojd3j/

We will be updating CMV to use this method soon.

**Comment by marhensa** [comment]
thank you for the heads up, have a good day!
:)
