### ISSUE TITLE
Try to import the ESRI time slider to CMV as widget, still in very earlier stage, but need help

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#415]
example url:

http://developers.arcgis.com/javascript/sandbox/sandbox.html?sample=time_sliderwithdynamiclayer

ported to CMV

TimeSlider.js:

define([
    'dojo/_base/declare',
    'dijit/_WidgetBase',
    'dijit/_TemplatedMixin',
    'dijit/_WidgetsInTemplateMixin',
    'dijit/form/Button',
    'dojo/_base/lang',
    'esri/TimeExtent', 
    'esri/dijit/TimeSlider',
    'dojo/_base/array',
    'dojo/dom', 
    'dojo/domReady!',
    'dojo/on',
    'dojo/text!./TimeSlider/templates/TimeSlider.html',
    'dojo/topic',
    'xstyle/css!./TimeSlider/css/TimeSlider.css',
    'dojo/dom-construct'
], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin, Button, lang, TimeExtent, TimeSlider, arrayUtils, dom, ready, on, TimeSliderTemplate, topic, css, domConstruct) {
    return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        map: true,
        widgetsInTemplate: true,
        templateString: TimeSliderTemplate,
        timeSlider: null,
        postCreate: function(){
            this.inherited(arguments);
            this.map.on('layers-add-result', lang.hitch(this, 'initSlider'));
        },

        initSlider: function () {

            var timeSlider = new TimeSlider({
                style: "width: 100%;"
            }, dom.byId("timeSliderDiv"));

            this.map.setTimeSlider(timeSlider);
              
            var timeExtent = new TimeExtent();
            timeExtent.startTime = new Date("1/1/1921 UTC"); //hardcode for now to test
            timeExtent.endTime = new Date("12/31/2009 UTC"); //hardcode for now to test
            timeSlider.setThumbCount(2);
            timeSlider.createTimeStopsByTimeInterval(timeExtent, 2, "esriTimeUnitsYears");
            timeSlider.setThumbIndexes([0,1]);
            timeSlider.setThumbMovingRate(2000);
            timeSlider.startup();
              
            //add labels for every other time stop
            var labels = arrayUtils.map(timeSlider.timeStops, function(timeStop, i) { 
                if ( i % 2 === 0 ) {
                  return timeStop.getUTCFullYear(); 
                } else {
                  return "";
                }
            }); 
              
            timeSlider.setLabels(labels);
              
            timeSlider.on("time-extent-change", function(evt) {
                var startValString = evt.startTime.getUTCFullYear();
                var endValString = evt.endTime.getUTCFullYear();
                dom.byId("daterange").innerHTML = "<i>" + startValString + " and " + endValString  + "<\/i>";
            });
        }

    });
});

but the issue is it wont draw on my top pane

here is the config part

            timeSlider: {
                
                include: true, // false will not load widget
                id: 'timeSlider',
                type: 'contentPane', // can be contentPane
                canFloat: false, // if contentPane, use false
                path: 'widgets/TimeSlider',
                title: '<i class="icon-large icon-find"></i>&nbsp;&nbsp;Time Slider', // title will appear if type: titlePane

                position: 0, // use your position value as needed
                placeAt: 'top', // right or left if type: titlePane, can use top or bottom if type: contentPane
                options: { // map is required to use the widget
                    map: true
                }

            },          

another two helper files:
1. TimeSlider.css
.timeInfo{
        border-radius: 4px;
        border: solid 2px #ccc;
        background-color: #fff;
        display: block;
        padding: 5px;
        position: absolute;
        bottom:40;
        left:40;
        z-index:40;
        text-align: center;
        width: 1000px;
    }

2. TimeSlider.html

<div id="timeInfo">
	<div>Test of Time Slider</div>
	<div id="timeSliderDiv"></div>
</div>

**Comment by DavidSpriggs** [comment]
@ERS-Long I am assuming you want the time slider on top of the map? If so, have a look at the locate button widget, it is a good example of how to do what you want. 

For the widget config you need to use `type: 'domNode'` and `srcNodeRef: 'locateButton'` like this:
https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L194-L196

The `srcNodeRef` needs to be present here:
https://github.com/cmv/cmv-app/blob/master/viewer/js/viewer/templates/mapOverlay.html#L13-L17 
This is where your widget will be rendered.

Then in the widget JS code place the widget inside the widget container like so:
https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/LocateButton.js#L31

Let me know how that goes.

**Comment by ERS-Long** [comment]
Thanks David:

Yes, I managed to use the domnode/srcNodeRef option to put the TimeSlider
on top of the map, it works.

I will play it more to see if i can put the time slider on the top panel
(like the NavTool user widget).

The CMV is such a wonderful js map solution. I learned a lot from this
group and all the sample codes.

Thanks again.

Long

**Comment by ERS-Long** [comment]
Hi, Daivd:

Based on CMV user goriliukasbuxton's code

I got the one version of configurable elevationsProfile widget working in
CMV

Here is the url

https://github.com/ERS-Long/ElevationsProfile

For some reason i cannot add to the user contributed widget table. Please
see if you can add to the list.

Thanks.

Long
