### ISSUE TITLE
Mosaic Dataset Image List

### ISSUE THREAD

**Issue by jmontroyosm** [cmv/cmv-app#417]
I would like to be able to access a mosaic dataset image service and have the available images within it listed in the layers window, below the service label, rather than the Red, Green Blue that is the default. I can't seem to find any image Service parameters that will allow this.

**Comment by DavidSpriggs** [comment]
@jmontroyosm I would post to gis stack exchange as this is a questions on how to implement ImageService functionality. Please post it with the `configurable-map-viewer` tag: https://gis.stackexchange.com/questions/tagged/configurable-map-viewer

Whatever code you come up with would be implemented in the Image controller class of layerControl:
https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/LayerControl/controls/Image.js
