### ISSUE TITLE
Proxy blocks legend call in dynamic map service

### ISSUE THREAD

**Issue by steven3535** [cmv/cmv-app#418]
The legend widget only pulls dynamic map services published directly to the root folder.  If create a folder in manager and publish to it, the legend won't display.

**Comment by jebu75** [comment]
Hmm...we do not publish any of our layers to the root folder and are able to use the legend widget without problems.  Here's an app using several dynamic layers in sub folders:
https://fis.ipf.msu.edu/apps/campusbenchmarks

What types of layers are you using?  Can you share your config?

**Comment by steven3535** [comment]
The first service runs fine but it's pulled from the root directory which is what made me think it was a folder issue.  The second service doesn't load into the legend.  Running server 10.3.1 but was the same at 10.3 and 10.2.2.

operationalLayers: [
{		

				type: 'dynamic',
				url: 'http://igems.doi.gov/arcgis/rest/services/igems_haz/MapServer',
				title: 'Weather Layers',
				options: {
					id: 'weatherLayers',
					opacity: 1.0,
					visible: false,
					imageParameters: imageParameters
				},
				identifyLayerInfos: {
					layerIds: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
				}
			},  

  {

				type: 'dynamic',
				url: 'https://aosgis.aoscloud.net/aosmaps/rest/services/MapAnalytix/Education_MapAnalytix/MapServer',
				title: 'Shawnee County Layers',
				options: {
					id: 'shawneeISDLayers',
					opacity: 1.0,
					visible: true,
					imageParameters: imageParameters
				},
				identifyLayerInfos: {
					layerIds: [0,1,2]
				}
			}
	],

**Comment by jebu75** [comment]
Are you getting any errors in your developer console?  I wondering about the mix of https and http layers and what affect on the XHR calls that might have.  Is your app served over http?

**Comment by steven3535** [comment]
Https only.  I'm not getting any errors that I can see related to http and https.  I have added all http requests to the proxy config.  I can pull in feature services from the same published service just fine and it loads into the legend.  It seems it doesn't like my dynamic services.  I have published them several times in case some went wrong during publishing.  I'll keep tinkering and see if I can find anything else that may be causing the issue.

**Comment by jebu75** [comment]
Okay, that was the only thing I saw but it sounds like it's probably not the issue.

**Comment by steven3535** [comment]
I just published the same service to root directory and it loaded into the legend.  Hmm...

**Comment by jebu75** [comment]
Have you traced the call to the legend endpoint when the service is in a subdir (..MapServer/legend?f=json) in your developer tools?  Is it returning a 200 status code with no data?

**Comment by steven3535** [comment]
The issue is security.  It's not passing a token through to the legend call.  With it unsecured it works as it should.

**Comment by roemhildtg** [comment]
It sounds like you may not be using a proxy. I would recommend configuring a proxy to handle the token authentication for secured services. We are also using secured services and the proxy automatically retrieves a token when necessary and appends it to the requests.

**Comment by steven3535** [comment]
Hmm, we have the proxy folder and our base URLs are in the config.  Are there other URLs that need to be listed?

**Comment by jebu75** [comment]
Strange, but your proxy does append the token to other calls to the same service such as the call to export the map, query etc.?  

We are using the Identify manager so I don't have much experience with having the proxy handle getting the token.

**Comment by steven3535** [comment]
Everything else works except for the legend.  We might just use feature layers because they seem to work right.

**Comment by jebu75** [comment]
Too bad, that feels like sort of like a compromise you shouldn't have to make but maybe someone else more knowledgeable will chime in.   Best of luck!

**Comment by DavidSpriggs** [comment]
@steven3535 Do you have your proxy page configured with a token? If the legend calls are going thought the proxy it will append the token, if you have a token configured. If the legend calls are not being sent through the proxy then try adding a proxy rule in the js to see if that will catch it:
docs: https://developers.arcgis.com/javascript/jsapi/esri.urlutils-amd.html#addproxyrule
example: https://developers.arcgis.com/javascript/jssamples/widget_directions_basic.html
From example link:
```javascript
//all requests to route.arcgis.com will proxy to the proxyUrl defined in this object.
        urlUtils.addProxyRule({
          urlPrefix: "route.arcgis.com",  
          proxyUrl: "/sproxy/"
        });
        urlUtils.addProxyRule({
          urlPrefix: "traffic.arcgis.com",  
          proxyUrl: "/sproxy/"
        });
```

**Comment by steven3535** [comment]
I'm using the proxy that came with the application.  I converted it to an application in IIS in a .Net app pool of 4.0.  I set the base URLs in the proxy.config.  Should I put the entire legend string there instead?  All of our services are loaded over https only.

The strange thing is, the legend shows up fine when I use feature layers.  It's only the dynamic layers that fail to pass the token through.  

In Chrome dev tools, on the network tab, I can see the legend call trying to pass the token.  When I click preview it brings up the rest services login page.  I assume it should bring up the actual legend in the rest services instead.

**Comment by tmcgee** [comment]
@steven3535 you mentioned seeing the legend calls with the token in the Chrome Network tab. If you have the proxy setup as @DavidSpriggs suggested, you would not see any tokens. You would see calls to the proxy url with the legend url passes along as a query string parameter. Hope this help.

**Comment by steven3535** [comment]
Here is the URL.  It does go to the proxy first.  Thanks for everyone's help on this!
>https://myurl/viewer/proxy/proxy.ashx?https://myurl/rest/services/cmv_app/MapServer/legend?token=1OuyGMmn-vNWjnEH-f1WycPkfQPD5igmADVQZCmpbYk.?f=json

**Comment by DavidSpriggs** [comment]
@steven3535 Remove the token from your js code/config. You do not want to see it on the network tab of dev tools. The token should only be in the proxy config, thats it.

**Comment by tmcgee** [comment]
@steven3535 did you get this resolved?

**Comment by steven3535** [comment]
@tmcgee No, I'm kind of stumped.

We use token based authentication.  When we go to an app we are immediately prompted for user name and password (this is identity manager, correct?).  We have the base URLs in the proxy with no other information in the proxy.  The proxy is converted to an application in IIS.  We have alwaysuseproxy set to true.  When set to false, the legend shows just fine.

**Comment by tmcgee** [comment]
@steven3535 did you remove the token from your jscode/config as suggested by @DavidSpriggs? With the security tokens handled by the proxy, you would not see the tokens in the network tab of Chrome's dev tools.

**Comment by steven3535** [comment]
@tmcgee @DavidSpriggs I'm not sure what you mean remove the token.  I never hard coded a token into the application.

**Comment by tmcgee** [comment]
@steven3535 the url you posted on June 16th looks odd with the multiple question marks suggesting that the token is hard coded but perhaps you've the url is just posted here incorrectly. A url like that would definitely fail since the REST service will never see the ?f=json parameter tacked on to the end. If that's not the actual parameters sent to the proxy then please verify the url in the dev tools and post again. Try opening the actual url in a browser and see what is returned. It should be JSON. With the url written above, it would not return the necessary JSON required by the legend widget.

**Comment by steven3535** [comment]
@tmcgee Ya, that's the correct URL that is displayed in the network tab.  When I take the ?f=json off the URL it takes me to the legend (not in JSON).  With ?f=json it takes me to my rest services login page.

We are using Server 10.3.1 but surely that wouldn't cause the issue would it?

**Comment by tmcgee** [comment]
As I said, that is odd.

In order to return the correct JSON, one of the question marks should be an ampersand. Something like this:

https://myurl/viewer/proxy/proxy.ashx?https://myurl/rest/services/cmv_app/MapServer/legend?token=1OuyGMmn-vNWjnEH-f1WycPkfQPD5igmADVQZCmpbYk.&f=json

or like this:

https://myurl/viewer/proxy/proxy.ashx?https://myurl/rest/services/cmv_app/MapServer/legend?f=json&token=1OuyGMmn-vNWjnEH-f1WycPkfQPD5igmADVQZCmpbYk.

The second version with the `?f=json` first and the `&token=...` is how my secured services appear and what I would expect based on my understanding of how the tokens get appended.

I would not expect the version of server to make a difference in this case. The version of the JavaScript API would have more influence. What version of the JavaScript API are you using? Is the API served from the ESRI CDN or is it self-hosted?

**Comment by steven3535** [comment]
Version 3.12compact served through the CDN.

**Comment by tmcgee** [comment]
Since the user is logging in within the app you may not need to use the proxy (at least not for security of that service). Try not using the proxy. 

I am using 3.13. You can try testing with version 3.13 or even 3.14 (released yesterday) to see if it is by chance an api bug that has been addressed.

**Comment by steven3535** [comment]
Ya, I set the alwaysuseproxy to false and the legend comes through.

**Comment by tmcgee** [comment]
Ok. It sounds like you never needed the proxy in the first place. If you do require a proxy for other reasons,  don't use `alwaysUseProxy`. That is rarely if ever a good practice. You can add specific URLs individually to use the proxy for just those specific services/servers. I am on mobile so don't have an example handy. Post again if you need an example.

**Comment by steven3535** [comment]
Thanks for your help, I appreciate it!
