### ISSUE TITLE
Attribute editing via pop-up

### ISSUE THREAD

**Issue by Stefanstrukton** [cmv/cmv-app#422]
I am trying to create editable pop-up, to allow users to edit specified fields via pop-ups when they click on an object. However, I cannot find documentation on how to do this. As example I would like to make several layers within this service editable:

{
			type: 'dynamic',
			url: 'https://gistest.strukton.com/arcgis/rest/services/IRISSYS_Data/MapServer',
			title: 'IRISSYS data',
			slider: true,
			noLegend: false,
			collapsed: false,
			sublayerToggle: false, //true to automatically turn on sublayers
			options: {
				id: 'irissysID',
				opacity: 1.0,
				visible: false,
				imageParameters: imageParameters
				},
			identifyLayerInfos: {
				layerIds: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21]
			},

I assume I need to incorporate the coding, 			

                        editorLayerInfos: {
				disableGeometryUpdate: false
			},

within the previous mentioned part, but I do not know how to define it.

**Comment by DavidSpriggs** [comment]
The first thing you need is a featureService. You can't edit with a dynamic map service, turn on the feature service capability. After you have that running, see here for an example: 
https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L64-L76

**Comment by steven3535** [comment]
I just noticed that the attributes don't show up in editor mode on my phone.  I can edit the geometry just fine.

**Comment by tmcgee** [comment]
Most issues that you find with the editor widget are likely within the ESRI JavasScript API as CMV's widget is just a wrapper around the ESRI widget.
