### ISSUE TITLE
Point of Interest Query in Direction Widget

### ISSUE THREAD

**Issue by marhensa** [cmv/cmv-app#423]
Is it possible to type manually, origin and destination places in direction widget?

I have a lot of point of interest / places, 
and it's correct and valid in term of geometry location.

Is it possible to make that POI / places into search query in direction widget?

Thank you.

**Comment by friendde** [comment]
If you geocode your POI table you should be able to what you are asking. See the help links on how to geocode place name tables.

[ArcGIS v10.0](http://help.arcgis.com/en/arcgisdesktop/10.0/help/index.html#/The_place_name_alias_table/002500000042000000/)

[ArcGIS v10.1](http://resources.arcgis.com/en/help/main/10.1/index.html#//002500000042000000)
