### ISSUE TITLE
esri feature collection

### ISSUE THREAD

**Issue by vxpert** [cmv/cmv-app#425]
Hi CMV gurus,

From the arcgis sample

https://developers.arcgis.com/javascript/jssamples/fl_featureCollection.html

i am able to publish service as esri feature collection from my oracle sdo_geometry data. and displayed it successfully in my dojo design viewer along with dgrid on bottom of map just like CMV dgrid widget with same functionality...

I developed ,my app on this pattern

http://demo.dojotutorial.org/014-mvc-form/

https://github.com/cepa/dojo-tutorial/tree/master/014-mvc-form

How to publish feature collection data with CMV

Regards

**Comment by tmcgee** [comment]
@vxpert Were you able to get this working in cmv? The sample you linked to shows adding a feature layer to the map. I suspect you could do that same thing in a cmv widget.
