### ISSUE TITLE
Search Contributor Widget load error

### ISSUE THREAD

**Issue by AllisonBell99** [cmv/cmv-app#426]
Hi,
I'm trying to incorporate the search, attribute table, and export widgets into my CMV app. I'm getting the following error when I try to search for "Widget uniqName_10, attrTab-attributesContainer":
Microsoft JScript runtime error: uniqName_10: parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation. 
I can get it to work on Chrome sometimes usually with tabs set to false, but it always fails in IE8. Can anyone help me? I'm not sure how to troubleshoot this.
Thanks

**Comment by tmcgee** [comment]
@AllisonBell99 Support for my widgets is handled at my widgets repo https://github.com/tmcgee/cmv-widgets/.  Please post your issue there. Also note that those widgets are completely untested with IE8 and I am very unlikely to make them work with that ancient browser.
