### ISSUE TITLE
Why the service Noaa RIDGERRadar doesn't work in cmv?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#427]
},{
			type: 'dynamic',
			url: 'http://gis.srh.noaa.gov/arcgis/rest/services/RIDGERadar/MapServer',
			title: 'NOAA US Radar Warnings',
			options: {
				id: 'NOAAUSWeather',
				opacity: 0.6,
				visible: false,
				imageParameters: imageParameters
			},
			layerControlLayerInfos: {
				swipe: true,
				metadataUrl: true,
				expanded: false
			}

**Comment by btfou** [comment]
It appears to be an issue with the service. One it's very slow. And two it will show initially but returns "blank" pngs for me on extent change.

**Comment by GilbertLasnier** [comment]
Thanks but if you go direct with 
http://gis.srh.noaa.gov/arcgis/rest/services/RIDGERadar/MapServer?f=jsapi
 everything work???

**Comment by btfou** [comment]
It's also slow and most of the time doesn't return anything on extent change.

**Comment by DavidSpriggs** [comment]
The service seems to be the issue. It works for me but is very slow. Closing due to it being a non CMV issue.
