### ISSUE TITLE
Request Blocked by Privoxy

### ISSUE THREAD

**Issue by kampar** [cmv/cmv-app#429]
I'm using privoxy to surf the net and found that http://js.arcgis.com/3.12compact/esri/dijit/PopupMobile.js was blocked by privoxy because it matches privoxy generic block pattern 

this is privoxy default.action
```
{+block{Path matches generic block pattern.} }
/(.*/)?((flash)?pop|live(cnt|count(er)?)).*\.(js|php|cgi)
```

And this one is also blocked
http://js.arcgis.com/3.12compact/dijit/popup.js

Yes I know that not everyone using privoxy to block ads when surfing, and putting following two lines in privoxy user.action file will white-list arcgis
```
{ -block }
js.arcgis.com/.*\.js$
```

FYI, I live in a country where our ISP injects / put invasive-yet-annoying advertisements on others web page unless it's https / ssl secured.

This is not an issue on cmv, so ... I dont mind if its closed automagically

**Comment by tmcgee** [comment]
duly noted and appreciated. closing not-so-automagically ;)
