### ISSUE TITLE
How to change the blue ICON in the Drag and Drop when you use the CSV files? 

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#431]
Hello, I must change the icon to other symbol like way points smaller that the icon blue, Do you think its possible and where i must change i try many things nothing change?  Also by the simple fact to be able to change the icon on that function, we will be able to drag two list of points and compare between these points, overlap , near bad points etc...
![draganddropsymbol](https://cloud.githubusercontent.com/assets/6784515/8527610/7ee84da6-23db-11e5-8a9d-ec51c2fbe3f5.jpg)
...
Many thanks for your collaboration!

**Comment by tmcgee** [comment]
@GilbertLasnier That is not a CMV core widget so you most likely will not get your question answered here. You should ask the creator of that widget. That like it might be [Brian Bunker's widget](https://github.com/BrianBunker/cmv-widgets/). You should ask your question in his repo.

**Comment by GilbertLasnier** [comment]
Tank you Tim for that precision…
