### ISSUE TITLE
 Is there any sample of cmv In ASP.net MVC?

### ISSUE THREAD

**Issue by Grjalalifar** [cmv/cmv-app#434]
Hello, Im beginner of Asp.net MVC and i want to develop CMV in Asp.net MVC. does anybody have a sample of cmv-app to help me? @tr3vorm  
Thanks!

**Comment by tmcgee** [comment]
There are a number of Asp.net developers that use MVC with CMV. @tr3vorm @gobsmack @roemhildtg come to mind.

I'm not sure if any of them have examples available in github repos. It would be most helpful if one or more examples could be made available to the community.

**Comment by tr3vorm** [comment]
My approach was as follows - I am sure there are better ways, but this works for me. 
 - Copy CMV to your MVC project (say in a folder called `/CMV`)
 - I created a MapModel, which is optional. I just use that to pass information to CMV from my MVC controller. 
 - Create a MapController with a single Action (say Index)
 - Create a razor view "Index" based on the original `index.html` with no layout. I just copied index.html to /Views/Index.cshtml and added the following at the top:-
```
    @model SPT.ViewModels.MapModel
    @{
        ViewBag.Title = "Map";
        Layout = null; 
    }

You will also need to change the 3 pathnames near line 40...
`location: location.pathname.replace(/[^\/]+$/, '') + 'CMV/js/viewer'`

I pass data to CMV in this view from my model, before the Controller is called. E.g. 
```
    var defaultExtent = {
        xmin:@Model.x1,
        ymin:@Model.y1,
        xmax:@Model.x2,
        ymax:@Model.y2
    };

**Comment by gobsmack** [comment]
I think @tr3vorm did a nice job explaining it. Definitely put CMV in it's own /cmv folder to facilitate updating. I followed advice from @tmcgee to create a separate /widgets folder for custom or community widgets.

You could also serve the config from a ConfigController. But frankly, unless your pulling it from a database, there's no point in using an MVC ConfigController.

**Comment by Grjalalifar** [comment]
@tmcgee @tr3vorm @gobsmack  Thanks for your attention. but it doesn't work! dbootstrap and some references dont work when I Try to run my project. would you please upload simple examples in github to be available to the community? Thanks !

**Comment by tmcgee** [comment]
@Grjalalifar you mention references to dbootstrap so it makes me wonder about which version of CMV you are using. There used to be a dependency on dbootstrap as a dojo module. We removed that awhile ago and now it is just a css stylesheet to allow for additiona themee. So ensure you are using the latest version of CMV (that is v 1.3.3 at the moment but not for long...)

**Comment by Grjalalifar** [comment]
@tmcgee  Thanks! I update my version

**Comment by saurabhgis** [comment]
I want to use CMV with ASP.NET, PLS suggest me authentication.

**Comment by tr3vorm** [comment]
@saurabhgis If you follow the approach outlined above, authentication just becomes part of ASP.Net authentication - completely independent of CMV

**Comment by saurabhgis** [comment]
@tr3vorm Thanks for reply..

I am very thankful to you if you can share asp.net sample code. waiting your reply.

**Comment by tr3vorm** [comment]
@saurabhgis You can just add CMV to a web folder and control authentication using ASP.Net, using one of the authentication options: Windows, Forms... Simplest case is just use Windows authentication. This sounds more like an ASP.Net question. 

My replies in this thread (above) were specifically with regard to MVC where I needed to replace the `index.html` with a razor view.
