### ISSUE TITLE
mediaInfos' visibility in config/identify

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#437]
Do you have any suggestions to toggle/render the display of mediaInfos whether or not for example {Location URL} is a valid one?
I tried to define a function like the one below but the value that the function receives is not the value itself, but the string representing the field:

```javascript
mediaInfos : [ {
					title : 'Photo',
					caption : '',
					type : 'image',
					value : {
						sourceURL : urlFoto('{Photo}'),
						linkURL : urlFoto('{Photo}')
					}
				}
```

and the *urlFoto* function is something like this:

```javascript
function urlFoto (value) {
    if (value) { return 'http://someurl/' + value; }
    return '';
}
```

This way, it always enters the first *if* statement.

**Comment by tmcgee** [comment]
Putting the field there with quotes will not work as you've seen. It will use that string when the JSON is first accessed to create the PopUpTemplate, not when the template is used to format the returned identified result data.

The `content` parameter will accept a function or a string value. There's an example in the docs for the [Identify widget](http://docs.cmv.io/en/1.3.4/widgets/Identify/) of how to use that. Perhaps you can do it that way. There might be some additional useful info in this [developer docs tutorial](https://developers.arcgis.com/javascript/jshelp/intro_formatinfowindow.html).

**Comment by carrbrpoa** [comment]
Thanks, I'll try this way tomorrow and post the results.

**Comment by carrbrpoa** [comment]
As I saw, the ```content``` parameter does not combine with the ```fieldInfos``` array which I'm also using. 
I was hoping for a less custom alternative than ```content```, which will force me to code all the ```infoWindow``` layout, but I will do this way if absolutely needed.
