### ISSUE TITLE
Null Values in Attribute Table Date Field 12/31/69

### ISSUE THREAD

**Issue by steven3535** [cmv/cmv-app#440]
Null values in the attribute table date fields display as 12/31/69.  Is there way to show them as blank?

-Steven

**Comment by tmcgee** [comment]
You can check for a null value in your format function or in the get method for your column and return an empty string. (I assume that the format functions you posted in #441 are from the same app)

**Comment by tmcgee** [comment]
Also a public service announcement to the community:

I realize there are many places to request assistance and it can be a challenge to know where to post. Perhaps we have too many places were support is offered! ;)

Let's try to keep the cmv-app repo focused on the core cmv project. Issues about a contributed widget are best answered in that widget's repo. Thanks!

Sorry to hijack @steven3535's thread. We now return you to your local broadcast...
