### ISSUE TITLE
Editor widget documentation

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#442]
There is any documentation about editor widget? http://docs.cmv.io/en/1.3.4/widgets/Editor/ is empty.

**Comment by tmcgee** [comment]
That is correct. No documentation for that widget has yet been created. Since this widget is basically just a wrapper around the ESRI Editor widget, there really aren't many (any?) configuration options specific to this cmv widget. Pull Requests are welcome.

**Comment by tmcgee** [comment]
Oh and as an fyi, issues related to documentation should go in the [cmv-docs](https://github.com/cmv/cmv-docs) repo.
