### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#444]
Currently, while a widget is loading, nothing except a blank stripe appears. That behavior may confuse final users.
Do you guys have some tips about how to do something like the following, that appears only while widget is loading (specific or generic way)?

![cmv_widget_loading_new](https://cloud.githubusercontent.com/assets/10212618/8963191/313d2096-35f5-11e5-87ae-6f167fd02431.png)

PS: consider that the image is an animated gif.

**Comment by gobsmack** [comment]
I wonder if that's something that could be part of the widget model in CMV2? Since the app will publish widget events, it could be possible. But, owing to the complexity with different types of widgets, perhaps it should be incumbent upon the widget developer to include their own loading overlay.

**Comment by roemhildtg** [comment]
We implemented a loader similar to the one on [hard cider](https://github.com/btfou/hardcider) to help deal with the inconsistent loading of the widgets/map layers. It definitely helped improve the user experience, and might be easier to implement, thoughts?

**Comment by carrbrpoa** [comment]
I did some experiments here and create a new base class called *_CMVBase*:

```javascript
define([
	'dojo/_base/declare',
	'dojo/_base/lang',
	'dojo/dom-construct',
	'dojo/topic'
], function (declare, lang, domConstruct, topic) {
	return declare(null, {
		widgetLoading: null,
		
		postCreate: function () {
			this.widgetLoading = domConstruct.create('div', {
                innerHTML: '<img style="display:inline;" src="data:image/gif;base64,R0lGODlhIAAgALMAAP///7Ozs/v7+9bW1uHh4fLy8rq6uoGBgTQ0NAEBARsbG8TExJeXl/39/VRUVAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQFBQAAACwAAAAAIAAgAAAE5xDISSlLrOrNp0pKNRCdFhxVolJLEJQUoSgOpSYT4RowNSsvyW1icA16k8MMMRkCBjskBTFDAZyuAEkqCfxIQ2hgQRFvAQEEIjNxVDW6XNE4YagRjuBCwe60smQUDnd4Rz1ZAQZnFAGDd0hihh12CEE9kjAEVlycXIg7BAsMB6SlnJ87paqbSKiKoqusnbMdmDC2tXQlkUhziYtyWTxIfy6BE8WJt5YEvpJivxNaGmLHT0VnOgGYf0dZXS7APdpB309RnHOG5gDqXGLDaC457D1zZ/V/nmOM82XiHQjYKhKP1oZmADdEAAAh+QQFBQAAACwAAAAAGAAXAAAEchDISasKNeuJFKoHs4mUYlJIkmjIV54Soypsa0wmLSnqoTEtBw52mG0AjhYpBxioEqRNy8V0qFzNw+GGwlJki4lBqx1IBgjMkRIghwjrzcDti2/Gh7D9qN774wQGAYOEfwCChIV/gYmDho+QkZKTR3p7EQAh+QQFBQAAACwBAAAAHQAOAAAEchDISWdANesNHHJZwE2DUSEo5SjKKB2HOKGYFLD1CB/DnEoIlkti2PlyuKGEATMBaAACSyGbEDYD4zN1YIEmh0SCQQgYehNmTNNaKsQJXmBuuEYPi9ECAU/UFnNzeUp9VBQEBoFOLmFxWHNoQw6RWEocEQAh+QQFBQAAACwHAAAAGQARAAAEaRDICdZZNOvNDsvfBhBDdpwZgohBgE3nQaki0AYEjEqOGmqDlkEnAzBUjhrA0CoBYhLVSkm4SaAAWkahCFAWTU0A4RxzFWJnzXFWJJWb9pTihRu5dvghl+/7NQmBggo/fYKHCX8AiAmEEQAh+QQFBQAAACwOAAAAEgAYAAAEZXCwAaq9ODAMDOUAI17McYDhWA3mCYpb1RooXBktmsbt944BU6zCQCBQiwPB4jAihiCK86irTB20qvWp7Xq/FYV4TNWNz4oqWoEIgL0HX/eQSLi69boCikTkE2VVDAp5d1p0CW4RACH5BAUFAAAALA4AAAASAB4AAASAkBgCqr3YBIMXvkEIMsxXhcFFpiZqBaTXisBClibgAnd+ijYGq2I4HAamwXBgNHJ8BEbzgPNNjz7LwpnFDLvgLGJMdnw/5DRCrHaE3xbKm6FQwOt1xDnpwCvcJgcJMgEIeCYOCQlrF4YmBIoJVV2CCXZvCooHbwGRcAiKcmFUJhEAIfkEBQUAAAAsDwABABEAHwAABHsQyAkGoRivELInnOFlBjeM1BCiFBdcbMUtKQdTN0CUJru5NJQrYMh5VIFTTKJcOj2HqJQRhEqvqGuU+uw6AwgEwxkOO55lxIihoDjKY8pBoThPxmpAYi+hKzoeewkTdHkZghMIdCOIhIuHfBMOjxiNLR4KCW1ODAlxSxEAIfkEBQUAAAAsCAAOABgAEgAABGwQyEkrCDgbYvvMoOF5ILaNaIoGKroch9hacD3MFMHUBzMHiBtgwJMBFolDB4GoGGBCACKRcAAUWAmzOWJQExysQsJgWj0KqvKalTiYPhp1LBFTtp10Is6mT5gdVFx1bRN8FTsVCAqDOB9+KhEAIfkEBQUAAAAsAgASAB0ADgAABHgQyEmrBePS4bQdQZBdR5IcHmWEgUFQgWKaKbWwwSIhc4LonsXhBSCsQoOSScGQDJiWwOHQnAxWBIYJNXEoFCiEWDI9jCzESey7GwMM5doEwW4jJoypQQ743u1WcTV0CgFzbhJ5XClfHYd/EwZnHoYVDgiOfHKQNREAIfkEBQUAAAAsAAAPABkAEQAABGeQqUQruDjrW3vaYCZ5X2ie6EkcKaooTAsi7ytnTq046BBsNcTvItz4AotMwKZBIC6H6CVAJaCcT0CUBTgaTg5nTCu9GKiDEMPJg5YBBOpwlnVzLwtqyKnZagZWahoMB2M3GgsHSRsRACH5BAUFAAAALAEACAARABgAAARcMKR0gL34npkUyyCAcAmyhBijkGi2UW02VHFt33iu7yiDIDaD4/erEYGDlu/nuBAOJ9Dvc2EcDgFAYIuaXS3bbOh6MIC5IAP5Eh5fk2exC4tpgwZyiyFgvhEMBBEAIfkEBQUAAAAsAAACAA4AHQAABHMQyAnYoViSlFDGXBJ808Ep5KRwV8qEg+pRCOeoioKMwJK0Ekcu54h9AoghKgXIMZgAApQZcCCu2Ax2O6NUud2pmJcyHA4L0uDM/ljYDCnGfGakJQE5YH0wUBYBAUYfBIFkHwaBgxkDgX5lgXpHAXcpBIsRADs="/>',
                'style': 'text-align:center;'
            }, this.containerNode, 'only');
			
			topic.subscribe('cmv/loaded', lang.hitch(this, 'loadingFinished'));
		},
		
		loadingFinished: function () {
			//alert('Finished');
			domConstruct.destroy(this.widgetLoading);
		}
	});
});
```

I copied the loading stuff from *Editor* widget and then, as sample, I inherited *_CMVBase* from *LayerControl*:

```javascript
var LayerControl = declare([WidgetBase, Container, CMVBase], {
        map: null,
        (...)
```

Then at the end of *LayerControl*'s ```postCreate``` ```require``` call, I do:

```javascript
topic.publish('cmv/loaded');
```

What do you guys think?

However, there's a little problem here. Sometimes some layer fails to load and the loader's destroyer doesn't fire, there's js error:

![cmv_loading_error](https://cloud.githubusercontent.com/assets/10212618/8983797/7ed514c2-36a3-11e5-951e-dffb98b3f9f7.png)

**Comment by gobsmack** [comment]
Nice work @carrbrpoa. I like the idea of a _CMVBase, or perhaps a _CMVmixin. It would be helpful for testing and development if widgets could be just plain Dijits. That way you could instantiate a widget without it being wired into CMV. Then, for them to work in CMV, those other CMV-specific properties and methods (like parentWidget) would be mixed in.

**Comment by roemhildtg** [comment]
CMV 2.0 has loading indicators on widgets
