### ISSUE TITLE
Feature layer exhibition

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#445]
I'm trying to put a feature layer from feature server on my ```operationalLayers``` but it doesn't get plotted to the map. No js errors. The same feature layer get plotted on ArcGIS online map viewer and the requests generated by one and other are different:

CMV:
http://.../FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100

AGOLMV:
http://.../FeatureServer/0/query?f=json&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-5701896.559986655%2C%22ymin%22%3A-3509376.8458717577%2C%22xmax%22%3A-5701590.811873471%2C%22ymax%22%3A-3509071.0977585763%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

CMV layer definition:
```javascript
{
    type: 'feature',
    url: 'http://.../FeatureServer/0',
    title: 'Consumo',
    options: {
        id: 'testeConsumo',
        opacity: 1.0,
        //visible: true,
        outFields: ['*'],
        mode: 0
    }
}
```

PS1: I have another feature layer between my operational layers which get plotted as expected, which the same layer definition than the one that doesn't work (changing the URL, of course).

PS2: The layer that doesn't get plotted has related table:

![arcgis_layers](https://cloud.githubusercontent.com/assets/10212618/9008470/fb38eafc-3770-11e5-9863-56bc784efb43.png)

Any ideias about it?
Thanks!

**Comment by btfou** [comment]
Try setting `mode: 1`.

`mode: 0` is snapshot mode meaning the feature layer is trying to get all the features. `mode: 1` is ondemand and will request features as the map extent changes. It also makes multiple requests making for better performance of the server querying and returning features.

**Comment by carrbrpoa** [comment]
Worked! Thanks!
