### ISSUE TITLE
how to add arcgis javascript api widgets samples into the template

### ISSUE THREAD

**Issue by cananiculi** [cmv/cmv-app#448]
How to add samples from arcgis js api into the template??
I would like to add several samples from there into the template.

for example: add shp file widget (https://developers.arcgis.com/javascript/jssamples/portal_addshapefile.html)
Sorry for bothering. Noob developer here...:)
Thanks.

**Comment by roemhildtg** [comment]
@cananiculi Check out the [user contributed widgets](https://github.com/cmv/cmv-contrib-widgets) there is a drag-n-drop widget which is already able to add zipped shapefiles. For additional examples on how to write custom widgets, start with the [dojo tutorial](http://dojotoolkit.org/reference-guide/1.10/quickstart/writingWidgets.html) on writing custom widgets.
