### ISSUE TITLE
Graphic with TextSymbol don't get printed

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#449]
I'm building a new widget where I add some text programmatically over a ```GraphicsLayer``` and, despite it is plotted in the map, it just doesn't get printed. No errors.

The ```GraphicsLayer``` unique instantiation:

```javascript
postCreate : function() {
    (...)
    this.labelsLayers = new GraphicsLayer();
    this.labelsLayers.id = 'LabelsLayer';
    this.map.addLayer(this.labelsLayers);
}
```

The function to plot the labels (simplified version):

```javascript
plotLabel : function(feature, text, plotShadow) {
    var textSymbolJson = {
        type : 'esriTS',
        color : [ 0, 0, 0, 255 ],
        verticalAlignment : 'middle',
        horizontalAlignment : 'center',
        font : {
            family : 'Helvetica',
            size : 15,
            style : 'normal',
            weight : 'bold'
        }
    };

    var geoprocessorResult = text;

    var labelTextSymbol = new TextSymbol(textSymbolJson);
    labelTextSymbol.setText(geoprocessorResult);
    //var location = feature.geometry.getExtent().getCenter();
    var labelGraphic = new Graphic(feature.geometry, labelTextSymbol);
    this.labelsLayers.add(labelGraphic);
}
```

I've tried with the ```location``` variable too. Same result.

Example in map:
![cmv_label_map](https://cloud.githubusercontent.com/assets/10212618/9145494/459d47a4-3d2b-11e5-96ea-05f42093a632.png)

Example printed:
![cmv_label_print](https://cloud.githubusercontent.com/assets/10212618/9145501/4caa4326-3d2b-11e5-9b0e-96ce483b6997.png)

PS: Same results with my Printing Tools or ESRI's and I see the label data being passed in ```Web_Map_as_JSON``` of the Print request.

Any ideias about?

Thanks!

**Comment by tmcgee** [comment]
I thought I replied to this when first asked. Probably forgot to submit the comment. If I recall, there may be issues with AGS Print Services being able to print Text Graphics. This may be related. @DavidSpriggs may be able to shed more light on this.

**Comment by roemhildtg** [comment]
@carrbrpoa what version is your ArcGIS Server?

**Comment by carrbrpoa** [comment]
@Gregg, it's 10.3.1

**Comment by roemhildtg** [comment]
Hm, We've added text to our printouts on AGS 10.2 without any real problems. Here's a section of the relevent code:
```JavaScript
/* set up text draw tools */
            this.textFont = new Font(
                    '12px',
                    Font.STYLE_NORMAL,
                    Font.VARIANT_NORMAL,
                    Font.WEIGHT_BOLD,
                    'Helvetica');
            this.textColor = new Color('#000000');
            this.textRenderer = new SimpleRenderer(this.textFont);
            this.textRenderer.label = 'User drawn text';
            this.textRenderer.description = 'User drawn text';
            this.textGraphics = new GraphicsLayer({
                id: 'drawGraphics_text',
                title: 'Draw Text'
            });
            this.textGraphics.setRenderer(this.textRenderer);
            this.map.addLayer(this.textGraphics);
```

**Comment by carrbrpoa** [comment]
@roemhildtg, I tried your way like this:

```javascript
plotLabel : function(feature, text, plotShadow) {
					var textFont = new Font(
		                    '12px',
		                    Font.STYLE_NORMAL,
		                    Font.VARIANT_NORMAL,
		                    Font.WEIGHT_BOLD,
		                    'Helvetica');
					
		            var textColor = new Color('#000000');
		            var textRenderer = new SimpleRenderer(textFont);
		            textRenderer.label = 'User drawn text';
		            textRenderer.description = 'User drawn text';
		            
		            var labelsLayers = new GraphicsLayer({id : 'LabelsLayer', title : 'LabelsLayer'});
					labelsLayers.setRenderer(textRenderer);
				
					this.map.addLayer(labelsLayers);
},
```

...but now the label doesn't even appears in the map.
```plotLabel``` is a function that is called as a *callback* of a GPServer call, which I verified that is being called.

**Comment by roemhildtg** [comment]
Oh I forgot to include the part that adds the text. 
```JavaScript
var font = new Font(this.textSize, this.textStyle, Font.VARIANT_NORMAL, this.textWeight, 'Helvetica');
var textSymbol = new TextSymbol(form.drawText, font,  this.textColor );
var textGraphic  = new Graphic(evt.mapPoint, textSymbol);
this.textGraphics.add(textGraphic);
```

I'm really not sure if this is all necessary, some of it probably doesn't need to be here, but it did work.

**Comment by roemhildtg** [comment]
Basically, that first snippet I showed was in the postCreate function. It gets the text layer ready. Then whenever text needs to be drawn, that second snippet gets run.

**Comment by carrbrpoa** [comment]
Thanks @roemhildtg, got it working the way you suggested.
One more thing: my "text" was actually a numeric value, so I needed to pass it with ```toString()```, otherwise PrintServer don't prints it.
I tried just to use ```toString()``` with my old version too, no success.

Resuming:

My ```postCreate```:
```javascript
postCreate : function () {
	this.inherited(arguments);
	(...)
	this.textFont = new Font(
			'18px',
			Font.STYLE_NORMAL,
			Font.VARIANT_NORMAL,
			Font.WEIGHT_BOLD,
			'Helvetica');

	this.textColor = new Color('#000000');
	this.textRenderer = new SimpleRenderer(this.textFont);
	this.textRenderer.label = 'User drawn text';
	this.textRenderer.description = 'User drawn text';

	this.labelsLayers = new GraphicsLayer({
			id : 'LabelsLayer',
			title : 'LabelsLayer'
		});
	this.labelsLayers.setRenderer(this.textRenderer);

	this.map.addLayer(this.labelsLayers);
```

My ```plotLabel```, called multiple times:
```javascript
plotLabel : function (feature, text, plotShadow) {
	var textSymbol = new TextSymbol(text.toString(), this.textFont, this.textColor);
	var textGraphic = new Graphic(feature.geometry.getExtent().getCenter(), textSymbol);

	if (plotShadow) {
		var shadowColor = new Color('#FFFFFF');
		var shadowSymbol = new TextSymbol(text.toString(), this.textFont, shadowColor);
		shadowSymbol.yoffset = -2;
		shadowSymbol.xoffset = 2;
		var shadowGraphic = new Graphic(feature.geometry.getExtent().getCenter(), shadowSymbol);

		this.labelsLayers.add(shadowGraphic);
	}

	this.labelsLayers.add(textGraphic);
}
```

Map result:
![cmv_label_map_2](https://cloud.githubusercontent.com/assets/10212618/9466780/a07059ec-4b0d-11e5-93e3-eb167614c69e.png)

Print result:
![cmv_label_print_2](https://cloud.githubusercontent.com/assets/10212618/9466798/b844e45c-4b0d-11e5-8efa-d357172f670f.png)
