### ISSUE TITLE
Configuring layers to use the proxy

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#45]
I am not able to get the proxy working correctly with a combination of secured and unsecured services. I had a similar problem with a custom map I made in another application when upgrading to 3.8. My work around there was to use the addProxyRule() method instead of having 'alwaysUseProxy' property set to true. 

I have added the new proxy.ashx that can request dynamic tokens and configured my proxy.config to include the credentials. I then tried the following code in Controller.js (esri/urlUtils included):-

```
    initConfig: function () {
        urlUtils.addProxyRule({
            urlPrefix: "btwgis01:6080/arcgis/rest/services/BTWInternal",
            proxyUrl: "proxy/proxy.ashx"
        });
        //esri.config.defaults.io.proxyUrl = config.proxy.url;
        //esri.config.defaults.io.alwaysUseProxy = config.proxy.alwaysUseProxy;
        esri.config.defaults.geometryService = new GeometryService(config.geometryService.url);
    },
```

I always get prompted for the credentials. It's as if I have the initialisation code in the wrong place. Because once I enter the details, the token is retrieved and included with service calls as required. Am I on the right track, or am I in the wrong place for initialisation?

**Comment by lee53** [comment]
Is there anyway to use proxy for selected layers?  for example operational layers go through proxy and basemaps go through proxy?  Instead of ..alwaysUseProxy = true;

**Comment by tmcgee** [comment]
@lee53. Yes there is. Much like how @tr3vorm did in his original post. You can do this in viewer.js:

``` javascript
define([
    'esri/config',
    'esri/urlUtils',
    'esri/tasks/GeometryService'
], function(esriConfig, urlUtils, GeometryService) {

    esriConfig.defaults.geometryService = new GeometryService('https://server/arcgis/rest/services/Utilities/Geometry/GeometryServer');

    urlUtils.addProxyRule({
        urlPrefix: 'https://server/arcgis/rest/services/',
        proxyUrl: '../common/proxy/proxy.ashx'
    });
...
```

**Comment by lee53** [comment]
@tmcgee Thank you for your quick response.  much appreciate your help and sharing this wonderful viewer.
