### ISSUE TITLE
Using mediaInfos in config/Identify.js widget, other image types?

### ISSUE THREAD

**Issue by MesquiteGIS** [cmv/cmv-app#450]
I'm trying to use mediaInfos for a basic Traffic Cam web app. The popup displays a broken image icon rather than the image. If I click on the broken image icon in the popup window, the browser opens a new tab and displays the traffic cam image. 
![traffic cam](https://cloud.githubusercontent.com/assets/7807619/9372471/aa7b0f3c-4693-11e5-9a53-d02d9b8ec2f4.PNG)

My code is:
```
trafficcams:{
			0:{
				title: '{Location}',
				mediaInfos: [{
					title: '',
					caption: '',
					type: 'image',
					value: {
						sourceURL: '{Thumb_URL}',
						linkURL: '{URL}'
					}
				}]
				
				
				}
			},
```

Any suggestions? Are there other image types to try besides "image"/?

**Comment by tmcgee** [comment]
Does the `Thumb_URL` field contain a valid url? Did you try replacing `{Thumb_URL}` with '{URL}` for the sourceURL property?

**Comment by MesquiteGIS** [comment]
Hi Tim,

Yes, the Thumb_URL is a valid url, and yes I did try replacing them. The cameras are producing a live video feed but the URL I'm using is a snapshot link reloaded every 30 seconds or so.

I'll keep at it.

Tahnks,

Ryan

**Comment by tmcgee** [comment]
@MesquiteGIS If you right-click on the broken image and inspect the element using Chrome Dev Tools, does the url for the image look correct, referencing an invalid path for the image, or is it missing completely?

Looking at the response for the IdentifyTask for this layer in Chrome Dev Tools, verify that the `Thumb_URL` field/value is being returned.

**Comment by MesquiteGIS** [comment]
Yep, rick clicking and inspecting the broken image element references the correct url for the image. 
![inspectelement](https://cloud.githubusercontent.com/assets/7807619/9473067/9fda69dc-4b0d-11e5-83d1-8da9b0a049c4.JPG)
The only thing I can think of is that perhaps this cannot be recognized as a Media Image. The Url is a snapshot from a live video feed. Are there other Media types to try beside image?

**Comment by MesquiteGIS** [comment]
Looks like my options are  image, piechart, barchart,columnchart,linechart
![mediainfos](https://cloud.githubusercontent.com/assets/7807619/9473257/b08e7dc6-4b0e-11e5-8a19-55791448b7b0.JPG)

Has anyone used a video feed for this instead of a still image?

**Comment by tmcgee** [comment]
The url for your image is a web page not an actual image. Have you tried something like this:

"http://bugatti.nvfast.org/Snapshots/7001.jpeg"

**Comment by tmcgee** [comment]
You could try something like this for live video but that would not play within a `mediaInfo`:

http://bugatti.nvfast.org/LiveVideoPlayer.aspx?cctv=7001

You might be able to put that in an iframe.

**Comment by MesquiteGIS** [comment]
Thanks Tim!!!

changing the url to "http://bugatti.nvfast.org/Snapshots/7001.jpeg" corrected the issue.

Thanks!!!
