### ISSUE TITLE
Reload/Refresh function for Popup?

### ISSUE THREAD

**Issue by MesquiteGIS** [cmv/cmv-app#453]
I've recently been working on a Traffic Camera web app using this cmv. Everything is working great, I've got my traffic cam image to appear in the popup window, etc. The issue I'm having now is that the image appears to be cached, so that once you click on the traffic camera and view the image (which is a snapshot from a live video feed, refreshed every 5 seconds), it stays that image even after you close the popup window and reopen it. Does anyone know if a refresh/reload function exists for ESRI popup window? I would like to add a second function similar to the Zoom to function that could refresh/reload the traffic cam image. 
![refresh](https://cloud.githubusercontent.com/assets/7807619/9497266/152da4b8-4bc9-11e5-8795-390ac6c54301.JPG)

Thank you

**Comment by carrbrpoa** [comment]
Hey @MesquiteGIS, did you already implemented the function that refreshes the image but it doesn't work or the implementation is exactly your issue?
Could you share some code? :)

**Comment by tmcgee** [comment]
@MesquiteGIS Are you looking to refresh the image on demand (clicking a link/button) OR do you want the image to be refreshed each time the popup is opened?

Either way, the "problem" is the browser's cache. A common practice is to add some random number to the end of the url like: http://bugatti.nvfast.org/Snapshots/7001.jpeg?r=2531

With the second method (new image each time the popup is opened), you might be able to do that easily using a url something like this:

``` javascript
'http://bugatti.nvfast.org/Snapshots/{ID}.jpeg?r=' + random()
```

**Comment by MesquiteGIS** [comment]
@carrbrpoa , No I havent written any function in to refresh the popup image, just hoping/wondering if someone else had.

@tmcgee Tim, I think that is a great suggestion to add a random number at the end of the URL, but I can't get it to work. I've tried a few variations of the idea, including using a timestamp, etc.
'''trafficcams:{
			0:{
				title: '{Location}',
				description:"<b>Fast Track</b>: <a href='http://fast.mesquitenv.gov/MesquiteLiveVideo/CCTVVideoWallFullScreen.aspx' target='_blank'>Live Video</a><br />",
				mediaInfos: [{
					title: '',
					caption: '',
					type: 'image',
					value: {
						sourceURL: 'http://bugatti.nvfast.org/Snapshots/{Id}.jpeg?r='+new Date().getDate,
						linkURL: 'http://bugatti.nvfast.org/Snapshots/{Id}.jpeg?r='+new Date().getTime()
					}
				}]
				
				
				}
			},
'''
Also have tried:
'''
trafficcams:{
			0:{
				title: '{Location}',
				description:"<b>Fast Track</b>: <a href='http://fast.mesquitenv.gov/MesquiteLiveVideo/CCTVVideoWallFullScreen.aspx' target='_blank'>Live Video</a><br />",
				mediaInfos: [{
					title: '',
					caption: '',
					type: 'image',
					value: {
						sourceURL: 'http://bugatti.nvfast.org/Snapshots/{Id}.jpeg?r='+random(),
						linkURL: 'http://bugatti.nvfast.org/Snapshots/{Id}.jpeg?r='+Math.random()
					}
				}]
				
				
				}
			},
'''

Any thing I'm missing?
Thanks

**Comment by roemhildtg** [comment]
In both your examples, the sourceURL will have unexpected results. In the first example, you forgot parentheses on the new `Date().getDate`. It should be new `Date().getDate()`.

In the second example you're calling `random()` without `Math`. It should be `Math.random()`

I would use the new Date().getTime() function since it will never have a duplicate value.

**Comment by MesquiteGIS** [comment]
@roemhildtg Thanks Gregg. I'm now using the ```new Date().getTime()``` for both the sourceURL and the linkURL. I've noticed the image will not refresh in the popup window by simply closing the window or clicking on another camera location. However, the image does refresh if I click on the image itself which opens the linkURL page. So I'm getting closer but not quite there. 
Perhaps the caching of the image is unavoidable, but I'd still like to create a function to easily refresh/reload the snaphot image.
http://mesquitenvpolice.appspot.com/index.html

**Comment by tmcgee** [comment]
If I'd thought about it a little harder, I would have remembered that the template for the popup is built once on the first click so each image gets the same "random" number regardless of if you use `Math.random()` or `new Date().getDate()`

I am working on another idea. please hold...

**Comment by tmcgee** [comment]
@MesquiteGIS Here's a solution. I created an invisible widget that will refresh the image every 5 seconds (or whatever frequency) while the infoWindow is visible. 

__Add `dojo/query` and `dojo/lang` to the array of modules at the top of viewer.js:__
``` javascript
define([
   'esri/units',
   'esri/geometry/Extent',
   'esri/config',
   'esri/tasks/GeometryService',
   'esri/layers/ImageParameters',
   'dojo/query',
   'dojo/_base/lang'
], function (units, Extent, esriConfig, GeometryService, ImageParameters, query, lang) {
```

__Add this new widget to viewer.js:__

``` javascript
trafficCam: {
    include: true,
    id: 'trafficCam',
    type: 'invisible',
    path: 'dijit/_WidgetBase',
    options: {
        map: true,
        intervalID: null,
        interval: 5000,
        startup: function () {

            this.map.infoWindow.on('show', lang.hitch(this, function () {
                this.intervalID = window.setInterval(function () {
            		var els = query('img.esriPopupMediaImage');
            		if (els.length > 0) {
            			var el = els[0];
            			var src = el.src, k = src.indexOf('rnd=');
            			if (k >= 0) {
            				src = src.substring(0, k - 1);
            			};
            			k = src.indexOf('?');
            			src += ((k < 0) ? '?' : '&') + 'rnd=' + new Date().getTime();
            			el.src = src;
            		}
            	}, this.interval);
            }));

            this.map.infoWindow.on('hide', lang.hitch(this, function () {
        	    window.clearInterval(this.intervalID);
            }));
        }
    }
}
```

I tested this with the cmv demo as it has traffic cameras in the Louisville, KY area. I also tested it with your source for camera images (but only 1 hard-coded camera url).

As written, this will widget refresh the image in the mediaInfo for any layer that has one. Depending on your app, you might want to check the layer being identified and/or that the image src url is from a certain site.

**Comment by MesquiteGIS** [comment]
@tmcgee , Wow Tim! Thank you so much for this. I'll test this out this morning and let you know my results. Much appreciated. Thank you. Just looking at the code, is there another part to this? I see the path is dijit/_WidgetBase. Is there a _WidgetBase.js file I need as well?

Thanks!

**Comment by tmcgee** [comment]
Nope.  No other code needed. _WidgetBase.js is part of the base dojo framework.

**Comment by tmcgee** [comment]
For reference: I first came up with this implementation of a simple widget in viewer.js without the additional files in response to issue #399

**Comment by MesquiteGIS** [comment]
@tmcgee Tim, Thank you for all your help on this. Unfortunately, even with the invisible widget my image remains cached in the pop up. 

http://mesquitenvpolice.appspot.com/

You mentioned that the image source URL needs to be from a certain site?

**Comment by tmcgee** [comment]
No the url does not need to be from a certain site. What I meant was that somebody might want to use the code for only certain layers with `mediaInfos` with images that are updated frequently while not refreshing icons for other layers with `mediaInfos` with static images. There is no point running the code on an image that is static.

It should work without modification for the server from where you are getting your images/videos. I tested that. Perhaps if it is not working for you, it is a difference in browsers. I tested using Chrome. I did not invest time in testing other browsers but it is a common trick that should work for all modern browsers.

I cannot see if the widget is working on your site because the operational layer is not available. Possibly this is due to your AGS server not being accessible publicly via port 6080?

**Comment by tmcgee** [comment]
I see that you fixed the access to the server.

There is an error on the page `lang.hitch is not a function` which explains why the image refresh is not working. I am not sure yet why there is the error.

**Comment by tmcgee** [comment]
Also just an fyi: there is a timeout for a few of your layers in the base maps - probably because of the same situation of using port 6080.

**Comment by carrbrpoa** [comment]
I *guess* that the error is because of bad order of injection stuff:

```javascript
define([
	'esri/units',
	'esri/geometry/Extent',
	'esri/config',
	'esri/tasks/GeometryService',
	'esri/layers/ImageParameters',
	'esri/dijit/Basemap',
	'esri/dijit/BasemapLayer',
	"esri/map", 
    "esri/dijit/HomeButton",
    "dojo/domReady!",
	'esri/geometry/Point',
	'dojo/query',
	'dojo/_base/lang'
	
], function(units, Extent, esriConfig, GeometryService, ImageParameters, Basemap, BasemapLayer, query, lang) {
(...)
```

You jump from BasemapLayer directly to query. Where are the guys in the middle?

**Comment by tmcgee** [comment]
@carrbrpoa that would cause it for sure.

**Comment by tmcgee** [comment]
Here's a working version with your layers and the removal of  unused modules: http://mesquitegis-tmcgee13.c9.io/viewer/

The problem at the moment is that the provider for the traffic camera images/videos is not available so the images are broken. Either that or they blocked my i.p. address because of the frequent image refreshes hitting their server. ;)

**Comment by tmcgee** [comment]
FWIW: [cloud 9](https://c9.io/) is pretty awesome (and free) for this kind of quick test and shared development environment. I had the app referenced above up and running in about 2 minutes pulling from the cmv repo and then copying/pasting the necessary code from @MesquiteGIS's site.

The shared editor workspace is [here](https://c9.io/tmcgee13/mesquitegis). Anyone can sign up for a free account (using github credentials, if desired) and view the entire app, editor and code. With proper permissions, a workspace can also be shared so multiple people can edit it and see immediate results. 

__FYI: The workspace and app mentioned is just an example and will only be around for a day or two.__

**Comment by MesquiteGIS** [comment]
Okay, so I've fixed all my server links so that they will work externally. 

@tmcgee Tim your app at http://mesquitegis-tmcgee13.c9.io/viewer/ works perfect, so it gives me hope. Mine still doesn't work, at least not internally. On mobile devices using chrome, it seems to refresh the image after I close the popup and reopen it. Not sure what the deal is with that. I've tested using chrome, firefox, and ie9

I really like how your viewer refreshes automatically every five seconds in the popup window. At this point I may start over with a clean download of the CMV and go from there. 

I'll keep you all posted. Once again, Thank you Tim.

**Comment by tmcgee** [comment]
does the app I shared work on mobile or is it exhibiting the same you describe? I did not test on any browser other than Chrome on my desktop. I suspect a mobile popup uses a css class on the image other than `esriPopupMediaImage'.

**Comment by MesquiteGIS** [comment]
Just tried on an Ipad-mini in Safari and Chrome, both are working, that is refreshing the image with in the popup every 5 seconds without closing the window.

**Comment by tmcgee** [comment]
It does work on a tablet. I suspect it would not on phone since it uses a different popup to view the identify info.

**Comment by MesquiteGIS** [comment]
yeah, I was testing on my android phone. Doesnt quite work the same because the popup is a separate page .

**Comment by MesquiteGIS** [comment]
Its "Refreshing" to see the image refreshing! Lol. Sorry about that. Thanks

**Comment by tmcgee** [comment]
Actually, I think the css class might be the same for mobile popup BUT I believe the mini mobile infoWindow is hidden when the full screen mobile popup appears. The current code only runs when the infoWindow is showing.

**Comment by MesquiteGIS** [comment]
So I downloaded a fresh cmv, and only added my traffic cam operational layer, the invisible widget, and the identify.js configuration for the traffic cam layer and everything works as it should perfectly. Something, somewhere in my old application was corrupt. 

This is perfect for the police, they just want a quick, easy "mapplication" to view traffic cams on their laptops and Ipads

Thanks for your help on this. I'll close this issue.

**Comment by heisman98** [comment]
@MesquiteGIS, would you mind sending me your contact info? I would like to send you my viewer.js and identify.js and see if you can tell me why I can't get the popup to even appear? My email is mgarza@pape-dawson.com.
Mike
