### ISSUE TITLE
The hide  legendLayerInfos seem not working?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#463]
}, {
			type: 'dynamic',
			url: 'http://GIS.ICAO.INT/ArcGIS/rest/services/FIRMSD/MapServer',
			title: 'ICAO FIR 2015 26 June',
			options: {
				id: 'ICAOFIR2014',
				opacity: 1.0,
				visible: true,
				imageParameters: imageParameters
			
			},
			identifyLayerInfos: {
                layerIds: []
			},
            legendLayerInfos: {
                layerInfo: {
                    hideLayers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
                }
            }
My legend is still appear

**Comment by jebu75** [comment]
If you want to exclude the entire layer from the legend, have you tried setting `exclude:false` like this:
```
legendLayerInfos: {
    exclude: true
}
```

**Comment by GilbertLasnier** [comment]
Thanks but doesn't work!

**Comment by tmcgee** [comment]
HI @GilbertLasnier Examples of both versions are provided in the cmv demo code. 

[Line 109](https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L109)  in `viewer.js` hides the Plume sublayer in the legend.

[Line 123](https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L123)  in `viewer.js` hides the "Damage Assessment" layer in the legend.

They do both work in the [demo](http://demo.cmv.io/viewer) so perhaps it is something in your implementation that is not working. `exclude: true` was added not too long ago so make sure you have the latest version of CMV.

**Comment by GilbertLasnier** [comment]
YOUR RIGHT I DON'T HAVE THE LATEST VERSION

**Comment by GilbertLasnier** [comment]
Now its worst all the layesr have no legend and I erase the
 legendLayerInfos: {
            layerInfo: {
                hideLayers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
            }
I have just that...and i don't understand i have no legend at all , It seam that i am not able to recouvery my legend for that services! i check everywhere in the code other line like legendLayerInfos: {
                exclude: true
            }, and it seam that everything are Ok???
}, {
			type: 'dynamic',
			url: 'http://GIS.ICAO.INT/ArcGIS/rest/services/FIRMSD/MapServer',
			title: 'ICAO FIR 2015 26 June',
			options: {
				id: 'ICAOFIR2014',
				opacity: 1.0,
				visible: true,
				imageParameters: imageParameters
			},
			layerControlLayerInfos: {
				swipe: true,
				metadataUrl: true,
				expanded: false
		
            }
I don't understand!

**Comment by kcarrier** [comment]
@GilbertLasnier 

Try something like this, it should exclude the plus sign and all legend info, play with the boolean(true,false) parameters until you get the desired outcome. Hope it helps!

```
{
            type: 'dynamic',
            url: 'http://yoururlhere',
            title: 'YourLayerName',
            collapsed: true,
            options: {
                id: 'YourLayerName',
                opacity: 1,
                visible: true,
                imageParameters: imageParameters
            },
            identifyLayerInfos: {
                exclude: true //layerIds: [5, 6, 7, 8, 9, 10, 11, 12]
            },
            layerControlLayerInfos: {
                sublayers: false,
                noLegend: true
            }
        },
```

**Comment by kcarrier** [comment]
```
{
            type: 'dynamic',
            url: 'http://GIS.ICAO.INT/ArcGIS/rest/services/FIRMSD/MapServer ',
            title: 'ICAO FIR 2015 26 June',
            collapsed: true,
            options: {
                id: 'ICAOFIR2014'
                opacity: 1,
                visible: true,
                imageParameters: imageParameters,
                swipe: true,
                metadataUrl: true
            },
            layerControlLayerInfos: {
                sublayers: false,
                noLegend: true
            }
        },
```

**Comment by GilbertLasnier** [comment]
Ok I try that Many thanks for your answer
