### ISSUE TITLE
How to just select 1 or two layers to use with the Nearby search?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#464]
In the Nearby search tool, I have almost 200 layers appear and I just want that the user has the choice with just 2 or 3 layers, because they have difficulties to find the layers to make the function Nearby?
Do you think there is a way to realize that???
Thanks to answer

**Comment by tmcgee** [comment]
@GilbertLasnier Is your question about this widget? https://github.com/BrianBunker/cmv-widgets/tree/master/Nearby If so, your question is best asked at that repo.
