### ISSUE TITLE
Programatically  coding of datagrid for attribute Table...getting "Sorry an error occured"

### ISSUE THREAD

**Issue by pnh10** [cmv/cmv-app#465]
"Sorry an error occured" for the attribute table in the datagrid.....on load ...

 displayAttributeTable: function (LayerUrl) {
            //map = this.map;

            if (pMap.graphics.graphics.length != 0) {
                pMap.graphics.clear();
            }
            if (statesLayer != undefined) {
                statesLayer.clearSelection();
                statesLayer.clear();

            }
            statesLayer = new FeatureLayer(LayerUrl, {
                mode: FeatureLayer.MODE_SELECTION,
                outFields: ["*"]
            });

            pMap.addLayers([statesLayer]);

            statesLayer.on("load", function (evt) {

                if (pMap.graphics != null) {
                    pMap.graphics.clear();
                }

                var query = new Query();
                query.where = "1=1";
                evt.layer.queryFeatures(query, function (featureSet) {
                    var items = array.map(featureSet.features, function (feature) {
                        var graphic = feature;
                        pMap.graphics.add(graphic);
                        return feature.attributes;
                    });

                    var data = {
                        identifier: "OBJECTID",
                        items: items
                    };

                    //currentStore = new dojo.data.ItemFileReadStore({ data: data });
                    var currentStore = new dojo.data.ItemFileWriteStore({ data: data });
                    //currentStore.fetch();
                    var store2 = new Memory({
                        idProperty: 'ID',
                        data: data
                    });
                    //grid.set('store', currentMemory); 

                    var currentLayout = []
                    for (fieldName in items[0]) {
                        if (fieldName == "ID" || fieldName == "ROWGUID" || fieldName == "Shape" || fieldName == "FID") {
                            var addField = {
                                field: fieldName, hidden: true
                            };
                            currentLayout.push(addField);
                        }
                        else if (fieldName == "NOTES") {
                            var addField = {
                                field: fieldName, width: "500px"
                            };
                            currentLayout.push(addField);
                        }
                        else {
                            var addField = {
                                field: fieldName
                            };
                            currentLayout.push(addField);
                        }
                    }

                    //                    if (this.grid != null) {
                    //                        this.grid = null;
                    //                    }
                    document.getElementById("gridDiv").innerHTML = "";
                    document.getElementById("gridDiv").style.height = "20em";
                    document.getElementById("divClear").style.display = "inline";
                    var grid = new DataGrid({
                        //id: 'grid',
                        store: currentStore,
                        structure: currentLayout,
                        selectionMode: "single"
                    });

                    /*append the new grid to the div*/
                    grid.placeAt("gridDiv");
                    //this.findResultsGrid.style.display = 'block';
                    //document.getElementById("gridDiv").style.display = "table";

                    /*Call startup() to render the grid*/
                    grid.startup();

                    dojo.connect(grid, "onRowClick", grid, function (evt) {

                        // Colors
                        //var highlightSymbol = new SimpleFillSymbol().setColor(new esri.Color([255, 255, 0, 0.5]));
                        var fieldsSelectionSymbol =
                            new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,
                            new SimpleLineSymbol(SimpleLineSymbol.STYLE_DASHDOT,
                            new Color([255, 0, 0]), 2), new Color([255, 255, 0, 0.5]));

                        var markerSymbol = new SimpleMarkerSymbol();
                        markerSymbol.setColor(new Color("#00FFFF"));

                        var lineSymbol = new CartographicLineSymbol(
                                CartographicLineSymbol.STYLE_SOLID,
                                new Color([255, 0, 0]), 10,
                                CartographicLineSymbol.CAP_ROUND,
                                CartographicLineSymbol.JOIN_MITER, 5
                            );

                        var clickedTaxLotId = evt.grid.getItem(evt.rowIndex).OBJECTID;
                        var selectedTaxLot = arrayUtils.filter(pMap.graphics.graphics, function (graphic) {
                            if ((graphic.attributes) && graphic.attributes.OBJECTID === clickedTaxLotId) {
                                selectedTaxLot2 = new esri.Graphic(graphic.geometry).setAttributes(
                                                    graphic.attributes);
                                //statesLayer.add(selectedTaxLot2);
                            }

                            return ((graphic.attributes) && graphic.attributes.OBJECTID === clickedTaxLotId);
                        });
                        statesLayer.clearSelection();
                        if (selectedTaxLot.length) {

                            var selectQuery = new Query();
                            selectQuery.geometry = selectedTaxLot[0].geometry;

                            if (selectedTaxLot[0].geometry.type == "point") {
                                var point = selectedTaxLot[0].geometry;
                                pMap.centerAndZoom(point, 11);
                                //selectedTaxLot[0].setSymbol(markerSymbol);
                                //statesLayer.graphics[0].setSymbol(markerSymbol);
                                statesLayer.setSelectionSymbol(markerSymbol);
                                statesLayer.selectFeatures(selectQuery, FeatureLayer.SELECTION_NEW);
                            }
                            if (selectedTaxLot[0].geometry.type == "polyline") {
                                var line = selectedTaxLot[0].geometry.getExtent();
                                pMap.setExtent(line);
                                //selectedTaxLot[0].setSymbol(lineSymbol);
                                //statesLayer.graphics[0].setSymbol(lineSymbol);
                                statesLayer.setSelectionSymbol(lineSymbol);
                                statesLayer.selectFeatures(selectQuery, FeatureLayer.SELECTION_NEW);
                            }
                            if (selectedTaxLot[0].geometry.type == "polygon") {
                                pMap.setExtent(selectedTaxLot[0].geometry.getExtent(), true);
                                //selectedTaxLot[0].setSymbol(highlightSymbol);
                                statesLayer.setSelectionSymbol(fieldsSelectionSymbol);
                                //statesLayer.graphics[0].setSymbol(fieldsSelectionSymbol);
                                statesLayer.selectFeatures(selectQuery, FeatureLayer.SELECTION_NEW);
                            }
                        }

                    });

                    pMap.centerAndZoom(center, zoom);

                });
            });
        },

**Comment by tmcgee** [comment]
@pnh10 Your question does not appear to be related to CMV or one of the CMV core widgets. Perhaps you posted in the wrong repository?
