### ISSUE TITLE
A request for new Widget ...Can we have a widget with symbology  as same as in ArcMap?

### ISSUE THREAD

**Issue by pnh10** [cmv/cmv-app#466]

**Comment by pnh10** [comment]
Any Guidance for solving this issue...

**Comment by pnh10** [comment]
widget with symbology function as same as in ArcMap?

**Comment by DavidSpriggs** [comment]
@pnh10 do you mean a legend? We do have a legend widget already. Or, if you mean the TOC (kringe) like in ArcMap then we have this already too. It's called the LayerControl widget.

**Comment by pnh10** [comment]
I would like to change the color of the layers ;if we have color picker when we click on any color,,then it should change the color of the layer?

**Comment by durga-pericherla** [comment]
@tmcgee can we change the color and symbology of the legend either in legend widget or in the layer control widget ? Or is it possible in any other way ? 

Thanks in Advance.
