### ISSUE TITLE
Help with Identify and TabContainer

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#469]
Hello,

I'm playing with the [example of identifier popup with tabs](http://docs.cmv.io/en/1.3.4/widgets/Identify/) and after correcting the coding issues and click in a feature, everything seems fine. However, if I resize the window or switch between different identified features, the contents are gone:

First time:
![tabs_first_time](https://cloud.githubusercontent.com/assets/10212618/10402642/fdd19d82-6e9c-11e5-9449-11b9d73d420e.png)

After *Next Feature* followed by *Previous Feature*:
![tabs_previous_feature](https://cloud.githubusercontent.com/assets/10212618/10402692/47c281fe-6e9d-11e5-9463-25018860b1c5.png)

Resizing window (seems even worse!):
![tabs_resizing](https://cloud.githubusercontent.com/assets/10212618/10402714/63378ce0-6e9d-11e5-8a96-5357ef57dbb9.png)

My actual case is more complex, but as you can see, the basic example is not working 100%. Any ideas about how to fix it? Thanks!

**Comment by roemhildtg** [comment]
I think in the past, I got the tab container working with a little hacky code. There are certainly better ways to do it but at the time this was the quickest and easiest: 
```javascript
           var container = new TabContainer({
                style: 'width:100%;height:300px;'
            }, domConstruct.create('div'));
            container.startup();
            //delay then resize
            setTimeout(function () {
                container.resize();
            }, 200);

            container.addChild(new ContentPane({
                title: 'Something',
                content: 'content',
                style: 'width:100%;'
            }));
            container.addChild(new ContentPane({
                title: 'Attributes',
                content: formatters.table(data),
                style: 'width:100%;'
            }));
            return container.domNode;
```

Alternatively you could do something like:
1. get the map object using `dijit.byId`
2. set event handler for `onInfoWindowShow` or something like that
3. resize the container on that event.

Let me know if that helps at all.

**Comment by carrbrpoa** [comment]
Thanks @roemhildtg, I'll give a feedback as soon as I come back to this subject ;)

**Comment by carrbrpoa** [comment]
Hey @roemhildtg, I followed your main alternative and it worked, thanks! :100:

**Comment by roemhildtg** [comment]
No prob, glad it helped :)
