### ISSUE TITLE
Proxy  Issue

### ISSUE THREAD

**Issue by goriliukasbuxton** [cmv/cmv-app#473]
Proxy rule:
urlUtils.addProxyRule({
        urlPrefix: "route.arcgis.com",
        proxyUrl: "http://[yourmachine]/proxy/proxy.ashx"
    });

Doesn't hold the token. then you query for a attachments.

Thank you,

**Comment by btfou** [comment]
How are you making the the attachment request? `esri/request`? Against a feature layer? Requests through the API should use the proxy. If you make a request with say `dojo/request` then you need to use the proxy url with the request url encoded as the query string.

**Comment by goriliukasbuxton** [comment]
I am using layer.queryattachements function. It gets info but where is no token

**Comment by btfou** [comment]
I don't completely understand what you're asking. If you use a proxy to handle auth there should be no tokens involved.

**Comment by goriliukasbuxton** [comment]
Right. I get attachement URL, but it asks you to login. i was assuming proxy would have token.

**Comment by goriliukasbuxton** [comment]
I think what i am seeing the same as here:
https://github.com/Esri/resource-proxy/issues/221

**Comment by tmcgee** [comment]
Are you using the php or dot net proxy? Your example above shows dot net but the resource proxy issue you reference discusses a few problems with the php proxy. 

Are you using the newest proxy version? The version included with CMV is old and should be removed from the project in my opinion.

**Comment by goriliukasbuxton** [comment]
@tmcgee, I am using the .NET proxy. Also the Attachment https://github.com/cmv/cmv-app/issues/177  solution doesn't work with this proxy either.

**Comment by tmcgee** [comment]
@goriliukasbuxton Staying on this issue: You mention using `layer.queryattachements`. It sounds like you have a custom widget or custom code that uses [`queryAttachmentInfos`'](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#queryattachmentinfos). Presuming that is correct, an object that looks something like this:

``` javascript
"attachmentInfos": [
        {
           "id": 3,
           "contentType": "video/quicktime",
           "size": 397540,
           "name": "360 degree view.mov"
        },
        {
           "id": 2,
           "contentType": "application/pdf",
           "size": 270133,
           "name": "Sales Deed.pdf"
        },
        {
          "id": 1,
           "contentType": "image/jpeg",
           "size": 45325,
           "name": "Picture of the house.jpg"
        }
    ]
}
```

will be sent as an argument to the callback function you have sent as an additional argument for `queryAttachmentInfos`. What are you doing with the object in the callback function? If you are displaying urls for the attachements, I suspect you'll need to ensure that url includes the proxy. This assumes the token is stored in the proxy. I am unclear if that is the case.

Is this close to what you are after?

**Comment by goriliukasbuxton** [comment]
@tmcgee, Example in calling attachments in Search Widget config renderCell is good too:
layer.queryAttachmentInfos(value, function (infos) {
window.open(infos[0].url);
});

**Comment by tmcgee** [comment]
To use the proxy (and the token), you can perhaps change that to something like:
```
window.open('http://[yourmachine]/proxy/proxy.ashx?' + infos[0].url)
```

Of course this is completely untested so you'll probably have to dive in further.

**Comment by goriliukasbuxton** [comment]
I think this will work, for this example.
How could we use this in https://github.com/cmv/cmv-app/issues/177 configuring attachments for secure services for Identify?

**Comment by tmcgee** [comment]
If you are asking how can you bypass the username and login when the attachment opens in a separate window, I do not have an answer for that. As I noted in that issue, I suspect the problem in the JS API (or perhaps the REST api).

**Comment by goriliukasbuxton** [comment]
Understood. Will investigate it. Thank you.

**Comment by goriliukasbuxton** [comment]
@tmcgee , your resolution at https://github.com/cmv/cmv-app/issues/177 works with .NET proxy, PHP has a bug in holding token for attachments
