### ISSUE TITLE
Identify failing for entire map service. 

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#476]
I have just had someone report that they could not identify features in the following public map service. I went to a new CMV v1.34 configuration with the following config change. 

        operationalLayers: [{
            type: 'dynamic',
            url: 'http://maps.npdc.govt.nz/arcgis/rest/services/viewer/utilities/MapServer',
            title: 'NPDC Utilities',
            slider: false,
            collapsed: true,
            options: {
                id: 'npdc',
                opacity: 1.0,
                visible: false
            }
        }],

I get the following javascript error when trying to identify: `An error occurred when starting a widget embedded within InfoWindow: Cannot read property '1' of null line 915: http://js.arcgis.com/3.14compact/init.js`

There is something in the map service that the API doesn't like but I cannot figure it out. I have tried to make a custom template for the info but can only seem to get the OBJECTID to display. I was working on layer id 37 (random pick) but it appears that the problem is across all layers.

**Comment by tmcgee** [comment]
Hey @tr3vorm good to see you here! I see the same error message with that layer. I do not see an obviously apparent reason for this. FWIW, I did find that identify works for the `Airport Waste Sludge Zone (31)` layer which is a polygon.

Possibly a server issue? That server is running AGS version 10.3.1 which means it was upgraded recently.

I'm not sure if issue #156 is "related" but  the same error was documented there when working with related records.

**Comment by tr3vorm** [comment]
Hi @tmcgee - yes I am still here :-) trying to keep up to date on CMV progress, and will get back to CMV again soon. Looks like there is a lot of development in progress. 

I saw the other "related" post too, but nothing helpful for me in this instance. 

Thanks for finding a layer that works though - this might be a good place to start. Now I will have to change this thread title too!

**Comment by tr3vorm** [comment]
As @tmcgee pointed out, there other layers that work, but I don't see any correlation yet. The response from the map service (for a feature identification that fails) is as follows (I added the newline chars). Can anyone see anything wrong with this? Maybe there is a reserved word, unescaped character (e.g. I do see a `ampersand`), out of range? My JavaScript debugging skills are about to get tested. 

        {
	"results":[{
		"layerId":37,
		"layerName":"Waste Water Lateral",
		"displayFieldName":"Unit ID:",
		"value":"NP-MANGO0131SL/1",
		"attributes":{
			"OBJECTID":"2474425",
			"Depth":"0.6",
			"SHAPE":"Polyline",
			"Install":"Null",
			"Unit ID:":"NP-MANGO0131SL/1",
			"Owner:":"W&W",
			"Installed:":"20/07/1964",
			"Service Status:":"IN",
			"Plan Reference:":"BK 18/1986",
			"Spatial Accuracy:":"AS BUILT",
			"Type:":"STD",
			"Width/Diameter:":"100",
			"Pipe Type:":"GEW",
			"Pipe Length:":"8.117518",
			"Surface Cover:":"CSFP",
			"Additional Information:":"3.4M FROM LEFT BDY",
			"Asset ID:":"115807",
			"Comments:":"Null",
			"NPDC_VECTOR_SDEADMIN_SVEW_WWLATERAL_area":"NP",
			"SHAPE_Length":"8.117518"
		},
		"geometryType":"esriGeometryPolyline",
		"geometry":{
			"paths":[[[19380715.101717468,-4730352.7294308199],[19380705.678131767,-4730348.2100598849]]],"spatialReference":{"wkid":102100,"latestWkid":3857}
		}
	}]
}

**Comment by tr3vorm** [comment]
Found the problem, but not the solution. The field aliases have ":" characters appended to them.

**Comment by tmcgee** [comment]
yes, I suspect that might be a problem for the JS API. Looks like a bug either in the JS API or the REST API.

**Comment by tr3vorm** [comment]
Anything I can do about it in CMV as a hack? Strip the trailing colons off in `identify.js` - I am struggling for time but while I am not happy about the map service, there is nothing I can do about it.

**Comment by tr3vorm** [comment]
An update. I can confirm that the problem is caused by the trailing colon on field names. If any of the fieldnames have a trailing colon (`:`) then the identify fails and an empty window appears. If I have a template, only values for selected fields without colons appear correctly. 

The REST API response appears to be syntactically correct (e.g. `"Service Status:":"IN",`) but somehow this gets changed to `"Service Status"::"IN"`

**Comment by tmcgee** [comment]
@tr3vorm Did you find an acceptable solution or work-around for this?

**Comment by tr3vorm** [comment]
No @tmcgee - I had forgotten about it until this morning when someone enquired. I added a [ticket on ESRI Geonet](https://geonet.esri.com/message/565790#565790), but no replies there either.

**Comment by tr3vorm** [comment]
I fixed this by stripping off the trailing colon in `identify.js` - line 354 

        fieldInfos.push({
            fieldName: prop.replace(/:$/, ''),
            visible: true
        });
