### ISSUE TITLE
Global helpers

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#483]
Hello,

I wish to declare a global variable/widget/whatever which is composed by some complex (which has many dojo/esri/dojox dependencies) functions. I also need that it could be visible by widgets configs and widgets implementations. 
Actually, I want to expose the `formatter` variable [from this example](http://docs.cmv.io/en/1.3.4/widgets/Identify/) (with some additions that require dependencies) and use it anywhere (or any popup that need my custom content stuff).

Could you guys provide me tips about an elegant way to do this?

Thanks in advance

**Comment by btfou** [comment]
@carrbrpoa The simplest approach is to write a utility Class with methods which create and return content for the popup, and require it in your widgets. You should avoid assigning global vars.

Could you give a workflow/use case example?

**Comment by carrbrpoa** [comment]
Sure, something like this:

Considering the [formatter example](http://docs.cmv.io/en/1.3.4/widgets/Identify/), imagine that I included a new function in the formatter which will plot a Chart in the InfoTemplate for me.
Now, I want to separate it from Identify's config because I wish to use the same formatter's logic in some widget implementation file that will plot a Chart in an InfoTemplate popped by me.

**Comment by btfou** [comment]
So write a Class to do that. Include it in identify config and anywhere else you need it. It's modularization of the formatter object for use anywhere.

```javascript
define([ /* mods */ ], function ( /* classes */ ) {

  // all logic and helper methods here
  function chartDimensions(options) {
    // do stuff
    return [width, height];
  }

  var formatters = { // just return formatter methods
    makeChartContent: function (someArgs) {
      // do stuff
      return someDomNode;
    },
    tabContainer: function (identifyResults) {
      var container = new TabContainer({
        style: 'height: 100%; width: 100%;'
      }, domConstruct.create('div'));
      container.addChild(new ContentPane({
        title: 'my title',
        content: 'You clicked a feature. The results are in the next tab'
      }));
      container.addChild(new ContentPane({
        title: 'my title',
        content: formatters.attributeList(identifyresults)
      }));
      return container.domNode;
    }
  };

  return formatters;

});
```

Then require in identify config. 

```javascript
define(['path/to/formatters'], function (formatters) {
  return {
    map: true,
    mapClickMode: true,
    mapRightClickMenu: true,
    identifyLayerInfos: true,
    identifyTolerance: 5,
    identifies: {
      electric: {
        1: {
          title: 'Pole',
          content: formatters.tabContainer
        }
      }
    }

  };
});
```

**Comment by carrbrpoa** [comment]
Thank you very much @btfou, that's exactly what I was looking for and did the trick! :100:
