### ISSUE TITLE
Implement session timeout

### ISSUE THREAD

**Issue by husenk** [cmv/cmv-app#487]
Hi all
I am using secured services and has implemented sign in and sign out functionality. I am looking if anyone here has implemented session timeout. What I want to achieve is sign out automatically (esri.id.destroyCredentials) when the session is idle for certain period.

Thanks.

**Comment by tmcgee** [comment]
@husenk What would you consider "idle"? Are you looking to track every mouse movement or map interaction to extend the session (resetting an idle timer)?

**Comment by husenk** [comment]
@tmcgee Yes. The idle timer gets reset when there is a mouse movement on the page.

**Comment by tmcgee** [comment]
Ok. Perhaps you could add something like the following to your current code that resets the idleTimer. This is completely untested but in theory it should destroy the credentials after 10 minutes of no mouse movement.

``` javascript
var minutes = 10;
if (this.myTimer) {
    clearTimeout(this.myTimer);
}
this.myTimer = setTimeout(function(){
    esri.id.destroyCredentials();
}, (minutes * 60 * 1000));
```

**Comment by husenk** [comment]
Thanks. It works fine now. I start the idle timer after user logs in (onCredentialCreate) and get reset on mousemove, keydown, click,etc.
Thanks for your idea.

**Comment by tmcgee** [comment]
Glad that I could help.
