### ISSUE TITLE
Advanced Time Slider Widget Auto-Open

### ISSUE THREAD

**Issue by paulanergraz** [cmv/cmv-app#488]
I am developing an Webapp with this great viewer. But i have a small problem and i can't find the solution. I am using the Advanced Time Slider Widget and it's working fine. But i need to auto activate it at the start of the application (like with the widgets on the sidebar where you can chose if they are open or not)

**Comment by tmcgee** [comment]
@paulanergraz Is [this](https://github.com/vojvod/CMV_TimeSlider_Widget) the Time Slider widget you are asking about? If so, based on my quick look at the example configuration, that widget should be visible on the map immediately upon startup.

**Comment by paulanergraz** [comment]
Thanks for your fast response. 

yes it's the widget i am asking about. It's only the button witch is visible on the startup in my app but i need the time widget activated.
see: http://46.163.106.182/cmv-app-master/viewer/

**Comment by tmcgee** [comment]
I took a quick look at the widget code and believe you can do this by adding this to the `options` portion of the config for the widget:

``` javascript
startup: function () {
    this.EnableTimeSlider();
}
```

I've never used this widget so the above is just an educated guess. If you need additional assistance with this widget, you should post your questions in @vojvod's [repo](vojvod).

**Comment by paulanergraz** [comment]
Thanks a lot, that worked
