### ISSUE TITLE
Identify With Content Formatter

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#490]
I was trying to use the example in the documentation found here
http://docs.cmv.io/en/1.3.4/widgets/Identify/#identify-widget-configuration-file
but I am having problems with the formatting.

What I would like to do is add some if then else logic to the identify where if a certain attribute is returned from a map click then I format the content based on the returned attribute.

Could someone please help me with how this should be formatted in the Identify.js and also any customizations I might have to make in viewer.js?

This was the example I was trying to work with, I do not need tab containers, I just need to be able to get a returned attribute and if it meets a certain criteria format the popup.
```
define([
    'dojo/_base/lang',
    'dijit/layout/TabContainer',
    'dijit/layout/ContentPane',
    'dojo/dom-construct',
], function (lang, Container, ContentPane, domConstruct) {
    var formatters = {
        attributeList: function (identifyResults) {
            var listItem = '<li>{0}: {1}</li>';
            var html = ['<ul>'];
            for (var a in identifyResults.attributes) {
                //make sure a is an own property
                if (identifyResults.attributes.hasOwnProperty(a)) {
                    html.push(lang.replace(listItem, [a, identifyResults.attributes[a]]));
                }
            }
            html.push('</ul>');
            return html.join('');
        },
    tabContainer: function(identifyResults) {
        var container = new TabContainer(
            style: 'height: 100%; width: 100%;'
                }, domConstruct.create('div'));
        container.addChild(new ContentPane({
            title: 'my title',
            content: 'You clicked a feature. The results are in the next tab'
        });
        container.addChild(new ContentPane({
            title: 'my title',
            content: formatters.attributeList(identifyresults)
        });
        return container.domNode;
    }
    };
    return {
        map: true,
        mapClickMode: true,
        mapRightClickMenu: true,
        identifyLayerInfos: true,
        identifyTolerance: 5,
        identifies: {
            electric: {
            1: {
            title: 'Pole',
            content: formatters.tabContainer
            }
        }
        }

    };
});
```

**Comment by roemhildtg** [comment]
@kcarrier the first thing to note is when using the `content: myFormatter` we are completely overriding the default identify html. So in your scenario, you will have something like this:

If scenario 1, 
Do some customization to your values and return that html

Else
return html that looks like the default identify template.

For example, this function (from the documentation) recreates the default identify popup.(I'll admit it could be made a little bit easier to understand than what I wrote in the docs)

```Javascript
    attributeList: function (identifyInfo) {
            //this is the template for each line. It takes two values
            var listItem = '<li>{0}: {1}</li>';
            //initialize a list of html
            var html = ['<ul>'];
            //iterate through each attribute in the identifyInfo
            for (var a in identifyInfo.attributes) {
                //make sure a is an own property, not inherited
                if (identifyInfo.attributes.hasOwnProperty(a)) {
                    //use lang.replace to place the field name and the field value into the template
                    html.push(lang.replace(listItem, [a, identifyInfo.attributes[a]]));
                }
            }
            //end the list
            html.push('</ul>');
            //return html string
            return html.join('');
        },
```
You could customize the inside of that for loop and do something like:
```Javascript
var newVal;
if(a === 'my_field'){
   newVal = formatters.ChangeValue(identifyInfo.attributes[a]);
} else {
   newVal = identifyInfo.attributes[a];
}
html.push(lang.replace(listItem, [a, newVal));
```

**Comment by kcarrier** [comment]
Would it be possible for you to possibly post the entire code for the identify.js file with the contentFormatter please?

**Comment by kcarrier** [comment]
I was getting some formatting errors when copying and pasting from the docs.

**Comment by tmcgee** [comment]
@kcarrier: the original example code that you posted should work as is, If you do not want tabs, you can change `content: formatters.tabContainer` to this: `content: formatters.attributeList`.

**Comment by kcarrier** [comment]
OK I was getting a formatting error let me look again thanks @roemhildtg @tmcgee

**Comment by kcarrier** [comment]
something with the tab container formatting was not working for me in VS 2012. once I removed that function and added this before the final return '};' all is working now. Not sure what I was missing.

**Comment by kcarrier** [comment]
@tmcgee - Maybe I have been looking at this far too long now I cannot even get a simple identify to work. I thought I had the code close for the formatter but then when I went to test nothing would show up, so I defaulted back to the simple identify just to get something to show up and now I cannot even get a popup to come up. Any thoughts on where I went wrong?

viewer.js
```
{
            type: 'tiled',
            url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Elementary_Basemap_151128_clipped/MapServer',
            title: 'Elementary Schools',
            collapsed: true,
            options: {
                id: 'elementaryschools',
                opacity: 1,
                visible: true,
                imageParameters: imageParameters
            },
            identifyLayerInfos: {
                layerIds: [11]
            },
            layerControlLayerInfos: {
                sublayers: false,
                noLegend: true
            }
        },
```

```
            identify: {
                include: true,
                id: 'identify',
                type: 'invisible',
                path: 'gis/dijit/Identify',
                title: 'Identify',
                open: false,
                position: 3,
                options: 'config/identify'
            },
```

identify.js
```
define({
    map: true,
    mapClickMode: true,
    mapRightClickMenu: true,
    identifyLayerInfos: true,
    identifyTolerance: 30,

    identifies: {
        elementaryschools: {
            11: {
                title: 'Parcels',
                fieldInfos: [{
                    fieldName: 'PID',
                    visible: true
                }]
            }
        }
    }
});
```

**Comment by tmcgee** [comment]
@kcarrier Change the layer from `type: 'tiled'` to `type: 'dynamic'` and it works. Perhaps you have been looking at it too long. ;)
