### ISSUE TITLE
Combine tiled and dynamic/feature layers services

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#491]
I would like to be able to combine a tiled and dynamic service and present it as one layer in CMV, is something like this possible?

More specifically I wish to combine a tiled service and a feature layer from a map service.

For example how could I combine these 2 services together so the feature layer is on top of the tiled service but still present it as one layer in CMV, any help would be greatly appreciated thank you in advance.

```
{
            type: 'dynamic',
            url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Boundary_Labels_100709/MapServer/0',
            title: 'Boundary Labels',
            collapsed: true,
            options: {
                id: 'boundarylabels',
                opacity: 1,
                visible: true,
                imageParameters: imageParameters
            },
            identifyLayerInfos: {
                exclude: true //layerIds: [5, 6, 7, 8, 9, 10, 11, 12]
            },
            layerControlLayerInfos: {
                sublayers: false,
                noLegend: true
            }
        },
{
            type: 'tiled',
            url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Elementary_Basemap_151127_clipped/MapServer',
            title: 'Elementary Schools',
            collapsed: true,
            options: {
                id: 'elementaryschools',
                opacity: 1,
                visible: true,
                imageParameters: imageParameters
            },
            identifyLayerInfos: {
                exclude: true //layerIds: [5, 6, 7, 8, 9, 10, 11, 12]
            },
            layerControlLayerInfos: {
                sublayers: false,
                noLegend: true
            }
        },
```

**Comment by tr3vorm** [comment]
I don't actually know, but does the `basemaps.js` config file give any clues? The hybrid custom basemaps.

**Comment by kcarrier** [comment]
@tr3vorm - Yes it gave me some clues where I am stuck is the combination or mashup of tiled with dynamic/feature. How would you be able to structure the code so 2 different types of services are considered 1 mashup/operational layer?

**Comment by roemhildtg** [comment]
You can combine multiple layers in an `esri/dijit/BasemapLayer`. The downside is BasemapLayers are limited to use in a BasemapGallery or as the map Basemap.

```Javascript
//config/basemaps.js
//...
basemaps: {
            layer_id: {
                title: 'Basemap Gallery Layer Title',
                basemap: new Basemap({
                    id: 'layer_id',
                    layers: [new BasemapLayer({
                            url: '/ArcGIS/rest/services/dynamic_layer_name/MapServer',
                        }), new BasemapLayer({
                            url: '/ArcGIS/rest/services/tiled_layer_name/MapServer',
                            displayLevels: [1,2,3,4,5]
                        })]
                })
            },
//...
```

See [this page](https://developers.arcgis.com/javascript/jsapi/basemaplayer-amd.html) for info on the BasemapLayer object.

**Comment by tmcgee** [comment]
@kcarrier: I think what would be needed is the concept of a 'Group' or layer. That concept does not exist in the ESRI JavaScript API. It would have to be created as a new layer "type" for CMV and then new logic added to the layerControl widget to "manage" the layers as a single unit with regards to visibility, opacity, layer order, legend, etc. Sounds like a non-trivial task that cannot be addressed fully here in issues.

**Comment by tmcgee** [comment]
I suppose another option would be to fuse/combine the tiles from the two (or more) services into a single tile cache server-side. This is not exactly what you had in mind but perhaps possible approach depending on your use case.
