### ISSUE TITLE
Select Polygon not working with identify task

### ISSUE THREAD

**Issue by saurabhgis** [cmv/cmv-app#492]
I have created custom widget for select polygon and pass polygon field information into URL using query-string. I have used indentify widget used for this purpose.

This tool is working fine if i disable identify tool and but we require both tool.

**Comment by roemhildtg** [comment]
Is the custom widget using the map click? [CMV has its own map click object](http://docs.cmv.io/en/1.3.4/configure/widgets/) to handle different widgets using map click events. 

Someone might be able to help troubleshoot if you provide some more details. Can you post any errors in your browser's console, and possibly the code in the custom widget? 

Either post it here formatted with markdown or in a gist.

**Comment by saurabhgis** [comment]
Pls share ur email id.

My is : sbh.upd1@gmail.com
