### ISSUE TITLE
Control Layer Visibility

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#493]
Is there a way to control layer visibility based on the visibility of another layer

Basically,

If user turns on layer in layer control, I wish to enable the visibility of an excluded layer.

Can this be handled by a function within the viewer.js or some other js file within CMV.

**Comment by tmcgee** [comment]
@kcarrier: Have you tried subscribing to the `layerControl/layerToggle' topic. That topic is published when a layer's visibility changes. It is documented with a simple example [here](http://docs.cmv.io/en/1.3.4/widgets/LayerControl/). You could do that in an invisible widget.

**Comment by kcarrier** [comment]
@tmcgee - No I have not, could you possibly give a little more detail on how I might implement this as an invisible widget please? It sounds like what I would like to do just not entirely sure on how to get started. Not expecting any code to be written for me but in looking over the example you shared, I am not sure in what file I would put this could if you have any example code I could stare at that would really be helpful. I am working through my identify issue right now but I will take some more time to look over the documentation. Thanks again!

**Comment by tmcgee** [comment]
I do not have a specific example handy related to layer visibility. Perhaps the minimalist example of an invisible widget I provided in issue #399 will help get you started.
