### ISSUE TITLE
GraphicsLayer order

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#495]
Hello,

I'm playing with the **Measurement** widget in a way that I want to plot some labels over the area geometry. For instance:

![label_behind](https://cloud.githubusercontent.com/assets/10212618/11749621/0b7d9468-a016-11e5-9264-2f61c15b0b82.png)

To do it, I hooked the Measure's `measure-end` event. After it's call, I add a `GraphicsLayer` to the map and then the labels (Graphics) to it:

``` javascript
postCreate : function () {
    (...)
    this.measure.on("measure-end", lang.hitch(this, 'measureEnded'));
}

measureEnded : function (evt) {
    if (this.measure.getTool().toolName === 'area') {

        (...)

        if (!this.labelsLayers) {
            this.labelsLayers = new GraphicsLayer({
                    id : 'MeasureLabelsLayer',
                    title : 'MeasureLabelsLayer'
                });
            this.labelsLayers.setRenderer(this.textRenderer);
            this.map.addLayer(this.labelsLayers);
        }

        (...)

        var textSymbol = new TextSymbol(areaText, this.textFont, this.textColor);
        var textGraphic = new Graphic(center, textSymbol);

        this.labelsLayers.add(textGraphic);

        textSymbol = new TextSymbol(perimeterText, this.textFont, this.textColor)
            textSymbol.yoffset = -15;
        textGraphic = new Graphic(center, textSymbol);

        this.labelsLayers.add(textGraphic);
    }
}
```

See the map inspected:

![label_behind](https://cloud.githubusercontent.com/assets/10212618/11749843/36ebce0c-a017-11e5-9cb0-17a9b4897568.png)

As you can see in the screen, the labels are behind the measured area's geometry. Is there any way to bring it to front?

Thanks

**Comment by tmcgee** [comment]
@carrbrpoa have you tried changing the z-index of the measurement layer? Something like:

``` css
#MeasureLabelsLayer_layer {
    z-index: 9999;
}
```

**Comment by carrbrpoa** [comment]
Hey Tim,

I tried now, but no effect (yes, I verified that the style had been applied).

**Comment by tmcgee** [comment]
I was wrong s z-index is not supported within svg.

I think you will need to manipulate the dom with JS. Move the MeasureLabelsLayer_layer svg graphic element to be the first one within the svg tag. You should only need to do that once just after you create the layer. Try using [`domConstruct.place()`](https://dojotoolkit.org/reference-guide/1.10/dojo/dom-construct.html#dojo-dom-construct-place)

**Comment by carrbrpoa** [comment]
@tmcgee, your tip (or sort of it) worked. :100: 
What I did:

```javascript
//It occurs once
addLabelLayer : function () {
	this.labelsLayers = new GraphicsLayer({
			id : 'MeasureLabelsLayer',
			title : 'MeasureLabelsLayer'
		});
	this.labelsLayers.setRenderer(this.textRenderer);
	this.map.addLayer(this.labelsLayers);

	domConstruct.place("MeasureLabelsLayer_layer", "mapCenter_graphics_layer", "after");
},
```

Unfortunately, the change is not applied when I print the map:

![print_measure](https://cloud.githubusercontent.com/assets/10212618/11781854/290d95ce-a254-11e5-92c4-f71bb547464c.png)

Any ideas about?

Thanks!

**Comment by tmcgee** [comment]
You might need to create a custom PrintTask on the server? You can also look at the `Web_Map_as_JSON` that is sent to the PrintTask to see if there is anything you can manipulate before it goes to the server.

**Comment by tmcgee** [comment]
Maybe you just need to manipulate the order of the ids in `map.graphicsLayerIds` array to match the new order of your dom elements. Possibly there's a method of the map object that will do both of those things for you?

**Comment by carrbrpoa** [comment]
Nice @tmcgee, I'll take a closer look at map's methods and post something here later. Thanks a lot!

**Comment by tmcgee** [comment]
One more thought which is perhaps the easiest of all. Pass an index of 0 when adding the layer:

``` javascript
addLabelLayer : function () {
    this.labelsLayers = new GraphicsLayer({
            id : 'MeasureLabelsLayer',
            title : 'MeasureLabelsLayer'
        });
    this.labelsLayers.setRenderer(this.textRenderer);
    this.map.addLayer(this.labelsLayers, 0);

},
```

**Comment by carrbrpoa** [comment]
Just setting the index didn't work.

**Comment by tmcgee** [comment]
too bad. that's how it _SHOULD_ work. now you'll have to continue with your work-around.

**Comment by carrbrpoa** [comment]
Also sadly, seems that labels layers' id is already the last in the list:

`$ app.map.graphicsLayerIds`
`>>> ["streetview_graphics", "drawGraphics_point", "drawGraphics_line", "drawGraphics_poly", "test_graphics", "MeasureLabelsLayer"]`

See that `mapCenter_graphics_layer` doesn't appears in this list. So I think I'll need to manipulate `Web_Map_as_JSON` as you suggested or find a magic function between map's ones ;)
