### ISSUE TITLE
Reverse Geocode Popup Mobile

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#498]
@tmcgee - I am noticing an issue on Samsung Galaxy S4(Android), the reverse geocode does not show the popup while on mobile device. On desktop/laptop in Chrome/IE/Firefox the reverse geocode popup works as expected. If someone could help me test this theory I would appreciate it. If you need a url please reach out to me directly carrierkhework@gmail.com

The popup shows up but it does not return the results it just shows Location in the popup title.

**Comment by tmcgee** [comment]
@karrier this has been identified previously in issue #455. I'm going to close this issue and we'll track progress in the original one.
