### ISSUE TITLE
Blocking layer

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#501]
Hello,

I have a non ArcGIS accessory layer loaded as *wms* type:

```javascript
{
	type : 'wms',
	url : '...',
	title : 'Sulgás',
	options : {
		id : 'Sulgas',
		opacity : 1.0,
		visible : false,
		format : "image/png8", //doesn't respect
		visibleLayers : ['GEOM_ACO_GAS'],
		forceSRS : 3857 //custom stuff
	},
}
```

The problem is that the layer's server or local connection is not so stable so that the `GetCapabilities` request made by the application runs until 60 seconds timeout and until there, the application menu doesn't load:

![cmv_loading](https://cloud.githubusercontent.com/assets/10212618/12329979/0b3eecf8-baca-11e5-8a76-d79f4429f458.png)

Sometimes it loads but take like 30 seconds, then the menu appears.

Do you know a way to avoid this blocking?
Would be terrible to make the user wait 1 minute for something he can't even use.

PS: Yes, I use a blank basemap in this application.

Thanks!

**Comment by tmcgee** [comment]
@carrbrpoa It an option to add this layer from an invisible widget? Since this layer is so temperamental, perhaps you can give the user to load it optionally after the app is ready with everything else using [this WMS widget](https://github.com/vojvod/CMV_addWMSLayer_Widget) or your own custom one adapted from that widget.

**Comment by carrbrpoa** [comment]
Hey @tmcgee, I think that for this case, the invisible widget is the best option. I'll try something later and then give you a feedback. Thanks for the ideas.

**Comment by carrbrpoa** [comment]
I ended up using the WMS widget you mentioned, with some custom tweaks to work with my *alien* layer (legends included), which is an Oracle's MapViewer one. :100:

![wms_sulgas](https://cloud.githubusercontent.com/assets/10212618/12419189/98bcfb18-be9b-11e5-8073-da84eeeca30f.png)
