### ISSUE TITLE
Help with custom widget

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#502]
Hello,

Let's say I implemented a custom widget called MyCustom that looks like this:

```javascript
define([
		// basics
		'dojo/_base/declare',
		// mixins & base classes
		'dijit/_WidgetBase',
		'dijit/_TemplatedMixin',
		'dijit/_WidgetsInTemplateMixin',
		// templates & widget css
		'dojo/text!./MyCustom/templates/MyCustom.html',
		'xstyle/css!./MyCustom/css/MyCustom.css',
		'dojo/i18n!./MyCustom/nls/resource'
	], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin,
		template, css, i18n) {

	return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
		widgetsInTemplate : true,
		templateString : template,
		baseClass : 'gis_MyCustomDijit',
		i18n : i18n,
		map : null,

		postCreate : function () {
			this.inherited(arguments);
			this.setupConnections();

			(...)

			var someProp = this.someProp;
			
			// Some processing over someProp...
		},

		(...)
	});
});
```

This widget is declared in `viewer.js` like this:

```javascript
myCustom : {
	include : true,
	id : 'myCustom',
	type : 'titlePane',
	canFloat : true,
	position : 1,
	path : 'gis/dijit/MyCustom',
	title : 'My Custom',
	open : false,
	cssClass : 'search',
	options : {
		map : true,
		someProp : 'abc'
	}
},
```

The question is: what do I need to do to embed this widget in another one (`Search`, as sample) and pass the `someProp` to it?

I tried the following in the beginning of `config/searchWidget.js`, which resulted in undefined `someProp` inside `MyCustom.js`:

```javascript
(...)

return {
	map : true,
	mapClickMode : true,
	someProp : 'abc',

	(...)
```

**Comment by tmcgee** [comment]
Not entirely sure what you mean by "embed this widget in another one". Are you trying to establish a parent/child relationship between 2 widgets or are you wanting to pass a value from one widget to another?

**Comment by carrbrpoa** [comment]
Parent/child, I guess...I just want to reuse `MyCustom` and be able to pass `someProp` to it's consumption, because this property will always be needed. See:

![mycustom](https://cloud.githubusercontent.com/assets/10212618/12491544/dc85107e-c062-11e5-8b30-1c21f3fb386e.png)

The top highlighted is `MyCustom` inside Search (it's ugly yet :p), and the bottom is `MyCustom` alone. Both need to operate independently.

**Comment by roemhildtg** [comment]
You can embed widgets inside of each other, just modify the template and use `data-dojo-type` and `data-dojo-props`. 

I embed the app settings widget inside the help dialog template:

```html
                <div data-dojo-type="dijit/layout/ContentPane" title="Settings">
                    <!--add the AppSettings widget as another tab -->
                    <div id="settingsDijit" title="Settings"
                         data-dojo-type="widgets/AppSettings"
                         data-dojo-props="
                         mapRightClickMenu: this.mapRightClickMenu, 
                         map: this.map, 
                         layerInfos: this.layerInfos, 
                         shareNode: 'shareDijit', 
                         parameterName: this.parameterName,
                         server: this.server"></div>
                </div>
```
and the help settings in the cmv config would need to include both settings for help and the app settings widget. You could do the same for your widget, but note that modifying the template will affect that specific widget on a global level (for all your cmv configs)
```javascript
            help: {
                include: true,
                id: 'help',
                type: 'floating',
                path: 'widgets/Help',
                title: 'Help',
                options: {
                    layerControlLayerInfos: true,
                    mapRightClickMenu: true,
                    map: true,
                    server: '/save_load/settings.php',
                    parameterName: 'mySettings'
                }
            }
```

**Comment by tmcgee** [comment]
OK. Theoretically, you can have the same widget in your configuration multiple times with different options - assuming the widget supports that. Just use a different id and different options for each widget.

The second example is a straightforward widget of `type: 'titlePane'.

The top example is a little more complex so may require more discussion. Instead of modifying templates as @roemhildtg suggested, I have used another approach that is probably more supportable long term. How I have done this is to create a titlePane widget that has nothing but empty div tags (2 in your case) - this can all be done in `viewer.js` no additional widget files required. Then the other "child" widgets (search and myCustom in your case) are `type: 'domNode'` with `srcNode` property targeting the empty div tags. I have a shareable example of this somewhere if you need more direction. I believe it can also be done using `type: 'contentPane'` though that might require more customization.

**Comment by roemhildtg** [comment]
@tmcgee that is a good point, modifying the template would be harder to maintain in the long run. What about creating a third custom wrapper widget, like you mentioned, that instead embeds both widgets in its own template with data-dojo-type, and then passes parameters to those widgets with data-dojo-props?

**Comment by tmcgee** [comment]
I suppose you could do that but perhaps over-complicates it?

**Comment by roemhildtg** [comment]
Yeah, I suppose at that point you're working against the cmv framework.

**Comment by carrbrpoa** [comment]
Thanks for all the support guys, I'll check closer tomorrow! ;)

**Comment by tmcgee** [comment]
Perhaps. The custom widget you proposed would be a good solution if it were intended reused for multiple applications with the same (or similar) child widgets. What I suggested might give a little bit more flexibility for "one-off" combo widgets for a single app.

**Comment by roemhildtg** [comment]
@tmcgee that makes sense. Thanks for letting me bounce the ideas off you.

**Comment by tmcgee** [comment]
@roemhildtg It is a collaborative effort. There are always multiple ways to approach a problem. Your thoughts and input are always appreciated.

**Comment by carrbrpoa** [comment]
Hello guys!

I ended up using [@roemhildtg's suggestion](https://github.com/cmv/cmv-app/issues/502#issuecomment-173694430), because I didn't escape from modify the original `Search`'s code, since `MyCustom` is kind of a complex component with some specificities and now, with some input parameters to `MyCustom`, I'm able to mold it to fit `Search`'s widget exactly the way I want:

![after_logradouro](https://cloud.githubusercontent.com/assets/10212618/12552721/a3f6acae-c35a-11e5-9765-f70ca47a60b1.png)

Thanks for the tips!
:100:
