### ISSUE TITLE
How to edit the tool tips in the Draw widget?

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-app#506]
Hi,

I would like to know a way (or help) to edit the tool tips that popup when using the Draw widget.  Example: When clicking on the "point" button and hovering over the map, text in the pop up box shows "Click to add a point".  I'd like to have the option to change this.  I'm fairly new at JS/CSS so pardon the naivety. 

Thanks!

Jesse
![tooltip](https://cloud.githubusercontent.com/assets/16945459/12956810/73f64b3a-cfef-11e5-9e03-892f0842f9d0.JPG)

**Comment by tmcgee** [comment]
Hello @JhopStl and welcome.

Those tooltips are part of the "drawing" toolbar in the ESRI JavaScript API. An example of how to change the default text that happens to address your example specifically is at the bottom of [this page}(https://developers.arcgis.com/javascript/jshelp/localization.html)

**Comment by JhopStl** [comment]
Thank you sir, I'll look into this.
