### ISSUE TITLE
Possible to use "Custom TiledMapServiceLayer" as a basemap?

### ISSUE THREAD

**Issue by rangasatishkumar** [cmv/cmv-app#507]
Is it possible to use a  "Custom TiledMapServiceLayer" as a Basemap?
Is it possible to show a  "Custom TiledMapServiceLayer" in BasemapGallery?

Please refer to the link below for a sample "Custom TiledMapServiceLayer"...
https://developers.arcgis.com/javascript/jssamples/layers_custom_tiled.html

**Comment by tmcgee** [comment]
@rangasatishkumar 

I suspect it might be possible since `ArcGISTileMapServiceLayer` and `WebTiledLayer` are both supported by the `BaseMapLayer` Class and both of those classes inherit from the `TiledMapServiceLayer` class.

Let us know if you get this to work.

**Comment by rangasatishkumar** [comment]
Hi Tim,

Thanks for your reply.

Point to be noted here is, "Custom TiledMapServiceLayer" won't have a URL
property pointed to map service. Where as BaseMapLayer expects URL property.

On Friday, 12 February 2016, Tim McGee <notifications@github.com> wrote:

> @rangasatishkumar <https://github.com/rangasatishkumar>
>
> I suspect it might be possible since ArcGISTileMapServiceLayer and
> WebTiledLayer are both supported by the BaseMapLayer Class and both of
> those classes inherit from the TiledMapServiceLayer class.
>
> Let us know if you get this to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmv/cmv-app/issues/507#issuecomment-183113594>.
>


-- 
Regards,
Ranga

**Comment by tmcgee** [comment]
@rangasatishkumar 

You can provide a url even a fake one. :)

The example has a hard-coded url in the `getTileUrl` method. That could be a passed into the constructor like the BasemapLayer expects so the method would look somethhing line this:
```
getTileUrl: function(level, row, col) {
    return this.url + 
    "L" + dojo.string.pad(level, 2, '0') + "/" +
    "R" + dojo.string.pad(row.toString(16), 8, '0') + "/" +
    "C" + dojo.string.pad(col.toString(16), 8, '0') + "." +
    "png";
}
```

The BasemapLayer Class also requires a type property. Looking at the ESRI code, only these layer types are explicitly supported by the BasemapGallery in addition to the ESRI types:

- OpenStreetMap
- Bing
- WebTiledLayer

Those 3 types are pretty much the same thing with the only major difference being the url scheme to retrieve the tiles.

Based on your description, this is sounding like perhaps you can use a `WebTiledLayer` layer with an override to the `getTileUrl` method similar to that above to construct a url matching the map cache tiles directory structure. Does that sound about right?

**Comment by tmcgee** [comment]
One important thing to note is that the spatial reference of your tiles will have to match the spatial reference of the map and the other basemaps. I mention this because the example you provided has a wkid of 4326.

**Comment by tmcgee** [comment]
@rangasatishkumar 

I did a quick test and what I was envisioning will not work without modifications to the ESRI `BasemapLayer` and `BasemapGallery` classes. A custom `getTileUrl` method in the configuration does not passed along. I made an assumption that your folder/file structure matches that in the example with all the level, column and rows (z,y and x) having numbers padded with zeros. 

If my assumption is incorrect and your structure does not have the padded zeros, a `WebTileLayer` with a simple url scheme like this: 

``` javascript
url: 'http://myserver/_alllayers/L${level}/R${row}/C${col}.png'
```
could work.

I really don't like the BasemapGallery Class for this and a few other limitations/bugs that have been noted over the years.

**Comment by rangasatishkumar** [comment]
@tim

Forgot to mention, my map cache tiles does not follow wkid 4326, which
means I cannot use WebTileLayer isn't it?

On Saturday, 13 February 2016, Tim McGee <notifications@github.com> wrote:

> @rangasatishkumar <https://github.com/rangasatishkumar>
>
> I did a quick test and what I was envisioning will not work without
> modifications to the ESRI BasemapLayer and BasemapGallery classes. A
> custom getTileUrl method in the configuration does not passed along. I
> made an assumption that your folder/file structure matches that in the
> example with all the level, column and rows (z,y and x) having numbers
> padded with zeros.
>
> If my assumption is incorrect and your structure does not have the padded
> zeros, a WebTileLayer with a simple url scheme like this:
>
> url: 'http://myserver/_alllayers/L${level}/R${row}/C${col}.png'
>
> could work.
>
> I really don't like the BasemapGallery Class for this and a few other
> limitations/bugs that have been noted over the years.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmv/cmv-app/issues/507#issuecomment-183457603>.
>


-- 
Regards,
Ranga

**Comment by tmcgee** [comment]
@rangasatishkumar for any tiles you want to use for a basemap, the spatial reference wkid must match the wkid of the map and the other basemaps. If you don't specify a spatial reference with a wkid for your map, it will use the wkid of the first layer loaded (typically the initial basemap)

WebTileLayers for basemaps or otherwise pretty much always have a WKID of 3857 (102100 in the ESRI world). Old ESRI basemaps that they retired a number of years ago did have a WKID of 4326. I believe the ESRI example you provided is using one of those old services.

Hope this helps.

**Comment by rangasatishkumar** [comment]
@tim

Whatever I provided earlier was just a sample. My basemap tiles are in wkid
3414.

On Sunday, 14 February 2016, Tim McGee <notifications@github.com> wrote:

> @rangasatishkumar <https://github.com/rangasatishkumar> for any tiles you
> want to use for a basemap, the spatial reference wkid must match the wkid
> of the map and the other basemaps. If you don't specify a spatial reference
> with a wkid for your map, it will use the wkid of the first layer loaded
> (typically the initial basemap)
>
> WebTileLayers for basemaps or otherwise pretty much always have a WKID of
> 3857 (102100 in the ESRI world). Old ESRI basemaps that they retired a
> number of years ago did have a WKID of 4326. I believe the ESRI example you
> provided is using one of those old services.
>
> Hope this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmv/cmv-app/issues/507#issuecomment-183746893>.
>


-- 
Regards,
Ranga
