### ISSUE TITLE
Layers description

### ISSUE THREAD

**Issue by Irina-Danilova** [cmv/cmv-app#508]
Thanks for a great application.
Is it possible to add a description for each layer in web-application? Metadata of a whole service is not enough, I need to put copyrights of each data-set in order to see it straight on a map. 
Thanks for a help in advance!
Ira

**Comment by tmcgee** [comment]
Hello @Irina-Danilova  Good to see you here! :) 

Does this contributed metadata dialog widget meet your needs?
https://github.com/roemhildtg/cmv-widgets#metadatadialog
https://github.com/roemhildtg/cmv-widgets/tree/master/widgets/MetadataDialog

**Comment by Irina-Danilova** [comment]
Thanks a lot for a respond! Yes Metadata Dialog will be enough to use :)

**Comment by tmcgee** [comment]
Great!
