### ISSUE TITLE
Can Custom Print Services Be Used for the Print Widget?

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-app#509]
In order to create custom print layout I had to publish a Print GP Service separate from the one that's included with ArcGIS Server, however, when using this other service, I cannot get any maps to save/print.  Does the Print widget require the Print service under Utilities or can custom print services be used?  i.e. Export Web Map Service over Export Web Map Task Service (under Utilities).

Thanks

Jesse

**Comment by DavidSpriggs** [comment]
Any print service can be used. Make sure you point it at the full URL to the service (see the default URL for an example). Check the network request and see if any errors are reported from the GP service. YOu can also try running the print task directly from the services directory and see what happens. Sounds like an error with the service. If you are trying to print secure services there is an extra step when publishing to allow this.

**Comment by kcarrier** [comment]
You might also have to setup a proxy in some cases, I recently ran into this when mashing up services from multiple sources and yes one was secure and that is why I had to configure a proxy.

**Comment by LarryStout** [comment]
I’ve never had to create a custom print service.  After you drag a new template into the folder, you have to restart the service for it to be recognized.

**Comment by JhopStl** [comment]
Thanks for the tips guys.  I've gotten the Print task to work, but only for default templates  It's odd, because even if I change the size of the template's data frame a little bit, that template will no longer work (e.g., trying to create an 8.5" x 14" template)  After testing, It seems to be the JSON that's being posted to the service that's causing it to fail.

**Comment by JhopStl** [comment]
Looks like it was an issue with permissions.  Got it working now.  Thanks!
