### ISSUE TITLE
Using fields from a related table in a popup template, that is formatted as an attribute list. 

### ISSUE THREAD

**Issue by dfralia** [cmv/cmv-app#510]
Hi all, 
I am new to using the CMV code, (and JS). I am trying to get related records to show up in an attribute list format. I am able to get the related records table to work properly, however the data shows up in tabs. I don't really want the tabs. I want the data to show up as it does here (with some different formatting though)
![untitled](https://cloud.githubusercontent.com/assets/13559288/13096247/195890a8-d4d5-11e5-92c1-8ac07d472e20.png)

I can only get the code to show the records from the main feature class, and not the table from the related table. I am using the code from the CMV documents. I can swap out the "formatters.attributeList" with "formatters.relationship" but that will put the related fields into tabs.

Any help on this is much appreciated! 

          `define([
    'dojo/dom-construct',
    'dojo/_base/lang',
    'dijit/layout/TabContainer',
    'dijit/layout/ContentPane',
       // 'widgets/roemhildtg/widgets/RelationshipTable/RelationshipTable'//path is relevent to wherever you placed the file
	'gis/dijit/RelationshipTable/RelationshipTable'
    ], function (domConstruct, lang, TabContainer, ContentPane, RelationshipTable) {
    var formatters = {
		 attributeList: 
			function (identifyInfo) {
            var listItem = '<li>{0}: {1}</li>';
            var html = ['<ul>'];
            for (var a in identifyInfo.attributes) {
                //make sure a is an own property
                if (identifyInfo.attributes.hasOwnProperty(a)) {
                    html.push(lang.replace(listItem, [a, identifyInfo.attributes[a]]));
                }
            }
            html.push('</ul>');
            return html.join('');
        },
			 
		
		 
		
        relationship: function (relationship) {
           return function (data) {
			   var content = new ContentPane({
				   style: 'height:300px; width: 100%'
				 
			   }, domConstruct.create('div'));
			   content.startup();
			   
			   
               content.addChild(new RelationshipTable(lang.mixin({
                   attributes: data.attributes,
                   title: 'Related Records',
                   style: 'width:100%;'
               }, relationship)));
               return content.domNode;
    };
		}
	};
    return {
        map: true,
        mapClickMode: true,
        mapRightClickMenu: true,
        identifyLayerInfos: true,
        identifyTolerance: 5,
        identifies: {
           LandManagement: {
							2: {
								title: 'BLM',
								content: formatters.attributeList`

**Comment by roemhildtg** [comment]
Please ask this question over here, since its related to the Related Records widget:https://github.com/roemhildtg/cmv-widgets/issues

It'll help others find it if they have similar questions.

**Comment by dfralia** [comment]
Ok Thanks! I will open up another ticket there. 
Sorry, new to Github and CMV. Wasn't sure where to post.

**Comment by roemhildtg** [comment]
No worries! You can close this one out. Issue moved here for future reference: https://github.com/roemhildtg/cmv-widgets/issues/21
