### ISSUE TITLE
Do you thyink its possible to put arrow right left in the cmv to navigate with arrow!

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#511]
Will be very useful for the Ipad

**Comment by tmcgee** [comment]
@GilbertLasnier I'm not sure I understand what you are asking. Can you please clarify your request?

**Comment by GilbertLasnier** [comment]
The arrow near the house button by the way take a look of http://gis.icao.int/SVGICAOMAP/ICAOREGWEBSECgil.html
[cid:image001.png@01D17303.8185F0F0]

**Comment by carrbrpoa** [comment]
Hey @GilbertLasnier,

Seems it is API's built-in. See http://forums.esri.com/Thread.asp?c=158&f=2396&t=276861.
I tested adding `nav: true` in map configuration and a call to `this.map.showPanArrows();` in Controller's `initMap` function.

Result (ok, some conflicting with existing stuff):

![pan](https://cloud.githubusercontent.com/assets/10212618/14083361/a28ab78a-f4eb-11e5-8139-7288d1fe92f1.png)

**Comment by roemhildtg** [comment]
This looks like it is resolved, if its not @GilbertLasnier feel free to reopen.
