### ISSUE TITLE
Do you think its possible to put the scale value when we are zooming?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#512]
Because its will be useful to understand the precision versus the real zoom scale max for some layer
example: when the people zoom on a country Boundary good for 1:3000000 and they zoom to 1:240 and ask where there is no match between the vector and the raster!!!

**Comment by tmcgee** [comment]
@GilbertLasnier The MapInfo widget can include the map's scale: https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/MapInfo.js#L32

**Comment by GilbertLasnier** [comment]
Thanks I try tomorow
