### ISSUE TITLE
I am still looking for thr drag and drop for KML files to you have a suggestion to start that tool?

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#514]

**Comment by tmcgee** [comment]
I think the Drag And Drop contributed widget would be a good place to start: https://github.com/BrianBunker/cmv-widgets/tree/master/DnD

**Comment by tmcgee** [comment]
@GilbertLasnier Last week, I contributed drag and drop for KML files to @BrianBunker's DnD widget that I had mentioned in my last comment here.

In that enhancement, dropping a file/url will add the layer to the layerControl widget and remove the layer from the widget when it is removed from the DnD widget. NOTE: This add/remove capability is not yet in the released version of cmv. It worn't break anything now. It will just magically work once that capability becomes available.

I am going to close this issue. Any additional comments about that functionality should be discussed in that Github repo.

**Comment by GilbertLasnier** [comment]
Thank for your effort 
i must succeed to have that functionality because i want to scrap the google earth link i use in an other program filemakerpro
You must close OK

**Comment by GilbertLasnier** [comment]
i  just see what you make for the KML in the BrianBunker's i try that tomorrow, Merci beaucoup its wonderful, the dream come true...

**Comment by GilbertLasnier** [comment]
Its work great...have a very good week! Bravo i bring your sample point in the map
