### ISSUE TITLE
How to make DomNode widget (Time Slider) drag-able?

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-app#518]
I'm sure this is partially do to me not fully understanding the differences between widget types (domNode, floating, TitlePane etc.), but is there a way to make a domNode widget move-able/drag-able? I've sorta combined both versions of the user- contributed Time Slider widget, and I'd like to be able to drag the panel around, but I'm struggling to do so.  I've even started to experiment with the Dojo/dnd/Moveable module.  

I've attached an image and code for a better understanding. (Note: The yellow arrow is point at the button that opens up the Time Slider widget.

Thanks,

Jesse
![timeslider](https://cloud.githubusercontent.com/assets/16945459/13445931/f7b7bf2c-dfd4-11e5-9e3e-5117395ec229.JPG)

`define([
    'dojo/_base/declare',
    'dijit/_WidgetBase',
    'dijit/_TemplatedMixin',
    'dijit/_WidgetsInTemplateMixin',
    'dojo/_base/lang',
    'dojo/dom-attr',
    'dojo/dom-construct',
	'dojo/_base/array',
    'esri/TimeExtent',
    'esri/dijit/TimeSlider',
    'dojo/text!./TimeSlider/templates/TimeSlider.html',
    'dojo/i18n!./TimeSlider/nls/resource',
    'xstyle/css!./TimeSlider/css/TimeSlider.css'
], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin, lang, domAttr,
             domConst, array, TimeExtent, TimeSlider, TimeSliderTemplate, i18n, css) {
    return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        widgetsInTemplate: true,
        templateString: TimeSliderTemplate,
        i18n: i18n, 
        timeExtent: null,
        timeSlider: null,
		timeInterval: 1,
		timeIntervalUnits: 'esriTimeUnitsYears',
        setToLabel: null,
        setTo: null,
        setFromLabel: null,
        setFrom: null,
        setButton: null,
		timeSliderEnableStyle: 'position:absolute;top:120px;left:90px;z-index:50;width:485px;display: inline;background-color:white;height:110px;padding-top:50px;padding-left:10px;padding-right:10px;box-shadow: -1px 1px 5px 2px rgba(143,137,143,0.4);border: 0.5px solid #B3B3B3; border-radius: 5px',
		setHeaderEnableStyle: 'position:absolute;left:110px;top:130px;z-index:50;width:485px;display:inline;height:20px;font-size:19px;font-weight:bold',
		setBorderEnableStyle: 'position:absolute;left:91px;top:130px;z-index:50;width:505px;display:inline;height:30px;border-bottom:1px solid #eee',
		setQualifiedEnableStyle: 'position:absolute;left:120px;top:240px;z-index:50;width:160px;display:inline;height:30px;font-size:12px',     //border-top:1px solid #eee
		setDisqualifiedEnableStyle: 'position:absolute;left:270px;top:240px;z-index:50;width:160px;display:inline;height:30px;font-size:12px',
		setPendingEnableStyle: 'position:absolute;left:440px;top:240px;z-index:50;width:160px;display:inline;height:30px;font-size:12px',
        disableStyle: 'display: none;',
        enable: false,
		
        postCreate: function () {
            this.timesliderbtn.title = this.i18n.timesliderbntTIP;

            this.timeSlider = new TimeSlider({
                style: 'width: 100%;'
            }, domConst.create('div', {}, this.map.id));
            domAttr.set(this.timeSlider.domNode, 'style', this.timeSliderDisableStyle);
		    	
			
			this.timeExtent = new TimeExtent();
			this.timeExtent.startTime = new Date("1/1/2007 UTC");
			this.timeExtent.endTime = new Date("12/31/2016 UTC");			
            this.timeSlider.setThumbCount(2);
			this.timeSlider.createTimeStopsByTimeInterval(
				this.timeExtent,
				this.timeInterval,
				this.timeIntervalUnits
			),
            this.timeSlider.setThumbIndexes([0,1]);
            this.timeSlider.setThumbMovingRate(1500);
			this.setHeader = domConst.create('div', {innerHTML: "Parcel Sales Tracker 2007-2016"}, this.map.id);
			this.setBorder = domConst.create('div', {}, this.map.id);
			this.setQualified = domConst.create('div', {innerHTML: '<img src="images/Qualified.png"> Qualified Sales'}, this.map.id);
			this.setDisqualified = domConst.create('div', {innerHTML: '<img src="images/Disqualified.png"> Disqualified Sales'}, this.map.id);
			this.setPending = domConst.create('div', {innerHTML: '<img src="images/Validation.png"> Validation Pending'}, this.map.id);
        },
		startup: function() {
			this.inherited(arguments);
			this.timeSlider.startup();
			this.setLabels();
		},
		setLabels: function() {
			//add labels for every other time stop
			var labels = array.map(this.timeSlider.timeStops, function(timeStop, i) { 
				if ( i % 2 === 0 ) {
					return timeStop.getUTCFullYear(); 
				} else {
					return "";
				}
			}); 
			this.timeSlider.setLabels(labels);

		},
        EnableTimeSlider: function () {
            if(!this.enable){
                this.map.setTimeSlider(this.timeSlider);
                domAttr.set(this.timeSlider.domNode, 'style', this.timeSliderEnableStyle);
				domAttr.set(this.setHeader, 'style', this.setHeaderEnableStyle);
				domAttr.set(this.setBorder, 'style', this.setBorderEnableStyle);
				domAttr.set(this.setQualified, 'style', this.setQualifiedEnableStyle);
				domAttr.set(this.setDisqualified, 'style', this.setDisqualifiedEnableStyle);
				domAttr.set(this.setPending, 'style', this.setPendingEnableStyle);
                this.enable = true;
                this.timesliderbtn.title = this.i18n.timesliderbntTIPdis;
            }
            else
            {
                var timeExtent = new TimeExtent();
                timeExtent.startTime = new Date('1/1/1990 UTC');
                var dt = new Date();
                dt.setDate(dt.getDate() + 1);
                timeExtent.endTime = dt;
                this.map.setTimeExtent(timeExtent);
                domAttr.set(this.timeSlider.domNode, 'style', this.disableStyle); 
				domAttr.set(this.setHeader, 'style', this.disableStyle);
				domAttr.set(this.setBorder, 'style', this.disableStyle);
				domAttr.set(this.setQualified, 'style', this.disableStyle);
				domAttr.set(this.setDisqualified, 'style', this.disableStyle);
				domAttr.set(this.setPending, 'style', this.disableStyle);
                this.enable = false;
                this.timesliderbtn.title = this.i18n.timesliderbntTIP;
            }
        },
        _setTimeSlider: function(){
            this.timeSlider.createTimeStopsByTimeInterval(this.timeExtent, 1, 'esriTimeUnitsYears');
            this.timeSlider.startup();

        }
    });
});`

**Comment by carrbrpoa** [comment]
Hey @JhopStl,

You just need to use `Moveable`, something like this:

```javascript
var dnd = new Moveable(this.timeSlider.domNode, { //What to drag
		handle : this.setFromLabel // The draggable point/handle
	});
```

The problem is that this widget is constructed directly over the map, with absolute positioning. To my example to work, it would need to be constructed in a way that every piece of it is constructed in a container div, not in the map.

**Comment by JhopStl** [comment]
Awesome.  I'll give this a try!

Thanks for the response.
