### ISSUE TITLE
Drill down identify with features

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#521]
Hello guys,

Consider these layers:

```javascript
{
	type : 'feature',
	url : '.../FeatureServer/0',
	title : 'CEU',
	options : {
		id : 'ceu0',
		opacity : 1.0,
		visible : true,
		outFields : ['*'],
		mode : 1,
		showLabels : true
	},
	identifyLayerInfos : {
		layerIds : [0]
	},
	layerControlLayerInfos : {
		swipe : true,
		metadataUrl : false,
		expanded : false
	}
}, {
	type : 'feature',
	url : '.../MapServer/1',
	title : 'Lotes',
	options : {
		id : 'lotes0',
		opacity : 0.5,
		visible : true,
		imageParameters : imageParameters,
		outFields : ['*'],
		mode : 1
	},
	identifyLayerInfos : {
		layerIds : [1]
	},
	layerControlLayerInfos : {
		swipe : true,
		metadataUrl : false,
		expanded : false
	}
}
```

Do you have any clue about why the "drill down" identify doesn't happen with them?
See:

![identify](https://cloud.githubusercontent.com/assets/10212618/13878838/c2efe3b6-ecf2-11e5-9d95-b8e25f7ff8c4.png)
The selected featured labeled *DM1* is on top of a *Lote* feature.

The Editor seems to be able to recognize that there are two features there:

![edit](https://cloud.githubusercontent.com/assets/10212618/13878865/e89bcecc-ecf2-11e5-9f1b-65aea55522aa.png)

Thanks in advance!

**Comment by tmcgee** [comment]
@carrbrpoa "drill-down" identify does not occur when you click on a graphic feature from a feature layer. The mouse click is intercepted by the top-most graphic on the map. This is a "feature" of the JavaScript API.

**Comment by carrbrpoa** [comment]
Thanks @tmcgee. By the way, do you have any ideas why when I click the feature label's, it identifies the feature behind it?

**Comment by tmcgee** [comment]
That is another "feature" of the API trying to help you out...
