### ISSUE TITLE
Help with Class breaks renderer -in Dyanamic Feature Layer Renderer on CMV

### ISSUE THREAD

**Issue by stillwolly2013** [cmv/cmv-app#523]
Has anyone implemented the following feature on 
https://developers.arcgis.com/javascript/jssamples/renderer_class_breaks.html

the one on the dynamic feature has collor ramps and i need to use custom colors instead of the Ramp

**Comment by roemhildtg** [comment]
@stillwolly2013 this example you linked isn't using a Dynamic layer, its actually of type `FeatureLayer`. Is that what you meant?

**Comment by stillwolly2013** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 2, 2016 at 6:44 AM, Gregg Roemhildt<notifications@github.com> wrote:   
@stillwolly2013 this example you linked isn't using a Dynamic layer, its actually of type FeatureLayer. Is that what you meant?

**Comment by roemhildtg** [comment]
@stillwolly2013 creating a custom widget to do this is fairly straightforward. You first need to create your feature layer in the operationalLayers section, but the rest is in a custom widget.

If you want the simplest approach:
```javascript
    renderer: {
        include: true,
        type: 'invisible',
        id: 'mouseover',
        path: 'dijit/_WidgetBase',
        options: {
            map: true,
            startup: function() {
        var symbol = new SimpleFillSymbol();
        symbol.setColor(new Color([150, 150, 150, 0.5]));

        // Add five breaks to the renderer.
        // If you have ESRI's ArcMap available, this can be a good way to determine break values.
        // You can also copy the RGB values from the color schemes ArcMap applies, or use colors
        // from a site like www.colorbrewer.org
        //
        // alternatively, ArcGIS Server's generate renderer task could be used
        var renderer = new ClassBreaksRenderer(symbol, "POP07_SQMI");
        renderer.addBreak(0, 25, new SimpleFillSymbol().setColor(new Color([56, 168, 0, 0.5])));
        renderer.addBreak(25, 75, new SimpleFillSymbol().setColor(new Color([139, 209, 0, 0.5])));
        renderer.addBreak(75, 175, new SimpleFillSymbol().setColor(new Color([255, 255, 0, 0.5])));
        renderer.addBreak(175, 400, new SimpleFillSymbol().setColor(new Color([255, 128, 0, 0.5])));
        renderer.addBreak(400, Infinity, new SimpleFillSymbol().setColor(new Color([255, 0, 0, 0.5])));

                var layer = this.map.getLayer('layer-id');

                layer.setRenderer(renderer);
            }
        }
    }
```
You also need to add the required classes to your define block in the header section of viewer.js.
