### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#527]
Hello,

Have you ever tried rotate the map, automagically by user's location or just dragging the map? Accordingly to [this link](https://developers.arcgis.com/javascript/beta/sample-code/widgets-compass-2d/index.html), a Compass widget will be added to API 4.0 ([demo here](https://developers.arcgis.com/javascript/beta/sample-code/widgets-compass-2d/live/index.html)), but did you guys built something with the current version?

Thanks!

**Comment by tmcgee** [comment]
@carrbrpoa Not sure what is possible today. We already have support for the compass widget from the 4.0 API (both 2D and 3D) working in a not yet released version of CMV. That pre-release will be available publicly for testing before the release of the ESRI 4.0 API.

**Comment by carrbrpoa** [comment]
Great!
Which is the branch?

**Comment by tmcgee** [comment]
@carrbrpoa It is in a separate repo that is not yet on GitHub.

**Comment by carrbrpoa** [comment]
:100:
