### ISSUE TITLE
Invoking another widget

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#528]
Hey guys,

Is it possible to invoke an already instantiated widget from another one, without the use of `topic` stuff? For example, I would like to call Geocoder's `reverseGeocode` function from my custom widget/utility class.

**Comment by tmcgee** [comment]
You can always use the dojo [dijit/registry](https://dojotoolkit.org/reference-guide/1.10/dijit/registry.html) to get the widget by its id. Then call the function directly.

We typically use topic so as not to make too many dependencies/assumptions about what other widgets are available in the app. The above method certainly works as well.

**Comment by carrbrpoa** [comment]
Nice. Never used `registry`before, but I prefer the first option, since I do not wish to write custom code to a widget that is CMV's built-in.
