### ISSUE TITLE
canFloat: true; IE cursor will not release the widget.  

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-app#529]
IE will not allow the cursor to release the widget.  The functionality works as designed in Firefox.  Is anyone else having this issue?

**Comment by tmcgee** [comment]
This has been identified previously in issue #379 It was fixed and then broke again. In that issue, you'll see that I have a new "fix" for it that I hope to provide in a PR very soon.

I'm going to close this issue as progress is tracked in the original one.
