### ISSUE TITLE
Placing a graphic on geocode location

### ISSUE THREAD

**Issue by gregoryaroberts1** [cmv/cmv-app#53]
Hello,
I have been attempting to place a temporary graphic on the geocode result after an address has been searched but I haven't had much luck thus far. Would it be possible to do this in the Controller or would a new custom geocode widget have to be created to accomplish this?

Thank you for your help.
Gregory Roberts

**Comment by friendde** [comment]
I updated the gist linked above. Sorry it took 2 years, but I was busy ;>)
