### ISSUE TITLE
Programatic InfoWindow

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#532]
Hello,

I'm trying to display InfoWindow from some GraphicLayer's click and it just blinks, instead of stay fixed in the page. My code:

```javascript
graphicsLayerFinish.on('click', this.handleGraphicsFinishClick);
graphicFinish = new Graphic(lastPnt, symbolFinish, {Number: 80}, infoTemplate); // Number: 80 is just a test
graphicsLayerFinish.add(graphicFinish);

(...)

handleGraphicsFinishClick : function (evt) {
	var graphic = evt.graphic;
	window.map.infoWindow.clearFeatures();
	window.map.infoWindow.setTitle('Rota sugerida');
	window.map.infoWindow.setContent(graphic.getContent());

	window.map.infoWindow.setFeatures([graphic]);

	var screenPnt = window.map.toScreen(evt.mapPoint);
	window.map.infoWindow.show(screenPnt, window.map.getInfoWindowAnchor(screenPnt));
}
```

Any ideas?

Thanks in advance

**Comment by carrbrpoa** [comment]
Guess I found out guys: seems that the problem is that my click is also being handled by Identify widget, because I didn't handle `mapClickMode` accordingly.
I'll fix it and give feedback here.

**Comment by carrbrpoa** [comment]
I have handled `mapClickMode` so now it doesn't conflicts with Identify widget.

**Comment by ERS-Long** [comment]
Hi, @carrbrpoa:

Could you please share how did you handle the mapclickMode. I am trying to do a similar thing, would like to see your method if possible. 

I want to do attachmentEditor tool, but there i need to handle the featurelayer click event, i dont know how to make the default map click and this feature layer click work together.

Here is the ESRI example i try to using in CMV

https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=ed_attachments


Thanks a lot!

**Comment by ERS-Long** [comment]
hi, @carrbrpoa:

Figured it out. Never mind.

Thanks!
