### ISSUE TITLE
point remains on the map when apply geocoder

### ISSUE THREAD

**Issue by rkoch19** [cmv/cmv-app#539]
Hello, to geocoding an address or coordinate I need the graphical point that was generated remains static in the application, ie I geocoding an address and a point is placed on the map when I geocoding another address another point is placed on the map but the previous point remains on the map and so on ...

**Comment by ERS-Long** [comment]
you can comment out the following line in Geocoder.js  

line 134
            on.once(this.map.infoWindow, 'hide', lang.hitch(this, function () {
                //this.graphics.clear();
            }));

Then use the menu right click on the map to do the geocode, then all the points stay

**Comment by tmcgee** [comment]
for clarity, using the menu from right-clicking the map does a reverse geocode, not a geocode.

Keeping all the points returned from the geocoder widget may leave "undesirable" points on the map from bad geocodes, selecting the wrong choice from the list, etc. I think a separate widget is best with an interface to manage the collected points. The points can come from the geocoding widget if desired.

And an additional fyi: The Esri Geocoder widget is deprecated and has been replaced by their search widget. Thus I would not invest too much time using the geocoder widget.

**Comment by rkoch19** [comment]
Thanks a lot!

Renato

2016-04-18 14:14 GMT-03:00 Tim McGee <notifications@github.com>:

> for clarity, using the menu from right-clicking the map does a reverse
> geocode, not a geocode.
>
> Keeping all the points returned from the geocoder widget may leave
> "undesirable" points on the map from bad geocodes, selecting the wrong
> choice from the list, etc. I think a separate widget is best with an
> interface to manage the collected points. The points can come from the
> geocoding widget if desired.
>
> And an additional fyi: The Esri Geocoder widget is deprecated and has been
> replaced by their search widget. Thus I would not invest too much time
> using the geocoder widget.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmv/cmv-app/issues/539#issuecomment-211481298>
>



-- 
Renato Koch Murakami

**Comment by roemhildtg** [comment]
This issue looks resolved @rkoch19 if its not, feel free to reopen
