### ISSUE TITLE
hidden geocoder

### ISSUE THREAD

**Issue by rkoch19** [cmv/cmv-app#540]
Hi,

The geocoder tool is not showing up for me ... any ideas?

In the configuration file is enabled to appear ... but does not appear

Thanks

Renato

**Comment by tmcgee** [comment]
@rkoch19 please provide your config for the geocoder widget. Don't need the whole viewer.js, just the config for that widget.

**Comment by rkoch19** [comment]
Ok thanks.

2016-04-18 14:15 GMT-03:00 Tim McGee <notifications@github.com>:

> @rkoch19 <https://github.com/rkoch19> please provide your config for the
> geocoder widget. Don't need the whole viewer.js, just the config for that
> widget.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmv/cmv-app/issues/540#issuecomment-211481555>
>



-- 
Renato Koch Murakami
