### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by rkoch19** [cmv/cmv-app#541]
Hi
I need to create profiles, or according to a user logs on certain layers appear to him, another user other layers, so on...

Thanks
Renato

**Comment by tmcgee** [comment]
@rkoch19 This is best addressed on the server in my opinion. More secure that way. I know that several developers have done this successfully on the server using php and dotNet. I don't have any examples myself. There might be some references in prior issues here.

**Comment by rkoch19** [comment]
OK thanks.
