### ISSUE TITLE
research

### ISSUE THREAD

**Issue by rkoch19** [cmv/cmv-app#544]
Hi
In research as I do to make a where clause, for example I want to look for a concatenated field with other
Thanks
Renato

**Comment by tmcgee** [comment]
Is this a question related to the core cmv project or perhaps a widget such as my [search and attributestables widget](https://github.com/tmcgee/cmv-widgets)? If it related to core CMV, please clarify your question here. If it is for my widget, please ask the question over in that repo. Thanks.

**Comment by rkoch19** [comment]
Hi

is the core of cmv, research I can search for specific fields [field1],[field2],[field3]..., but if I want a search that need to concatenate two fields how to do? [field1 AND field2] or [field1 & field2]

Thanks
Renato

**Comment by tmcgee** [comment]
So I think you mean the find widget? That widget uses the [FindTask](https://developers.arcgis.com/javascript/jsapi/findtask-amd.html) which can look for one term across multiple layers and multiple fields as you show.

You may want to look into using the [QueryTask](https://developers.arcgis.com/javascript/jsapi/querytask-amd.html) which can look for multiple terms in multiple fields (but only one layer) as you desire

My Search widget supports both the FindTask and the QueryTask in a single widget. There are [other contributed CMV widgets](https://github.com/cmv/cmv-contrib-widgets) that use QueryTask as well.

**Comment by rkoch19** [comment]
Hello!

excellent this widget as I do to disable the tabs that will not use? disabling the spatial selection tab for address ...

Thanks

Renato

**Comment by tmcgee** [comment]
You can exclude the tab by adding this to your configuration:
```
hiddenTabs: [1]
```
https://github.com/tmcgee/cmv-widgets/blob/master/widgets/Search.js#L115-L120

**Comment by rkoch19** [comment]
Fantastic, thanks
