### ISSUE TITLE
MapServer

### ISSUE THREAD

**Issue by rkoch19** [cmv/cmv-app#546]
Hi
Within a mapserver there are several layers, I wanted one of these layers did not show up, I wanted to hide one of these layers, is it possible to mapserver?

ie:

this a mapserver
http://localhost/arcgis/rest/services/SIGAS/SIGAS/MapServer

I want hide one layer from this map server
http://localhost/arcgis/rest/services/SIGAS/SIGAS/MapServer/2

The layer 2 don´t show. 

Thanks
Renato

**Comment by roemhildtg** [comment]
@rkoch19 You'll need to post the code that you are using to configure the layers in order for someone to help. The best place for this type of question is on StackOverflow.com with the tag `cmv` since it will probably have a more broad audience.
