### ISSUE TITLE
Streetview widget moves after maximize

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#550]
The new streetview widget lets you maximize to full screen (which is awesome). 

But if you move the streetview widget somewhere via the drag mechanism, once you escape from the full screen, the widget moves to the top of the sidebar on top of the other widgets. 

This happens in Chrome  49.0.2623.112

**Comment by tmcgee** [comment]
For clarity, the full screen maximize button is not a new addition to cmv. It is part of Google StreetView API and has been there for some time. I don't know when they add it. You can see the same behavior in the [demo](http://demo.cmv.io/viewer/).

**Comment by roemhildtg** [comment]
@tmcgee that is what I had assumed. It is a great addition, and personally, I wouldn't consider it a major issue, just something to save for a rainy day.

**Comment by roemhildtg** [comment]
Can't reproduce anymore..closing
