### ISSUE TITLE
Bookmark "Tried to register widget with id==bookmarks_widget but that id is already registered"

### ISSUE THREAD

**Issue by Tozievski** [cmv/cmv-app#551]
Hi.Im working on CMV template and i hit an isue.I load bookmark correctly the bookmark drop an error

"Tried to register widget with id==bookmarks_widget but that id is already registered"

![image](https://cloud.githubusercontent.com/assets/12472609/14881391/03fd5aee-0d34-11e6-8044-549241677c14.png)

Regards!!!

**Comment by tmcgee** [comment]
@Tozievski Are you using version 3.16 of the Esri JavaScript API? The Esri bookmark widget included with that version introduced this issue. You can either switch to an older version of the API or use CMV in the develop branch. A change to CMV to work around the API change is in that branch. Let us know if that solves it for you.

**Comment by Tozievski** [comment]
@tmcgee i was ussing 3.16 and i changed to 3.15 and now works correctly.I will test the other widgets to see if there is some changes there.
Regards.

**Comment by carrbrpoa** [comment]
Hey @tmcgee,

We have the same problem here, but: we can't change to `develop` branch due to changes we already made over CMV 1.3.4 nor downgrade the Esri JavaScript API (due to the Chrome's `Export` problem).
Do you know any workaround for that?

Thanks!

**Comment by roemhildtg** [comment]
@carrbrpoa you just need to change this in the `gis/dijit/Bookmarks` widget:

 https://github.com/cmv/cmv-app/commit/edfac16cb9fba5e8e283f58c36d1787fd0194bb2

**Comment by tmcgee** [comment]
@carrbrpoa Esri has addressed the issue that affected the Chrome Export in version 3.18 or later of the JavaScript API. I don't know of a work-around for older versions of the API.

**Comment by carrbrpoa** [comment]
Thanks guys, @roemhildtg workaround worked! 👍
