### ISSUE TITLE
Print error

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#554]
Hi, @tmcgee and everyone:

I am experiencing a print error whenever i try to print a map that is generating from using this ESRI library

https://developers.arcgis.com/rest/elevation/api-reference/trace-downstream.htm

We have a server proxy in there we set the ArcGIS online login stuff for this the above tool. It generates the map with the spill path image ok, and it does show on the map. The issue is when we try to print that map to a pdf, then we get the print error.

Please let me if you guys know the resolution for this. 

Thanks!

**Comment by tmcgee** [comment]
@ERS-Long what is the print error?

**Comment by ERS-Long** [comment]
@tmcgee After i switched to the ESRI example print service, it prints just fine. I guess the issue is our customized print service. Thanks a lot. We can close this issue.
