### ISSUE TITLE
Export data in XML Format

### ISSUE THREAD

**Issue by biljanaManeva** [cmv/cmv-app#556]
Is this possible to export attribute table to XML?

Thanks.

**Comment by roemhildtg** [comment]
I don't think it supports xml, but here's a workaround, You can export it to an Excel spreadsheet, and in Excel, you can Save as... `(*.xml)` to get an xml file.

**Comment by tmcgee** [comment]
@biljanaManeva The response by @roemhildtg is correct. My search widget does not currently have an XML export capability. The `Save as` option in Excel is a decent alternative.

I am going to close this issue as questions about a contributed widget such as this should be addressed in the [repo for the widget](https://github.com/tmcgee/cmv-widgets/issues).
