### ISSUE TITLE
Tried to register widget with id==layerControl_parent but that id is already registered

### ISSUE THREAD

**Issue by m0n1que** [cmv/cmv-app#558]
I'm using CMV and I've connected the CMV with a user management system, so I can control visible layers for my users. I have a problem every time user is logged in and the CMV is reloaded with the data for a user I'm getting error that laerControl_parent is registered and no of the layers are showed.

**Comment by tmcgee** [comment]
@m0n1que Hard to know exactly what is going on in your custom code. As a first hunch, it sounds like the user-specific configuration you are building based on their privileges is not valid.
