### ISSUE TITLE
Customising basemap

### ISSUE THREAD

**Issue by deepal13** [cmv/cmv-app#560]
Hello,

I want to show thumbnail images in basemap. I added thumbnailurl but it's not working. Can you please help.

Thanks

**Comment by tmcgee** [comment]
@deepal13 Are you asking about the basemap widget within CMV? It currently does not use thumbnails, only the text list of basemap options defined in basemaps.js

**Comment by deepal13** [comment]
Yes, basemap widget within CMV. Is there any way I can get the thumbnails working?
Thanks

**Comment by tmcgee** [comment]
You might want to try the [Esri Basemap Gallery](https://developers.arcgis.com/javascript/3/jssamples/widget_basemap.html) widget or the [Esri Basemap Toggle](https://developers.arcgis.com/javascript/3/jssamples/widget_toggle.html) widget. 

I believe some folks have used both of those widget with CMV. I have not..

**Comment by deepal13** [comment]
@tmcgee The error is fixed. 
I came across this demo http://tmcgee.github.io/cmv-widgets/demo.html?config=basemapToggle. Can you please give me the link to the code for this example.

Thanks.

**Comment by tmcgee** [comment]
@deepal13 The name of the configuration file that contains the basemap gallery widget is in the url you provided. You can find it within my repo [here](https://github.com/tmcgee/cmv-widgets/blob/master/config/basemapToggle.js). I had forgotten that example configuration file was there.

**Comment by deepal13** [comment]
That was really helpful. Just one more help, if you can guide me how to add custom basemaps to Basemap Gallery. i set showArcGISBasemaps:false, basemaps: same basemap as in custom basemap (config/basemap.js). But this doesn't seem to work. If you can guide me that will be helpful.

**Comment by deepal13** [comment]
@tmcgee I have tried this link: http://www.gitterforum.com/discussion/cmv-cmv-app?page=69 but it doesn't seem to work. I want custom basemaps using Basemap Gallery. Your help will be appreciated.

**Comment by adityakumar529** [comment]
I am using Basemap widget and facing same problem.There is no thumbnail associated. Can,t we directly use BasemapGallery widget in CMV?

**Comment by tmcgee** [comment]
@adityakumar529 Yes, CMV includes the Basemap Gallery [widget](https://github.com/cmv/cmv-app#widgets-included).

**Comment by adityakumar529** [comment]
I am trying to call it in the viewer.js page but its not coming. Any suggestions will be helpful.

**Comment by tmcgee** [comment]
@adityakumar529 Please include your widget configuration from viewer.js here.
