### ISSUE TITLE
Feature layer displays on the top of the TOC

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-app#562]
I have a feature layer that wants to override the order of the layers in the viewer.js file and move to the top of the TOC.  I am using feature and dynamic.  I want it to display as layer 7 instead of 1.  Can I invoke an ordering of the layers?

**Comment by tmcgee** [comment]
@cmccullough2 All feature layers all always on top of dynamic layers. This is something built into the Esri JavaScript API and cannot be changed without a great deal of customization.
