### ISSUE TITLE
Security & Loading

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#567]
Hello guys!

I have the following scenario: one of my services is secured. The user can just cancel the login so normally it can continue using the application, expect that it can't interact with that particular service. OK. I load an util script that handles 'ready` event to do some stuff like creating a new right click menu option. The problem is that when the user cancel the login, seems that this util is broken and I don't see my new menu item.

Do you have any ideas?

Thanks in advance!

**Comment by tmcgee** [comment]
@carrbrpoa I probably need to understand the workflow better. When you say "util is broken" are you saying that util script never loads because the "ready" event doesn't fire?

**Comment by carrbrpoa** [comment]
Hey Tim!

The script is there, I can see it under Sources tab in Chrome's F12; but yes, "ready" doesn't fire when I cancel the login. My util is actually an "invisible singleton and reusable widget" that doesn't inherit from `widgetBase`, referenced in Search Widget's config and in another custom and "normal" widget. :)

**Comment by tmcgee** [comment]
@carrbrpoa Did you get this resolved?

**Comment by tmcgee** [comment]
@carrbrpoa Did you get this resolved?

**Comment by tmcgee** [comment]
@carrbrpoa Did you get this resolved?

**Comment by carrbrpoa** [comment]
Hello @tmcgee, sorry for the long delay. Actually I "solved" this problem implementing the auth mechanism in another way. I suppose it can be closed. Thanks!
