### ISSUE TITLE
Is the directions network service allowed?

### ISSUE THREAD

**Issue by Jfairfield1** [cmv/cmv-app#569]
Does Esri allow the use of http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Network/USA/NAServer/Route
as the network service for use in the directions widget?
It looks like they charge credits for hosting your own service.
https://developers.arcgis.com/features/directions/

**Comment by tmcgee** [comment]
@Jfairfield1 As with all of the services in the CMV example application, that network service is just a sample. That service says "This is a sample service hosted by ESRI, powered by ArcGIS Server. ESRI reserves the right to change or remove this service at any time and without notice." ESRI has additional services hosted at arcgisonline that do require credits.

ESRI does not charge credits if you host your own service. From your second link: "Users can license a ready-to-use transportation network with the StreetMap Premium data product or build their own transportation network using ArcGIS Desktop."
