### ISSUE TITLE
Change Widget Title according to your locale

### ISSUE THREAD

**Issue by saurabhgis** [cmv/cmv-app#574]
I am working on multilingual web site, please tell me how to change widget title from nls(resource.js)

**Comment by iled** [comment]
The [develop branch](https://github.com/cmv/cmv-app/tree/develop) already has a complete translation to Portuguese (pt-pt). You can use that as an example on how to translate to other languages.

Widget titles are defined in [config/nls](https://github.com/cmv/cmv-app/tree/develop/viewer/js/config/nls). Make a copy of the `pt-pt` folder, rename it to your [language tag](https://en.wikipedia.org/wiki/IETF_language_tag), and then edit the files, replacing the strings.

The English version is in [main.js](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/nls/main.js), but you shouldn't edit the strings there. Use the English strings as a guide. Finally, add a line below [this one](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/nls/main.js#L65), again, with `'your-language-tag': true`.
