### ISSUE TITLE
All, We have required to display user role based map for example: I am district xyz user, can view only xyz map, edit on xyz area. please suggest me

### ISSUE THREAD

**Issue by saurabhgis** [cmv/cmv-app#576]
All, We have required to display user role based map for example: I am district xyz user, can view only xyz map, edit on xyz area. please suggest me

**Comment by carrbrpoa** [comment]
@saurabhgis, one approach we use here is to consider the publishing of two services: one for read only purposes and MapServer only and another editable (with Feature Access enabled - to enable the use with Editor Widget) and then protect the editable one in ArcGIS Manager or Portal.

When the user enters the application, it will detect that some service is protected and ask for login; if the user inform a login that is associated with the protection we applied in that service, so it will be able to interact with it; if not, everything except that service(s) will work normally.

**Comment by tmcgee** [comment]
@saurabhgis The approach that @carrbrpoa mentions is a common practice I have implemented for my clients as well for editing.

**Comment by roemhildtg** [comment]
@saurabhgis this looks like it is resolved, but feel free to reopen if it is not.
