### ISSUE TITLE
How to create onclick event in config/identify.js

### ISSUE THREAD

**Issue by agrub** [cmv/cmv-app#578]
I am probably missing something very easy, but I have been stuck for days now.  I am trying to define an onclick event on a button.  I would like the onclick to call a function that uses one of the attribute values as a parameter, which is an email address.   If I try to escape the quotes around {email}, with \' or \&#39 or \x022 or &apos, I get an unterminated string literal error, and if I dont use quotes I get an unexpected character at the @ sign.  

Anyone know of a way I can accomplish this?

`0: {
  title: 'Here is my title',
  description: '<button onclick="sendEmail({email})">Send Email</button>'
}`

**Comment by roemhildtg** [comment]
Hello and welcome :) 

The popup syntax for variable substitution is actually `${email}` (note the $). [The esri api docs describe this](https://developers.arcgis.com/javascript/3/jsapi/infotemplate-amd.html)

To trigger the function on click, you could define a global function. Dojo and the AMD module format highly discourages this but the quick and dirty is *somewhere* in your code (probably in your viewer.js https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L8) you might do 

```javascript
window.sendEmail = function(email){ /* code to send email here */ };
```

**Comment by roemhildtg** [comment]
The *better* approach might be to write a SendEmail widget, that that inherits from a button, and import that into your identify.js, and use it in the template via

```html
<div data-dojo-type="gis/dijit/SendEmail" />
```

**Comment by agrub** [comment]
Not sure why but all my substitutions work without the $.  If I use it like described the $ is displayed on screen.  
I get how to call the function, I can call it with no parameters.  The issue is the 3rd level of quotes to send the parameter as a string.  Escaping does not work.

I like the idea of creating a widget, I will look into this.

Thank you.

**Comment by roemhildtg** [comment]
Oh, I must have misunderstood. What about this?
```javascript
0: { 
title: 'Here is my title', 
description: "<button onclick=\"sendEmail('{email}')\">Send Email</button>"
}
```

**Comment by agrub** [comment]
I still get an unterminated string literal error pointing to the first quote around {email}.

**Comment by roemhildtg** [comment]
This works for me. I have an id field called `cid`. 

```javascript
define([

], function() {
    window.sendEmail= function(id){
      alert(id);
    }
    return {
        map: true,
        mapClickMode: true,
        mapRightClickMenu: true,
        identifyLayerInfos: true,
        identifyTolerance: 5,

        // config object definition:
        //  {<layer id>:{
        //      <sub layer number>:{
        //          <pop-up definition, see link below>
        //          }
        //      },
        //  <layer id>:{
        //      <sub layer number>:{
        //          <pop-up definition, see link below>
        //          }
        //      }
        //  }

        // for details on pop-up definition see: https://developers.arcgis.com/javascript/jshelp/intro_popuptemplate.html

        identifies: {
            stmPipe: {
                4: {
                    title: 'Here is my title',
                    description: "<button onclick=\"sendEmail('{cid}')\">Send Email</button>"
                }
            }
        }
    };
});
```

**Comment by agrub** [comment]
Thank you very much for your time.  You have helped me solve my issue.  My issue ended up being the field I was storing my email address in was also storing a carriage return.  After removing that, it works as expected.

**Comment by roemhildtg** [comment]
Ah, I see. I'm surprised that would cause the issue.
