### ISSUE TITLE
Filter widget

### ISSUE THREAD

**Issue by ctropasso** [cmv/cmv-app#582]
Is anyone currently building a filter widget or would you be willing to share code for filtering where features from a rest service can be configured to be filtered by the user and then the app only displays the filtered data in the map?

**Comment by carrbrpoa** [comment]
Hey @ctropasso, isn't the [Search Widget](https://github.com/tmcgee/cmv-widgets#search) what you are looking for?

**Comment by roemhildtg** [comment]
I think he means a widget to set a definition query on a layer. Something that would set call the `setLayerDefinitions` on a layer: https://developers.arcgis.com/javascript/3/jsapi/arcgisdynamicmapservicelayer-amd.html

**Comment by Wernazuma** [comment]
@ctropasso Any progress on this? That sounds like a very interesting thing to have to create actual customized maps via the app!

**Comment by carrbrpoa** [comment]
To filter stuff in some dynamic layer being displayed, I did something like this in a manual and specific way:
In `config/viewer.js`, I declared a `buildImageParameters` function to set `layerDefinitions` in a layer which has 9 sublayers and a field called `ZONAL`:

```javascript
function buildImageParameters(config) {
	var ip = new ImageParameters();
	for (var key in config) {
		if (config.hasOwnProperty(key)) {
			ip[key] = config[key];
		}
	}
	
	...
	
	for (var i = 0; i < 9; i++) {
		ip['layerDefinitions'][i] = 'ZONAL = \'' + [MY WHERE CLAUSE] + '\'';
	}

	return ip;
}
```

Then in `operationalLayer`'s configuration:

```javascript
{
	type : 'dynamic',
	url : servidorArcgis + '/arcgis/rest/services/STUFF/MY_FEATURE_CLASS/MapServer',
	title : 'My Feature Class',
	options : {
		id : 'idClass',
		opacity : 1.0,
		visible : true,
		imageParameters : buildImageParameters({
			format : 'png'
		})
	},
	identifyLayerInfos : {
	},
	layerControlLayerInfos : {
		swipe : true,
		metadataUrl : false,
		expanded : false
	}
}
```

**Comment by roemhildtg** [comment]
@ctropasso I added a basic filter widget to my repo...its currently use at your own risk without much for documentation but its a start. 

https://github.com/roemhildtg/cmv-widgets/blob/master/widgets/Filter.js

**Comment by ERS-Long** [comment]
@roemhildtg could you please provide a sample config setting for this widget? Thanks.

**Comment by roemhildtg** [comment]
Its basically just title pane type, with `map: true`

**Comment by ERS-Long** [comment]
Thanks. I dont know what was the issue, after I added that option, then I got the following error

Uncaught TypeError: Cannot read property 'filter' of undefined
    at http://wsdtxmal/CMV696/widgets/filter.js:86:39

Please see if you have the solution for this error.

Thanks again!

**Comment by roemhildtg** [comment]
Not sure, what does your `widgets/filter.js` look like? is that a config?

**Comment by roemhildtg** [comment]
Ah, maybe you're using an old browser? This widget might not be compatible with old ie versions...filter was added to arrays in ie9

**Comment by tmcgee** [comment]
If filter is the problem, iyou should be able to address it by using dojo's `array.filter`.

**Comment by ERS-Long** [comment]
The error is from this line in the widget code, happened on both IE and Chrome.

                    l.layer.layerInfos.filter(function (sub) {

Error Msg is  Uncaught TypeError: Cannot read property 'filter' of undefined

Is there other setting I need to set? Not urgent, please let me know if you have something. 

Thanks

**Comment by roemhildtg** [comment]
@ERS-Long just added a check that should fix it.

**Comment by ERS-Long** [comment]
Yes, that is it. Thanks!
