### ISSUE TITLE
Printing Error (Service using proxy)

### ISSUE THREAD

**Issue by deepal13** [cmv/cmv-app#583]
I am having trouble with printing. When I am using a secure service with proxy setup, the print fails giving error.
error Error: Unable to complete operation.
at Error (native)
at Object.g.load (https://js.arcgis.com/3.17compact/init.js:663:426)
at https://js.arcgis.com/3.17compact/init.js:87:450
at c (https://js.arcgis.com/3.17compact/init.js:103:393)
at d (https://js.arcgis.com/3.17compact/init.js:103:182)
at resolve.callback (https://js.arcgis.com/3.17compact/init.js:105:10)
at c (https://js.arcgis.com/3.17compact/init.js:104:96)
at d (https://js.arcgis.com/3.17compact/init.js:103:182)
at resolve.callback (https://js.arcgis.com/3.17compact/init.js:105:10)
at https://js.arcgis.com/3.17compact/init.js:92:118

Thanks

**Comment by roemhildtg** [comment]
You'll have to look into your ArcGIS server logs. They'll give you a hint as to what is going on.

The best place for this question might be on the GeoNet forum. You'll get responses from Esri folks that might have more experience with secure print services behind a proxy.

**Comment by ehajek** [comment]
You may have to publish a print service with the authentication you're doing with the proxy built in. 

First setup and run Export Web Map from the ArcGIS Toolbox -> ServerTools -> Printing area. 
Then open the Results window and right click on the Export Web Map that just completed, then select Edit. You'll be able to add an ArcGIS Server connection to it. 

Then you can right click, and Share as Service to get it hosted. That print service will connect to your server with the credentials you entered, which should allow it to access the services like your proxy allows the map to access the services.

**Comment by deepal13** [comment]
I will try this. Thanks for your help.

**Comment by NTTA-Tarig** [comment]
Great App. love it. 
Is there any documentation on how to add our own Google API key?

Thanks

Sent from Tarig iPhone


-- 
DISCLAIMER: http://www.cityoflewisville.com/index.aspx?page=905

**Comment by roemhildtg** [comment]
@NTTA-Tarig This really isn't related to the issue, I think the gitter chat room should be used for this.
