### ISSUE TITLE
Adding individual layers

### ISSUE THREAD

**Issue by deepal13** [cmv/cmv-app#585]
@tmcgee  I want to add individual layers in operationLayers instead of complete service but it fails. But when I add the layer using Drag-n-Drop widget (https://github.com/BrianBunker/cmv-widgets), it works fine.

Can you please help?
Thanks

**Comment by tmcgee** [comment]
Sounds like you want to add individual `feature` layers.

**Comment by deepal13** [comment]
@tmcgee Yes, like,: http://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/guidance_model_ocean_grtofs_offsets/MapServer/5

**Comment by deepal13** [comment]
@tmcgee Is there any way I can add the individual layers?

**Comment by tmcgee** [comment]
@deepal13 sounds like what you want in this case is to add the map service as a dynamic but only display the single sub layer. This operational layer config will display only the one sub layer you referenced:

``` javascript
{
    type: 'dynamic',
    url: 'http://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/guidance_model_ocean_grtofs_offsets/MapServer',
    title: 'NOAA 1',
    options: {
        id: 'noaa1',
        opacity: 1.0,
        visible: true,
        imageParameters: buildImageParameters({
            layerIds: [1],
            layerOption: 'show'
        })
    },
    layerControlLayerInfos: {
        sublayers: false,
        noLegend: true
    }
}
```

![image](https://cloud.githubusercontent.com/assets/200780/17683885/a864359e-630b-11e6-9bbb-73743a9f894e.png)

**Comment by deepal13** [comment]
@tmcgee ..This is helpful. Is there a way I can get legends too, below each layer? Also, the legend widget shows no legends.

**Comment by tmcgee** [comment]
No, because that sub layer has no legend available: http://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/guidance_model_ocean_grtofs_offsets/MapServer/legend

**Comment by deepal13** [comment]
@tmcgee Ok. I really appreciate your help. Thank you.
