### ISSUE TITLE
Editing after spatial Search

### ISSUE THREAD

**Issue by carrbrpoa** [cmv/cmv-app#586]
Hey guys:

See this screen:

![image](https://cloud.githubusercontent.com/assets/10212618/17622694/3e9e13a0-6072-11e6-8b7d-5c0b85c8abdf.png)

I do a spatial search (1) to select those two features (2 and 3). Then, I try to edit them (4). The problem is that the big circle I made for selection and even the small purple ones that highlight the results are over the features, so I can't interact with them (to edit, in this case).

Is there any way to workaround it?

Thanks!

**Comment by carrbrpoa** [comment]
Found some ugly workaround:

In the end of Editor's `toggleEditing` function (last thing of `if` statement), I do:

```
domConstruct.place("mySearch_FeatureGraphics_layer", "myEdit_layer", "before");
domConstruct.place("mySearch_SourceGraphics_layer", "myEdit_layer", "before");
domConstruct.place("mySearch_SelectedGraphics_layer", "myEdit_layer", "before");
domConstruct.place("mySearch_BufferGraphics_layer", "myEdit_layer", "before");
```

I'm sure there's something better.. :p

**Comment by tmcgee** [comment]
@carrbrpoa In a newer version of the AttributesTable widget that is not yet released, I include an option to add a new layer for each tab to the layerControl. This allows you to show/hide all the graphic layers (features, selected features, source graphic(s) and buffer graphic(s)) associated with that search. I'll try to get that version checked in soon.

NOTE: This only works with the version of the layerControl that is in the `develop` branch for cmv-app.

**Comment by carrbrpoa** [comment]
Great @tmcgee! But in this case, as a question of usability, it would be interesting to the user to search, keep it's search results marks (the purple circle around the found features) and edit any of these features, all the same time. Ok, the feature will be edited/moved and the purple circle will stay in the same place as before, patience... :)

**Comment by tmcgee** [comment]
Understood, That feature came from usability testing with my client as the least likely to interfere with the overall workflow - it put the control in the user's hands. Your workflow may vary. :) You can always turn on the layer again after a feature has been selected for editing.

One other thought, in a custom editor (not based off of the Esri editor widget), I hide irrelevant layers when the edit selection tools are active. Removing the clutter makes the target features for editing easy to find on the map.
