### ISSUE TITLE
Clustering Point Features

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-app#587]
Has anyone tried to 'cluster' point features in the CMV?

**Comment by tmcgee** [comment]
@cmccullough2 Perhaps this contributed widget will meet your needs. https://github.com/ERS-Long/PointClustering

**Comment by vamsi0406** [comment]
Is it possible to integrate CMV with any business Intelligence tools

**Comment by tmcgee** [comment]
@cmccullough2 Did that widget meet your needs?

**Comment by cmccullough2** [comment]
Sorry for the delayed response.  This is not working for me. The only thing that is different in the config is buildImageParameters vs. ImageParameters based on the example. I am not sure if this is the issue.  
I am not getting any error messages in the developer tools.  I am building this with the CMV WAB template.  
Viewer:
{
            type: 'dynamic',
            url: 'https://{airliftstatus}/gis/rest/services/Logistics/AircraftStatus/MapServer/',
            title: 'Airlift Status',
            options: {
                id: 'airliftStatus',
                opacity: 1.0,
                visible: true,
                imageParameters: buildImageParameters({
                            })
            },
              identifyLayerInfos: {
                layerIds: [0]
            },
            layerControlLayerInfos: {
                swipe: true,
								metadataUrl: true,
								expanded: false,
								 menu: [{
			                  label: 'PointClustering',
			                  topic: 'clusterMap',
			                  iconClass: 'fa fa-search fa-fw'
			              },{
			                  label: 'Remove PointClustering',
			                  topic: 'removeClusterMap',
			                  iconClass: 'fa fa-search fa-fw'
			              }]     
            },
            legendLayerInfos: {
                layerInfo: {
                    hideLayers: []
                }
            }
        }

Widget Configuration:
clusterMap: {
		            include: true,
		            id: 'clusterMap',
		            type: 'invisible', //titlePane, invisible
		            canFloat: true,
		            title: '<i class="icon-large icon-road"></i>&nbsp;&nbsp;clusterMap',
		            path: 'widgets/PointClustering',
		            position: 30,
		            open: false,
		            options: {
		                map: true,
		            }
		        },

**Comment by ERS-Long** [comment]
Hi, @cmccullough2 

Please plug in your service to this 

https://github.com/Esri/cluster-layer-js


to see if it works or not. I used that to find one of the my service's issue.

**Comment by roemhildtg** [comment]
On the latest version of cmv, the topic changed in Layer Control :( [this line](https://github.com/ERS-Long/PointClustering/blob/master/PointClustering.js#L54) the topic should be changed to `layerControl/...`

**Comment by tmcgee** [comment]
@roemhildtg good catch.

**Comment by roemhildtg** [comment]
I just noticed that a couple of my widgets were no longer working

**Comment by tmcgee** [comment]
yep. as you noted in the original PR #503, this is a breaking change.

**Comment by cmccullough2** [comment]
Is it safe to assume I need to make the same changes on line 143,       topic.subscribe('layerControl/removeClusterMap', function (r) {

**Comment by tmcgee** [comment]
yes it is.

**Comment by ERS-Long** [comment]
Yes, confirmed, if using the updated layercontrol, then we need to adjust that topic to use (layerControl) instead of (LayerControl).
Also need to test the map service, the GIS guy had to change something for one of the layers, otherwise it does not draw the cluster. I forgot what it was exactly, if i remember it correctly it is something about the underneath database thing. 

![image](https://cloud.githubusercontent.com/assets/5911272/18727551/c773436a-800e-11e6-9972-cf08f3cac2ec.png)

Thanks

**Comment by tmcgee** [comment]
It is worth pointing out that in the cmv develop branch, you can add your own custom layers directly in the operational layers array. So in theory, you could add a ClusterLayer when the application initializes without using the sublayer menu item. Untested, so your mileage may vary...

**Comment by roemhildtg** [comment]
I vaguely remember seeing something about that, are there cmv docs on
adding a custom layer type?

**Comment by tmcgee** [comment]
@roemhildtg documentation? surely you jest! ;)

https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L98

**Comment by tmcgee** [comment]
Here's another interesting implementation of [point clustering](https://github.com/nickcam/FlareClusterLayer) that should be fairly easy to integrate within a CMV application.

**Comment by ERS-Long** [comment]
Thanks @tmcgee  for the link about this very beautiful clustering example, did a quick test integration in CMV using the exact data, yes, it is very straightforward and it is working just fine. 

To use this cluster method for map service, still need to get the json data from the map service, I guess.

![image](https://cloud.githubusercontent.com/assets/5911272/18736813/787af202-8050-11e6-96ae-c269daaf4cbf.png)

**Comment by roemhildtg** [comment]
:smile: I'll see if I can find some time to write some docs on that before the big 2.0 release

**Comment by cmccullough2** [comment]
:+1:
