### ISSUE TITLE
Unable to get property 'toLowerCase' of undefined or null reference

### ISSUE THREAD

**Issue by cmccullough2** [cmv/cmv-app#589]
I am consistently getting this error.  Is this happening to anyone else.  The IE error:
SCRIPT5007: Unable to get property 'toLowerCase' of undefined or null reference
File: 3.16, Line: 1911, Column: 307.  
I have seen references to this line of code, <meta http-equiv="X-UA-Compatible" content="IE=edge">.  I am not sure how to fix it.  I have tried several of the suggested edits.

**Comment by roemhildtg** [comment]
Which version of IE are you using?

**Comment by cmccullough2** [comment]
IE 11.  Our end users are using multiple versions of IE.

**Comment by cmccullough2** [comment]
Or Edge

**Comment by cmccullough2** [comment]
This is the code I have in my index.html:  <meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by cmccullough2** [comment]
meta http-equiv="X-UA-Compatible" content="IE=edge" sorry the text dropped off.

**Comment by roemhildtg** [comment]
Do you get the same error using a fresh cmv install, or using a customized version?

**Comment by cmccullough2** [comment]
I am using the CMV WAB version, https://github.com/tmcgee/cmv-wab-widgets.  I have added so many widgets to this application that one may be causing me havoc.  I will investigate more tonight and tomorrow.  thanks

**Comment by roemhildtg** [comment]
Yeah, I'd suggest commenting them out and check for errors, then add them in one at a time. Report back on what you find.

**Comment by cmccullough2** [comment]
I found out that it is the eSearch widget, http://gis.calhouncounty.org/WAB/V2.0/widgets/eSearch/.  I over use it in my Flex application.  It is a must have.  I am going to install it on a clean CMV WAB viewer and test as I add additional layers.  I have 7 search layers in the widget now.  I am sure that I have configured something wrong.

**Comment by tmcgee** [comment]
@cmccullough2 It does sound like a possible configuration issue. I have also used the eSearch widget in CMV to assist someone migrating from WAB to CMV. ;) I modified it slightly to work with my AttributesTable widget.

Out of curiosity, is there specific functionality you use in the eSearch widget that my Search widget does not provide?

**Comment by cmccullough2** [comment]
Familiarity was my first reason for using the widget.  I know the Flex version very well.  We have a large number of hits everyday for that one widget.  https://github.com/rscheitlin/eSearch.  My configuration requirements are not necessarily simple: Many layers, some layers have child parameters, all have links that are queried with an attribute in the rest service.  The only thing that I do not like about the eSearch widget is that the results did not display in the Attribute table.  Yours does.  If I can make my configurations work with your widget, I will use it.  I had used yours, but I had trouble with it.  I cannot remember why.  My boss likes the Flex app very much.  It has been a challenge migrating him to JS.   Anyway I can make a smooth transition is the best way.  I will work with your Search Widget again.

**Comment by tmcgee** [comment]
@cmccullough2 Let me know if I can help - either with my widget or Robert's - preferably mine only since I can respond more quickly and make changes if needed. Happy boss and happy users is the end result we are after. 😄

**Comment by cmccullough2** [comment]
Thank you so much for your support.  This is a fun template to work with.

**Comment by cmccullough2** [comment]
I have been trying to configure your Search widget.  However, I am not doing something correct.  I am not sure if I am configuring things out of order??? I am sure it is a simple twist of code.

**Using the Public Safety Fire Layer, can you tell me if this is possible?   Your Public Safety by Name example is close.  I need the placeholder tag to be a drop down instead of a text box. 
<https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/PublicSafety/PublicSafetyOperationalLayers/MapServer/1>
1.  A query must be performed by first choosing a search layer; Fire Stations
2.  Search Layer field can one to many fields.  These fields use a drop down menu; FDNAME, ADDRESS, ABBR, etc. This is the key component I need. 
3.  Individual queries are then passed to render a selection. 
I can do this with the eSearch widget, but it is interfering with other widgets and I need the functionality of your widget.  The eSearch widget is giving me the original error message (above) before I make any edits. 
Let me know if this is possible.  If not, I can make the eSearch work.

**Comment by tmcgee** [comment]
@cmccullough2 this new topic should be an issue discussed in [my widgets repo](https://github.com/tmcgee/cmv-widgets/issues).

**Comment by tmcgee** [comment]
@cmccullough2 One additional comment before we take the discussion over to the other repo. That Public Safety sample service is not a good candidate for using dropdown menus since it is an old version of AGS (10.01) which does not support retrieving distinct values.
