### ISSUE TITLE
Remove Layer from Layer Widget

### ISSUE THREAD

**Issue by deepal13** [cmv/cmv-app#590]
Hello,

How can I add "Remove Layer" functionality in layer widget just like transparency/move up-down?

Thanks

**Comment by deepal13** [comment]
@tmcgee Can you please guide me?

**Comment by tmcgee** [comment]
@deepal13 I did not write the menu logic for the layerControl widget so am not certain how you would add to the menu.

One important question is how did the layer get added? If it is from a widget, the [Drag and Drop](https://github.com/BrianBunker/cmv-widgets/tree/master//DnD) widget might be a good example to follow on how to add layers and remove them. That widget has code to add a [dropped layer to the layerControl](https://github.com/BrianBunker/cmv-widgets/blob/master/DnD/DnD.js#L875) and then to [remove that layer from the layerControl](https://github.com/BrianBunker/cmv-widgets/blob/master/DnD/DnD.js#L898) when it is removed from the map. I added that particular code to the Drag And Drop widget so  can answer questions about that implementation. NOTE: the methods used there are dependent on enhancements to the layerControl widget that are in the [`develop`](https://github.com/cmv/cmv-app/tree/develop) branch of cmv.

**Comment by roemhildtg** [comment]
It doesn't appear that there is an easy way to add menu items to the layer control. I think you'd want to modify this file https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/LayerControl/plugins/LayerMenu.js. 

Add a menu item that publishes a topic (as @tmcgee  suggested) 
```
javascript
control.removeLayer= new MenuItem({
      label: 'Remove Layer',
      onClick: function () {
          topic.publish('layerControl/removeLayerControls', [control.layer]);
      }
});
self.addChild(control.removeLayer);

**Comment by deepal13** [comment]
@tmcgee The layer can be added using drag and drop or operational layer. I want to give the option for all the layers in layer widget. I will check develop branch again but the code I am using right now doesn't allow me to remove the layer from drag and drop widget. When I hit close, it removes the layer from DnD control but not from the map or layer widget. But I can refer the old code because it removed the layer from the map. Thanks for the help.

@roemhildtg I will try doing that. Thanks for the help.
