### ISSUE TITLE
I am looking to create a label on the map and to  save the entered text .

### ISSUE THREAD

**Issue by vamsi0406** [cmv/cmv-app#592]
In the draw widget I would like to add button label where I am able to capture the text of the user entered   and the location with the label symbol on the map. I was able to capture the location and set a label , But I am not sure how get a text box so the user can enter the value . And if he click cross he can also delete it 

![image](https://cloud.githubusercontent.com/assets/7122556/18204954/7d2b9e68-70ed-11e6-88d3-8852439a45f6.png)

**Comment by tmcgee** [comment]
@vamsi0406 Depending on how you want to capture/save the location and the label text, a custom widget might be the best solution for this. The draw widget has no mechanism to save the data provided by the user.

**Comment by vamsi0406** [comment]
@tmcgee thanks the comment I have modified the out of box code and able to get user input to var variable but that event is generating from create graphic function in draw.js , what I am stuck is when user click on the map I want to execution to wait until the user input in label and then again redirect to creategraphic function .

**Comment by tmcgee** [comment]
@vamsi0406 a suggestion - you might have better luck capturing the desired text (in a text box) before the user clicks the map.

**Comment by roemhildtg** [comment]
@vamsi0406 any luck or potential solution with this?
