### ISSUE TITLE
Tooltip is missing 

### ISSUE THREAD

**Issue by vamsi0406** [cmv/cmv-app#593]
The github version which I am working in 8 month back and I hope tooltip for drawwidget  is was included in that version . But my drawwidget doesnt have tooltip . I have checked the all file ( identify.js, draw js and html , index.html) still unable what is the reason behind the  why tool tip is missing . 
Attached the screenshot.
![tooltip is missing](https://cloud.githubusercontent.com/assets/7122556/18312832/a0654eb6-74d9-11e6-809a-e87145e45bee.png)

**Comment by tmcgee** [comment]
@vamsi0406 The Draw widget has included tooltips for a long time. What browser (and version) are you using?

**Comment by roemhildtg** [comment]
@vamsi0406 we can't seem to reproduce this issue, so I'm going to close it, if you are continuing to run into the issue and can give us steps to produce the bug feel free to reopen it.
