### ISSUE TITLE
Controlling/Turning On Layer When Opening a Widget?

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-app#600]
Is there a straightforward way to turn on a layer when opening up a widget?  I'd like to turn on a layer only when my Time Slider widget is opened.

Thanks

**Comment by vamsi0406** [comment]
3 'mode' options: MODE_SNAPSHOT = 0, MODE_ONDEMAND = 1, MODE_SELECTION = 2 
in viewer.js try-->options try mode:1

**Comment by JhopStl** [comment]
Well this could help with only loading a certain number of features, but I'd like to control the layer (specifically turn it on) when I open up my Time Slider widget.  I basically do not want the layer (i.e. Property Sales - a time enabled layer) to show up unless I am using the Time Slider widget.

**Comment by ERS-Long** [comment]
it should be doable. 

put the follwoing code in timeslider widget somewhere

            //Now make sure the Sample Layer is on
            var sampleLayer = this.map.getLayer('your layer id'); //your layer id is from the viewer.js operation layer configuration part. 
            sampleLayer.setVisibleLayers([0]);  //set the visible layer(s)
            sampleLayer.show();

**Comment by roemhildtg** [comment]
The streetview widget does this. It toggles its graphics layer when the widget is open and closed.

https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/StreetView.js#L65-L76

**Comment by JhopStl** [comment]
Alright thanks, I'll give it a try

**Comment by JhopStl** [comment]
Thanks guys, got it.  ERS-Long, your code worked perfectly after I put it under the enable function.
