### ISSUE TITLE
Identify widget identifies child layers when inside non visible group

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#601]
When a dynamic layer has a group layer, and the group layer is turned off, but the group's child layers are turned on, the child layers are identified. 

Example layer tree:
![image](https://cloud.githubusercontent.com/assets/5471079/18519084/2c2d2b38-7a68-11e6-92a6-1b09be9d203f.png)

This occurs when the app loads initially, and does not occur after the group layers are toggled on and off.

**Comment by tmcgee** [comment]
@roemhildtg The identify widget gets the subway visibility from the layer itself. Something must change in the visibleLayers array to correct this once the Group layer is toggled on and off.

**Comment by roemhildtg** [comment]
The problem is probably related to some of the conversation here: https://github.com/cmv/cmv-app/issues/217

Initially when the app loads, layers that are checked but not visible (because their parent group is off) are included in the visible layers array.  

Then, when their parent is toggled on and off, those layers remain checked in the layer control (good) but are no longer included in the visible layers array. 

What needs to happen, is when the identify initializes, it needs to check to see if each layer in the visible layers array has a parent, and whether or not that parent is included in the visible layers array. If it isn't, that layer should not be identifyable. 

Consider this:

- [ ] group layer (0) 
- [ ] ---- layer (1) 
- [ ] ---- layer (2)

On init, visible layers will be `[1, 2]`, but no layers are visible because 0 is not turned on. The identify widget still identifies 1 and 2 though. 

After toggling group layer 0 on and off again, visible layers now is `[-1]`

Confusing, right?

**Comment by tmcgee** [comment]
@roemhildtg it is actually a bit more complex than that since Group layers can be nested several layers deep so looking only at the sublayer's parent would not be enough.

In the issue #217, Ben mentioned switching to using the layer's `visibleLayers` to properly get the visibility of each sub layer. That is what we do with the identify widget as well so at least it is consistent. :smile" What is puzzling is why the widget gets the correct information from that `visibleLayers` array after the Group Layer is toggled of and then on again. Looks like more investigation is needed.

**Comment by roemhildtg** [comment]
Right, its because the visible layers array is different when it is initialized than when it is set. I guess it makes sense how Esri set it up, its so you can see which layers are "checked" even though they aren't visible. What doesn't make sense that not visible layers would be in the visible layers array. 

I guess identify would have to recursively look up a layer's parent to see if each parent's parent is visible.

**Comment by tmcgee** [comment]
@roemhildtg I am seeing some different behaviors that might be related to newer versions of the Esri JS API. What version of CMV and the Esri JavaScript API are you using? Can you confirm that the "Water Systems" group layer referenced above has a default visibility of false in the Map Service?

**Comment by roemhildtg** [comment]
Yes, here is some of the json for the mapserver page: 
```json
{"id":19,"name":"Water System","parentLayerId":-1,"defaultVisibility":false,"subLayerIds":[20,21,22,23,24,25,26],"minScale":0,"maxScale":0},
{"id":20,"name":"Curb Stops","parentLayerId":19,"defaultVisibility":true,"subLayerIds":null,"minScale":4000,"maxScale":0},{"id":21,"name":"Water Service Lines","parentLayerId":19,"defaultVisibility":true,"subLayerIds":null,"minScale":4000,"maxScale":0},
{"id":22,"name":"Water Structures","parentLayerId":19,"defaultVisibility":true,"subLayerIds":null,"minScale":7999.999999999946,"maxScale":0},
{"id":23,"name":"Wells and Reservoirs","parentLayerId":19,"defaultVisibility":true,"subLayerIds":null,"minScale":0,"maxScale":0},
{"id":24,"name":"Water Pipes","parentLayerId":19,"defaultVisibility":true,"subLayerIds":null,"minScale":19999.99999999999,"maxScale":0},
{"id":25,"name":"Water Hydrant Zones","parentLayerId":19,"defaultVisibility":false,"subLayerIds":null,"minScale":0,"maxScale":0},
```

**Comment by tmcgee** [comment]
@roemhildtg what versions of CMV and JS API?

**Comment by roemhildtg** [comment]
The esri version is 3.16 and I've been using the develop branch of cmv.

**Comment by roemhildtg** [comment]
Just noticed, this is a duplicate of this issue: https://github.com/cmv/cmv-app/issues/367

**Comment by roemhildtg** [comment]
Closed in https://github.com/cmv/cmv-app/pull/604
