### ISSUE TITLE
Create a custom widget with tab container

### ISSUE THREAD

**Issue by junchengzhang** [cmv/cmv-app#606]
Hi, 

  I am new to ArcGIS javascript API, I am able to make a simple mapping website, with some layers, now i am thinking to make a custom widget which contains a data grid for displaying the feature attribute value  I plan to pass the data to widget for display via json or whatever object type. I did not know how to get started. Can anyone point me a direction or give me a sample for similar scenario? great thanks to any input.

Dave

**Comment by roemhildtg** [comment]
Just off the top of my head, these widgets loads data in a grid, it might be a good place to start: 
 - https://github.com/roemhildtg/cmv-widgets/blob/master/widgets/RelationshipTable/RelationshipTable.js
- https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable/Table.js

Also check out the guide on building widgets: https://dojotoolkit.org/reference-guide/1.10/quickstart/writingWidgets.html#quickstart-writingwidgets

**Comment by junchengzhang** [comment]
Thank you Roemhildt, this is great example, I will take a deep look into it.

Dave

**Comment by roemhildtg** [comment]
@junchengzhang did those suggestions help solve your issue?
