### ISSUE TITLE
develop version issue

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#616]
if add the following config seeting

placeAt: 'right',

then it breaks the app,

the Error i got is

init.js:113 TypeError: Cannot read property 'nodeType' of null(…) "TypeError: Cannot read property 'nodeType' of null
    at addChild (https://js.arcgis.com/3.18/init.js:388:396)
    at placeAt (https://js.arcgis.com/3.18/init.js:359:493)
    at _createTitlePaneWidget (http://wsdtxmal/CMV321/js/viewer/_WidgetsMixin.js:193:53)
    at widgetLoader (http://wsdtxmal/CMV321/js/viewer/_WidgetsMixin.js:102:32)
    at .<anonymous> (http://wsdtxmal/CMV321/js/viewer/_WidgetsMixin.js:63:30)
    at Object.forEach (https://js.arcgis.com/3.18/init.js:70:348)
    at initWidgets (http://wsdtxmal/CMV321/js/viewer/_WidgetsMixin.js:62:27)
    at initMapComplete (http://wsdtxmal/CMV321/js/viewer/_MapMixin.js:185:18)
    at https://js.arcgis.com/3.18/init.js:63:154
    at h (https://js.arcgis.com/3.18/init.js:107:279)

**Comment by tmcgee** [comment]
Is this the configuration for a pane or a widget or ???

**Comment by ERS-Long** [comment]
here is the panel setting in viewer.js

        panes: {
        	left: {
        		splitter: true
        	},
        	right: {
        		id: 'sidebarRight',
        		placeAt: 'outer',
        		region: 'right',
        		splitter: true,
        		collapsible: true
        	},
        	bottom: {
        		id: 'sidebarBottom',
        		placeAt: 'outer',
        		splitter: true,
        		collapsible: true,
        		region: 'bottom'
        	},
        	top: {
        		id: 'sidebarTop',
        		placeAt: 'outer',
        		collapsible: true,
        		splitter: true,
        		region: 'top'
        	}
        },
        collapseButtonsPane: 'center', //center or outer

**Comment by tmcgee** [comment]
Be sure that the widget's `position` is correct - should be `0` if it is the only widget in that pane.

**Comment by ERS-Long** [comment]
:+1: that is why. Thanks!

**Comment by tmcgee** [comment]
The same thing happens in the left pane (with any cmv version, I think) if you do not have a widget with `position: 0` for that pane.

**Comment by ERS-Long** [comment]
Just put it here, i got a dirty version working for webmap, have to use some global variable, for some reason the topic in the mapDeferred.then call does not work. And then i have to some customized widgets for the webmap layer and legend. But anyway it works as is now just fine in the current CMV. Here is a screenshot

![image](https://cloud.githubusercontent.com/assets/5911272/19164857/3cea345a-8bc7-11e6-9a42-ef83dc6186ff.png)

**Comment by tmcgee** [comment]
👍

There a couple of new widgets labeled `WebMap Layers` and `WebMap Legend`. I would hope the existing widgets would work and new ones specific to webmaps are not required. Let's continue this discussion elsewhere. Can you create a repo for study/contribution?

**Comment by ERS-Long** [comment]
will do shortly after.

**Comment by ERS-Long** [comment]
Hi, @tmcgee :  I put the code in 

https://github.com/ERS-Long/WebInCMV,

This is a very rough version, works as minimal requirement but still leaves a lot room to be desired. :)

**Comment by tmcgee** [comment]
I will check it out over there. Thanks for sharing!
