### ISSUE TITLE
Adding a basemap using WebTiledLayer

### ISSUE THREAD

**Issue by jkyoungchoi** [cmv/cmv-app#619]
Hi,
I was trying to add a basemap with TMS from Nearmap, to call this TMS have to use WebTiledLayer instead of BasemapLayer. Some reason BasemapLayer brings only zoom level up to 19 but it works fine with WebTiledLayer.
`define([
    "esri/layers/WebTiledLayer",
    'esri/dijit/Basemap',
    'esri/dijit/BasemapLayer'
], function ( WebTiledLayer,Basemap, BasemapLayer ) {
    return {`

`nearMap: {
                title: 'Nearmap',
                basemap: new Basemap({
                    id: 'nearMap',
                    layers: [new WebTiledLayer({
                        url: "https://us${subDomain}.nearmap.com/maps?x=${col}&y=${row}&z=${level}&nml=v&ticket=ticket&httpauth=false&version=2",
                        copyright: "Nearmap, 2016",
                        id: "nearMap",
                        subDomains: ["0", "1", "2", "3"],
                        minScale:19,
                        maxScale:21
                        }),`

but it didn't work 

> init.js:152 GET https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer?f=json net::ERR_NAME_NOT_RESOLVED

> q {message: "Unable to load https://services.arcgisonline.com/A…vices/World_Street_Map/MapServer?f=json status: 0", response: Object, status: 0, responseText: "", xhr: XMLHttpRequest…}

How can I add a basemap using WebTiledLayer?

**Comment by roemhildtg** [comment]
Those error messages aren't related to the web tiled layer. 

But the problem is [Basemaps](https://developers.arcgis.com/javascript/3/jsapi/basemap-amd.html) can't have `WebTiledLayers` as basemap layers. Its weird, you have to pass an array of [BasemapLayers](https://developers.arcgis.com/javascript/3/jsapi/basemaplayer-amd.html) as the `layers` property.

It looks like you need to pass a `type` parameter, see the basemap layer page mentioned above for details. 

```javascript
            world_topo: {
                title: 'World Topographic (Esri)',
                id: 'world_topo',
                basemap: new Basemap({
                    id: 'world_topo',
                    layers: [new BasemapLayer({
                        type: 'WebTiledLayer',
                        url: 'https://${subDomain}.tile.thunderforest.com/cycle/${level}/${col}/${row}.png',
                        'subDomains': ['a', 'b', 'c']
                    })]
            }
```

**Comment by jkyoungchoi** [comment]
Thanks,
reason why I wanted to use WebTiledLayer becuase TMS that I use (nearmap) some reason it pulls only up to zoom 19 if I use basemaplayer, but when I try it with  WebTiledLayer it gets zoom level up to 24.
Currently, I use it just like what you post but I can't get tiles after zoom 19.
Wonder why it becomes limited when it becomes basemap.

**Comment by roemhildtg** [comment]
Its based off of your first basemap. What do you have for mapOptions?

**Comment by roemhildtg** [comment]
This issue mentions something similar: https://github.com/cmv/cmv-app/issues/439

**Comment by jkyoungchoi** [comment]
@tmcgee I've had lod sets already up to 21. 

```
      {"level" : 19, "resolution" : 0.298582141647617, "scale" : 1128.497176},
      {"level" : 20, "resolution" : 0.149291070823808, "scale" : 564.248588},
      {"level" : 21, "resolution" : 0.074645535, "scale" : 282.124294},
      {"level" : 22, "resolution" : 0.0373227677059521225, "scale" : 141.0621470000000125}
```
but it didn't help. I was wondering if BasemapLayer has limitation??

**Comment by tmcgee** [comment]
@jkyoungchoi It isn't a specific limitation of the BasemapLayer, I have used lods to level 22 and 23 with custom basemaps.

also make sure you don't have `maxZoom` in mapOptions set to a smaller zoom level number.

can you post your complete mapOptions?

**Comment by jkyoungchoi** [comment]
`nearMap: {
                title: 'Nearmap',
                basemap: new Basemap({
                    id: 'nearMap',
                    layers: [new BasemapLayer({
                        //url: "https://us${subDomain}.nearmap.com/maps?hl=en&x={col}&y={row}&z={level}&nml=Vert&ticket=15271234D99CF9146085B65527722A008A65F2DD2FD13F0BA37B4CD460E7D4CAFB7B5D8735C1206E68F68E7D0A4B56C986DFDF9E4F54424FAE17E1DE2DA9073A9F2BCFC6551519173A4CB2E5858A6B206148613A21825CB742B9334D0631FB4CE&httpauth=false&version=2",
                        url: "https://us${subDomain}.nearmap.com/maps?x=${col}&y=${row}&z=${level}&nml=v&ticket=3eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkRPbTBRdFJYZzhmS09fcGg2ZmRVd2E2RGdkbyIsImtpZCI6IkRPbTBRdFJYZzhmS09fcGg2ZmRVd2E2RGdkbyJ9.eyJpc3MiOiJodHRwczovL2FkbWluLm5lYXJtYXAuY29tIiwiYXVkIjoiaHR0cHM6Ly9hZG1pbi5uZWFybWFwLmNvbS9yZXNvdXJjZXMiLCJleHAiOjE0NzcyMjM2MTYsIm5iZiI6MTQ3NzA5NDAxNiwiY2xpZW50X2lkIjoidmVuZWVyIiwic2NvcGUiOlsibWFwIiwidXNlcl9pbmZvIl0sInN1YiI6IjAyOTljZjRhLTdjYjYtNDIwNC04MDE4LWVkODgwZWQxYmEzZCIsImF1dGhfdGltZSI6MTQ3NzA5NDAxNiwiaWRwIjoiaWRzcnYiLCJmZWF0dXJlX2tleSI6WyJoaWRlX3ZpZXdfbXVsdGkiLCJjdWx0dXJlX2VuX3VzIiwiZmVhdHVyZV9zb2xhcl9jYWxjdWxhdGUiLCJoaWRlX211bHRpdmlldyIsImhpZGVfdmlld190ZXJyYWluIiwiYnJvd3Nlcl9hdGxhcyIsImhpZGVfdGVycmFpbiIsImhpZGVfdmlld19zdHJlZXQiLCJnY21fYnVzaW5lc3MiXSwiYXJlYV9jb3ZlcmFnZV9yb2xlIjoiYXJlYV91cyIsImdpdmVuX25hbWUiOiJKYWNrIiwiZmFtaWx5X25hbWUiOiJDaG9pIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZ2Nob2lAdHJjc29sdXRpb25zLmNvbSIsImVtYWlsIjoiZ2Nob2lAdHJjc29sdXRpb25zLmNvbSIsImFtciI6WyJwYXNzd29yZCJdfQ.Uhrgrg-ffcvEyGbKBvN3FcOZSPQ2YuxYz8rwHdidTD9_iXqy10BaG_3C6CYRZVFmu0d-PeWSb6eLDvl3NIWIRBB5ZLEyDZLIkGKtXT59AP6_MCc2FrnqA1roC16vrexEWlIB82JObMqat9w9kJSUCXxzLuAK8vTioQHwThC2TRoF5gbIT7Hkdg3jzo50LY2iV2aFSah8lrvdKY1g3dkmCDNAatnQbRTR8lobYLbD2neKD5ruH8e0aJ3yQgSHIMQoMZjVxe4onrDHjACCZmJZEO5k6ZZK0lvTZbjGFq4mI3KE8_cgDPp7KrR1vJW9K9A9_hWWvDckzsfyPLBJmVAD6Q&httpauth=false&version=2",
                        copyright: "Nearmap, 2016",
                        id: "nearMap",
                        subDomains: ["0", "1", "2", "3"],
                        displayLevels: [19,20,21,22],
                        type:"WebTiledLayer"
                        })
                        // new BasemapLayer({
                        // url: "https://mt${subDomain}.google.com/vt/lyrs=s&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        // copyright: "Google, 2016",
                        // id: "googleSatellite",
                        // subDomains: ["0", "1", "2", "3"],
                        // displayLevels: [0, 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15,16,17,18],
                        // type:"WebTiledLayer"
                        // })
                    ]
                })
            },
`

`define([
    'esri/units',
   'esri/geometry/Extent',
    'esri/config',
    'esri/tasks/GeometryService',
    'esri/layers/ImageParameters'
], function (units, Extent,esriConfig, GeometryService, ImageParameters) {
    esriConfig.defaults.io.proxyUrl = 'https://webmap1.trcsolutions.com/proxy/proxy.ashx';
    esriConfig.defaults.io.alwaysUseProxy = false;
    esriConfig.defaults.geometryService = new GeometryService('https://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer');
    esriConfig.defaults.io.corsEnabledServers.push("us0.nearmap.com", "us1.nearmap.com", "us2.nearmap.com","us3.nearmap.com");
    var imageParameters = new ImageParameters();
    imageParameters.format = 'png32';
/*FROM NCTD*/
var maplods = [
          {"level" : 0, "resolution" : 156543.033928, "scale" : 591657527.591555}, 
      {"level" : 1, "resolution" : 78271.5169639999, "scale" : 295828763.795777}, 
      {"level" : 2, "resolution" : 39135.7584820001, "scale" : 147914381.897889}, 
      {"level" : 3, "resolution" : 19567.8792409999, "scale" : 73957190.948944}, 
      {"level" : 4, "resolution" : 9783.93962049996, "scale" : 36978595.474472}, 
      {"level" : 5, "resolution" : 4891.96981024998, "scale" : 18489297.737236}, 
      {"level" : 6, "resolution" : 2445.98490512499, "scale" : 9244648.868618}, 
      {"level" : 7, "resolution" : 1222.99245256249, "scale" : 4622324.434309}, 
      {"level" : 8, "resolution" : 611.49622628138, "scale" : 2311162.217155}, 
      {"level" : 9, "resolution" : 305.748113140558, "scale" : 1155581.108577}, 
      {"level" : 10, "resolution" : 152.874056570411, "scale" : 577790.554289}, 
      {"level" : 11, "resolution" : 76.4370282850732, "scale" : 288895.277144}, 
      {"level" : 12, "resolution" : 38.2185141425366, "scale" : 144447.638572}, 
      {"level" : 13, "resolution" : 19.1092570712683, "scale" : 72223.819286}, 
      {"level" : 14, "resolution" : 9.55462853563415, "scale" : 36111.909643}, 
      {"level" : 15, "resolution" : 4.77731426794937, "scale" : 18055.954822}, 
      {"level" : 16, "resolution" : 2.38865713397468, "scale" : 9027.977411}, 
      {"level" : 17, "resolution" : 1.19432856685505, "scale" : 4513.988705}, 
      {"level" : 18, "resolution" : 0.597164283559817, "scale" : 2256.994353}, 
      {"level" : 19, "resolution" : 0.298582141647617, "scale" : 1128.497176},
      {"level" : 20, "resolution" : 0.149291070823808, "scale" : 564.248588},
      {"level" : 21, "resolution" : 0.074645535, "scale" : 282.124294},
      {"level" : 22, "resolution" : 0.0373227677059521225, "scale" : 141.0621470000000125}

          ];
/*FROM NCTD*/
    return {
        isDebug: false,

        defaultMapClickMode: 'identify',
        mapOptions: {
            basemap: 'streets',
            center: [-117, 32.75],
            zoom: 19,
            sliderStyle: 'small',
            lods: maplods
        },`

**Comment by tmcgee** [comment]
@jkyoungchoi I used your mapOptions + maplods array and added the nearmap/google basemap to the Basemaps widget and it worked for me all the way to zoom 22. The Esri Street, Satellite and Hybrid maps were visible at this level too though pixelated.

![image](https://cloud.githubusercontent.com/assets/200780/19615916/46af2ddc-97bc-11e6-8287-9e81cb1c0214.png)

**Comment by jkyoungchoi** [comment]
I just install new cmv and add my code that I post above but it stop showing after 19
what else I could try?

**Comment by jkyoungchoi** [comment]
@tmcgee thanks for sharing your code!
but unfortunately still the same... wondering what's doing this

**Comment by tmcgee** [comment]
@jkyoungchoi If you can provide a publicly available demonstration of the code not working, I can review it to identify the possible issue(s).

**Comment by jkyoungchoi** [comment]
@tmcgee I've tried set up a sample but some reason getting 401 error with map service. So meanwhile I'd like to try loading a tile layer with WebTiledLayer (which has no issue with zoom or anything) when zoom level is like 20 or later. Would this is even possible? Thanks!

**Comment by jkyoungchoi** [comment]
@tmcgee 
I twick https://github.com/ishiland/cmv-wms-basemaps widget to use WebTiledLayer
When you open it's going to load default hybrid map at zoom 19. Just switch to nearmap basemap then it's going to load it. Zoom one more level, that default hybrid map will appear.
Thanks!
https://goo.gl/VgpD7n

**Comment by tmcgee** [comment]
@jkyoungchoi You should not have to use that contributed widget. WebTiledLayers are supported in the CMV Basemap widget. As shown in my screenshot earlier, your original basemap configuration for nearmaps works. There are additional examples included in [`basemap.js`](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/basemaps.js#L262-L298)

**Comment by jkyoungchoi** [comment]
@tmcgee I switch back to regular base map (using type: 'WebTiledLayer') . But still it disappears after zoom 19. Would this means nearmap has to something with this?

**Comment by jkyoungchoi** [comment]
I misread comment, it works on dev. one! Thanks

**Comment by rylincoln** [comment]
@tmcgee  @roemhildtg Jack (@jkyoungchoi) wasn't using the development branch.  He works with me - I just checked out the development branch and copied his basemap.js code into it and it works.  So thank you for your help.  👍 I think we're good now.

**Comment by tmcgee** [comment]
@jkyoungchoi @rylincoln got it. For reference and for others reading this, the secret sauce is the newer version of the Esri API included in the develop branch. You need to use at least version 3.16 of the API for this to work.

**Comment by GilbertLasnier** [comment]
I just try all that for the version cmv 2.0 and nothing work for me what i make wrong?
the base map contain google...
basemaps: {
			
            googleHybrid: {
                title: 'EVONERGIE Toiture',
                basemap: new Basemap({
                    id: 'googleHybrid',
                    layers: [new BasemapLayer({
                        url: "https://mt${subDomain}.google.com/vt/lyrs=s,h&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleHybrid",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
			},
            googleSatellite: {
                title: 'EVONERGIE no Label',
                basemap: new Basemap({
                    id: 'googleSatellite',
                    layers: [new BasemapLayer({
                        url: "https://mt${subDomain}.google.com/vt/lyrs=s&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleSatellite",
                        subDomains: ["0", "1", "2", "3"],
						displayLevels: [0, 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
And for the viewer i put the same then Tim but ( now i put in comment )
  });
    topic.subscribe('layerControl/goodbye', function (event) {
        topic.publish('growler/growl', {
            title: 'Goodbye!',
            message: event.layer._titleForLegend + ' ' +
                (event.subLayer ? event.subLayer.name : '') +
                ' says goodbye'
        });
    });
	/*  var maplods = [
        {'level': 0, 'resolution': 156543.033928, 'scale': 591657527.591555},
        {'level': 1, 'resolution': 78271.5169639999, 'scale': 295828763.795777},
        {'level': 2, 'resolution': 39135.7584820001, 'scale': 147914381.897889},
        {'level': 3, 'resolution': 19567.8792409999, 'scale': 73957190.948944},
        {'level': 4, 'resolution': 9783.93962049996, 'scale': 36978595.474472},
        {'level': 5, 'resolution': 4891.96981024998, 'scale': 18489297.737236},
        {'level': 6, 'resolution': 2445.98490512499, 'scale': 9244648.868618},
        {'level': 7, 'resolution': 1222.99245256249, 'scale': 4622324.434309},
        {'level': 8, 'resolution': 611.49622628138, 'scale': 2311162.217155},
        {'level': 9, 'resolution': 305.748113140558, 'scale': 1155581.108577},
        {'level': 10, 'resolution': 152.874056570411, 'scale': 577790.554289},
        {'level': 11, 'resolution': 76.4370282850732, 'scale': 288895.277144},
        {'level': 12, 'resolution': 38.2185141425366, 'scale': 144447.638572},
        {'level': 13, 'resolution': 19.1092570712683, 'scale': 72223.819286},
        {'level': 14, 'resolution': 9.55462853563415, 'scale': 36111.909643},
        {'level': 15, 'resolution': 4.77731426794937, 'scale': 18055.954822},
        {'level': 16, 'resolution': 2.38865713397468, 'scale': 9027.977411},
        {'level': 17, 'resolution': 1.19432856685505, 'scale': 4513.988705},
        {'level': 18, 'resolution': 0.597164283559817, 'scale': 2256.994353},
        {'level': 19, 'resolution': 0.298582141647617, 'scale': 1128.497176},
        {'level': 20, 'resolution': 0.149291070823808, 'scale': 564.248588},
        {'level': 21, 'resolution': 0.074645535, 'scale': 282.124294},
        {'level': 22, 'resolution': 0.0373227677059521225, 'scale': 141.0621470000000125}
    ]; */
 and other copy and paste
    // simple clustering example now. should be replaced with a layerControl plugin
    topic.subscribe('layerControl/toggleClustering', function (event) {
        var layer = event.layer;
        if (layer.getFeatureReduction()) {
            if (layer.isFeatureReductionEnabled()) {
                layer.disableFeatureReduction();
            } else {
                layer.enableFeatureReduction();
            }
        }
    });

    return {
        // used for debugging your app
        isDebug: true,

        //default mapClick mode, mapClickMode lets widgets know what mode the map is in to avoid multipult map click actions from taking place (ie identify while drawing).
        defaultMapClickMode: 'identify',
        // map options, passed to map constructor. see: https://developers.arcgis.com/javascript/jsapi/map-amd.html#map1
        mapOptions: {
            basemap: 'osm',
            center: [-73.72179687497497, 45.56596293629694],
            zoom: 12,
            sliderStyle: 'small'
			/* lods: maplods */
What is wrong with that to see google at more level of zoom?

**Comment by tmcgee** [comment]
@GilbertLasnier You do not need to use `displayLevels` to zoom in further for Esri, Google or many other providers. You do need to use the `maplods` and the `lods: maplods` mapOption as I demonstrated above in viewer.js.

NOTE: This assumes the provider has data at those higher zooms. Many areas of the world do not have tiles available at higher zoom levels:

![image](https://user-images.githubusercontent.com/200780/48017522-50a52b80-e0e3-11e8-80f3-e014cf0df646.png)

**Comment by GilbertLasnier** [comment]
Thanks for your fast answer but i show you when i need that: 
![capturefromcmv](https://user-images.githubusercontent.com/6784515/48024113-bad2c600-e10d-11e8-9135-65cdad99bae7.JPG) and the same one from mapsgoogle
![capturefrommapsgoogle](https://user-images.githubusercontent.com/6784515/48024212-0be2ba00-e10e-11e8-923e-5e912c8c941d.JPG)

**Comment by GilbertLasnier** [comment]
Hello Tim thanks again for your support but we must find a solution or explication for...The resolution is better in mapsgoogle. its for that i need to know how to zoom at the best level and if we have the same picture date of the imagery etc... in our cmv

**Comment by tmcgee** [comment]
@GilbertLasnier If you properly apply the changes I mentioned above, you will be able to zoom in further with a Google base map. To recap, this is the relevant change needed:

``` javascript

    var maplods = [
        {"level" : 0, "resolution" : 156543.033928, "scale" : 591657527.591555}, 
        {"level" : 1, "resolution" : 78271.5169639999, "scale" : 295828763.795777}, 
        {"level" : 2, "resolution" : 39135.7584820001, "scale" : 147914381.897889}, 
        {"level" : 3, "resolution" : 19567.8792409999, "scale" : 73957190.948944}, 
        {"level" : 4, "resolution" : 9783.93962049996, "scale" : 36978595.474472}, 
        {"level" : 5, "resolution" : 4891.96981024998, "scale" : 18489297.737236}, 
        {"level" : 6, "resolution" : 2445.98490512499, "scale" : 9244648.868618}, 
        {"level" : 7, "resolution" : 1222.99245256249, "scale" : 4622324.434309}, 
        {"level" : 8, "resolution" : 611.49622628138, "scale" : 2311162.217155}, 
        {"level" : 9, "resolution" : 305.748113140558, "scale" : 1155581.108577}, 
        {"level" : 10, "resolution" : 152.874056570411, "scale" : 577790.554289}, 
        {"level" : 11, "resolution" : 76.4370282850732, "scale" : 288895.277144}, 
        {"level" : 12, "resolution" : 38.2185141425366, "scale" : 144447.638572}, 
        {"level" : 13, "resolution" : 19.1092570712683, "scale" : 72223.819286}, 
        {"level" : 14, "resolution" : 9.55462853563415, "scale" : 36111.909643}, 
        {"level" : 15, "resolution" : 4.77731426794937, "scale" : 18055.954822}, 
        {"level" : 16, "resolution" : 2.38865713397468, "scale" : 9027.977411}, 
        {"level" : 17, "resolution" : 1.19432856685505, "scale" : 4513.988705}, 
        {"level" : 18, "resolution" : 0.597164283559817, "scale" : 2256.994353}, 
        {"level" : 19, "resolution" : 0.298582141647617, "scale" : 1128.497176},
        {"level" : 20, "resolution" : 0.149291070823808, "scale" : 564.248588},
        {"level" : 21, "resolution" : 0.074645535, "scale" : 282.124294},
        {"level" : 22, "resolution" : 0.0373227677059521225, "scale" : 141.0621470000000125}
    ];

    return {
        isDebug: false,

        defaultMapClickMode: 'identify',
        mapOptions: {
            basemap: 'streets',
            center: [-117, 32.75],
            zoom: 19,
            sliderStyle: 'small',
            lods: maplods
        },
```

This may or may not get the same dated imagery as available in Google maps. As I stated in #865:
> I am not aware of any other method to access tiles that might use newer base imagery.

If you have additional problems, please create a new issue instead of adding to a closed one.

**Comment by GilbertLasnier** [comment]
Thanks Tim I will retry tomorrow ,
