### ISSUE TITLE
Proxy config/set up

### ISSUE THREAD

**Issue by blee07** [cmv/cmv-app#623]
How is te proxy.config supposed to be set up for a typical IIS server? Is the URL that was already existing as http://services.arcgisonline.com need to be changed to the services coming from my ArcGIS server? Or, does another tag need to be added with the ArcGIS server? I have tried both. My issue is I cannot get the print to work. I noticed that the arcGIS online service they were pointing to does not exist (no service in the folder). so, I have created my own on ArcGIS Server and placed that URL in the print.config but am getting this ERROR: Unable to load proxy/proxy.ashx?https://arceam.ameren.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/execute status 500.
The print will work in another CMV application that is using ArcGIS Online feature service layer 9with security).
I did not change any proxy settings at all yet. So, I am concerned I need to do that as well. But, everything else in the CMV application is working fine. 
I feel like this is a simple fix but just need to configure the proxy correctly maybe. 
Thank you for any input.

**Comment by roemhildtg** [comment]
Your arcgis server url isn't accessible, it doesn't have anything to do with your esri proxy config. When I visit http://arceam.ameren.com/arcgis/rest/services, it redirects me to a 404 error page.

You first need to be able to access your server directly. Then you can start configuring your proxy for your app. See the documentation on the proxy scripts here: https://github.com/Esri/resource-proxy docs

**Comment by blee07** [comment]
This is an internal application for my company. It is only accessible within our firewall.

**Comment by blee07** [comment]
The layers and everything else in CMV work fine.

**Comment by roemhildtg** [comment]
Ah. I see. I didn't notice the proxy/proxy.ashx? in your url above. 

You will have to configure your proxy.config to include the arceam.ameren.com. Otherwise it won't let you proxy that url. 

See this page for the config options: https://github.com/Esri/resource-proxy/blob/master/README.md#proxy-configuration-settings

You can set mustMatch to false, that will open it up to any url. But in production, you want to restrict it to just the urls your using.

**Comment by blee07** [comment]
I've tried that and I luck unless the code was wrong.. also, how is it accessing the layers from arceam now but not the print URL?I've found the same issue on stack exchange someone had and says the aspic page needs a max request length and also execution timeout and am currently trying to research that.. since I have not configured that before.

**Comment by roemhildtg** [comment]
Not sure. The proxy isn't used unless necessary, so the api might be directly accessing the layer url. Printing requires a proxy because it sends a lot of data. 

What's the error message you get when you visit the url `proxy/proxy.ashx?https://arceam.ameren.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/execute`? If it just says "error 500" that's not super helpful. You'd need to turn on aspx debugging in iis to get the error message. 

Or you can sometimes visit that url into a browser on the server and it will give you the error message.

**Comment by tmcgee** [comment]
@blee07 @roemhildtg Let me step back and ask if a proxy required at all. Since this is an internal application presumably accessing internal Print Service, it may not be necessary. 

Printing does not require a proxy though it does work with one, The proxy request uses an HTTP POST instead a GET to handle the large amounts of data.

If accessing these internal resources securely is a requirement, then a proxy MAY be desirable depending on the needs. Frequently secured printing is achieved by creating a custom Print Service with an embedded security token. Not saying that is necessary, just one approach.

**Comment by blee07** [comment]
Good info , thanks Tim. This is an internal application so it is already  secure . And yes, I was trying to use a service URL we created on ArcGIs server (web task export tool). The same service but different URL obviously as the preconfigured CMV provided (arcgis online service). However that service is no longer in their folder. Does not exist anymore. My service on my company's server does not work with it either. The really strange part of it all is that their service URL works in another CMV application  I created but the layers are coming from our  arcgis online account not arcgis Server.

**Comment by tmcgee** [comment]
@blee07 The Esri Print Service still exists and works in the demo application. They have disabled browsing the services on that server. That's unrelated to any issues you might have with your internal Print Service. You should troubleshoot that outside of cmv to ensure the Print Service works. This [page](http://communityhub.esriuk.com/technicalsupport/2014/10/24/troubleshooting-web-service-printing-failures.html) provides some basic diagnostics.

**Comment by blee07** [comment]
Yes, it works when I use arcgis online service layers but not arcgis server. I tried originally to just use theirs because it's exactly the same as mine anyways. Is there a way to disable it in the code? 
Thanks Tim!!

**Comment by tmcgee** [comment]
@blee07 The Esri Print Service not being to access your internal arcgis services behind your firewall is to be expected. What do you mean by

> Is there a way to disable it in the code?

What exactly do you want to disable?

**Comment by blee07** [comment]
Can I ask for assistance in the setting up the proxy? I believe that mine is not configured properly and that is the issue. What needs to be changed from the original CMV code? 
Thank you very much!

**Comment by roemhildtg** [comment]
There's a few resources available on configuring proxies. https://github.com/Esri/resource-proxy should be able to provide you with everything you need. The main readme has general details and each folder (dotnet, php) has more detailed instructions. 

You don't need to change any cmv code other than configure the url to the proxy.  https://github.com/cmv/cmv-app/blob/master/viewer/js/config/viewer.js#L10

**Comment by tmcgee** [comment]
@blee07 the basics for using a proxy with cmv pretty simple. An example is provided in this viewer.js: 
https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js. Look at the code comments in the top 22 lines.

Having said that, most internal sites do not require the use of a proxy. That depends on your specific server configuration(s) and requirements which

**Comment by blee07** [comment]
Thank you Tim. I added that code to my viewer.config. 
My issue is I cannot get the print widget to work and I am 99% sure it has to do with the proxy. Do I need to change anything in the proxy.config? Do I need to add my server URL? I've tried that before but that was before I added what you told me.

**Comment by blee07** [comment]
Also, for the URL prefix in the code you sent .. what URL is it exactly? The IIS server that all the JS is on or the ArcGIS server URL where the services are ?
Thanks!

**Comment by tmcgee** [comment]
@blee07 

The `urlPrefix` entered would be the beginning part of the ArcGIS Server REST end-point urls.
The `proxyPage` must a proxy installed on the IIS server where CMV is running.

Is your internal Print Service on the same server as your internal ArcGIS Services? If so, no proxy should be required.

Have you verified that your internal Print Service is running and working? I provided a link to some diagnostics but don't know if you tried that.

**Comment by blee07** [comment]
Tim the print service is in the same ArcGIS server. One of them though, because right now there are services coming from two different server Rest points. Also, I have not tested the print service yet , and cannot find the link you sent before. Can you resend it please ? 
This may not matter, but for a sanity check for me , does anything from the original CMV code on the proxy.config file need to be changed? Should the URL be the same , services.arcgisonline.com? 

Sent from my iPhone

**Comment by blee07** [comment]
Tim,
I noticed an error from ArcGIS server logs about the ArcGIS online base maps. When I remove those is works. So, my guess it is a proxy issue..? Our print service is definitely not it because it works. It will only print with a custom basemap. Any suggestions to get it to print with the ArcGIS online basemaps?

**Comment by tmcgee** [comment]
@blee07 I see that my comment from the other day did not get posted. Must not have hit the Comment button. To restate my original comment:

This is not an issue with CMV or the Esri JavaScript API or something a proxy page on the IIS web server can resolve. This will most likely require attention from the your IT Network staff to allow access to the internet from your ArcGIS Server. All printing is completed by the ArcGIS Server via the Print Service. If that server and the user logon for the AGS Services does not have access to the internet, it cannot print a map that includes services that reside outside your environment. That includes the Esri basemaps, services at ArcGIS Online and any other external Map Service that you may want to print.

Typically this is controlled by a network firewall or possibly an existing proxy server within the network. The [troubleshooting page](http://communityhub.esriuk.com/technicalsupport/2014/10/24/troubleshooting-web-service-printing-failures.html) I provided earlier is a good test for checking that connectivity to outside resources like the esri basemaps. Once this is resolved with the server and network, you should be good to go.
