### ISSUE TITLE
Max records found from query/find widget

### ISSUE THREAD

**Issue by blee07** [cmv/cmv-app#627]
I am only getting a 1000 records found on a query that I know should have more. I am using ArcGIS Server rest service. I increased the maximum number of records returned by the server and thought that would do it but did not. I do not see anything in the JavaScript code that programs that. Is there a way to increase this and get all of the records returned on the find search? 
Thank you.

**Comment by tmcgee** [comment]
@blee07 you can query the rest interface to verify the number of records being returned from each layer. I don't recall any additional parameters that can be changed in the JavaScript to influence this in the FindTask.

**Comment by blee07** [comment]
Yes, but I believe it only works for a feature service not a dynamic map service. Also, do you know what can of limitations/performance it puts on the server. I have a layer that needs thousands of records selected. I did get it to work with a feature service but it makes the page unresponsive for a minute and have to click the wait in the unresponsive page window. This isn't ideal for users. Any more effective way to do this kind of large selection on a map service (not feature service)? 
Thanks!

**Comment by tmcgee** [comment]
@blee07 you can adjust the feature limit for dynamic map services as well and the FindTask respects that limit. At least at version 10.3.1. Not positive about older versions.

**Comment by blee07** [comment]
Yes when I do that though from the service it only adjusts it as a query at the rest . But ,on the rest page it still only says 1000. I've only got it to work for a feature service.

**Comment by blee07** [comment]
Do you know anywhere in the widget or anywhere else in JS it can be adjusted ?
Thank you.

**Comment by tmcgee** [comment]
I have it working for dynamic map services and the MaxRecordCount reflects what I set in the service. Just tested the FindTask with a service where I have the limit set to 2000 and it worked as expected.

As noted before, I am not aware of any adjustments in the Find widget or other JavaScript where you can override the settings in the Map Service.

**Comment by blee07** [comment]
Okay, I actually was able to get it to work with a map service as well. However , I am worried about the workload on the server. Do you know how much it will impact it more to set it to 5000?
I appreciate your input.
