### ISSUE TITLE
LayerControl: mapimage type untested?

### ISSUE THREAD

**Issue by jerrygarciame123** [cmv/cmv-app#635]
I assume mapimage type commented below as "untested" means it has not been implemented and does not work?

Any advice as to how I can move forward with this implementation?  I need to overlay a georeferenced raster image on the map.

Thanks!

			var layerTypes = {
				csv: 'CSV',
				dataadapter: 'DataAdapterFeature', //untested
				dynamic: 'ArcGISDynamicMapService',
				feature: 'Feature',
				georss: 'GeoRSS',
				image: 'ArcGISImageService',
				imagevector: 'ArcGISImageServiceVector',
				kml: 'KML',
				label: 'Label', //untested
				mapimage: 'MapImage', //untested
				osm: 'OpenStreetMap',
				raster: 'Raster',
				stream: 'Stream',
				tiled: 'ArcGISTiledMapService',
				webtiled: 'WebTiled',
				wms: 'WMS',
				wmts: 'WMTS' //untested
			};

**Comment by tmcgee** [comment]
@jerrygarciame123 If it is in that list of layers then it is implemented. The MapImageLayer is untested only because Esri does not provide a working example of how to use MapImageLayer in the docs. Here's an [simple example](http://stackoverflow.com/questions/36453652/how-to-rotate-a-mapimage-with-arcgis-javascript-api) I just found via a Google search. I have not tested this one either.

**Comment by roemhildtg** [comment]
The problem, it looks like this is another case where while you can create a `MapImageLayer` in cmv, adding `MapImage`s isn't super easy. You'd need to create a widget like this:
```javascript
mapImageWidget: {
    include: true,
    type: 'invisible',
    path: 'dijit/_WidgetBase',
    options: {
        startup: function() {
            this.map.getLayer('mapImageLayerID').addImage(new MapImage({
                'extent': {
                    'xmin': -8864908,
                    'ymin': 3085443,
                    'xmax': -8062763,
                    'ymax': 3976997,
                    'spatialReference': {
                        'wkid': 3857
                    }
                },
                'href': 'https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png'
            }));
        }
    }
}
```

**Comment by jerrygarciame123** [comment]
Thanks for the responses!  

Given the pattern, I probably did not due this justice... but, I did it like this:

Operational Layer:
            {
                type: 'mapimage',
                title: 'Sediment Delivery',
                slider: true,
                noLegend: false,
                options: {
                    id: 'sedimentDeliveryImage',
                    opacity: 1.0,
                    visible: true,
                    swipeScope: true,
                    imageParameters: imageParameters,
                    mapImage: {
                        'extent': {
                            xmin: -10556648.952447832,
                            ymin: 5149065.289192979,
                            xmax: -10555559.724794738,
                            ymax: 5151210.303299288,
                            'spatialReference': {
                                'wkid': 3857
                            }
                        },
                        'href': 'https://~~~/Agren.SoilCalculator.Viewer/images/1.png'
                    }
                },

Added to the controller function:
		initLayer: function (layer, Layer) {

		    var l = new Layer(layer.url, layer.options);

			this.layers.unshift(l); //unshift instead of push to keep layer ordering on map intact
			//Legend LayerInfos array
			this.legendLayerInfos.unshift({ //unshift instead of push to keep layer ordering in legend intact
				layer: l,
				title: layer.title || null
			});
			//LayerControl LayerInfos array
			this.layerControlLayerInfos.unshift({ //unshift instead of push to keep layer ordering in LayerControl intact
				layer: l,
				type: layer.type,
				title: layer.title,
				controlOptions: layer.layerControlLayerInfos
			});
			if (layer.type === 'feature') {
				var options = {
					featureLayer: l
				};
				if (layer.editorLayerInfos) {
					lang.mixin(options, layer.editorLayerInfos);
				}
				this.editorLayerInfos.push(options);
			}
			if (layer.type === 'dynamic' || layer.type === 'feature') {
				var idOptions = {
					layer: l,
					title: layer.title
				};
				if (layer.identifyLayerInfos) {
					lang.mixin(idOptions, layer.identifyLayerInfos);
				}
				if (idOptions.exclude !== true) {
					this.identifyLayerInfos.push(idOptions);
				}
			}
			**if (layer.type === 'mapimage') {
			    var mi = new MapImage(layer.options.mapImage);
			    l.addImage(mi);
			}**
		},

I also added a MapImage control file for the LayerControl...

**Comment by tmcgee** [comment]
@jerrygarciame123 and @roemhildtg I think the best answer might be to create a custom layer that encapsulates creating the layer and adding the image. The version of CMV in the develop branch supports this.

https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L121
https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/_MapMixin.js#L105-L106

This would be preferable to modifications to the controller which are harder to mange with future releases of CMV. I don't have time right now to whip up an example. It should be pretty easy to do and test. 

Add the MapImage control (and any other layers missing) to LayerControl widget is an additional enhancement that make a nice PR.

**Comment by roemhildtg** [comment]
Good idea, I like that approach better. It bugs me that esri doesn't allow you to pass `mapImages` to the layer constructor, but a custom layer type would indeed allow that.
