### ISSUE TITLE
CMV doesnot work on the IPAD with Safari browser!!1

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#636]
I try yesterday my CMV app like always on my Ipad 
with Safari nothing with drop down or tree view popup.
Its work befor with the version Mac OS 8.0 to 9.7 with 10 or 10.1 or 10.1.1
Its worst!!
So I try with Crome and every thing is working on the Ipad!!
**How we must send that issue directly to APPLE Safari team?**

**Comment by tmcgee** [comment]
@GilbertLasnier Can you test using a different iPad with the same version of the operating system? Can you test using some of the basic Esri and Dojo examples to verify the root cause of the issue? I doubt this is specific to CMV.

**Comment by GilbertLasnier** [comment]
Your RIGHT Its not specifique to CMV but the probleme is directly the consequence of **Safari** incompatibilities with ESRI javascript Dojo example in an Ipad its not depending of the Ipad...

**Comment by GilbertLasnier** [comment]
I DON'T UNDERSTAND... I try here on a brad new IPAD and its work 
I try at home to delete the cash OF safari!!!
Have a good day Tim
