### ISSUE TITLE
Editor widget - input/textarea

### ISSUE THREAD

**Issue by Wernazuma** [cmv/cmv-app#637]
In our editor, I'd need one input field to have multiple lines. I tried to somehow style it that way but people on stackoverflow told me I couldn't do that but would have to change the input to a textarea field. One guy was even kind enough to suggest a jQuery code to achieve that: $('#dijit_form_TextBox_0').replaceWith('<textarea class="dijitReset dijitInputInner" data-dojo-attach-point="textbox,focusNode" autocomplete="off" tabindex="0" id="dijit_form_TextBox_0" maxlength="1000" value="" aria-disabled="false"></textarea>');

What I couldn't figure out is: where, if that's the way to go, would I inject that to make it work? Any ideas?

**Comment by tmcgee** [comment]
@Wernazuma 

You can easily do this in your configuration for the operational layer:

``` javascript
editorLayerInfos: {
    fieldInfos: [
        {
            fieldName: 'notes',
            label: 'Notes',
            'stringFieldOption': AttributeInspector.STRING_FIELD_OPTION_TEXTAREA
        }
    }
}
```

To use the above, you will also need to include the AttributeInspector in your modules array at the top of `viewer.js`

``` javascript
define([
    ... 
    'esri/dijit/AttributeInspector'
    ...
], function (..., AttributeInspector, ...) {
```

**Comment by Wernazuma** [comment]
You're the best, as always! However, I'm not, so I managed to break the code again. My code for the operational layer is:
`            type: 'feature',
            url: 'https://www.hgis-indias.net:6443/arcgis/rest/services/HGIS/HGIS_Edit_Comentarios/FeatureServer/0',
            title: 'Comentarios/advertencias',
            options: {
                id: 'Comentarios',
                opacity: 1.0,
                visible: false,
                outFields: ['*'],
                mode: 0
            },
            editorLayerInfos: {
				fieldInfos: {
					{
						fieldName: 'notes',
						label: 'Comentario',
						'stringFieldOption': AttributeInspector.STRING_FIELD_OPTION_TEXTAREA
					}
				},
                disableGeometryUpdate: false
            },
            legendLayerInfos: {
                exclude: false,
                layerInfo: {
                    title: 'Comentarios'
                }
            }
  },`

**Comment by roemhildtg** [comment]
It looks like your `fieldInfos` needs to be an array, not an object. 
```javascript
		fieldInfos: [{
			fieldName: 'notes',
			label: 'Comentario',
			'stringFieldOption': AttributeInspector.STRING_FIELD_OPTION_TEXTAREA
		}],
```

**Comment by Wernazuma** [comment]
Problem solved. Thanks again, guys!
