### ISSUE TITLE
how to hide identify widget

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#638]
I need identify widget working by clicking features on map for all displayed layers. but I do want the widget display in the panel.  Please help!!

**Comment by roemhildtg** [comment]
You're looking for the widget `type: 'invisible'` 

https://docs.cmv.io/en/latest/widgets/Identify/

**Comment by JudyZhou** [comment]
Thanks so much @roemhildtg.

**Comment by roemhildtg** [comment]
No problem
