### ISSUE TITLE
Mouse Hover Event Popup

### ISSUE THREAD

**Issue by kcarrier** [cmv/cmv-app#639]
Does anyone have any examples of how to implement a mouse hover event with a popup in CMV?
Someone here is my office would like to see this with our data.
I noticed in Esri JS API 3.18 there are some example just did not know if anyone had any examples from other projects.
Just not sure how or where to implement the logic for this.

**Comment by roemhildtg** [comment]
Its not too difficult, basically you just create a simple widget like so:

```javascript

    mouseover: {
        include: true,
        type: 'invisible',
        id: 'mouseover',
        path: 'dijit/_WidgetBase',
        options: {
            map: true,
            startup: function() {
                this.map.on('mouse-over', function(event){
                    //do something
                });
            }
        }
    }
```

If it gets to be a big widget, you can easily extract this into its own file, and then reuse it as needed between multiple cmv configs.

**Comment by kcarrier** [comment]
Would this code be placed in main config?

**Comment by roemhildtg** [comment]
You may place it in the main `viewer.js` config, under the `widgets` property. Or, you could make it more modular and put it in its own file, like `gis/dijit/mouseover.js` and change the widget path in the code above to `gis/dijit/mouseover`.

**Comment by kcarrier** [comment]
Thank you I will work on a solution and report back if I have a solution so
others can see it.

**Comment by kcarrier** [comment]
@roemhildtg - Not sure what I am doing wrong here would you mind looking over the code and suggesting any changes please?

```
mouseover: {
				include: true,
				type: 'invisible',
				id: 'mouseover',
				path: 'dijit/_WidgetBase',
				options: {
					map: true,
					startup: function() {
						this.map.on('mouse-over', function(event){
							// set featurelayer
							var parcels = new FeatureLayer('http://maps18.hamilton-city.org/arcgis/rest/services/FlexAppOperationalLayerParcel15/MapServer/1', {
							mode: FeatureLayer.MODE_SNAPSHOT,
							outFields: ['PIN', 'OWNER']
							});
							// set fill symbol for feature layer on mouse-over
							var symbol = new SimpleFillSymbol(
							SimpleFillSymbol.STYLE_SOLID,
							new SimpleLineSymbol(
							SimpleLineSymbol.STYLE_SOLID,
							new Color([255,255,255,0.35]),
							1
							),
							new Color([125,125,125,0.35])
							);
							// associate fill symbol with featurelayer
							parcels.setRenderer(new SimpleRenderer(symbol));
							// set up ToolTip dialog
							var dialog = new TooltipDialog({
							id: 'tooltipDialog',
							style: 'position: absolute; width: 250px; font: normal normal normal 10pt Helvetica;z-index:100'
							});
							dialog.startup();
							// set fill symbol when mouse is over feature
							var highlightSymbol = new SimpleFillSymbol(
								SimpleFillSymbol.STYLE_SOLID,
								new SimpleLineSymbol(
									SimpleLineSymbol.STYLE_SOLID,
									new Color([255,0,0]), 3
								),
								new Color([125,125,125,0.35])
							);
							// close the dialog when the mouse leaves the highlight graphic
							this.map.on('load', function(){
								this.map.graphics.enableMouseEvents();
								this.map.graphics.on('mouse-out', closeDialog);
							});
							// setup popup template for mouse-over event
							//listen for when the onMouseOver event fires on the countiesGraphicsLayer
							//when fired, create a new graphic with the geometry from the event.graphic and add it to the maps graphics layer
							parcels.on('mouse-over', function(evt){
							var t = '<b>Parcel Number: </b>${PIN}<br>' +
							        '<b>Owner: </b>${OWNER}<br>';

							var content = esriLang.substitute(evt.graphic.attributes,t);
							var highlightGraphic = new Graphic(evt.graphic.geometry,highlightSymbol);
							this.map.graphics.add(highlightGraphic);

							dialog.setContent(content);

							domStyle.set(dialog.domNode, 'opacity', 0.85);
								dijitPopup.open({
									popup: dialog,
									x: evt.pageX,
									y: evt.pageY
								});
							});
							// close dialog function
							function closeDialog() {
								this.map.graphics.clear();
								dijitPopup.close(dialog);
							}
							
						});
```

**Comment by roemhildtg** [comment]
```
// close the dialog when the mouse leaves the highlight graphic
this.map.on('load', function() {
  this.map.graphics.enableMouseEvents();
  this.map.graphics.on('mouse-out', closeDialog);
 });
```

Inside the function, `this` is no longer the scope of the widget. Its the scope of that function. So `this.map` doesn't exist. You have to create a closure or use `lang.hitch`.

```
// close the dialog when the mouse leaves the highlight graphic
var _this = this;
this.map.on('load', function() {
  //inside this scope use _this
  _this.map.graphics.enableMouseEvents();
  _this.map.graphics.on('mouse-out', closeDialog);
 });
```

**Comment by kcarrier** [comment]
@roemhildtg - Thank you for your assistance, I was able to get something working.

Here is the code in case any should ever come across this post looking for a working example

```
mouseover: {
    include: true,
    type: 'invisible',
    id: 'mouseover',
    path: 'dijit/_WidgetBase',
    options: {
        map: true,
        startup: function() {
            // set reference to layer by layerid
            var parcels = this.map.getLayer('bcparcels');

            // set up ToolTip dialog
            var dialog = new TooltipDialog({
                style: 'position: absolute; width: 250px; font: normal normal normal 10pt Helvetica;z-index:100'
            });
            dialog.startup();

            // set up fill color of symbol when mouse is over feature
            var symbol = new SimpleFillSymbol(
                SimpleFillSymbol.STYLE_SOLID,
                new SimpleLineSymbol(
                    SimpleLineSymbol.STYLE_SOLID,
                    new Color([255, 255, 255, 0.35]),
                    1
                ),
                new Color([125, 125, 125, 0.35])
            );

            // set up outline color of symbol when mouse is over feature
            var highlightSymbol = new SimpleFillSymbol(
                SimpleFillSymbol.STYLE_SOLID,
                new SimpleLineSymbol(
                    SimpleLineSymbol.STYLE_SOLID,
                    new Color([255, 0, 0]), 3
                ),
                new Color([125, 125, 125, 0.35])
            );

            // enable mouse events on graphics within map
            this.map.graphics.enableMouseEvents();

            // clear graphics and close popup when mouse moves out of features
            this.map.graphics.on('mouse-out', function(evt) {
                this._map.graphics.clear();
                dijitPopup.close(dialog);
            });

            // when mouse is over feature, setup popup attributes, 
            // highlight and fill the graphic, add to map, show popup
            parcels.on('mouse-over', function(evt) {
                var t = '<b>Parcel ID </b>: ${PIN}';
                var content = esriLang.substitute(evt.graphic.attributes, t);
                var highlightGraphic = new Graphic(evt.graphic.geometry, highlightSymbol);
                this._map.graphics.add(highlightGraphic);
                dialog.setContent(content);
                domStyle.set(dialog.domNode, 'opacity', 0.85);
                dijitPopup.open({
                    popup: dialog,
                    orient: ['below-centered', 'above-centered'],
                    x: evt.pageX,
                    y: evt.pageY
                });
            });
        }
    }
},
```

**Comment by Zone14** [comment]
Noobie question here. @roemhildtg indicated the code may be placed in the main `viewer.js` config, under the widgets property or in its own file, like `gis/dijit/mouseover.js`. @kcarrier which method have chosen here? It appears to be contained within the main viewer.js config file but I'm thrown off by 
`path: 'dijit/_WidgetBase',`
I have no idea where this file is. Does it pre-exist in the CMV app? Do I have to create it? 

I've essentially copied @kcarrier code in the main `viewer.js` config, under the widgets property as is and changed the layer ID unsuccessfully.

**Comment by tmcgee** [comment]
@Zone14 Here is a working [demonstration](https://tmcgee.github.io/cmv-widgets/demo.html?config=mousehover) of the mousehover based on the code provided above.

**Comment by Zone14** [comment]
Thanks again @tmcgee ! Don't know where you find the time to help everyone and still get your own work done but thank you.

**Comment by kcarrier** [comment]
Thanks @tmcgee I agree do not know where he finds the time but I will be sure to include more of the code next time so the final solution is easier to understand. I left out the define and functions part of the code @Zone14 my apologies for not getting back sooner.

**Comment by cmccullough2** [comment]
Is there a way to use the mouseover with a point?  I just want a point symbol - nothing special at this time. My format is wrong.  I am getting an Expected ')' error before new SimpleMarkerSymbol(
Code example: 
mouseover: {
                include: true,
                type: 'invisible',
                id: 'mouseover',
                path: 'dijit/_WidgetBase',
                options: {
                    map: true,
                    startup: function () {
                        // set reference to layer by layerid
                        var hover = this.map.getLayer('hover');

                        // set up ToolTip dialog
                        var dialog = new TooltipDialog({
                            style: 'position: absolute; width: 250px; font: normal normal normal 10pt Helvetica;z-index:100'
                        });
                        dialog.startup();
                        domStyle.set(dialog.domNode, 'opacity', 0.85);

                        // set up outline color and fill of symbol when mouse is over feature
                         var highlightSymbol = new SimpleMarkerSymbol(
                            SimpleMarkerSymbol.STYLE_CIRCLE, 10
                            new SimpleMarkerSymbol(
                                SimpleMarkerSymbol.STYLE_CIRCLE, 10
                                new Color([255, 0, 0]), 3
                            ));
												 // enable mouse events on graphics within map
                        this.map.graphics.enableMouseEvents();

                        // clear graphics and close popup when mouse moves out of features
                        this.map.graphics.on('mouse-out', function () {
                            this._map.graphics.clear();
                            popup.close(dialog);
                        });

                        // when mouse is over feature, setup popup attributes,
                        // highlight and fill the graphic, add to map, show popup
                        hover.on('mouse-over', function (evt) {
                            this._map.graphics.clear();
                            var highlightGraphic = new Graphic(evt.graphic.geometry, highlightSymbol);
                            this._map.graphics.add(highlightGraphic);

                            var t = '<b>{INSTLN_ID}</b>:<hr><b>Name: </b>{FEAT_NAME}<br>';
                            var content = lang.replace(t, evt.graphic.attributes);
                            dialog.setContent(content);

                            popup.open({
                                popup: dialog,
                                orient: ['below-centered', 'above-centered'],
                                x: evt.pageX,
                                y: evt.pageY
                            });
                        });
                    }
                }
            },

**Comment by roemhildtg** [comment]
I don't know if it will work after this, but briefly glancing at the code, there's a syntax error, you're missing a comma..

also I think you need to check the parameters for `SimpleMarkerSymbol`, because it looks like your passing a `SimpleMarkerSymbol` to another `SimpleMarkerSymbol` which is probably not correct

```javascript
                         var highlightSymbol = new SimpleMarkerSymbol(
                            SimpleMarkerSymbol.STYLE_CIRCLE, 10 //here 
                            new SimpleMarkerSymbol(
                                SimpleMarkerSymbol.STYLE_CIRCLE, 10 
                            ));
```

**Comment by cmccullough2** [comment]
Thank you!  That was the right clue.  I was also missing another comma after the second 10. 
 var highlightSymbol = new SimpleMarkerSymbol(
                            SimpleMarkerSymbol.STYLE_CIRCLE, 10 //missing comma here 
                            new SimpleMarkerSymbol(
                                SimpleMarkerSymbol.STYLE_CIRCLE, 10 //missing comma here 
                            ));

**Comment by roemhildtg** [comment]
fyi https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by drusexton** [comment]
@roemhildtg @kcarrier has the path: `'dijit/_WidgetBase' `changed? I am trying to implement this with 2.0.0-beta1 and I attempting to do it in the viewer.js without using a mousehover.js file. Although I am unsure of where to point it because this file does not seem to exist in the file structure.

**Comment by tmcgee** [comment]
@drusexton The `dijit` package is part of dojo that is bundled with the Esri JavaScript API. Its location has not changed. Sounds like something else is the issue. Can you post the relevant section of your viewer.js?

**Comment by drusexton** [comment]
@tmcgee 

```
mouseover: {
				include: true,
				type: 'invisible',
				id: 'mouseover',
				path: 'dijit/_WidgetBase',
				options: {
					map: true,
					startup: function() {
						// set reference to layer by layerid
						var parcels = this.map.getLayer('CompanyName');

						// set up ToolTip dialog
						var dialog = new TooltipDialog({
							style: 'position: absolute; width: 250px; font: normal normal normal 10pt Helvetica;z-index:100'
						});
						dialog.startup();

						// set up outline color and fill of symbol when mouse is over feature
						var highlightSymbol = new SimpleFillSymbol(
							SimpleFillSymbol.STYLE_SOLID,
						new SimpleLineSymbol(
							SimpleLineSymbol.STYLE_SOLID,
						new Color([255, 0, 0]), 3
						),
						new Color([125, 125, 125, 0.35])
					);

					// enable mouse events on graphics within map
					this.map.graphics.enableMouseEvents();

					// clear graphics and close popup when mouse moves out of features
					this.map.graphics.on('mouse-out', function() {
						this._map.graphics.clear();
							dijitPopup.close(dialog);
					});

					// when mouse is over feature, setup popup attributes, 
					// highlight and fill the graphic, add to map, show popup
					parcels.on('mouse-over', function(evt) {
						this._map.graphics.clear();
						var t = '<b>Company </b>: ${CompanyName}';
						var content = esriLang.substitute(evt.graphic.attributes, t);
						var highlightGraphic = new Graphic(evt.graphic.geometry, highlightSymbol);
						this._map.graphics.add(highlightGraphic);
						dialog.setContent(content);
						domStyle.set(dialog.domNode, 'opacity', 0.85);
						dijitPopup.open({
							popup: dialog,
							orient: ['below-centered', 'above-centered'],
							x: evt.pageX,
							y: evt.pageY
						});
					});
				}
			}
		}
```

**Comment by drusexton** [comment]
@tmcgee when you say _WidgetBase.js is part of the the `dijit` package that is part of dojo ( bundled with the Esri JavaScript API ) and has not changed, does this mean that the file is being referenced some place else such as an ESRI sever and therefore the file path would never change? Or are you suggesting it should be included with the files when you acquire CMV?

**Comment by tmcgee** [comment]
@drusexton It is loaded with the Esri JavaScript API. That could be from the Esri server or your own local copy of the API. There is nothing more you need to include to use modules from the `dijit` package/namespace.

I don't see anything wrong with your widget configuration. It includes references to other modules like `dijitPopup` and `Color` and a few others that would need to included at the top of the viewer.js.

I referenced above in this conversation a complete working example. Here's the [demo](https://tmcgee.github.io/cmv-widgets/demo.html?config=mousehover) and here's the [configuration file](https://github.com/tmcgee/cmv-widgets/blob/master/config/mousehover.js). You should be able to use your layer instead of the parcel layer in that example to test the complete solution.

**Comment by drusexton** [comment]
@tmcgee Should it make a difference that I am attempting to apply the mouse hover to a dynamic service (operational layer) and opposed to a feature service (which is used in the demo)?

**Comment by tmcgee** [comment]
yes it makes a difference. you cannot use this approach to do a mouse over for a dynamic layer. That would require a somewhat different widget.

The mouse over utilizes the individual feature graphics of the feature layer. Each graphic of a feature layer is available on the maps and includes the geometry (for highlighting) and attributes (for the tool tip).

For a dynamic layer, there are no individual features or graphics on the map to mouse over. A dynamic layer is just a single image (a map tile) received from the server displaying all the sublayers symbolized on that one image. A mouseover for one (or more) sublayers in a dynamic layer is possible but requires more complex code and a trip to the server to get the details about the feature(s) under the mouse cursor.

**Comment by drusexton** [comment]
@tmcgee Luckily I am only in need of doing this for 1 layer, and I do have access to the service. Is there an documentation that you can perhaps point me towards that might help me do this for a dynamic service? I suppose I could also switch this to a feature layer...

**Comment by kcarrier** [comment]
Dru I think you just need to reference the feature layer within the map
service. Doing it this way should act similar to a feature service and
expose the needed functionality for the mouse hover event.

For example,

http://domain.com/arcgis/rest/services/YourServiceName/MapServer/1

**Comment by tmcgee** [comment]
@drusexton As @kcarrier mentioned, a feature LAYER in the map can be from a single sub layer from a dynamic Map service. You do not need to create a Feature Service to have a feature layer.

**Comment by JhopStl** [comment]
I'm having issues when implementing this with point features.  The sticking point seems to be clearing the dialog box when moving from point to point:
`this.map.graphics.on('mouse-out', function() {
							this._map.graphics.clear();
							popup.close(dialog);`

Screenshot: 
![hover1](https://user-images.githubusercontent.com/16945459/33290986-0ca49c8e-d38a-11e7-91c0-6e798cf2cece.PNG)

Any ideas on what could be causing this, or if there are other ways to force close the box upon mouseout?

Thanks,

Jesse

**Comment by JhopStl** [comment]
I fixed this issue by adding a mouse-out event handler after the dialog box is opened.


              mouseover: {
                include: true,
                type: 'invisible',
                id: 'mouseover',
                path: 'dijit/_WidgetBase',
                options: {
                    map: true,
                    startup: function () {
                        // set reference to layer by layerid
                        var parcelHover = this.map.getLayer('parcel_sales');

                        
                  var dialog = new TooltipDialog({
                style: 'position: absolute; width: 200px; font: normal normal normal 10pt Helvetica;z-index:100'
                        });
			console.log("Created Tooltip");
                        dialog.startup();
                        domStyle.set(dialog.domNode, 'opacity', 0.75);

			//attach mouse-over event to parcel sales layer
                        parcelHover.on('mouse-over', function (evt) {
                            var t = '<b>Parcel ID </b>: {Account}<br />' +
									'<b>Price </b>: ${Price}<br />' +
									'<b>Date </b>: {sale_dateStr}<br />' +
									'<b>Style </b>: {Style}<br />';
                            var content = lang.replace(t, evt.graphic.attributes);
                            dialog.setContent(content);
			console.log("Open Dialog");
                            popup.open({
                                popup: dialog,
                                orient: [],
                                x: evt.pageX,
                                y: evt.pageY,
								
                            });
							
                        });
			parcelHover.on('mouse-out', changeHandler);
			function changeHandler(evt) {
			    console.log("Closing");
			    popup.close(dialog)
			};
                    }
							
                }		
	}`
