### ISSUE TITLE
Editor-attachment

### ISSUE THREAD

**Issue by cici004** [cmv/cmv-app#640]
Hi I was trying to use attachment function when I was editing individual feature, but when I click on stop editing, the attachment was gong. How can I fix that problem?

**Comment by roemhildtg** [comment]
I've never seen that problem before, are you using the cmv editor widget? The cmv editor widget uses the default esri editor widget behind the scenes. 

- For starters, can you post your relevant code? 
- Also can you check your network requests during the attachment editing process and post any potential error messages?

**Comment by roemhildtg** [comment]
@cici004 I'm going to close for now, if you have further issues or can help us reproduce the issue, feel free to reopen.
