### ISSUE TITLE
how to change background color of titlePane 

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#646]
All titlePanes like Legend, Help etc., they have silver color as Title background, can I make it different color?

**Comment by tmcgee** [comment]
@JudyZhou you can change any colors you like based on the css classes that dojo adds to the HTML elements. Here's where that color is [set](https://github.com/cmv/cmv-app/blob/develop/viewer/css/cmv-theme-overrides.css#L10-L13). You can override that in your own css file.
