### ISSUE TITLE
Print fails when feature layer point is identified

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#647]
When the identify window is open on a point feature layer, the print widget fails, at least on arcgis server 10.4. 

Note that this only occurs on feature layers of type point. The error message printed by arcgis server is:
```
	Error executing tool. Export Web Map Task Job ID: j0e68064e005b49ffa960aa2692d79638 : Layer "mapCenter_graphics": ᧖ Failed to execute (Export Web Map). Failed to execute (Export Web Map Task).
```

![image](https://cloud.githubusercontent.com/assets/5471079/21028705/f882c536-bd5b-11e6-9119-2cd4bcedd840.png)

**Comment by tmcgee** [comment]
This sounds like an issue with the Print Service?

**Comment by roemhildtg** [comment]
Not sure, I guess it could be. Its the default print service that comes with the arcgis server. The only difference is its secured. Its such an isolated event I was just curious if anyone else had dealt with it.

**Comment by tmcgee** [comment]
I am curious if the issue would disappear if you switched to an older version of the Esri JS API.

**Comment by roemhildtg** [comment]
It doesn't seem to be related to the print service or the api version, I tried pasting the web map json into the public print service, same error message. I also tried the 3.17 version of the api. 

This is what the json looks like to cause the error: https://gist.github.com/roemhildtg/8eaa2f0e5ac7e02c5748d974add5a5dc

**Comment by roemhildtg** [comment]
The error seems directly related to the identified point layer: 
```json
{
        "id": "mapCenter_graphics",
        "opacity": 1,
        "minScale": 0,
        "maxScale": 0,
        "featureCollection": {
            "layers": [{
                "layerDefinition": {
                    "name": "pointLayer",
                    "geometryType": "esriGeometryPoint"
                },
                "featureSet": {
                    "geometryType": "esriGeometryPoint",
                    "features": [{
                        "geometry": {
                            "x": -10383352.152273616,
                            "y": 5510635.822251622,
                            "spatialReference": {
                                "wkid": 102100,
                                "latestWkid": 3857
                            }
                        },
                        "symbol": {
                            "color": [0, 0, 0, 0],
                            "size": 12,
                            "angle": 0,
                            "xoffset": 0,
                            "yoffset": 0,
                            "type": "esriSMS",
                            "outline": {
                                "color": [0, 255, 255, 255],
                                "width": 1.5,
                                "type": "esriSLS",
                                "style": "esriSLSSolid"
                            }
                        }
                    }]
                }
            }]
        }
    },
```

**Comment by roemhildtg** [comment]
Sounding more like an esri bug. I'm not too concerned about it since there's an easy workaround...just close the identify popup.

**Comment by roemhildtg** [comment]
I'm going to close this for now I think, if anyone else experiences it they can reopen.
