### ISSUE TITLE
Trying to figure out event where add and delete occurs in editor.js

### ISSUE THREAD

**Issue by vamsi0406** [cmv/cmv-app#653]
I am trying to get small trigger in editor widget when a user tries to add a trail or road , I was able capture the event where edit of trail or roads occurs in editor.js 
Is there way where I can find these events happen.

**Comment by roemhildtg** [comment]
The default editor widget is very limited. The only event I can see in the api is the `load` event which doesn't help you...https://developers.arcgis.com/javascript/3/jsapi/editor-amd.html

It might be in your best interest to create a custom widget to do the editing for your use case.

**Comment by tmcgee** [comment]
@vamsi0406 First off, I agree it is best to create a custom widget as the default Esri editor widget is limited and flawed (in my opinion). Having said that, one option might be for you to listen to the ['before-apply-edits'](https://developers.arcgis.com/javascript/3/jsapi/featurelayer-amd.html#event-before-apply-edits) on the feature layer.

**Comment by saurabhgis** [comment]
@vamsi0406  I have also tried to add save button, and on click save button final save in geodatabase but not succeed..when we add new feature a progress automaticall started and directly update in database.. I am not to find solution how to stop this, event only fired when we click on save button.
