### ISSUE TITLE
how to add my basemap to the basemap list?

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#654]
Hi, I added my basemap PWECartograph like this, but it doesn't display, Could you please help?
 basemapsToShow: ['streets', 'satellite', 'hybrid', 'topo', 'lightGray', 'gray', 'osm', 'oceans','PWECartograph'],
basemaps: { // agol basemaps
            streets: {
                title: 'ESRI Streets'
            },
            satellite: {
                title: 'ESRI Satellite'
            },
            hybrid: {
                title: 'ESRI Hybrid'
            },
            topo: {
                title: 'ESRI Topo'
            },
            gray: {
                title: 'ESRI Gray'
            },
            oceans: {
                title: 'ESRI Oceans'
            },
            osm: {
                title: 'Open Street Map'
            },
            PWECartograph: {
                title: 'PWE Cartograph',
                basemap: new Basemap({
                    id: 'PWECartograph',
                    layers: [new BasemapLayer({
                        url: 'http://pwecohgims.houstontx.gov/arcgis/rest/services/Basemap/basemap_cartographic/MapServer'
                    })]
                })
            }

**Comment by ERS-Long** [comment]
does not look like we can access this url
http://pwecohgims.houstontx.gov/arcgis/rest/services/Basemap/basemap_cartographic/MapServer

**Comment by roemhildtg** [comment]
Looks like that code works for me too.

**Comment by ERS-Long** [comment]
yes, it does work me too, but you have to zoom in to Houston area

![image](https://cloud.githubusercontent.com/assets/5911272/21368660/2a060ff2-c6c9-11e6-86c5-03bbf78f7274.png)

**Comment by JudyZhou** [comment]
@ERS-Long @roemhildtg, that is interesting. I did also like this, is it correct?
define([
    'esri/dijit/Basemap',
    'esri/dijit/BasemapLayer',
    //'esri/layers/osm'
], function (  Basemap, BasemapLayer, osm  )

**Comment by ERS-Long** [comment]
if you dont need osm module, you should do something like the following

define([
'esri/dijit/Basemap',
'esri/dijit/BasemapLayer'
//'esri/layers/osm'
], function ( Basemap, BasemapLayer /*, osm*/ )

**Comment by JudyZhou** [comment]
@ERS-Long yes, I removed osm already

**Comment by JudyZhou** [comment]
but still not work

**Comment by JudyZhou** [comment]
is there any other code I need to modify?

**Comment by JudyZhou** [comment]
it is weird.  
even I add the my basemap url to replace hybrid or satellite or streets, display same as ESIR's in map viewer.

**Comment by JudyZhou** [comment]
after I changed to mode: 'custom', basemap tools doesn't open in map viewer anymore. Please help!

**Comment by JudyZhou** [comment]
which file I should modify? basemaps.js in config folder or in gis/dijit ?

**Comment by ERS-Long** [comment]
basemaps.js in config folder.

**Comment by tmcgee** [comment]
@JudyZhou you can mix Esri and custom basemaps like that using the current version of cmv in the develop branch. In prior versions, you could not mix them. I can tell from the screenshot provided by @ERS-Long, he tested using the current version. Based on your prior questions, I believe that you are using that current version so this comment may not be relevant to you but perhaps for others reading this issue.

**Comment by JudyZhou** [comment]
@tmcgee  I am not sure where to download current version. could you let me know? also,  I did change mode to custom like this : mode: 'custom',//'agol', is that correct? @ERS-Long?

**Comment by JudyZhou** [comment]
@tmcgee @ERS-Long @roemhildtg
 I see Basemaps.js in dijits folder also include code like this:
mode: 'agol',
        title: i18n.title,
        //baseClass: 'gis_Basemaps_Dijit',
        //buttonClass: 'gis_Basemaps_Button',
        //menuClass: 'gis_Basemaps_Menu',
        mapStartBasemap: 'streets',
        basemapsToShow: ['streets', 'satellite', 'hybrid', 'topo', 'gray', 'oceans', 'national-geographic', 'osm'],
....
should I change this code?
**could anyone of you all  kindly send me or attach to here the code for two basemap.js in config and dijits folder?**

**Comment by roemhildtg** [comment]
@JudyZhou you can view and download the latest code from github at any time, which has the code you requested. You just need to switch from the "master" branch to the "develop" branch. 

![image](https://cloud.githubusercontent.com/assets/5471079/21393741/4b62b186-c75b-11e6-9545-ad8561b56878.png)

We don't recommend changing any of the code in the `js/gis/dijit/` folders because it will make updating to new cmv releases more difficult. Instead, and what makes cmv so great, is that you can put these properties in your config file, which are essentially **overriding** the properties in the main widget.

**Comment by tmcgee** [comment]
@JudyZhou I provided instructions to you on how to download the develop version in #628. You should not have any reason to edit the Widget (in dijits folder). Everything is handled in the config file.
