### ISSUE TITLE
Add Quick Help on Widget Title Pane?

### ISSUE THREAD

**Issue by JhopStl** [cmv/cmv-app#657]
I'm looking for help on adding a "quick help" link similar to each individual widget (similar to what Larry Stout did at Hamilton County: http://gis.hamiltoncounty.in.gov/jsViewer3/)

![hc_quickhelp](https://cloud.githubusercontent.com/assets/16945459/21661092/fbda458c-d297-11e6-9a59-f453b72ddf0f.PNG)

To get me started, is there another/ more up-to-date way to do this or is sticking to the Hamilton County code my best bet?

Thanks

**Comment by tmcgee** [comment]
@JhopStl I'm not aware of a more up-to-date way to do this. Larry had a heavily customized cmv Controller that handled this a few other things.

Today, I would probably handle this with an invisible widget. These execute after the titlePane widgets have been created. That widget would query the dom for the relevant titlePane nodes and adds the icons with click events.

**Comment by JhopStl** [comment]
Thanks Tim
