### ISSUE TITLE
how to remove some geo-information fields from Identify window?

### ISSUE THREAD

**Issue by JudyZhou** [cmv/cmv-app#658]
I have unchecked ObjectID from my map document, but it still displays in Identify window. since too many laters need to identify, I want all layers can be identified by default without configuring anything in identify.js. How to remove ObjectID and shape fields from Identify window for all layers? or is anyway to use ArcGIS online webmap? Please help!

**Comment by roemhildtg** [comment]
> How to remove ObjectID and shape fields from Identify window for all layers?

There isn't a super easy way to do this, you'd have to configure your `fieldInfos` property for each layer.

> or is anyway to use ArcGIS online webmap?

You can use web maps with the latest version of the develop branch. You just need to include the webmap id [look at this line for details](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L81-L82)

**Comment by JudyZhou** [comment]
thank you @roemhildtg. I am not sure where to config fieldInfos for each layer? in what file? 
And I don't quite understand the viewer.js file for webmap from your link. not sure that is a working file or not.

**Comment by tmcgee** [comment]
@JudyZhou If you don't want to configure the fieldInfos array for each layer/sublayer in identify.js, you can exclude fields for all layers by including them in the array appropriately named [`excludedFields`](https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/Identify.js#L45-L50).
