### ISSUE TITLE
Identify widget: Pulling info from xml file into custom identify table

### ISSUE THREAD

**Issue by Wernazuma** [cmv/cmv-app#672]
I have a huge XML file that contains descriptions of items in our database. The <div> tags have a key attribute that matches a column value of the corresponding identified feature. Usually, I'd do such a trick using PHP and an XSL file. Does anybody have an idea how to make such a thing work eithin the CMV App Viewer Identify widget?

Here's an example of what I'm talking about;

DICTIONARY.XML:
```
...
<div key="JUGUGUCT"><p>CHIMALTENANGO, Provincia y Corregimiento del Reyno de Goatemala, situado en el valle de esta Capital: es muy amena, fértil y poblada de Indios.</p></div>
...
```

When identifying Chimaltenango on the map, it has the value "JUGUGUCT" in the field [Entidad_ID].
The idea is to have the pop up always display the content of the div with the key attribute that matches [Entidad_ID] of the clicked feature.

**Comment by roemhildtg** [comment]
You could probably use the `content` property of your `identifies` object to do this. There's some examples in the latest docs: https://docs.cmv.io/en/latest/widgets/Identify/

Your content function will do something like this: 

1. Retrieve and parse the xml data file
2. Extract the property you need using the key
3. Return a deferred that resolves to the property html. 

https://developers.arcgis.com/javascript/3/jshelp/intro_formatinfowindow.html provides details on the content function. 

> Deferred Object
In some cases, the content you want to display is not immediately available. It may be content that you need to download from a server using esri/request, which returns an instance of dojo/Deferred. When a feature is clicked, a deferred is returned by a custom function. Once the deferred is resolved, the info window will update accordingly.
