### ISSUE TITLE
Identify CSS Error and Popup Help

### ISSUE THREAD

**Issue by drusexton** [cmv/cmv-app#674]
Please correct me if I am wrong, but I noticed the documentation on the CMV site for using the formatter function in a popup seems to have an error in the CSS. Please see the screenshot below:

![cmv_identify_csserror](https://cloud.githubusercontent.com/assets/14102180/23217262/a946827a-f8e6-11e6-8ce5-36dce37e160d.jpg)

Furthermore I am attempting to format the popup window to show the field name and not the alias, but I have been unsuccessful, and I am beginning to wonder if I am even on the right track. my code is below, and help is appreciated!

![cmv_identify_error](https://cloud.githubusercontent.com/assets/14102180/23217452/3f3d110e-f8e7-11e6-911e-26701d889c43.jpg)

@kcarrier
@tmcgee

**Comment by tmcgee** [comment]
@drusexton you don't need a custom formatter to label a field differently in the Identify Popup. Just use the `label` property like this:

``` javascript
{
    fieldName: 'CurrentOwnerName',
    label: 'Current Owner Name',
    visible: true
},
```

Formatters are more typically used to format the value within the field for display in the Popup window. Creating a clickable url from multiple attributes is a common example.

**Comment by drusexton** [comment]
@tmcgee Thanks for the tip! I knew I was over thinking this...
