### ISSUE TITLE
Find Widget - Grid doesn't display data in row

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-app#683]
Hi,

I am using Find widget, but grid doesn't display the data, I am getting the search result found some number and features highlighted on map, by clicking on the grid row it is zoom in to that features as well but he data doesn't display in grid row. I checked there is no null values of road name in the attributes.

I checked in console there were no errors. Here is the screenshots below:

![find](https://cloud.githubusercontent.com/assets/6058868/23497305/83088740-ff33-11e6-94b9-05e5c9463a9a.png)
![find_console](https://cloud.githubusercontent.com/assets/6058868/23497306/8308c4e4-ff33-11e6-8482-0be0781b3f6b.png)

**Comment by saurabhgis** [comment]
Hi Mayur check your css. it might be color issue

**Comment by mayur9785** [comment]
Hi Saurabh,

Thanks for reply. I checked css but still same, data doesn't display in grid..

**Comment by mayur9785** [comment]
Ok I got it. I had to give alias name of the field and it's working fine. 👍 Thanks :)
