### ISSUE TITLE
Attribute Table Resizing issue

### ISSUE THREAD

**Issue by saurabhgis** [cmv/cmv-app#684]
Hi,  I am facing this resizing related problem in attribute widget ( Widget some fields are not bind but when when we change browser size fields are bind). @roemhildtg, @tmcgee

**Comment by tmcgee** [comment]
@saurabhgis This should probably be asked in my widget repo but will give a brief response here. Earlier this week I committed a couple of updates to the Attributes Tables widget. One was specific to resizing of the tabContainer which appears to be related to the newest dojo dgrid provided with the Esri JS API. Try out the newest widget version and see how it goes. If problems continue, please request additional assistance in my repo.
