### ISSUE TITLE
Question: Can I run out of the zip?

### ISSUE THREAD

**Issue by gisnovice** [cmv/cmv-app#697]
I am using the new CMV viewer 2.0 and was wondering if I look at the index.html out of the folder into Google Chrome, should I see the map just like the demo? Or do I need to put it on a server of some sort? Thank you.

**Comment by drusexton** [comment]
@gisnovice Someone can correct me if I am wrong, but CMV does not run in your browser by just opening the files. You can use and Integrated Development Environment (IDE) such as Aptana Studio to test your applications on your local machine. However you need a server to serve it to any clients you want to be able to access it outside of your local machine. If you want something that will run in your browser you may want to look into OpenLayers or Leaflet.

**Comment by gisnovice** [comment]
No that's what I thought, that I needed an IDE. Thank you.

**Comment by kcarrier** [comment]
You don't need an IDE you can use notepad to edit and just enable/install a
web server like IIS, it comes with windows.

**Comment by drusexton** [comment]
@kcarrier tht is good to know! Thanks for sharing...

**Comment by roemhildtg** [comment]
I run a development IIS server to test cmv. Also `npm install live-server` is good. https://www.npmjs.com/package/live-server
