### ISSUE TITLE
App Title, Header Title and Header Subtitle Override?

### ISSUE THREAD

**Issue by drusexton** [cmv/cmv-app#698]
Has anyone else been experiencing any "override" issue with their custom Titles? For example try the public URL:

[http://bhgis.org/apeg/test/viewer/](http://bhgis.org/apeg/test/viewer/)

Watch closely as the titles quickly override to the default. @tmcgee you mentioned I needed to customize these, but as you should be able to see I already have. Does anyone think it could be the image size? I literally pulled the image straight from the source, and therefore didn't do any resizing. However I did the same thing with 1.3.4 and didnt have any issues so I doubt this is the culprit.

Thanks in advance for any help!

**Comment by roemhildtg** [comment]
I can see you haven't changed your default titles: 
http://bhgis.org/apeg/test/viewer/js/config/nls/main.js

**Comment by tmcgee** [comment]
Since you have modified the title in your index.html page, you can completely remove the titles object in your viewer.js file. This is something that also applied to version 1.3.4 so nothing new for version 2.0.

**Comment by drusexton** [comment]
@roemhildtg @tmcgee 
Gentleman, 

Thanks for pointing this out!
