### ISSUE TITLE
Start the app with panes closed

### ISSUE THREAD

**Issue by mtabdar** [cmv/cmv-app#703]
This is maybe not a bug so sorry if this is not the right place to ask but
Could anyone tell me if there is a way to "Start the app with panes closed" on pc
I noticed it alreay happens in mobile size screen.
Thanks

**Comment by tmcgee** [comment]
@mtabdar To have the left pane closed when the application starts, you can change the pane configuration in `viewer.js`:

``` javascript
panes: {
    left: {
        open: false
    }
},
```

With the default css, the above configuration will cause the pane to open for a split second, then collapse. To override this, you can include the style parameter below:

``` javascript
panes: {
    left: {
        open: false,
        style: 'display:none'
    }
},
```

**Comment by mtabdar** [comment]
Thanks a lot.
I tried it for left pane and it was a success but since i am using bottom pane for attributetable widget it doesnt work
I tried borh with style parameter and without it and The table doesnt appear although the query in the widget works and result is displayed in the map.

**Comment by tmcgee** [comment]
Sounds like the panes are working as I would expect but the attribute tables widget is not configured properly.

Your bottom pane should be configured like [this](https://github.com/tmcgee/cmv-widgets/blob/master/config/search.js#L29-L40) and then your attributes table widget should have [these properties](https://github.com/tmcgee/cmv-widgets/blob/master/config/search.js#L106-L107) in the configuration.

**Comment by mtabdar** [comment]
Yes thank you it worked fine.
In viewer.js in panes i put none instead of false and it worked.
