### ISSUE TITLE
add coordinates to identify popup

### ISSUE THREAD

**Issue by mtabdar** [cmv/cmv-app#709]
hi,
i am wondering if there is a way to add coordinates of a clicked point to identify popup window. something like in arcmap maybe?
- i tried to use [this](https://github.com/BrianBunker/cmv-widgets/tree/master/MapNavigationHash) with no success.
thanks

**Comment by roemhildtg** [comment]
You can add a "virtual field" to your `identifies` `fieldInfos` that would do this with a formatter. 

```javascript
fieldInfos: [{
    visible: true,
    fieldName: 'Coordinates',
    formatter: function(none, attrs, geom){
        return geom.x + ', ' + geom.y;
    }
}]

**Comment by tmcgee** [comment]
@roemhildtg that would only work when Identifying point features.

@mtabdar Will this widget meet your needs? https://github.com/tr3vorm/cmv-projections-widget

**Comment by mtabdar** [comment]
Hi.thanks for the insights.
I think roemhildtg's way is closer to what i have in mind but as tmcgee pointed it has a big shortage. (I have not tried it yet)
On the other hand tr3vorm's projectios widget is fantastic. Could it be loaded inside identify?

**Comment by roemhildtg** [comment]
Oh I had interpreted your question as you have a point feature you are identifying and would like to display the coordinates of the point in the popup. 

The identify popup formatters don't provide access to the coordinate of the mouse click...maybe they should @tmcgee ?

**Comment by mtabdar** [comment]
Thanks
@roemhildtg i applied your way for one of my point layers. The coordinates field title appears but instead of coordinates i get "undefined". Do you have any idea why?

**Comment by tmcgee** [comment]
Related:

These are formatter functions I have used to display the Latitude and Longitude for a point feature when the spatial reference for the point (based on the map's SR) is web mercator:
``` javascript

latlng: function (value, attributes, geometry) {
    if (geometry && geometry.type === 'point' && geometry.spatialReference.wkid === 102100) {
        var pt = webMercatorUtils.webMercatorToGeographic(geometry);
            var lat = number.format(pt.y, {
                places: 6
            });
            var lng = number.format(pt.x, {
                places: 6
            });
            return 'Latitude: ' + lat + '<br/>Longitude: ' + lng;
        }
    return '';
},

latitude: function (value, attributes, geometry) {
    if (geometry && geometry.type === 'point' && geometry.spatialReference.wkid === 102100) {
        var pt = webMercatorUtils.webMercatorToGeographic(geometry);
        return number.format(pt.y, {
            places: 6
        });
    }
    return '';
},

longitude: function (value, attributes, geometry) {
    if (geometry && geometry.type === 'point' && geometry.spatialReference.wkid === 102100) {
        var pt = webMercatorUtils.webMercatorToGeographic(geometry);
        return number.format(pt.x, {
            places: 6
        });
    }
    return '';
},
```

`number` and `webMercatorUtils` are modules defined at the top of identify.js:

``` javascript
define([
    ...
    'dojo/number',
    'esri/geometry/webMercatorUtils'
    ...
], function (
    ...
    number,
    webMercatorUtils
    ...
) {
```

**Comment by mtabdar** [comment]
thank you very much. i will give it a try and report back.
