### ISSUE TITLE
Exclusion of Attributes of Dynamic Layers

### ISSUE THREAD

**Issue by RiverGlen** [cmv/cmv-app#720]
__How often can you reproduce it?__ 

- [X ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
I would like to get the identify tool to be able to exclude attributes on dynamic mapservice layers.  In our mash ups, we utilized some external services and we don't want to show all the attributes of specific layers of those services in the identify popup windows.    I have not been successful at configuring the identify.js to do this. Can you direct me to the best way to configure or code this.

Thanks, Glenn

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/guresequba/edit?js,output)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 
| Browser                 |
| Operating system |

**Comment by roemhildtg** [comment]
What have you tried with your identify config file? 
If you use the `fieldInfos` property to pass your array of fields, it will only display the fields you specify. 

[here's some docs on this topic](https://docs.cmv.io/en/latest/widgets/Identify/#identifies-object)

**Comment by RiverGlen** [comment]
Greg, thanks for the reply.   Below is an example code from the fieldinfos:

fieldInfos: [{
            
            fieldName: 'FACILITYID',
            label: 'Facility ID',
            visible: true
    }

I added this code for all attributes and changed "visible: false" for attributes I don't want to see.  That seems logical but didn't make a difference for me, the attributes were still visible in the popup.   It seems I could add a parameter under fieldinfos like:

fields: 'facilityID', 'attribute2', 'attribute4',

And that would make 'attribute3' dissappear.  But, I am not sure how to change code to do that. It seems it would be easier to do such instead of configuring every attribute to be visible: true or visible: false.  Can you direct me to where I would need to add the code to make layer unique attributes invisible?  Thank you for your assistance. ~Glenn

**Comment by roemhildtg** [comment]
Yeah, the esri api is slightly verbose when it comes to customizing fields. But you don't need to include fields that you don't want to show. For example:

```javascript
fieldInfos: [{
    fieldName: 'attr1',
    visible: false
}, {
    fieldName: 'attr2',
    visible: true
}]
```

will have the exact same effect as only specifying the fields you want:
```javascript
fieldInfos: [{
    fieldName: 'attr2',
    visible: true
}]
```

It sort of sounds like you might be using the wrong layer and sublayer id above the fieldInfos. 

You should have something like this:
```javascript
identifies: {
    assets:
        5: {
            fieldInfos: [{ .......}]
        }
    }
}
```

Either that or you might be using sublayer id 0. There was a bug with that in the beta version of 2.0 that is now fixed in the develop branch.

**Comment by RiverGlen** [comment]
Thank you.  I am using the 2.0 version but make sure I have the develop branch.  Let me putts with your guidance above, make sure the id 0 bug isn't effecting what I am doing, I have the right layer/sublayer id, and get this to work for me.   And I will follow up.

And just to note, you shouldn't be working on the weekend, what's wrong with you?

**Comment by roemhildtg** [comment]
lol, I know. But neither should you :smile:
