### ISSUE TITLE
Align Legend images horizontally

### ISSUE THREAD

**Issue by srinipalavalli** [cmv/cmv-app#727]
Hi,

Is there a way to list the legend images in a layer horizontally in Legend Control?

currently its listing the images vertically.

**Comment by tmcgee** [comment]
@srinipalavalli There is no configuration for thisin the Esri Legend Widget that I know of.
You might be able to achieve what you want by overriding some of the properties in the css classes for the [Legend widget](https://developers.arcgis.com/javascript/3/jsapi/legend-amd.html)
