### ISSUE TITLE
CMV Team

### ISSUE THREAD

**Issue by drusexton** [cmv/cmv-app#732]
@tmcgee @roemhildtg @DavidSpriggs @btfou @jebu75 

All,

I am not sure that this is the proper platform for this sort of question, so I apologize in advance. I am involved with a professional organization called AOGDP or the [Appalachian Ohio Geospatial Data Partnership](http://www.geospatialpartnership.org). The organization is made up of members from Ohio's 32 Appalachian counties. We strive to foster data standards in the region, but also serve as a support group to help each other grow. Web mapping applications is something we all aim for, but some of us lack the resources, and sometimes the skills. I first heard of CMV at an Ohio Chapter of URISA workshop a few years ago from @kcarrier. However I have only begun to use it this year. Myself and several of my colleagues have liked what I been doing, and also want to learn more. I feel perfectly comfortable walking them through it, but at the same time we are looking to bring presenters to our AOGDP meetings who could show us some neat stuff. Therefore I proposed we reach out and see if anyone of you have ever presented CMV to a group, or if you might be interested. We would like to explore bringing a member from the CMV team here. Of course we would pay for travel, speaking, lodging and possibly meals. 

Thoughts? 

Thanks...

**Comment by roemhildtg** [comment]
@drusexton that's a good idea!  I could possibly, since I'm probably the closest 😄 (Minnesota). I've introduced several organizations to cmv, and always enjoy meeting new geographers. I'd just need some time to plan it out so I can get off for work, etc. What sort of time frame are we looking at?

**Comment by tmcgee** [comment]
@roemhildtg when considering this myself, I looked at the dates [here](http://www.geospatialpartnership.org/calendar/upcoming/). @drusexton can confirm if that's one of those meetings is what they are looking for. I am happy to be an alternate if you can't make the dates work. Travel is definitely further for me but not as far as @DavidSpriggs!

@drusexton My 2 sons and I are working remotely on CMV projects with a company near Columbus that @kcarrier introduced me to. His presentation must have been a good one! :smile:

**Comment by drusexton** [comment]
@roemhildtg @tmcgee @DavidSpriggs I am delighted to hear that you all would be willing to come out here and present CMV and the work done by your team. I need to work out the logistics with the AOGDP leadership, and get back to you with a specific date.

A few things that will help us: 

Are there any dates that would definitely NOT work for you?
How much $ would you want for presenting?

Also if you all would like to discuss this further via email as opposed to this thread, please email me your contact info at dsexton@buckeyehills.org. I will close this after you email me. Thanks again fellas!

**Comment by drusexton** [comment]
@roemhildtg @tmcgee We are still working on the logistics. One of our members suggested we perhaps bring you to our State GIS Conference as a presenter, or perhaps at our education series which we host in the spring. I will keep you all informed, as soon as I have more detail worked out.

**Comment by kcarrier** [comment]
@roemhildtg <https://github.com/roemhildtg> @tmcgee
<https://github.com/tmcgee> - This could be something we do in the fall,
the president of urisa was trying to get me to line something up for the
fall. Dru shoot me an email if you would like to discuss further.

**Comment by drusexton** [comment]
@roemhildtg @tmcgee We are probably thinking about October/November or in the Spring of next year. We are curious how much a you guys might want to be compensated, aside from travel and lodging.

**Comment by drusexton** [comment]
I am going to close this, but come back to it at some point. I would still be interested to know if you gentleman would like to do something like this.
