### ISSUE TITLE
CMV report PDF

### ISSUE THREAD

**Issue by FedwaSlimani** [cmv/cmv-app#733]
when i do a spatial or attribute search i want to upload a pfd report wich contains attributes tables of the search and the map. is there any widget or way to do it ?

**Comment by roemhildtg** [comment]
The [Report widget](https://github.com/tmcgee/cmv-widgets#report) might be a good starting point for you.

**Comment by FedwaSlimani** [comment]
i tried but it doesn't work, i want a report of the results of spatial and attributes tables, including the map!!

**Comment by tmcgee** [comment]
@FedwaSlimani The report widget can create a report that includes a map and tabular results. I don't have a public example but it can definitely be done.

**Comment by FedwaSlimani** [comment]
@tmcgee thank you for your answer, I tried to do it but i failed :/ which configuration I must do to report the map with results ?

**Comment by tmcgee** [comment]
@FedwaSlimani The example report configuration for the report widget includes a [map](https://github.com/tmcgee/cmv-widgets/blob/master/config/reportWidget.js#L173-L182) and [attributes](https://github.com/tmcgee/cmv-widgets/blob/master/config/reportWidget.js#L189-L400).

I also remembered that I wrote a detailed description of how to use a featureset (multiple records) with a map in this [issue](https://github.com/tmcgee/cmv-widgets/issues/99).
