### ISSUE TITLE
using internal dojo structure for other applications

### ISSUE THREAD

**Issue by pri0ri7y** [cmv/cmv-app#737]
__Description:__
Is it alright if I can replicate the internal structure of cmv application for openlayers by giving due credit to this team ?

**Comment by roemhildtg** [comment]
Yes, for sure. If you would like to use cmv as a starting point for your application, that is perfectly fine. Someone else has also started on this: https://github.com/vojvod/ocmv

**Comment by pri0ri7y** [comment]
thx !
