### ISSUE TITLE
Navigation Tool  bar

### ISSUE THREAD

**Issue by FedwaSlimani** [cmv/cmv-app#738]
why navigation toolbar doesn't appear on the map ? I put code on my application and paste the widget in the viewer but still not working !!

**Comment by roemhildtg** [comment]
Please post the code you are using to produce the problem, and any relevant screenshots and error messages in the browser console. 

Also please link to the widget that you're discussing.

**Comment by FedwaSlimani** [comment]
@roemhildtg this is the link of the widget i used https://github.com/friendde/ArcGIS_JS_NavigationTools i have no error in this console

**Comment by tmcgee** [comment]
@FedwaSlimani Please post the configuration for the widget from your viewer.js.

That widget is pretty old but I believe it still works in current versions of CMV though not 100% certain. I haven't looked at that one for a while.

**Comment by FedwaSlimani** [comment]
this is the code of the widget in the folder config/viewer.js
//Navtools
            navtools: {
            include: true,
            id: 'navtools',
            type: 'titlePane',
            canFloat: false,
            path: 'gis/dijit/NavTools',
            title: 'Navigation Tools',
            open: false,
            position: 0,
            placeAt: 'right',
            options: {
            map: true,
            mapRightClickMenu: true,
            mapClickMode: true
            }
            },

**Comment by tmcgee** [comment]
``` javascript
placeAt: 'right',
```
Do you have a right sidebar pane? If not, remove that line from your configuration. It will default to the left pane.

**Comment by FedwaSlimani** [comment]
@tmcgee i removed that line and it works perfectly, but i want to put on the top of the mao, not on the left pane

**Comment by tmcgee** [comment]
progress! you can easily add a top pane. There is an example in the repo [here](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L107-L113). The configuration options for that pane may not be exactly what you want but they should be close.
