### ISSUE TITLE
Navigation Hash Widget Error in Google Chrome Browser

### ISSUE THREAD

**Issue by drusexton** [cmv/cmv-app#740]
__How often can you reproduce it?__ 

- [ ] Always
- [X] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
When using Google Chrome to access an application that implements the Navigation Hash widget there is an error when you attempt to open a new tab in the browser window and access another URL that has a Navigation hash reference.  I have tested this issue in other browsers, but have only been able to recreate it in Google Chrome. The error occurs almost every single time, but on occasion will not.

__Steps to reproduce:__

1. Open the application in Google Chrome using the following [public URL](http://bhgis.org/apeg/propertyinventory/#/-83.39704/39.36070/16).
2. Open a new tab in the same browser window.
3. Paste the [public URL](http://bhgis.org/apeg/propertyinventory/#/-83.39704/39.36070/16) from step 1 into the address bar and hit enter.
4. There are no errors in the browser console.

__Expected results:__
The map should zoom to the same extent in the second browser tab as it does in the first browser tab

__Actual results:__
You should see in the second browser tab that the latitude and longitude has been ignored, and that the map is instead zoomed to the extent of the map center using the specified zoom from the Navigation Hash widget.

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version |  2.0.0-beta1
| Browser                 | Google Chrome
| Operating system | Windows

**Comment by roemhildtg** [comment]
You're right, I can see the problem there. Sometimes it zooms to the correct area, sometimes it does not. i end up in the SW corner of Perry.

**Comment by roemhildtg** [comment]
I'm using chrome also. And it doesn't happen when debugging afaik. Might want to ask @BrianBunker on https://github.com/BrianBunker/cmv-widgets/issues

**Comment by drusexton** [comment]
@roemhildtg I posted on the widget issues, but am just waiting on a reply. However I am curious if you can provide anymore insight on debugging afaik.

Thanks!
