### ISSUE TITLE
Export button only works once

### ISSUE THREAD

**Issue by ScottBassingthwaite** [cmv/cmv-app#752]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

Export button on attribute table only works once per session
__Description:__
Can only export attribute table contents once per session

query data and produce attribute table
click export button
save file
Clear all
query data and produce attribute table
click export button 
nothing happens
Refresh entire viewer
query data and produce table
click export button
save file
Clear all
query data and produce attribute table
click export button
save file
__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/guresequba/edit?js,output)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)
removeLink: function () {
            if (this.link && this.divExportLink) {
                this.divExportLink.removeChild(this.link);
NotFoundError
                this.divExportLink.innerHTML = '&nbsp;';
            }
            this.link = null;
        },

__Expected results:__
display save file

__Actual results:__
nothing

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 2.0.0 beta 2
| Browser                 |IE 11
| Operating system |Windows 7

**Comment by tmcgee** [comment]
@ScottBassingthwaite Please post this issue in the repository for the [widget](https://github.com/tmcgee/cmv-widgets/).
