### ISSUE TITLE
bug in phone sidebar layout

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#753]
Seems like the home button stops working when I turn on the following line

sidebar: 'phone'

__How often can you reproduce it?__ 

- [x ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/guresequba/edit?js,output)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 
| Browser                 |
| Operating system |

**Comment by tmcgee** [comment]
Hmm, very curious. I cannot think of any reason why the Esri home button widget (a domNode widget) would behave differently due to the presence or absence of the sidebar.

**Comment by tmcgee** [comment]
ok. I get it. this problem occurs if the extent has a different spatialReference than the map. It isn't specific to the `phone` sidebar layout. It is an issue when the sidebar is used regardless of sidebar layout. I have a fix.

**Comment by ERS-Long** [comment]
Great!

Please let us know the fix.

Thanks!
