### ISSUE TITLE
Group layer control issue

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#754]
If i use @tmcgee's search widget, after the search finished, the table of contents double itself with all the empty groups

__How often can you reproduce it?__ 

- [ x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/guresequba/edit?js,output)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 
| Browser                 |
| Operating system |

**Comment by ERS-Long** [comment]
![capture](https://user-images.githubusercontent.com/5911272/28839202-7be82202-76b8-11e7-8228-87d559a22d5e.PNG)

**Comment by ERS-Long** [comment]
![capture](https://user-images.githubusercontent.com/5911272/28839263-ae7b60b2-76b8-11e7-99b9-a19c43aef705.PNG)

**Comment by tmcgee** [comment]
@ERS-Long Might this be some custom code in your application? I cannot duplicate this issue in the [search widget demo](http://tmcgee.github.io/cmv-widgets/demo.html?config=search)

**Comment by ERS-Long** [comment]
@tmcgee i tried your demo example, after the search the toc has changed for me.

ok, your example works just fine. I will have to look more into mine. Thanks!

**Comment by tmcgee** [comment]
@ERS-Long  Please post a screenshot of what you see in the demo. I don't see it.

![image](https://user-images.githubusercontent.com/200780/28839763-9509f0d0-76a9-11e7-9733-43aaf7cedad4.png)

**Comment by ERS-Long** [comment]
i think i also grouped a list of mapserver services using the layerGroup: option, that is the main difference. not sure if that is reason for my issue.

**Comment by tmcgee** [comment]
@ERS-Long OK, got it. I see what is going on with group layer(s) when new layers are added to the layerControl widget. Thanks for providing the details.

**Comment by ERS-Long** [comment]
Added that line, and it fixed the problem I experienced. Thanks a lot!

**Comment by gregoryj98** [comment]
Awesome! This fixes the problem in Drag and Drop widget too.
