### ISSUE TITLE
Table of Attribute like Silverlight will be also wunderfull

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#76]
Because YOUR SUPER JAVASCRIPT INTERFACE WORK ON IPAD and other devices,
if we have the attribute table in a box like Displaying attributes in a DojoX DataGrid,
we don't need to use the silver light api

like the table is this template:  http://gis.icao.int/appsilver/ICAOFIR2014/

**Comment by farid2** [comment]
@tmcgee , How is it going with the two widgets you had promised to share?  I think AttributeTable and Search widget (the snapshot) are the must have widgets of CMV. When will you add those widgets to the repo?
Thanks

**Comment by tmcgee** [comment]
Hello @farid2 See my response to issue #207 for the latest update.

**Comment by DavidSpriggs** [comment]
As a note, in version 3.12 of the Esri JS API, there is now an out of the box attribute table. It would be very simple to add this to CMV. We will be doing this soon but feel free to take a whack at it if you want it soon.
Class: https://developers.arcgis.com/javascript/jsapi/featuretable-amd.html
Samples: https://developers.arcgis.com/javascript/jssamples/#search/FeatureTable

**Comment by DJJonnyFeeke** [comment]
Hello, i have implemented 3.12 JS API and used the Featurelayer and Featuretable. It is very easy to do and have added it to the CMV. For my purposes i just added a new Menu Item for the Layers, which in turn displays the attribute table in the bottom sidebar with minimal changes/additions of code.

**Comment by faridcher** [comment]
Jonny,
Can you make it a widget and share it with the community?
Thanks

**Comment by DJJonnyFeeke** [comment]
I wouldn't want to duplicate what will already be created later, and for my own personal use i didn't need it as a widget. I wanted it to be as simple as the "Zoom to Layer" function.
Let me give it a bash though.

**Comment by tmcgee** [comment]
I have __finally__ found time to publish my widget. See my response to issue #207 for details.
