### ISSUE TITLE
Attribute Table Widgets Issues - Bottom Panes display , Sub layer Menu- Open Attribute Table & Query Where 1=1

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-app#760]
Hi,
I have added the AttributeTable widgets. placing it in the bottom pane of app as is recommended. Now, If I add open:false in panes configuration, Attribute tables not displaying in the proper bottom area, instead it is display in left corner of the bottom pane. If you don't add this property open:false, it is display properly in bottom area. I am attaching both the screenshots below

## Attribute doesnt display properly in bottom pane after setting property open:false in panes bottom

 if open:false in bottom panes property and click on collapse button and open it display as below

![capture](https://user-images.githubusercontent.com/6058868/29313638-d35f1480-81c3-11e7-997f-9eacfef6c3dc.PNG)

without open:false property 

![capture1](https://user-images.githubusercontent.com/6058868/29313637-d35f2042-81c3-11e7-831f-5e7e58f1cde7.PNG)

## How to open Attribute table from Sublayer menu of dynamic layers

I added this in LayerControl widgets options
```
subLayerMenu: {
                        dynamic: [{
                            label: 'Open Attribute Table',
                            topic: 'openTable',
                            iconClass: 'fa fa-table fa-fw'
                        }]
                    }
```
I am getting Open Attribute Table menu option but, by clicking on that menu Attribute Table doesn't display. What are the additional steps are required to open the Attribute Table from sub layer menu.

I seen the related issue here https://github.com/tmcgee/cmv-widgets/issues/21.

I added code in viewer.js file 

Now here is the OpenAttributeTable Code after  topic.subscribe('layerControl/goodbye', function (event) {...
```
topic.subscribe('LayerControl/openAttributeTable', function (r) {
        var data_list = [
            {
                title: 'AttributesTable',
                topicID: 'AttributesTable',
                queryOptions: {
                    queryParameters: {
                        url: r.layer.url + '/' + r.subLayer.id,
                        maxAllowableOffset: 100,
                        where: '1=1'
                    },
                    idProperty: 'ObjectID'
                }
            }
        ];
        console.log(data_list);
        //this.addTables(data_list);
        //this.tables = data_list;
        topic.publish('attributesContainer/addTables', data_list);
    });
```
Attributetable is not opening with above code

##  Attribute Table query where 1=1 not binding the attribute information in grid but highlighting the features on map, If I use Where field name=value its working fine highlighting the features on map and binding info in grid. see the example below & screenshot of console 
I added the below options for Attributes table widgets
```
attributesTable: {
                include: true,
                id: 'attributesContainer',
                type: 'domNode',
                srcNodeRef: 'attributesContainer',
                path: 'gis/dijit/AttributesTable',
                //options: 'config/attributesTable'
                options: {
                    map: true,
                    mapClickMode: true,
                    useTabs: false,
                    sidebarID: 'sidebarBottom',

                    /*
                        any predefined tables to add to the tab container or possibly just one table
                    */
                    tables: [
                        {
                            // title for tab
                            title: 'Audit Stage',

                            // unique topicID so it doesn't collide with
                            // other instances of attributes table
                            topicID: 'auditStageQuery',

                            // allow tabs to be closed
                            // confirm tab closure
                            closable: true,
                            confirmClose: true,

                            queryOptions: {
                                // parameters for the query
                                queryParameters: {
                                    url: 'http://myserver.com/arcgis/rest/services/Road_Safety_Audit/MapServer/0',
                                    maxAllowableOffset: 100,
                                    where:'1=1' \\ this is not binding info in grid but highlighting on map
                                         //'PROJECT_NUMBER = \'AA-0003\'', \\ both working                                   
                                },
                                idProperty: 'OBJECTID'//'ObjectID'
                            }
                        }
                    ],
                }
            },
```
error in console when query where 1=1

![picture1](https://user-images.githubusercontent.com/6058868/29315511-42e0358e-81cc-11e7-8c33-33a29f9e1955.png)

## I don't want to highlights the features on map when application load, how do I disable that, I just like to load layers info in attribute table by default bottom panes hide and proper display of widget & without highlighting the features on map when app load....

Please note that I added Draw WAB widget in my app..but, I don't think so its related to this issues..

Please let me know if you have some suggestion on this.

**Comment by tmcgee** [comment]
@mayur9785 Please create issues for AttributesTable widget in the [repo](https://github.com/tmcgee/cmv-widgets/) for that widget. Also, please create separate issues for each of your questions so that they can be addressed individually.
