### ISSUE TITLE
layerControlLayerInfos Question

### ISSUE THREAD

**Issue by gisnovice** [cmv/cmv-app#768]
I was wondering for `layerControlLayerInfos`, can I show them dynamically still?

For example, my service is Parcels [0], Landuse [1]. Zoning [2], and Buildings [3]. However, I only want to show  `layerIds: [1, 2],` but all layers are still being shown on my CMV.

**Comment by green3g** [comment]
What code have you tried that isn't working correctly?

**Comment by gisnovice** [comment]
@roemhildtg This is the code for my layer. I want to show Layers 0 and 1, but the rest (layers 2-14) show up in my map. Is there any way around this or would I have to make a completely separate service? 

```
operationalLayers: [{ 
            type: 'dynamic',
            url: 'http://gis.ci.oceanside.ca.us/gis/rest/services/WebService/Planning/MapServer',
            title: 'Address',
            options: {
                id: 'Address',
                opacity: 1.0,
                visible: true,
                mode: 2
            },
            layerControlLayerInfos: {
                layerIds: [0, 1]
            },
            identifyLayerInfos: {
                exclude: true //excludes from being identify
            }
        },
```

**Comment by tmcgee** [comment]
@gisnovice The `layerControlLayerInfos` determines what layers can be toggled on/off via the LayerControl widget. To control the initial layer visibility on the map, you will want to set the `imageParameters` for the layer like [this](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L203-L206).

As an aside, you can remove `mode: 2` from the options as that is not used for a dynamic layer. It is for a feature layer. Just an observation. No harm in leaving that option in there. :smile:

**Comment by gisnovice** [comment]
@tmcgee as always, you are the best! thank you CMV team!

**Comment by gisnovice** [comment]
@tmcgee I noticed though, it is a "quick" fix, but if I turn on "all" the layers, the original layers that I wanted to exclude do come back. Do you think there's an addition to this? Or would the original idea of making a separate MXD be best; instead of hosting all in one?

![problem](https://user-images.githubusercontent.com/26489280/29980411-a7832840-8efe-11e7-9be1-6429b4d6b5c0.png)

**Comment by tmcgee** [comment]
Hmmm. That may be a bug. `Turn On/Off All Sublayers` should manage only those sublayers in the LayerControl widget. I'll have to look into that.

**Comment by gisnovice** [comment]
@tmcgee Got it, thank you much!
