### ISSUE TITLE
Street view widget  doesn't work with mobile sidebar

### ISSUE THREAD

**Issue by kjohnsonGIS** [cmv/cmv-app#779]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
When using the mobile sidebar, street view widget doesn't work.   street view widget works for me otherwise (as a title pane).  

__Steps to reproduce:__
in viewer.js config:
```
//setting the sidebar to be on
layout: {
    sidebar: 'true'
}
//add the street view widget as a titlePane
widgets: {
            streetview: {
                include: true,
                id: 'streetview',
                type: 'titlePane',
                canFloat: true,
                position: 10,
                path: 'gis/dijit/StreetView',
                title: i18n.viewer.widgets.streetview,
                iconClass: 'fa-street-view',
                paneOptions: {
                    resizable: true,
                    resizeOptions: {
                        minSize: {
                            w: 250,
                            h: 250
                        }
                    }
                },

                options: {
                    map: true,
                    mapClickMode: true,
                    mapRightClickMenu: true,
                    proj4Catalog: 'ESRI'
                }
            }
}
```

__Actual results:__

street view results area turns white, and console error getPanoramaByLocation  of undefined.
![image](https://user-images.githubusercontent.com/29210164/30994916-c0db96b0-a46b-11e7-9488-cf7ae144c886.png)

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version |  CMV 2 beta 2
| Browser                |  Chrome and IE 11
| Operating system | Windows 7
thanks

**Comment by tmcgee** [comment]
Confirmed this is a problem that needs to be fixed in StreetView widget. Should not assume that the parentWidget is a TitlePane.

Calling `this.parentWidget.toggle()` [here](https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/StreetView.js#L172) is also a similar problem for this widget.

**Comment by DJA30** [comment]
Were you using http or https?
