### ISSUE TITLE
StreetView - Widget can't read ESPG:3857 variable

### ISSUE THREAD

**Issue by cuthberts** [cmv/cmv-app#785]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
I've downloaded the latest development CMV app (downloaded 25/10/17) and without any customisation the Street View widget is coming up with the following error when I use it.

__Actual results:__
![image](https://user-images.githubusercontent.com/8953510/31982946-b563992c-b9a6-11e7-909a-589d7bc30067.png)

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | Latest Dev
| Browser:  | Chrome
| Operating system | Windows 7

**Comment by tmcgee** [comment]
@cuthberts Sounds like you cannot access the Proj4JS libs referenced [here](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/app.js#L17). Could access be blocked in your network?

**Comment by cuthberts** [comment]
@tmcgee I just checked the link and you're correct it is blocked. Is there a way around this?

**Comment by green3g** [comment]
You can host the proj4js file locally. Then you would need to update the location here: https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/app.js#L17
