### ISSUE TITLE
Bookmark widget not working at Javascript api 3.22

### ISSUE THREAD

**Issue by msamwill** [cmv/cmv-app#788]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
Bookmark widget not loading when using Javascript api version 3.22 works at 3.17.  Doesn't work with IE 11, Firefox 56.0.2, or Google Chrome 61.0.3163.100.

Load website using bookmark widget

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/zeyexiwubu/edit?html,js,output). Alternatively create a [Gist](gist.github.com)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

bookmark widget loads with bookmarks and icons to add or delete bookmarks.

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 
| Browser                 |
| Operating system |

**Comment by green3g** [comment]
Its true, here's a jsbin with the issue: http://jsbin.com/wunorasoke/1/edit?js,output

**Comment by tmcgee** [comment]
Wondering if this an issue with the Esri Bookmarks widget since we simply wrap that one with CMV Bookmarks widget. I'm in no position to test this from here. @roemhildtg

**Comment by msamwill** [comment]
It doesn't appear to be as this sample https://developers.arcgis.com/javascript/3/jssamples/widget_bookmarks_dropdownbutton.html is working I also tried it with the compact framework.

**Comment by green3g** [comment]
Did you figure this out @msamwill

**Comment by msamwill** [comment]
Not yet, will look at this after work today and see if I can figure it out.  Looks like I accidentally closed it.  Reopening it now.

**Comment by msamwill** [comment]
I got this to work by turning the bookmark widget into a templated widget.  Added a templates folder with a Bookmarks.html file.  The contains the following:
<div class="gis_BookmarksDijit">
   <div data-dojo-attach-point="bookmarksNode" ></div>
</div>

Modified bookmarks.js as follows:

define([
	'dojo/_base/declare',
	'dijit/_WidgetBase',
        'dijit/_TemplatedMixin',
        'dijit/_WidgetsInTemplateMixin',
   	'esri/dijit/Bookmarks',
        'dojo/text!./Bookmarks/templates/Bookmarks.html',
	'dojo/json',
	'dojo/cookie',
        'dojo/_base/lang',
	'xstyle/css!./Bookmarks/css/Bookmarks.css'
], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin, Bookmarks, template, json, cookie, lang) {

    return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        //declaredClass: 'gis.digit.Bookmarks',
        templateString: template,
		postCreate: function () {
			this.inherited(arguments);
			var bookmarks = this.bookmarks; // from the options passed in
			this.bookmarkItems = cookie('bookmarkItems');
			if (this.bookmarkItems === undefined) {
				this.bookmarkItems = [];
			} else {
				this.bookmarkItems = json.parse(this.bookmarkItems);
			}
            this.bookmarks = new Bookmarks({
                map: this.map,
                id: this.id + '_esri',
                editable: this.editable,
                bookmarks: lang.mixin(this.bookmarkItems, bookmarks)
            }, this.bookmarksNode);
                        
			this.connect(this.bookmarks, 'onEdit', 'setBookmarks');
			this.connect(this.bookmarks, 'onRemove', 'setBookmarks');
		},
		setBookmarks: function () {
			cookie('bookmarkItems', json.stringify(this.bookmarks.toJson()), {
				expires: 365
			});
		},
		_export: function () {
			return json.stringify(this.bookmarks.toJson());
		}
	});

});

**Comment by green3g** [comment]
Cool @msamwill! Would you be interested in putting the code fixes into a pull request, so others can use the bookmarks widget?

**Comment by msamwill** [comment]
I've never done a pull request before but I will see if I can figure it out later this evening.

**Comment by green3g** [comment]
It sounds complicated, but it's pretty straightforward. Just fork the repo to your repository, make the changes/commit and create the pull request. https://help.github.com/articles/github-flow/

**Comment by tmcgee** [comment]
If I am understanding this correctly (and I may not be since the internet connection is slow and challenging where I am), the only difference is the DOM node that is passed to the Esri Bookmarks widget. While I am not opposed to using a Templated widget, that approach feels like a work-around avoiding the real issue with the Esri widget or the way CMV is providing the dom Node to that widget. Normally, I would dig into this myself and contribute to the discussion. However, due to my location and current situation, it will likely be many weeks before I am able to do that.
