### ISSUE TITLE
improve DnD

### ISSUE THREAD

**Issue by mtabdar** [cmv/cmv-app#795]
hi
i am wondering if there is a way to add local shp or kml files to cmv map. i know about this fantastic widget  called dnd but i have a few problems with it. mostly that it needs esri resources to parse shp or kml files.
(you see i am working in a disconnected environment and don't have portal)
i think one other option is improving dnd so that it draw lines or polygons from csv files instead of just points, with only one symbol!
sorry it is so long, but i appreciate any help.
thanks

**Comment by green3g** [comment]
These are just suggestions, I haven't tried doing any of this with cmv but try taking a look at shapefile-js. It seems capable of this:

https://github.com/calvinmetcalf/shapefile-js

Demo: http://leaflet.calvinmetcalf.com/#14/44.2953/-93.2642

**Comment by mtabdar** [comment]
hi,
thanks a lot for the answer and sorry to reply so late.
i tried shapefile-js with no success, and found terraformer in my search:
[https://github.com/Esri/terraformer](url)
it seems to be promising, or at least helped me understand graphic layers better.
i will keep working on it and try to improve DnD, to change graphic layers created from csv.
any help in this regard is appreciated.
thanks
