### ISSUE TITLE
Basemaps Not Switching 3.22

### ISSUE THREAD

**Issue by juperry** [cmv/cmv-app#801]
In CMV 3,22 my custom basemaps show up when I click the basemap button and the correct startup basemap is showing and is selected in the dropdown.  However, when I click on any of the other custom basemaps nothing happens.  They don't get selected in the dropdown and the map doesn't change to them.  I have them set up as in version 3.18 and they were working in that version.  Any help would be greatly appreciated.

Here is my Basemaps.js.

define([
    'dojo/_base/declare',
    'dijit/_WidgetBase',
    'dijit/_TemplatedMixin',
    'dijit/_WidgetsInTemplateMixin',

    'dojo/_base/lang',
    'dojo/_base/array',
    'dojo/topic',

    'dijit/DropDownMenu',
    'dijit/MenuItem',

    'esri/basemaps',
    'esri/dijit/BasemapGallery',

    'dojo/text!./Basemaps/templates/Basemaps.html',
    'dojo/i18n!./Basemaps/nls/resource',

    'dijit/form/DropDownButton',
    'xstyle/css!./Basemaps/css/Basemaps.css'
], function (
    declare,
    _WidgetBase,
    _TemplatedMixin,
    _WidgetsInTemplateMixin,

    lang,
    array,
    topic,

    DropDownMenu,
    MenuItem,

    esriBasemaps,
    BasemapGallery,

    template,
    i18n
) {

    return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        templateString: template,
        widgetsInTemplate: true,
        i18n: i18n,
        title: i18n.title,
        baseClass: 'basemapWidget',
        basemaps: {},
        currentBasemap: 'madco',
        mapStartBasemap: 'madco',
        basemapsToShow: ['madco', 'fifteen', 'thirteen', 'nine', 'six', 'three', 'ninetyfive'],
        galleryOptions: {
            basemapIds: null,
            basemaps: ['madco', 'fifteen', 'thirteen', 'nine', 'six', 'three', 'ninetyfive'],
            basemapsGroup: null,
            bingMapsKey: null,
            portalUrl: null,
            referenceIds: null,
            showArcGISBasemaps: false
        },

        postCreate: function () {
            this.inherited(arguments);
            this.initializeBasemaps();
            this.createBasemapGallery();
            topic.subscribe('basemaps/updateBasemap', lang.hitch(this, 'updateBasemap'));
        },

        initializeBasemaps: function () {
            if (this.galleryOptions.basemaps) {
                // if the basemaps to show is not explicitly set, get them from the gallery's basemap array
                this.basemapsToShow = this.basemapsToShow || array.map(this.galleryOptions.basemaps, function (basemap) {
                    return basemap.id;
                });
            } else {
                // no basemaps? use the Esri basemaps
                if (!this.basemaps || Object.keys(this.basemaps).length < 1) {
                    this.basemaps = lang.clone(esriBasemaps);
                    this.galleryOptions.showArcGISBasemaps = false;
                }

                // if the basemaps to show is not explicitly set, get them from the basemap object
                this.basemapsToShow = this.basemapsToShow || Object.keys(this.basemaps);

                var basemaps = [];
                array.forEach(this.basemapsToShow, lang.hitch(this, function (key) {
                    var map = this.basemaps[key];
                    // determine if it is a custom basemap or an esri basemap
                    if (map.basemap && map.basemap.declaredClass === 'esri.dijit.Basemap') {
                        var basemap = map.basemap;
                        basemap.title = map.title || basemap.title;
                        basemap.id = key;
                        basemaps.push(basemap);
                    } else {
                        if (!esriBasemaps[key]) {
                            map.basemap.title = map.title || map.basemap.title;
                            esriBasemaps[key] = map.basemap;
                        }
                        map.title = map.title || esriBasemaps[key].title;
                        this.galleryOptions.showArcGISBasemaps = false;
                    }
                }));
                this.galleryOptions.basemaps = basemaps;
            }

            // if the starting basemap is not explicitly set, get it from the map
            this.mapStartBasemap = this.mapStartBasemap || this.map.getBasemap();

            // check to make sure the starting basemap is found in the basemaps object
            if (array.indexOf(this.basemapsToShow, this.mapStartBasemap) < 0) {
                this.mapStartBasemap = this.basemapsToShow[0];
            }
        },

        createBasemapGallery: function () {
            var opts = lang.mixin({
                map: this.map
            }, this.galleryOptions);
            this.gallery = new BasemapGallery(opts);
            this.gallery.startup();
            if (this.galleryOptions.showArcGISBasemaps) {
                this.gallery.on('load', lang.hitch(this, 'buildMenu'));
            } else {
                this.buildMenu();
            }
        },

        buildMenu: function () {
            this.menu = new DropDownMenu({
                class: this.baseClass + '-menu',
                style: 'display: none;'
            });
            array.forEach(this.basemapsToShow, function (basemap) {
                if (this.basemaps.hasOwnProperty(basemap)) {
                    var menuItem = new MenuItem({
                        id: basemap,
                        label: this.basemaps[basemap].title,
                        iconClass: (basemap === this.mapStartBasemap) ? 'selectedIcon' : 'emptyIcon',
                        onClick: lang.hitch(this, 'updateBasemap', basemap)
                    });
                    this.menu.addChild(menuItem);
                }
            }, this);
            this.dropDownButton.set('dropDown', this.menu);
            this.setStartingBasemap();
        },

        setStartingBasemap: function () {
            if (this.mapStartBasemap && (this.gallery.get(this.mapStartBasemap) || esriBasemaps[this.mapStartBasemap])) {
                this.updateBasemap(this.mapStartBasemap);
            }
        },

        updateBasemap: function (basemap) {
            if (basemap !== this.currentBasemap && (array.indexOf(this.basemapsToShow, basemap) !== -1)) {
                if (this.gallery.get(basemap)) {
                    this.gallery.select(basemap);
                } else if (esriBasemaps[basemap]) {
                    this.gallery._removeBasemapLayers();
                    this.gallery._removeReferenceLayer();
                    this.map.setBasemap(basemap);
                } else {
                    topic.publish('viewer/error', 'Invalid basemap selected.');
                    return;
                }
                this.currentBasemap = basemap;
                var ch = this.menu.getChildren();
                array.forEach(ch, function (c) {
                    if (c.id === basemap) {
                        c.set('iconClass', 'selectedIcon');
                    } else {
                        c.set('iconClass', 'emptyIcon');
                    }
                });
            }
        }
    });
});

**Comment by juperry** [comment]
Here is my basemaps.js in the config folder.

define([
    'esri/dijit/Basemap',
    'esri/dijit/BasemapLayer',
    'dojo/i18n!./nls/main'
], function (Basemap, BasemapLayer, i18n) {

    return {
        map: true, // needs a reference to the map
        //mode: 'custom', // mut be either 'agol' or 'custom'

        /* optional starting basemap
        / otherwise uses the basemap from the map
        / must match one of the keys in basemaps object below
        */
        mapStartBasemap: 'madco',

        /* optional array of  basemaps to show in menu.
        / otherwise uses keys in basemaps object below
        / values in array must match keys in basemaps object
        */
        basemapsToShow: ['madco', 'fifteen', 'thirteen', 'nine', 'six', 'three', 'ninetyfive'],

        // define all valid basemaps here.
        basemaps: { 
            // examples of custom basemaps
            madco: {
                title: 'Streets',
                thumbnailUrl: "images/pointertop.png",
                basemap: new Basemap({
                    id: 'madco',
                    layers: [new BasemapLayer({
                        url: 'Custom URL'
                    })]
                })
            },
            fifteen: {
                title: '2015 Aerials',
                basemap: new Basemap({
                    id: 'fifteen',
                    layers: [new BasemapLayer({
                        url: 'Custom URL'
                    })]
                })
             },
             twelve: {
                 title: '2012 Aerials',
                 basemap: new Basemap({
                     id: 'twelve',
                     layers: [new BasemapLayer({
                         url: 'Custom URL'
                     })]
                 })
             },
             nine: {
                 title: '2009 Aerials',
                 basemap: new Basemap({
                     id: 'nine',
                     layers: [new BasemapLayer({
                         url: 'Custom URL'
                     })]
                 })
             },
             six: {
                 title: '2006 Aerials',
                 basemap: new Basemap({
                     id: 'six',
                     layers: [new BasemapLayer({
                         url: 'Custom URL'
                     })]
                 })
             },
             three: {
                 title: '2003 Aerials',
                 basemap: new Basemap({
                     id: 'three',
                     layers: [new BasemapLayer({
                         url: 'Custom URL'
                     })]
                 })
             },
             ninetyfive: {
                 title: '1995 Aerials',
                 basemap: new Basemap({
                     id: 'ninetyfive',
                     layers: [new BasemapLayer({
                         url: 'Custom URL'
                    })]
                 })
            },
        }
    };
});

**Comment by tmcgee** [comment]
@juperry You mention CMV versions 3.22 and 3.18. Those are version number for the Esri ArcGIS API that work both with numerous versions of CMV.  What version of CMV are you using?
