### ISSUE TITLE
loading widgets on a costum node (without panes)

### ISSUE THREAD

**Issue by Samaalir** [cmv/cmv-app#807]
Hello, and first thanks a lot for this template,
so I had an issue while loading the widgets on a costumized place, I was successful in doing that in the cmv 3.16, 
the principe was a little bit simple, by defining the widged as a floating type, then doing some changes in the source code of the plugin, ex 
In the viewer file:

`identify: {
                include: true,
                id: 'identify',
                type: 'floating',
                canFloat: true,
                path: 'gis/dijit/Identify',
                title: i18n.viewer.widgets.identify,
                open: false,
                options: 'config/identify'
            },`

----------------------------------------
For the gis/dijit/identify.js

`...
..
return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        widgetsInTemplate: true,
        templateString: IdentifyTemplate,
        baseClass: 'gis_IdentifyDijit',
        i18n: i18n,
        domTarget: 'identifyDijit',`

in the postcreat function I've added this lines:

```
if (this.parentWidget.toggleable) {
                this.own(aspect.after(this.parentWidget, 'toggle', lang.hitch(this, function () {
                    this.containerNode.resize();
                })));
            } else {
                var help = domConstruct.place(this.html, this.domTarget);
                on(help, 'click', lang.hitch(this.parentWidget, 'show'));

            }
```

after that I created my pesonalized layout, and it was working,
I think there was some changins inside the controller file in which all the viewer files (_XMixin.js,...) were grouped in one file Controller.js

any suggestions please?

**Comment by tmcgee** [comment]
@Samaalir You might want to check out how we use [CMV with Calcite Maps](https://github.com/cmv/cmv-calcite-maps). Within Calcite, there are no panes and the cmv widgets are used without modification.

**Comment by Samaalir** [comment]
Yes I already test it, anyway I was successful to find the problem thanks
