### ISSUE TITLE
Legend: Print Widget

### ISSUE THREAD

**Issue by drusexton** [cmv/cmv-app#808]
@tmcgee I have been searching for a way to change or possibly even completely exclude the feature labels from the layout of my print widget. It would be cool to show the directions from the direction widget without out the unnecessary feature text labels (pointLayer, polylineLayer, override 1, and override 2). Please see the include image for your reference.

On another note, I hope everything is settling down for you. I know you had indicated that the Wildfires in California were effecting you. My thoughts are with you, your family, and really anyone struck by that tragedy!

![legend-print widget](https://user-images.githubusercontent.com/14102180/35631099-048c252a-0671-11e8-812a-5d2d636d39c3.png)

**Comment by pucuz** [comment]
I have dealt with this by creating a custom ExportWebMap Geoprocessing Task that removes layers from the map legend. The default Print Task does not function well with Feature and Graphics layers.
