### ISSUE TITLE
Find / FindTask capabilities for Feature Server layer instead of Map Server layer

### ISSUE THREAD

**Issue by marhensa** [cmv/cmv-app#814]
Hi,

I found it's not possible to use Find widget for a map service published from ArcGIS Online, which is published as hosted feature server instead of normal map server from ArcGIS Server.

The service is looks like this:
https://server.example/rest/services/servicename/FeatureServer

Any workaround for this matters?
Or we just stuck to stick it it to use only ArcGIS Server published service only?

**Comment by tmcgee** [comment]
The Esri FindTask used by the Find widget is not available for Feature Layers (hosted on with ArcGIS Server). To search a Feature Layer, you can use Esri's QueryTask. My [Search widget](https://github.com/tmcgee/cmv-widgets#search) supports the QueryTask (spatial, and attribute searches), RelationshipQuery (search in related tables and FeatureClasses) and the FindTask (like the original Find widget).
