### ISSUE TITLE
Web service error - Proxy?

### ISSUE THREAD

**Issue by cuthberts** [cmv/cmv-app#817]
__How often can you reproduce it?__ 

- [ ] Always
- [x ] Most of the time
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
On the initial load of my web page the following errors appear in the dev tools for each web service. I thought it was the proxy and so I updated it, but it hasn't fixed the issue. I also downloaded the most recent CMV develop website and no luck either.

![image](https://user-images.githubusercontent.com/8953510/37331124-25435e40-26f7-11e8-9667-e29b89a26995.png)

__Environment:__

| Software       | Version
| ------------------ | -------
| CMV Version |  Latest
| Browser                 | IE or Chrome
| Operating system | Windows 7

**Comment by green3g** [comment]
@cuthberts there isn't enough information here to give you much advice. Please post the details on what type of service you are trying to access, what type of proxy your using and relevant configuration files and details. 

A couple things you can try:
1. Make sure your service endpoints are operational, and you can browse to them
2. Make sure your proxy is operational and you can browse to it. The esri proxy usually displays a message for debugging.

**Comment by tmcgee** [comment]
At first blush, these errors suggest a network connectivity issue not likely related specifically to CMV or the proxy.

**Comment by cuthberts** [comment]
I'm running a ESRI REST end services through a proxy, as they're locked down on the ArcGIS server. I've tried the latest Proxy Resource and the main release from July 2017. Also the server logs aren't listing any services that are timing out.

I can access the REST end point point by using the web service address, proxy and rest end point.
E.g. https://WEBSITTE/proxy/proxy.ashx?https://WEBSITE/arcgis/rest/services/SERVICE/MapServer

When I run the website in Incognito Mode, it works every time.
