### ISSUE TITLE
Error Print Widget with 'locale=fr'

### ISSUE THREAD

**Issue by cpaggiolo** [cmv/cmv-app#818]
https://demo.cmv.io/viewer/?locale=fr 
Click on Print widget not open the widget

__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
https://demo.cmv.io/viewer/?locale=fr 
Click on Print widget not open the widget

With all other locale langage, the "printer widget" works fine

__Steps to reproduce:__

just : https://demo.cmv.io/viewer/?locale=fr 
and Click on Print widget

__Expected results:__

__Actual results:__

__Environment:__

Firefox quantum on lubuntu
Firefox on windows 8.0

**Comment by green3g** [comment]
Confirmed. Looks like a dojo parser error due to the a special character in the template getting passed:

```
Error: SyntaxError: missing } after property list in data-dojo-props='name:'dpi',required:true,value:150,constraints:{min:100,max:300,places:0},invalidMessage:'S'il vous plaît entrer une valeur numérique.',rangeMessage:'S'il vous plaît entrer une valeur entre 100 et 300.',style:'width:100px;''
```

Cleaned up the props a bit to understand what's going on:
```javascript
name:'dpi',
required:true,
value:150,
constraints:{min:100,max:300,places:0},
invalidMessage:'S'il vous plaît entrer une valeur numérique.',
rangeMessage:'S'il vous plaît entrer une valeur entre 100 et 300.',
style:'width:100px;''
```

**Comment by green3g** [comment]
https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/Print/nls/fr/resource.js#L20

**Comment by green3g** [comment]
Why is there a quote in between the `S'il` ? Is that necessary?

Edit: Oh, I see its a contraction

**Comment by tmcgee** [comment]
Maybe we should just be less polite and not say `Please`? 😜 

Same problem exists for the Help Widget. https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/Help/nls/fr/resource.js#L9

**Comment by cpaggiolo** [comment]
Exact ! less polite is better ! :+1: 
We have to remove all contractions
