### ISSUE TITLE
Identify popup With Geoserver Layer not Showing

### ISSUE THREAD

**Issue by vincentgrobler** [cmv/cmv-app#824]
Maybe I have missed something but I cannot even get a simple identify to work. I have added a simple identify just to get something to show up but I cannot even get a popup to come up. Any thoughts on where I went wrong?

viewer.js

 ```
{
                type: 'TileWMS',
                title: 'Portions',
                options: {
                    serverType: 'geoserver',
                    params: {
                        LAYERS: 'portions_geo',
                        STYLES: '',
                        VERSION: '1.3.0'
                    },
                    ratio: 1.5,
                    url: 'http://localhost:8085/geoserver/wms',
                    visible: true,
		    id: 'portions',
                },
		identifyLayerInfos: {
                layerIds: [01]
				},
                layerControlLayerInfos: {
                    noLegend: false,
                    noZoom: false,
                    noTransparency: false,
                    swipe: false,
                    expanded: false,
                    sublayers: true,
                    metadataUrl: {
                        include: true,
                        url: 'http://localhost:8085/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities'		
                    }
                }
            },
```

           identify: {
                include: true,
                id: 'identify',
                type: 'invisible',
                path: 'gis/dijit/Identify',
                title: 'Identify',
                open: false,
                position: 2,
                options: 'config/identify'
            },

identify.js

      define({
        map: true,
        mapClickMode: true,
        mapRightClickMenu: true,
        identifyLayerInfos: true,
        identifyTolerance: 30,

        identifies: {
           portions: {
                01: {
                    title: 'Portions',
                    fieldInfos: [{
                        fieldName: 'pname',
                        visible: true
                    }]
                }
            }
        }
    });

**Comment by tmcgee** [comment]
@vincentgrobler The Identify widget currently only works with layers defined with the operational layers array as  `type: 'feature'` and `type: 'dynamic'`.

`dynamic` layers used the Esri IdentifyTask with an ArcGIS Map Service.

`feature` layers (and other layer types such as `kml` and `cmv` that add Graphics to the map) use an InfoTemplate - either predefined or generated automatically from the fields included in the `feature` layer.

It would be a great future enhancement for CMV to include identifying for `wms` layers.
