### ISSUE TITLE
Coordinate Transformation Widget

### ISSUE THREAD

**Issue by tr3vorm** [cmv/cmv-app#83]
I have had a request to create a widget similar to the one shown on this page http://hirds.niwa.co.nz/

Summarising: 
- be able to click on the map, and display the coordinate (already have this in the measurement widget)
- be able to transform the coordinate to another system
- enter a coordinate (in available projection), and draw a point on the map (recentered)

Has anyone got something similar working? My thoughts are to create a new widget (as opposed to extending the measurement widget). 

PS. Lots of changes made recently! I have been away from this, but looking forward to trying out the new release.

**Comment by dkitoko** [comment]
Hello All,

@LarryStout I know that is a bit old, but i'm looking for some tools that I found in your WebGIS. It's that possible to have your coordinates and email link widgets? 

@tr3vorm @tmcgee The MapInfo widget is availble for Flex? Im working with Flex 3.6.

I have my application in one projected CRS, but I would like to give the users the option to pick in the map and get coordinates in WGS84, using an specific transformation parameter.

Thanks in advance for any help or advice,
Dilson
