### ISSUE TITLE
 print widget can not print maps

### ISSUE THREAD

**Issue by Caixiujuan** [cmv/cmv-app#831]
__How often can you reproduce it?__ 

- [1 ] Always
- [x] Sometimes
- [x] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__I follow the configuration of the print widget that I know. I can't print the layer I loaded. What is the reason?

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/purinunuda/edit?js,output). Alternatively create a [Gist](gist.github.com)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

__Expected results:__Under normal circumstances, I should be able to print the map data I need, including legends and other map elements, after the printing widget is completed.

__Actual results:__Print failed, failed to print after loading data。

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | CMV.2.0.0
| Browser                 |chrome
| Operating system | Win7_64

**Comment by tmcgee** [comment]
@Caixiujuan Most issues related to printing are associated with the Print Service being used not being able to access the visible layer(s) in your map. You should use your own Print Service if possible. That makes it is easier to troubleshoot the problems. 

Here is an [article](https://communityhub.esriuk.com/technicalsupport/2014/10/24/troubleshooting-web-service-printing-failures.html) from a few years ago that provides some steps helpful in diagnosing printing issues.

**Comment by Caixiujuan** [comment]
@tmcgee I am using my own arcgisserver printing tool to print my own data service error. F12 shows Unable to complete operation. I would like to ask you what the problem is and how to solve it. I am grateful for it

**Comment by tmcgee** [comment]
Hi @Caixiujuan Sounds like your next step is to review the logs on your ArcGIS server looking at any errors associated with your Print Service.

**Comment by Caixiujuan** [comment]
Hi@tmcgee I checked the log of ArcGISServer according to what you said, showing the following problem.
Error executing tool. Export Web Map Task Job ID: jf3897489c985477483bfd705aeaceb48 : Layer "cities": Unable to connect to map server at https://10.10.11.94:6443/arcgis/rest/services/XiaobeihuNNR/XiaobeihuNNR/MapServer. Layer "louisvillePubSafety": Unable to connect to map server at https://10.10.11.94:6443/arcgis/rest/services/HLJbasicdata/MapServer. Layer "sf311Incidents": Unable to connect to map server at https://10.10.11.94:6443/arcgis/rest/services/HLJwetland/Heilongjiangwetland/MapServer. Failed to execute (Export Web Map). Failed to execute (Export Web Map Task). | Utilities/PrintingTools.GPServer
-- | --
I have found some methods but I have not solved them. What should I do next? Do you have any good suggestions? Thank you for your help.

**Comment by tmcgee** [comment]
Messages with `Unable to connect to map server at`... suggest that your ArcGIS Server hosting the Print Service does not have access to the ArcGIS Server hosting those services. Usually this is related to networking (one server cannot access the server) or permissions (the user account running the Print Service is not allowed to access those services). Since both of these issues are related to your network/server configuration, we can't provide support for that here.

**Comment by Caixiujuan** [comment]
@tmcgee Thank you very much for your help, thank you, I am checking my problems here to see if I can solve them. Thank you again

**Comment by Caixiujuan** [comment]
@tmcgee Thank you very much for your help, thank you, I am checking my problems here to see if I can solve them. Thank you again

**Comment by Caixiujuan** [comment]
@tmcgee Thank you very much for your help, thank you, I am checking my problems here to see if I can solve them. Thank you again
