### ISSUE TITLE
Adding MGRS/USNG to mapinfo widget

### ISSUE THREAD

**Issue by Zxcvbnm87** [cmv/cmv-app#839]
Hi,

Not really an issue as it looks like the widget isn't designed to do it out of the box, but is there a way to display MGRS/USNG in the mapinfo widget, possibly using proj4js?

Seems like a feature that would be worth having if it's not overly hard to implement.

**Comment by tmcgee** [comment]
@JMaps88 This may already be possible in the MapInfo widget since it supports proj4js.
