### ISSUE TITLE
type: Dynamic do NOT support a list of featureServer?   

### ISSUE THREAD

**Issue by hoogw** [cmv/cmv-app#841]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

when I use type as dynamic, it only works if there are a list of MapServers,  in below case, there are a list of FeatureServer, I got error. 

I wonder if this is not supported? Or it supported, but need other setup? Or just a bug? 
` 
      mapOptions: {
      basemap: 'streets',
      center: [-118.142841, 34.145795],
       zoom: 12,
       sliderStyle: 'small'
      },

  `
  `
        operationalLayers: 
        [

           {
            type: 'dynamic',
            
            url: 'https://services2.arcgis.com/zNjnZafDYCAJAbN0/ArcGIS/rest/services',
           
            title: 'test ',

`

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/purinunuda/edit?js,output). Alternatively create a [Gist](gist.github.com)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 
| Browser                 |
| Operating system |

**Comment by green3g** [comment]
@hoogw "https://services2.arcgis.com/zNjnZafDYCAJAbN0/ArcGIS/rest/services" is not a url to a dynamic map server. You need to include the whole url to the rest end point including the service name and /MapServer url

For instance: [the arcgis javascript docs](https://developers.arcgis.com/javascript/3/jssamples/map_dynamic.html) use the url:

```
https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer
```
