### ISSUE TITLE
How to set default transparency as 50% for all layers? 

### ISSUE THREAD

**Issue by hoogw** [cmv/cmv-app#843]
How to set default transparency as 50% for all layers? 

Right now, the default is 0%, user have to adjust it to 50% manually every time. 
It is not good, user complain don't know where to change transparency. 

It would be good if I can pre-set up as 50% at config/viewer.js file. 
But how?

**Comment by ERS-Long** [comment]
options: {opacity: 0.5} should do it. put that in the operationalLayers section.

**Comment by tmcgee** [comment]
Examples of how to set the opacity/transparency are in the demo configuration file:

* [0% transparency/100% opacity](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L174)

* [20% transparency/80% opacity](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L291)

**Comment by hoogw** [comment]
It works!

      operationalLayers: 
        [


            {
                type: 'dynamic',
                //type: 'feature',
                url: 'https://maps.lacity.org/lahub/rest/services/Census_2010/MapServer',
                title: 'Los Angeles Census_2010',
                
                options: {
                
                opacity: 0.5
                }
       }]
