### ISSUE TITLE
Support subfolder? type: dynamic

### ISSUE THREAD

**Issue by hoogw** [cmv/cmv-app#845]
For example:  [https://maps2.dcgis.dc.gov/dcgis/rest/services](url)

This url have a list of subfolders, and list of mapservers

If I set as below, it failed.

how to make it works with this URL   **https://maps2.dcgis.dc.gov/dcgis/rest/services**

     `
               url: https://maps2.dcgis.dc.gov/dcgis/rest/services
               type:dynamic

**Comment by tmcgee** [comment]
@hoogw This isn't possible within the core cmv-app though it could done in a custom widget. Since it doesn't seem to be a common use case (in my experience any way), I think a custom widget is the appropriate path.

**Comment by hoogw** [comment]
Thanks to clearify. I am trying to make it happen on my copy. Widget is hard to me, I try to make a extra page to dedicate display subfolder and services, then link to your core cmv.

**Comment by hoogw** [comment]
I am still working on it. I find the way to make it. modify the core component. I don't know how to do widget.

**Comment by hoogw** [comment]
Good news ! I found the way to work around it by make extra page for listing the mapserver, when user click any mapserver, it will bring user to the one. 

try this working sample: 



Sample 2, only list the mapserver, NO structure.

[https://transparentgov.net/json2tree/searchMapServer.html?org=Washington+DC+City&url=https%3A%2F%2Fmaps2.dcgis.dc.gov%2Fdcgis%2Frest%2Fservices&search=](https://transparentgov.net/json2tree/searchMapServer.html?org=Washington+DC+City&url=https%3A%2F%2Fmaps2.dcgis.dc.gov%2Fdcgis%2Frest%2Fservices&search=)


Sample 1, list structure. (not recommended)

[https://transparentgov.net/json2tree/folder1.html?url=https://maps2.dcgis.dc.gov/dcgis/rest/services](https://transparentgov.net/json2tree/folder1.html?url=https://maps2.dcgis.dc.gov/dcgis/rest/services)

**Comment by hoogw** [comment]
I found work around, by make extra page just list the mapserver with link.  When user click it, it open up a new page just show one mapserver with cmv
