### ISSUE TITLE
url inject operationallayer URL and other parameters?

### ISSUE THREAD

**Issue by hoogw** [cmv/cmv-app#846]
Is that possible add new feature as

Right now, the operational layer URL was manually setup at config file  (/config/xxx.js file.)
It is not convenient in lots of place. Because for a new resource (http://...../mapserver) user have to access to server config folder and manually add a new config file, to specify the new resource. 

It would be better to dynamically let user inject the new resource url from the main URL.

inject operational layer URL from main URL. instead of config.js file. 

For example, I hope to view http://new_city/../.../Mapserver ( dynamic type)

Now I have to access server folder to make a new config file, new_city.js (setup http://new_city/../.../Mapserver) 

then http://xxxxdomainxxx.com/cmv/?config=new_city

What I hope I can do is, no need to create a config file on server, instead, directly 

http://xxxxdomainxxx.com/cmv/?config=default_template&operational_url=http://new_city/../.../Mapserver

/config/default_template.js file have everything setup except operational layer URL, which inject dynamically from above main URL.

How to do that? Or if not, can you add a new feature to let it happen?

**Comment by tmcgee** [comment]
@hoogw This isn't possible within the core cmv-app though it could done in a custom widget. Since it doesn't seem to be a common use case (in my experience any way), I think a custom widget is the appropriate path.

**Comment by hoogw** [comment]
Thanks to clearify.  I am trying to make it happen on my copy.  Widget is hard to me, I try to chang the core code

**Comment by hoogw** [comment]
good news!  I made it. 




Share with anyone, who want this new feature. 


Your dynamic URL is:

    `http://localhost:10/mapserver1/viewer/?config=viewer_simple1&url=https://maps2.dcgis.dc.gov/dcgis/rest/services/Zoning/MapServer&title=Washington_DC_Zoning&zoom=14&lat=38.917292&long=-77.036420`






You need to modify 2 files

https://github.com/hoogw/mapserver1/blob/master/viewer/js/viewer/_ConfigMixin.js
https://github.com/hoogw/mapserver1/blob/master/viewer/js/config/viewer_simple1.js



1)
C:\Apache24\htdocs\cmv\viewer\js\viewer\_ConfigMixin.js

 add following:

          ` initConfigAsync: function () {
            var returnDeferred = new Deferred();
            // get the config file from the url if present
            var file = 'config/' + this.defaultConfig,
                s = window.location.search,
                q = s.match(/config=([^&]*)/i);
            
            
            if (q && q.length > 0) {
                file = q[1];
                if (file.indexOf('/') < 0) {
                    file = 'config/' + file;
                }
            }
            
            
            console.log(file);
            
            
            // ---------- dynamic parameters ----------
            
            
            
            
            var ___zoom;
            var ___lat;
            var ___long;
            var ___basemap;
            
            var ___type;
            var ___url;
            var ___title;
            var ___opacity;
            
            
            /*
             *  if (value) { 
             *     
             *  }
             * 
             * will evaluate to true if value is not:

                    null
                    undefined
                    NaN
                    empty string ("")
                    false
                    0
             * 
             * 
             * 
             */
            
            
            if ( location.search.match(/zoom=([^&]*)/i) )
            {
                 ___zoom = location.search.match(/zoom=([^&]*)/i)[1];
             }
            
            if ( location.search.match(/lat=([^&]*)/i) )
            {
               ___lat = location.search.match(/lat=([^&]*)/i)[1];
            }
            
            if (location.search.match(/long=([^&]*)/i))
            {
                ___long = location.search.match(/long=([^&]*)/i)[1];
            }
            
            if (location.search.match(/basemap=([^&]*)/i))
            {
                ___basemap = location.search.match(/basemap=([^&]*)/i)[1];
            }
            
            if (location.search.match(/type=([^&]*)/i))
            {
                ___type = location.search.match(/type=([^&]*)/i)[1];
            }
            
           if (location.search.match(/url=([^&]*)/i))
            {
                ___url = location.search.match(/url=([^&]*)/i)[1];
            }
            
            
            if (location.search.match(/title=([^&]*)/i))
            {
                ___title = location.search.match(/title=([^&]*)/i)[1];
            }
            
            if (location.search.match(/opacity=([^&]*)/i))
            {
                ___opacity = location.search.match(/opacity=([^&]*)/i)[1];
            }
            
            
            //console.log(location.search.match(/zoom=([^&]*)/i)[0]);   //    'zoom=17'
            //console.log(location.search.match(/zoom=([^&]*)/i)[1]);   //     '17'
            console.log(___zoom); 
            console.log(___lat); 
            console.log(___long); 
            console.log(___basemap); 
            
            console.log(___type); 
            console.log(___url); 
            console.log(___title); 
            console.log(___opacity); 
            
            
            
            
            // --------   End   ------- dynamic parameters ----------
            
            
            
            
            
            
            require([file], function (config) {
                 
                 
                // ******** both  ********* [1]  ********  [2] ************ works ************

                    //----------** [1]  ** ---- dynamic loading url and center_zoom, center_lat, center_long ----------
                       
                
                       //console.log(___zoom);
                       
                       if (___zoom && ___zoom.length > 0)
                       {
                        config.set_center_zoom(___zoom);
                       }
                       
                       if (___long && ___long.length > 0 && ___lat && ___lat.length > 0)
                       {
                         config.set_center_long_lat(___long, ___lat);
                       }  
                       
                       if (___basemap && ___basemap.length > 0)
                       {
                           config.set_basemap(___basemap);
                       }
                       
                       
                       if (___type && ___type.length > 0)
                       {
                           config.set_type(___type);
                       }
                       
                       if (___url && ___url.length > 0)
                       {
                         config.set_url(___url);
                       }  
                       
                       if (___title && ___title.length > 0)
                       {
                          config.set_title(___title);
                       }
                       
                       if (___opacity && ___opacity.length > 0)
                       {
                           config.set_opacity(___opacity);
                        }
                       
                       //console.log(config.get_center_zoom());

                       console.log(config.get_mapOptions());
                       console.log(config.get_operationalLayers());
                      //-------End  --** [1]  ** ---------  dynamic loading url and center_zoom, center_lat, center_long ----------
               
               
               

                    returnDeferred.resolve(config);




            });      // require  
            
            
            
             
            
            
            
            return returnDeferred;
        },

        initConfigSuccess: function (config) {
            
                
            // ******** both  ********* [1]  ********  [2] ************ works ************
            
              
               
              //----------**  [2] **------- dynamic loading url and center_zoom, center_lat, center_long ----------
               
              // config.set_center_zoom();
              // console.log(config.get_mapOptions());
               
              //------------End  ----**  [2] **----  dynamic loading url and center_zoom, center_lat, center_long ----------
               
            `

2)  C:\Apache24\htdocs\cmv\viewer\js\config\viewer_simple1.js

    `
    define([
    'esri/units',
    'esri/geometry/Extent',
    'esri/config',
    /*'esri/urlUtils',*/
    'esri/tasks/GeometryService',
    'esri/layers/ImageParameters',
    'gis/plugins/Google',
    'dojo/i18n!./nls/main',
    'dojo/topic',
    'dojo/sniff'
     ], function (units, Extent, esriConfig, /*urlUtils,*/ GeometryService, ImageParameters, GoogleMapsLoader, i18n, topic, has) {

    
    // https://developers.google.com/maps/documentation/javascript/get-api-key
    GoogleMapsLoader.KEY = 'xxxxxxxxxxxxx';

    
    var default_center_zoom = 12;
    var default_center_lat = 38.907292;
    var default_center_long = -77.036420;
    var default_basemap = 'streets';
    
    
    var  ___mapOption =  {
            basemap: default_basemap,
            center: [default_center_long, default_center_lat],
            zoom: default_center_zoom,
            sliderStyle: 'small'
        };
    
    
    
    
    var default_type = 'dynamic';
    
    //var default_url = 'https://maps2.dcgis.dc.gov/dcgis/rest/services/Zoning/MapServer';
    var default_url = '';
    
    //var default_title = 'Washington DC Zoning';
    var default_title = '';
    
    var default_opacity = 0.5;
    
    
    var ___operational_layer = {
                type: default_type,
                //type: 'feature',
                url: default_url,
                title: default_title,
                
                options: {
                
                opacity: default_opacity
                },
                
                
                
                layerControlLayerInfos: {
            
                    // layer control options
                    noLegend: false,
                    noZoom: false,
                    swipe: true,
                    swipeScope: true,
                    expanded: true,
                    sublayers: true,
                    metadataUrl: false,
                    allSublayerToggles	: true,
                   
                }



            };
    
    
    

    return {
        
        
        //-------------- dynamic loading url and center_zoom, center_lat, center_long ----------
        
        set_center_zoom: function(___zoom){
          
            ___mapOption.zoom = ___zoom;
            
        },
        
        
        set_center_long_lat: function(___long, ___lat ){
          
            ___mapOption.center = [___long, ___lat ];
            
        },
        
        
        
         set_basemap: function(___basemap ){
          
            ___mapOption.basemap = ___basemap;
            
        },
        
        
        
        set_type: function(___type ){
          
            ___operational_layer.type = ___type;
            
        },
        
        
        set_url: function(___url ){
          
            ___operational_layer.url = ___url;
            
        },
        
        set_title: function(___title ){
          
            ___operational_layer.title = ___title;
            
        },
        
        
        
        set_opacity: function(___opacity ){
          
            ___operational_layer.options.opacity = ___opacity;
            
        },
        
        
        
        
        get_center_zoom: function(){
            return ___mapOption.zoom;
        },
        
        get_mapOptions: function(){
            return ___mapOption;
        },
        
        get_operationalLayers: function(){
            return ___operational_layer;
        },
        //--------------------End  ------  dynamic loading url and center_zoom, center_lat, center_long ----------
        
        
        
        
        
        
        
        // used for debugging your app
        isDebug: true,

        //default mapClick mode, mapClickMode lets widgets know what mode the map is in to avoid multipult map click actions from taking place (ie identify while drawing).
        defaultMapClickMode: 'identify',
        // map options, passed to map constructor. see: https://developers.arcgis.com/javascript/jsapi/map-amd.html#map1
        mapOptions: ___mapOption,

        

        // custom titles
        titles: {
            header: i18n.viewer.titles.header,
            subHeader: i18n.viewer.titles.subHeader,
            pageTitle: i18n.viewer.titles.pageTitle
        },

        layout: {
            
        },

        
        // operationalLayers: Array of Layers to load on top of the basemap: valid 'type' options: 'dynamic', 'tiled', 'feature'.
        // The 'options' object is passed as the layers options for constructor. Title will be used in the legend only. id's must be unique and have no spaces.
        // 3 'mode' options: MODE_SNAPSHOT = 0, MODE_ONDEMAND = 1, MODE_SELECTION = 2
        operationalLayers: 
        [

              ___operational_layer

        ],


`
