### ISSUE TITLE
How to edit the Shape,KML or CSV files added through the Drag and Drop Widget.

### ISSUE THREAD

**Issue by durga-pericherla** [cmv/cmv-app#861]
Hai, I am using both Editor and DnD widgets in my viewer. Is it possible to edit the KML, Shape or CSV files which are added to the map via Drag and Drop widget using the Editor Widget. Or is there any way to edit the attachments which are added to map via Drag and Drop widget.

Thanks in Advance.

**Comment by tmcgee** [comment]
@ParkShinYoo The Editor widget requires a feature layer from a ArcGIS Server Feature Service and would not work directly with features in a KML, Shapefile or CSV graphics layer. You could possibly add those features from the graphics to the editable feature layer. Neither the DnD or Editor widgets support that so you'd have to write your own custom widget.

**Comment by durga-pericherla** [comment]
Got it. Thank you @tmcgee
