### ISSUE TITLE
Triggering event based on operational layer toggle

### ISSUE THREAD

**Issue by Zxcvbnm87** [cmv/cmv-app#862]
Once again not really an issue, more just after advice before I go adding code that may not be required. Is there an easy way to trigger an event, such as show/hide floating text, when an operational layer is turned on or off? My intent is to have cmv react in a similar way as it does with service layer credits, but use an if type statement to avoid it continuously adding credits for ever added service like it currently does. The end result will be not displaying similar sources multiple times if one source overwrites/contradicts another. I think I can achieve this using topic.subscribe and topic.publish but for all I know cmv may already have a way to achieve this.

**Comment by green3g** [comment]
There are already some events for layer toggling. The API provides some events I know, like 
```javascript
layer.on('visibility-change', function(){ 
// do something when layer visibility changes
})
```

Also the layer control publishes a topic when a layer is toggled:

https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/LayerControl/controls/_Control.js#L178

**Comment by tmcgee** [comment]
@jmaps88 This widget is an example of the second approach mentioned by @roemhildtg.

https://github.com/tmcgee/cmv-widgets/blob/master/widgets/LayerToggle.js

**Comment by Zxcvbnm87** [comment]
Cheers. I’ll have a play around with Modifying the layer toggle widget and see what I can come up with
