### ISSUE TITLE
Close icon displaying as a magnifying glass.

### ISSUE THREAD

**Issue by gisnovice** [cmv/cmv-app#863]
in .\css\theme\flat\flat.css

The close icon in any windows box comes up as a magnifying glass

.flat .dijitDialogCloseIcon:before{content:"\f00e";font-size:20px} to be changed to "\f410" symbol, perhaps?

**Comment by tmcgee** [comment]
@gisnovice. Verified. Thanks!

**Comment by gisnovice** [comment]
Love the work that you guys do! Thanks for everything!
