### ISSUE TITLE
Update the Basemap of Google in cmv ver 2 

### ISSUE THREAD

**Issue by GilbertLasnier** [cmv/cmv-app#865]
I put the google base map in the cmv 2.0 base map...Its work very well, but i realize that the version of the picture is 2015, not like on the site of maps google, there is a way to find a more recent version of that google map...? Also there is a way to make transparencies on that base map or other...its nor a gis web services...

googleHybrid: {
                title: 'googleHybrid',
                basemap: new Basemap({
                    id: 'googleHybrid',
                    layers: [new BasemapLayer({
                        url: "https://mt${subDomain}.google.com/vt/lyrs=s,h&hl=en&gl=en&x=${col}&y=${row}&z=${level}&s=png",
                        copyright: "Google, 2015",
                        id: "googleHybrid",
                        subDomains: ["0", "1", "2", "3"],
                        type:"WebTiledLayer"
                        })
                    ]
                })
            },
| CMV Version 2.0 | 
Waiting for some ideas???

**Comment by tmcgee** [comment]
@GilbertLasnier Are you sure the actual images are from 2015 or are you seeing a 2015 copyright only because that is what you entered in the config:
``` javascript
copyright: "Google, 2015",
```

**Comment by GilbertLasnier** [comment]
I am sure because
I compare with the site of google to day, and I must be able to see all the roof in white ( they people received un subvention for changing our roof in white for the control of the temperature of the earth...and that kind of imagery is on the latest google map not on the 2015 forget the copyright the imagery is not uptodate and the zoom level is also restricted...
Thanks for your very fast answer, Tim

Envoyé de mon iPad

Le 31 oct. 2018 à 14:36, Tim McGee <notifications@github.com<mailto:notifications@github.com>> a écrit :


@GilbertLasnier<https://github.com/GilbertLasnier> Are you sure the actual images are from 2015 or are you seeing a 2015 copyright only because that is what you entered in the config:

copyright: "Google, 2015",

**Comment by tmcgee** [comment]
@GilbertLasnier When I zoom in close on a particular area using the above code, I see a copyright date of 2018 on the Google map tiles. I am not aware of any other method to access tiles that might use newer base imagery.

**Comment by GilbertLasnier** [comment]
Sorry I answer with picture  in th #619

**Comment by GilbertLasnier** [comment]
its work now I just change zoom to 19 and after to 5
  mapOptions: {
            basemap: 'topo',
            center: [0.0, 30.0],
			zoom: 19,
            zoom: 5,
            sliderStyle: 'small'
			/* lods: maplods */
        },
If you want you must close tha case...
