### ISSUE TITLE
Streetview arrow rotation offset incorrect

### ISSUE THREAD

**Issue by duckblaster** [cmv/cmv-app#870]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

The arrow on the map indication the current streetview position and direction rotates around the back right leg instead of the center of the arrow.

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | Latest develop (5a223080f53aff2e1b0a84ccbed96444fc9880fc)
| Browser                 | Chrome 70.0.3538.77 (Official Build) (64-bit)
| Operating system | Windows 10

**Comment by tmcgee** [comment]
I did not know that arrows have legs. 😉

Despite my snarky reply, I do know what you are referring to. The rotation isn't quite right after the switch from an image Picture Symbol to a Font Awesome icon TextSymbol.
