### ISSUE TITLE
operational layer type='image' ----- No legend !!! bug? or is it design to be?

### ISSUE THREAD

**Issue by hoogw** [cmv/cmv-app#875]
Here is my code: 
it works, but under layers section it says 'No legend'. as well as legend section.

  
Did I missing something in options? or is it a bug? or is it design to be it?

         operational_layer = {

                                         type:'image',    
                                        
          url:'https://sampleserver3.arcgisonline.com/ArcGIS/rest/services/World/Temperature/ImageServer'
                             
                                    options: {
                                               opacity:0.5,
                                                visible: true,
                                              }
        }

**Comment by tmcgee** [comment]
The `legend` [REST resource](https://developers.arcgis.com/rest/services-reference/legend-image-service-.htm) for an Image Service was added at version 10.2 of ArcGIS Server. That server is still running version 10.05.

**Comment by hoogw** [comment]
Good information!  Got it. Very helpfull.  Other people facing same issue will like this answer.
