### ISSUE TITLE
Dijit TabContainer navigation icons not displaying correctly

### ISSUE THREAD

**Issue by ishiland** [cmv/cmv-app#888]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
When adding enough `ContentPane`'s to overflow the width of the `TabContainer`, the navigation arrows do not display correctly. See below image. 

<img width="455" alt="Screen Shot 2019-03-10 at 3 54 33 PM" src="https://user-images.githubusercontent.com/3847952/54090698-42934000-434d-11e9-8b2a-fffb8b4ccb67.png">

__Steps to reproduce:__

Add additional tabs

__Expected results:__
Left and Right arrow icons are expected, in addition to a Menu icon. 

__Actual results:__
Incorrect navigation icons are displayed. 

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 2.0.0 beta 2
| Browser                 | chrome
| Operating system | Mac

**Comment by tmcgee** [comment]
@ishiland Did we address this with the FontAwesome icons fix identified in #889?

**Comment by ishiland** [comment]
I think this was resolved. I will close for now.
