### ISSUE TITLE
can cmv be localized???

### ISSUE THREAD

**Issue by jiangning-hub** [cmv/cmv-app#949]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
I want to localize the cmv application I configure, but beside the ArcGIS server's service there is still one  problem that it use 'js.arcgis.com/3.21compact'. I download the 3.21compact/init.js and include it as a local source but not work.

__Steps to reproduce:__

1. replace the ArcGIS server service with the service I create and post on my ArcGIS server instance;
2. download the 'js.arcgis.com/3.21compact/init.js' and include it with a local path;
3. run by command "grunt connect";
4. then, the page is not as what I expected.

__Expected results:__

__Actual results:__
Error message: "The resource from “https://localhost:3000/viewer/js/arcgis-js-api/3.12compact/init.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). localhost:3000".
 
And the page show nothing at all!

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version |  latese(clone from github)
| Browser                 | both Chrome and FireFox
| Operating system | Windows

**Comment by tmcgee** [comment]
Using the ArcGIS JavaScript API locally is not a problem. Many developers including myself have done that. I have not tried this using grunt connect but would expect it to work. Be sure to follow the directions provided by Esri to set the path for dojo by editing init.js.

**Comment by jiangning-hub** [comment]
Thanks!
So the CMV app's localization would be possible if the configuration is correct? I'll try.
I am just new to all these. So,there will be quit a lot stupid questions :(

**Comment by jiangning-hub** [comment]
> Thanks!
> So the CMV app's localization would be possible if the configuration is correct? I'll try.
> I am just new to all these. So,there will be quit a lot stupid questions :(

Just happen to understand that '3.21compact' is an old version of the arcgis js api. And, just unable to get it since I failed to sign up an arcgis account. Stupid...

**Comment by jiangning-hub** [comment]
Figure it out, finally. Using the '3.22compact' version, and it work just fine. The '3.21compact' version can be download with just 200b/s, it is gonna kill me. Glad to see '3.22compact' work.
