### ISSUE TITLE
support arcgis javascript api v3.33?  or v3.28

### ISSUE THREAD

**Issue by hoogw** [cmv/cmv-app#966]
support arcgis javascript api v3.33?  or v3.28

**Comment by tmcgee** [comment]
@hoogw 

The current version we support is [v3.33](https://github.com/cmv/cmv-app/blob/develop/viewer/index.html#L49).  Most prior versions over the last several years will work as well.

**Comment by hoogw** [comment]
Thanks, I use v3.28 all the time until last week,  I suddenly found 2 year running CMV (with 3.28) broken
The error message is below

![image](https://user-images.githubusercontent.com/419582/95225335-8dd33600-07b0-11eb-9c31-67a319c568d7.png)

I try change index.html ( v3.28 to v3.33), same error,  looks like I need completely re-build to upgrade to v3.33

**Comment by hoogw** [comment]
I found the reason, it is because, 2 year ago,  zoom level support decimal. 
for example,  I set zoom=16.7,  it works fine.

Recently error is because recently, either CMV change code, or ESRI v3.28/v3.33 change code, will NOT support zoom=16.7,  you must use zoom=17 integer only. 

If I continual use zoom=16.7, will cause above error.

**Comment by tmcgee** [comment]
@hoog That would definitely be change in ESRI code, not CMV. I am surprised that non-decimal zoom levels were ever allowed. This is the first time I recall anyone attempting to use them. Glad you got it worked out. 👍🏽
