### ISSUE TITLE
How put an accordion in left pane

### ISSUE THREAD

**Issue by adrianrb** [cmv/cmv-app#977]
Hello!

Thank you for CMV! It´s a great software.

I want put an accordion in left pane, to separate standard cmv widgets from others (dojo, jQuery UI etc.).
Like this:

```
Accordion
  Group 1
  CMV widgets
  Group 2
  ...
```

How it´s possible?
Provide some code/example if possible.

Adrian

**Comment by tmcgee** [comment]
@adrianrb I'll try to put together a basic example next week.

**Comment by adrianrb** [comment]
Solved by navigating through DOM (bad and ugly!), and putting elements inside manually...

![image](https://user-images.githubusercontent.com/12686959/111629976-9d7b8f80-87d0-11eb-8060-3104492e262d.png)
