### ISSUE TITLE
Zoom Level in Attribute Grid

### ISSUE THREAD

**Issue by azinsharaf** [cmv/cmv-app#981]
When we click on a row in search result grid, it zooms to the feature on the map. For the points it zooms in too much so we always have to zoom out manually. Is there anyway to set a default zoom level for this? 

![image](https://user-images.githubusercontent.com/10101468/112366235-cbac1400-8c95-11eb-9971-d99af2bbefe0.png)

**Comment by tmcgee** [comment]
the default value of `pointExtentSize` used to expand the zoom extent is 250 meters (assuming Web Mercator). That is intended to show 250 meters in all 4 directions around the point. I believe you can adjust the size to your liking though it isn't documented. 

A scalebar of 2m/4ft suggests your zoomed in much closer than that 250 meters. I don't know why that would be without knowing more about your configuration and use case.
