### ISSUE TITLE
Home Button bug

### ISSUE THREAD

**Issue by ERS-Long** [cmv/cmv-app#989]
__How often can you reproduce it?__ 

- [x ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__Home button does not go back to the extent defined in the config file. Tried the CMV live version, it has the same issue.

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible. [You can use this as a starting point](http://jsbin.com/purinunuda/edit?js,output). Alternatively create a [Gist](gist.github.com)
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
4. Check the browser console for errors (Use F12 to access the console)

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| CMV Version | 
| Browser                 |
| Operating system |

**Comment by ERS-Long** [comment]
please discard this issue, not a bug

**Comment by tmcgee** [comment]
My favorite kind of bug. 😁

**Comment by ERS-Long** [comment]
hahaha
